const Map<String, String> arabic = {
  "Home": "الرئيسية",
  "Calorie": "السعرات الحرارية",
  "Analytics": "التحليلات",
  "Setting": "الإعدادات",
  "Track Food": "تتبع الطعام",
  "Consumed": "المستهلك",
  "Remaining": "المتبقي",
  "Protein": "البروتين",
  "Carbs": "الكربوهيدرات",
  "Fats": "الدهون",
  "History": "السجل",
  "View All": "عرض الكل",
  "BreakFast": "إفطار",
  "Lunch": "غداء",
  "snack(s)": "وجبة خفيفة",
  "Dinner": "عشاء",
  "Which meal would you like to track?": "أي وجبة ترغب في تتبعها؟",
  "Snap Tips": "نصائح التصوير",
  "Too close": "قريب جداً",
  "Too far": "بعيد جداً",
  "Multi-species": "متعدد الأنواع",
  "Continue": "متابعة",
  "OverView": "نظرة عامة",
  "Weight Goal": "الهدف من الوزن",
  "Update": "تحديث",
  "Current Weight": "الوزن الحالي",
  "kg": "كغ",
  "Try to update once a week so we can adjust your plan to ensure you hit your goal": "حاول التحديث مرة أسبوعيًا حتى نتمكن من تعديل خطتك لضمان تحقيق هدفك",
  "Update Weight": "تحديث الوزن",
  "Week": "أسبوع",
  "Month": "شهر",
  "Year": "سنة",
  "Update Weight Goal": "تحديث هدف الوزن",
  "Enter new weight (kg)": "أدخل الوزن الجديد (كغ)",
  "Cancel": "إلغاء",
  "Calorie Your Week :": "سعرات أسبوعك:",
  "Sun": "الأحد",
  "Mon": "الاثنين",
  "Tue": "الثلاثاء",
  "Wed": "الأربعاء",
  "Thu": "الخميس",
  "Fri": "الجمعة",
  "Sat": "السبت",
  "Average Calorie Month :": "متوسط السعرات الشهري:",
  "Average Calorie Yearly :": "متوسط السعرات السنوي:",
  "Jan": "يناير",
  "Feb": "فبراير",
  "Mar": "مارس",
  "Apr": "أبريل",
  "May": "مايو",
  "Jun": "يونيو",
  "Jul": "يوليو",
  "Aug": "أغسطس",
  "Sep": "سبتمبر",
  "Oct": "أكتوبر",
  "Nov": "نوفمبر",
  "Dec": "ديسمبر",
  "Age": "العمر",
  "Height": "الطول",
  "Customization": "تخصيص",
  "Dark Mode": "الوضع الداكن",
  "Language": "اللغة",
  "Personal details": "المعلومات الشخصية",
  "Adjust goals": "تعديل الأهداف",
  "Calories,carbs,fat and protein": "السعرات، الكربوهيدرات، الدهون والبروتين",
  "Chat history": "سجل المحادثات",
  "Legal": "قانوني",
  "Terms and Condition": "الشروط والأحكام",
  "Privacy Policy": "سياسة الخصوصية",
  "Reset Data?": "إعادة تعيين الحساب؟",
  "VERSION": "الإصدار",
  "History not found": "لم يتم العثور على السجل",
  "Delete Item": "حذف العنصر",
  "Are you sure you want to delete this item?": "هل أنت متأكد أنك تريد حذف هذا العنصر؟",
  "Delete": "حذف",
  "Search by Food Name/Dish": "ابحث باسم الطعام / الطبق",
  "🎯 Calorie Goal Reached": "🎯 تم الوصول إلى هدف السعرات",
  "You've completed your calorie goal for today. Would you like to add more?": "لقد أكملت هدف السعرات الحرارية لهذا اليوم. هل ترغب في إضافة المزيد؟",
  "Done": "تم",
  "Add More Calories": "أضف المزيد من السعرات",
  "Boiled Egg": "بيضة مسلوقة",
  "Oatmeal": "شوفان",
  "Banana": "موز",
  "Paratha": "باراثا",
  "Idli": "إدلي",
  "Dosa": "دوسا",
  "Upma": "أبما",
  "Poha": "بواها",
  "Bread Butter": "خبز وزبدة",
  "Cornflakes with Milk": "كورنفليكس مع الحليب",
  "Chilla (Besan)": "شيلا (بيسان)",
  "Sprouts Salad": "سلطة براعم",
  "Pancakes": "فطائر",
  "Apple": "تفاح",
  "Milk": "حليب",
  "Almonds": "لوز",
  "Smoothie (Fruit)": "سموذي (فاكهة)",
  "Yogurt (Plain)": "زبادي (طبيعي)",
  "Khichdi": "كيشدي",
  "Thepla": "ثيبلا",
  "Cheela (Moong dal)": "شيلا (عدس المونغ)",
  "Pav Bhaji": "باو بهجي",
  "Sabudana Khichdi": "سابودانا خيتشدي",
  "Roti with Sabzi": "روتي مع خضار",
  "Peanut Butter Bread": "خبز بزبدة الفول السوداني",
  "Fruit Bowl": "وعاء فواكه",
  "Vegetable Sandwich": "شطيرة خضروات",
  "Rice Idli with Sambar": "إدلي الأرز مع سامبار",
  "Boiled Corn": "ذرة مسلوقة",
  "Paneer Bhurji": "بانيـر بـهـورجي",
  "Protein Shake": "مشروب البروتين",
  "Muesli with Milk": "ميوسلي مع الحليب",
  "Chapati with Curd": "تشباتي مع لبن",
  "Porridge (Daliya)": "عصيدة (داليا)",
  "Rava Upma": "رافا أبما",
  "Chickpea Salad": "سلطة حمص",
  "Boiled Sweet Potato": "بطاطا حلوة مسلوقة",
  "Coconut Water": "ماء جوز الهند",
  "Masala Omelette": "عجة ماسالا",
  "Vegetable Poha": "بوهـا بالخضار",
  "1 egg": "1 بيضة",
  "1 bowl": "1 وعاء",
  "1 medium": "1 متوسط",
  "1 piece": "1 قطعة",
  "1 cup": "1 كوب",
  "2 slices": "2 شرائح",
  "2 small pieces": "2 قطع صغيرة",
  "10 pieces": "10 قطع",
  "1 glass": "1 كوب زجاجي",
  "2 pavs + bhaji": "2 باف + بهجي",
  "1 roti + sabzi": "1 روتي + خضار",
  "1 sandwich": "1 شطيرة",
  "2 idlis + sambar'": "2 إدلي + سامبار",
  "1 chapati + ½ cup curd": "1 تشباتي + ½ كوب لبن",
  "Rice with Dal": "أرز مع عدس",
  "Grilled Chicken": "دجاج مشوي",
  "Paneer Curry": "كاري البانيـر",
  "Mixed Vegetable Curry": "كاري خضار مشكّل",
  "Chapati with Daal": "تشباتي مع عدس",
  "Fish Curry with Rice": "كاري سمك مع أرز",
  "Rajma Chawal": "راجما تشاول",
  "Chole Bhature": "تشولي بهاتور",
  "Kadhi with Rice": "كادهي مع أرز",
  "Palak Paneer": "بانيـر بالسبانخ",
  "Stuffed Paratha": "باراثا محشوة",
  "Veg Pulao": "بيلاف نباتي",
  "Biryani with Raita": "برياني مع رايتا",
  "Tofu Stir Fry": "توفر مقلي سريع",
  "Chicken Tikka": "دجاج تيكا",
  "Veg Fried Rice": "أرز مقلي بالخضار",
  "Aloo Gobi with Roti": "بطاطا وقرنبيط مع روتي",
  "Baingan Bharta": "بينغان بهارتا",
  "Sambar with Rice": "سامبار مع أرز",
  "Chicken Curry with Roti": "كاري الدجاج مع روتي",
  "Bhindi Masala with Roti": "بامية ماسالا مع روتي",
  "Egg Curry with Rice": "كاري البيض مع أرز",
  "Lentil Soup with Bread": "شوربة عدس مع خبز",
  "Methi Thepla with Curd": "ثيبلا بالحنظل مع لبن",
  "Soybean Curry with Rice": "كاري فول الصويا مع أرز",
  "Cabbage Sabzi with Chapati": "ملفوف مع تشباتي",
  "Dal Makhani with Naan": "دال مـخـني مع نان",
  "Vegetable Korma with Roti": "كورما خضار مع روتي",
  "Tandoori Roti with Paneer": "روتي تندوري مع بانيـر",
  "Mixed Dal with Rice": "عدس مشكّل مع أرز",
  "Bottle Gourd Curry with Roti": "كاري قرع مع روتي",
  "Kofta Curry with Roti": "كاري كفتة مع روتي",
  "Paneer Bhurji with Bread": "بانيـر بـهـورجي مع خبز",
  "Chana Masala with Rice": "حمص ماسالا مع أرز",
  "Curd Rice": "أرز مع لبن",
  "Tomato Rice": "أرز بالطماطم",
  "Vegetable Stew with Appam": "يخنة خضار مع أبام",
  "Dhokla with Green Chutney": "دوكلا مع صلصة خضراء",
  "Besan Chilla with Salad": "بيسان شيلا مع سلطة",
  "Lauki Chana Dal": "قرع مع عدس الحمص",
  "Spinach Corn Curry": "كاري سبانخ مع ذرة",
  "Tinda Masala with Roti": "تيندا ماسالا مع روتي",
  "Masoor Dal with Rice": "عدس ماسور مع أرز",
  "Vegetable Handi with Naan": "هندي خضار مع نان",
  "Egg Bhurji with Chapati": "بـيـض بـهـورجي مع تشباتي",
  "Pumpkin Curry with Rice": "كاري يقطين مع أرز",
  "2 rotis + sabzi": "2 روتي + خضار",
  "1 cup rice + 1 cup dal": "1 كوب أرز + 1 كوب عدس",
  "1 breast": "1 صدر",
  "2 chapatis + dal'": "2 تشباتي + عدس",
  "1 bowl curry + 1 cup rice": "1 وعاء كاري + 1 كوب أرز",
  "1 bhatura + chole": "1 بهاتورا + تشولي",
  "1 paratha": "1 باراثا",
  "1 bowl + 2 rotis": "1 وعاء + 2 روتي",
  "1 cup + 1 bowl": "1 كوب + 1 وعاء",
  "1 bowl + 1 cup rice": "1 وعاء + 1 كوب أرز",
  "1 bowl + 1 bread slice": "1 وعاء + 1 شريحة خبز",
  "2 theplas + ½ cup curd": "2 ثيبلا + ½ كوب لبن",
  "1 bowl + 2 chapatis": "1 وعاء + 2 تشباتي",
  "1 bowl + 1 naan": "1 وعاء + 1 نان",
  "2 rotis + paneer": "2 روتي + بانيـر",
  "1 bowl + 2 slices": "1 وعاء + 2 شرائح",
  "1 bowl + 2 appams": "1 وعاء + 2 أبام",


  "3 pieces": "3 قطع",
  "2 chillas + salad": "2 تشيلا + سلطة",
  "Cal": "سعرة",
  "Cropper": "كروبير",
  "Calorie Tracker": "متتبّع السعرات الحرارية",
  "Add Calorie": "إضافة سعرات حرارية",
  "Quantity": "الكمية",
  "Ask With Open AI": "اسأل مع Open AI",
  "This picture not available Calorie,Protein,Carbs and Fats,": "لا تتوفر في هذه الصورة معلومات عن السعرات الحرارية أو البروتين أو الكربوهيدرات أو الدهون.",
  "Ask Botanist": "اسأل عالم النبات",
  "Write your message": "اكتب رسالتك",
  "Confirm Reset": "تأكيد إعادة تعيين",
  "Are you sure you want to Reset Data?": "هل أنت متأكد أنك تريد إعادة تعيين الحساب؟",
  "Reset": "إعادة تعيين",
  "You have been Reset Account": "تم إعادة تعيين حسابك",
  "Personal Details": "التفاصيل الشخصية",
  "Goal Weight": "وزن الهدف",
  "cm": "سم",
  "Date Of Birth": "تاريخ الميلاد",
  "Gender": "الجنس",
  "Male": "ذكر",
  "Female": "أنثى",
  "Choose your desired weight?": "اختر وزنك المرغوب؟",
  "Imperial": "الإمبراطوري",
  "Metric": "المتري",
  "Weight": "الوزن",
  "lb": "رطل",
  "ft": "قدم",
  "in": "بوصة",
  "Day": "يوم",
  "January": "يناير",
  "February": "فبراير",
  "March": "مارس",
  "April": "أبريل",
  "June": "يونيو",
  "July": "يوليو",
  "August": "أغسطس",
  "September": "سبتمبر",
  "October": "أكتوبر",
  "November": "نوفمبر",
  "December": "ديسمبر",
  "Update Your Gender": "تحديث جنسك",
  "Adjust Goals": "تعديل الأهداف",
  "How many workout do you per week?": "كم عدد التمارين التي تقوم بها في الأسبوع؟",
  "This will used to calibrate your custom plan": "سيتم استخدام هذا لمعايرة خطتك المخصصة",
  "Workout Now and then": "تمارين الآن ثم",
  "A few workout per week": "بعض التمارين في الأسبوع",
  "Dedicated athlete": "رياضي مكرس",
  "What is your goal?": "ما هو هدفك؟",
  "This helps is generate a plan for your calorie intake.": "يساعد هذا في إنشاء خطة لاستهلاكك من السعرات الحرارية.",
  "Gain Weight": "زيادة الوزن",
  "Lose Weight": "فقدان الوزن",
  "Update Calorie Goal": "تحديث هدف السعرات الحرارية",
  "Save": "حفظ",
  "Calorie Goal": "هدف السعرات الحرارية",
  "Update Protein Goal": "تحديث هدف البروتين",
  "Protein goal": "هدف البروتين",
  "Update Carb Goal": "تحديث هدف الكربوهيدرات",
  "Carb goal": "هدف الكربوهيدرات",
  "Update Fat Goal": "تحديث هدف الدهون",
  "Auto Generate Goal": "توليد الهدف تلقائيًا",
  "Fruit Salad": "سلطة فواكه",
  "Roasted Chickpeas": "حمص محمص",
  "Mixed Nuts": "مكسرات مشكلة",
  "Yogurt with Honey": "زبادي بالعسل",
  "Apple with Peanut Butter": "تفاحة مع زبدة الفول السوداني",
  "Protein Bar": "شريط البروتين",
  "Whole Wheat Crackers": "مقرمشات القمح الكامل",
  "Granola Bar": "شريط جرانولا",
  "Peanut Chikki": "شكي بالفول السوداني",
  "Bhel Puri": "بهل بوري",
  "Khakra": "خاكرا",
  "Masala Makhana": "مسالا مخانا",
  "Hummus with Veggies": "حمص مع خضروات",
  "Paneer Cubes": "مكعبات بانير",
  "Milkshake (Low Sugar)": "ميلك شيك (قليل السكر)",
  "Dhokla": "دخولا",
  "Vegetable Soup": "حساء الخضار",
  "Idli with Chutney": "إيدلي مع شاتني",
  "Cheese Slice": "شريحة جبن",
  "Chana Chaat": "شانا شات",
  "Moong Dal Chilla": "موونغ دال تشيلا",
  "Rice Cake with Peanut Butter": "كعكة أرز مع زبدة الفول السوداني",
  "Popcorn (Air-popped)": "فشار (منتفخ بالهواء)",
  "Avocado Toast": "توست الأفوكادو",
  "Stuffed Dates": "تمور محشوة",
  "Oats Cookies": "كوكيز الشوفان",
  "Fruit Smoothie": "سموثي الفواكه",
  "Carrot Sticks with Hummus": "عصي الجزر مع الحمص",
  "Soy Nuts": "مكسرات الصويا",
  "Trail Mix": "مزيج المسار",
  "Besan Ladoo": "بسان لادو",
  "Upma (small portion)": "أبما (حصة صغيرة)",
  "Egg Roll (Mini)": "لفة البيض (صغيرة)",
  "Rice Idli": "إيدلي الأرز",
  "Cucumber Sandwich": "ساندويتش الخيار",
  "Fruit Chaat": "فواكه شات",
  "Lassi (Sweet)": "لاسي (حلو)",
  "Cold Coffee (Low Sugar)": "قهوة باردة (قليلة السكر)",
  "Rava Dhokla": "روا دخولا",
  "Vegetable Cutlet": "كوتلت الخضار",
  "Chikki with Jaggery": "شيكي مع جاجري",
  "Milk (Low Fat)": "حليب (قليل الدسم)",
  "Baked Samosa": "سمبوسة مخبوزة",
  "Vegetable Wrap": "لفائف الخضار",
  "Roasted Soybeans": "فول الصويا المحمص",
  "1/2 cup": "نصف كوب",
  "1 handful": "قبضة واحدة",
  "1 apple + 1 tbsp PB": "تفاحة واحدة + 1 ملعقة طعام زبدة الفول السوداني",
  "1 bar": "شريط واحد",
  "5 pieces": "5 قطع",
  "½ cup hummus + veggies": "نصف كوب حمص + خضروات",
  "50g": "50 جرام",
  "1 idli + chutney": "1 إيدلي + شاتني",
  "1 slice": "شريحة واحدة",
  "1 chilla": "1 تشيلا",
  "1 cake + 1 tbsp PB": "كعكة واحدة + 1 ملعقة طعام زبدة الفول السوداني",
  "2 cups": "كوبين",
  "1 toast": "شريحة توست واحدة",
  "3 dates": "3 تمور",
  "2 cookies": "2 كوكيز",
  "½ cup": "نصف كوب",
  "1 small bowl": "1 وعاء صغير",
  "1 roll": "لفة واحدة",
  "1 wrap": "لفة واحدة",
  "Chapati with Sabzi": "شباتي مع سبزي",
  "Grilled Fish": "سمك مشوي",
  "Moong Dal Khichdi": "موونغ دال خيتشدي",
  "Paneer Bhurji with Roti": "بانير بهورجي مع روتي",
  "Brown Rice with Veg Curry": "أرز بني مع كاري الخضار",
  "Quinoa with Stir Fry Veggies": "كينوا مع خضار مقلي",
  "Grilled Tofu with Salad": "توofu مشوي مع سلطة",
  "Vegetable Pulao": "بولاو الخضار",
  "Palak Paneer with Chapati": "بالاك بانير مع شباتي",
  "Mixed Vegetable Soup": "حساء الخضار المختلط",
  "Stuffed Paratha with Curd": "باراثا محشوة مع لبن",
  "Oats Khichdi": "خيتشدي الشوفان",
  "Roti with Bhindi": "روتي مع بندي",
  "Dal Tadka with Jeera Rice": "دال تadka مع أرز جييرا",
  "Vegetable Handvo": "خضار هاندفو",
  "Kadhi with Bajra Roti": "كادي مع روتي باجرا",
  "Tofu Curry with Quinoa": "كاري التوفو مع كينوا",
  "Bhakri with Thecha": "باكري مع ثيكا",
  "Biryani (Veg)": "برياني (خضار)",
  "Rajma with Brown Rice": "راجما مع أرز بني",
  "Daliya (Broken Wheat Porridge)": "داليا (عصيدة القمح المكسور)",
  "Pumpkin Sabzi with Chapati": "سبزي اليقطين مع شباتي",
  "Cauliflower Stir Fry": "قلي زهرة القرنبيط",
  "Boiled Egg Salad": "سلطة البيض المسلوق",
  "Tomato Rasam with Rice": "طماطم راسام مع الأرز",
  "Sweet Potato with Curd": "بطاطا حلوة مع الزبادي",
  "Stuffed Capsicum": "فلفل محشي",
  "Paneer Tikka with Mint Chutney": "بانير تيكا مع صلصة النعناع",
  "Rice with Sambar": "أرز مع سامبار",
  "Vegetable Thepla with Dahi": "ثيفلا بالخضروات مع الزبادي",
  "Grilled Mushroom Skewers": "أسياخ الفطر المشوي",
  "Beetroot Sabzi with Roti": "سبزي الشمندر مع الروتي",
  "Spinach Dal with Rice": "دال السبانخ مع الأرز",
  "Lentil Soup with Toast": "شوربة العدس مع التوست",
  "Tinda Curry with Chapati": "كاري التيندا مع الشاباتي",
  "Egg Bhurji with Roti": "بهورجي البيض مع الروتي",
  "Karela Sabzi with Roti": "سبزي الكاريلا مع الروتي",
  "Zucchini Stir Fry": "قلي الكوسا",
  "Low Carb Paneer Bowl": "وعاء بانير قليل الكربوهيدرات",
  "Stuffed Tomato": "طماطم محشوة",
  "Vegetable Rava Upma": "أوبما بالسميد والخضروات",
  "2 chapatis + sabzi": "خبزتان + سبزي",
  "1 fillet": "قطعة واحدة",
  "1 bowl + 1 roti": "وعاء واحد + روتي واحد",
  "1 plate": "طبق واحد",
  "1 cup rice + dal": "كوب أرز + دال",
  "1 paratha + ½ cup curd": "باراثا واحدة + نصف كوب زبادي",
  "2 rotis + bhindi": "روتيتان + بهيندي",
  "1 roti + 1 bowl kadhi": "روتي واحد + وعاء كادي واحد",
  "1 bhakri + chutney": "باهكري واحد + صلصة",
  "1 bowl curry + 1 roti": "وعاء كاري واحد + روتي واحد",
  "2 chillas": "شيلتان",
  "1 bowl + ½ cup curd": "وعاء واحد + نصف كوب زبادي",
  "1 serving": "حصة واحدة",
  "1 cup rice + sambar": "كوب أرز + سامبار",
  "1 thepla + curd": "ثيفلا واحدة + زبادي",
  "1 skewer": "أسياخ واحد",
  "1 bowl + 1 toast": "وعاء واحد + توست واحد",
  "1 bowl + 1 appam": "وعاء واحد + أبام واحد",
  "1 tomato": "طماطم واحدة",
  "Restore": "استرجاع",
  "Get Premium": "احصل على المزايا المميزة",
  "Get All The New Exciting Features": "احصل على جميع الميزات الجديدة المثيرة",
  "Unlock Food Scanner": "فتح ماسح الطعام",
  "Unlock Food Calorie": "فتح تقدير سعرات الطعام",
  "Unlock Unlimited Chat with Ai": "افتح الدردشة غير المحدودة مع الذكاء الاصطناعي",
  "Unlimited Food Scanner To Calorie": "ماسح طعام غير محدود لتقدير السعرات",
  "Most Popular": "الأكثر شهرة",
  "Subscription": "الاشتراك",
  "BUY NOW": "اشتر الآن",
  "Terms of Condition": "شروط الاستخدام",
  "Welcome": "أهلاً وسهلاً",
  "Calorie tracking made easy": "تتبع السعرات بات أسهل",
  "Just snap a quick photo of your meal and we''ll do the rest": "التقط صورة سريعة لوجبتك وسنتولّى الباقي",
  "In-depth nutrition analyses": "تحليلات غذائية معمّقة",
  "We will keep your informed about your food choicer and their nutritional content": "نُبقيك على اطلاع بخياراتك الغذائية ومحتواها التغذوي",
  "Transform your body": "حوّل جسدك",
  "Today is best time to start working toward your dream body": "اليوم هو أفضل وقت للبدء بالعمل نحو جسمك المنشود",
  "Where were you born?": "أين وُلدت؟",
  "This Will be used to calibrate your custom plan": "سيتم استخدام هذا لمعايرة خطتك المخصصة",
  "What's stopping you from reaching your goals?": "ما الذي يمنعك من تحقيق أهدافك؟",
  "Lack of consistency": "نقص في الاستمرارية",
  "Unhealthy eating habits": "عادات غذائية غير صحية",
  "Lack of supports": "نقص الدعم",
  "Busy schedule": "جدول مزدحم",
  "Lack of meal inspiration": "نقص الإلهام للوجبات",
  "We're setting": "نقوم بإعداد",
  "everything up for you": "كل شيء من أجلك",
  "Customizing health plan....": "جارٍ تخصيص الخطة الصحية...",

  // Scan result description
  "meal_description": "هذه الوجبة تحتوي على {cal} سعرة حرارية، و{protein} غ بروتين، و{carbs} غ كربوهيدرات، و{fat} غ دهون.",

  // Units and labels
  "kcal_unit": "سعرة",
  "gram_unit": "غ",
  "meal_label": "الوجبة"

};
