const Map<String, String> arabic = {
  // ==============================================================================
  // 1. Navigation & Common UI
  // ==============================================================================
  "Home": "الرئيسية",
  "Setting": "الإعدادات",
  "Profile": "الملف الشخصي",
  "View All": "عرض الكل",
  "Continue": "متابعة",
  "Previous": "السابق",
  "Cancel": "إلغاء",
  "Exit": "خروج",
  "Done": "تم",
  "Save": "حفظ",
  "Add": "إضافة",
  "Update": "تحديث",
  "Delete": "حذف",
  "delete_item": "حذف العنصر",
  "delete_item_confirmation": "هل أنت متأكد أنك تريد حذف هذا العنصر؟",
  "Delete Item": "حذف العنصر",
  "Are you sure you want to delete this item?":
      "هل أنت متأكد من رغبتك في حذف هذا العنصر؟",
  "Search": "بحث",
  "Clear Search": "مسح البحث",
  "Close": "إغلاق",
  "Next": "التالي",
  "Skip": "تخطي",
  "Ok": "حسنًا",
  "Got it": "حسنًا",
  "Maybe later": "ربما لاحقًا",

  // ==============================================================================
  // 2. Dashboard & Tracking (Home Screen)
  // ==============================================================================
  "Calorie": "السعرات الحرارية",
  "Analytics": "التحليلات",
  "Track Food": "تتبع الطعام",
  "Consumed": "المستهلك",
  "Remaining": "المتبقي",
  "Protein": "البروتين",
  "Carbs": "الكربوهيدرات",
  "Fats": "الدهون",
  "History": "السجل",
  "No History Yet": "لا يوجد سجل بعد",
  "Start tracking your meals to see your nutrition history here":
      "ابدأ بتتبع وجباتك لرؤية سجلك الغذائي هنا",
  "History not found": "لم يتم العثور على سجل",
  "Calorie Goal Reached": "تم الوصول للهدف من السعرات",
  "You've completed your calorie goal for today. Would you like to add more?":
      "لقد أكملت هدفك من السعرات الحرارية لهذا اليوم. هل ترغب في إضافة المزيد؟",
  "Add More Calories": "إضافة المزيد من السعرات",
  "Daily Usage": "الاستخدام اليومي",
  "Scans": "المسح",
  "Chat": "الدردشة",
  "Left": "متبقي",
  "Login to view usage": "سجل الدخول لعرض استخدامك",
  "Track subtitle": "تتبع تغذيتك اليومية",
  "Goal label": "الهدف",
  "Daily macros": "المغذيات اليومية",
  "Daily macros reached": "تم تحقيق أهداف المغذيات اليومية",
  "track_activity": "تتبع النشاط",
  "workouts_logged": "تمارين مسجلة",
  "total_duration": "المدة الإجمالية",
  "calories_burned": "سعرات محروقة",
  "no_workouts_today": "لا توجد تمارين مسجلة اليوم",

  // ==============================================================================
  // 3. Meals & Portions
  // ==============================================================================
  "BreakFast": "فطور",
  "Lunch": "غداء",
  "snack(s)": "وجبة خفيفة",
  "Dinner": "عشاء",
  "Which meal would you like to track?": "أي وجبة ترغب في تتبعها؟",
  "Meal Breakdown": "تفاصيل الوجبة",
  "Tap to edit portions": "اضغط لتعديل الحصص",
  "Items": "عناصر",
  "Verified": "مؤكد",
  "Estimated": "تقديري",
    "verified": "مؤكد",
    "estimated": "تقديري",
  "Meal contains": "هذه الوجبة تحتوي على",
  "Conjunction and": "و",
  "Meal label": "الوجبة",

  // ==============================================================================
  // 4. Camera & AI Scanning
  // ==============================================================================
  "Snap Tips": "نصائح للتصوير",
  "Too close": "قريب جدًا",
  "Too far": "بعيد جدًا",
  "Multi-species": "أصناف متعددة",
  "Gallery": "معرض الصور",
  "Tips": "نصائح",
  "Perfect Shot": "لقطة مثالية",
  "Well-lit, centered food": "طعام مضاء جيدًا وفي المنتصف",
  "Move camera back": "أبعد الكاميرا للخلف",
  "Move camera closer": "قرّب الكاميرا أكثر",
  "Center food in the frame and tap to scan":
      "ضع الطعام في منتصف الإطار واضغط للمسح",
  "Analyzing food...": "جاري تحليل الطعام...",
  "Analyzing nutrition...": "جاري تحليل التغذية...",
  "Grant camera access in scanner": "اضغط على الإطار لمنح الوصول إلى الكاميرا",
  "Camera permission denied title": "إذن الكاميرا مطلوب",
  "Camera permission denied message":
      "تم رفض الوصول إلى الكاميرا. يرجى تفعيل إذن الكاميرا من إعدادات الجهاز لاستخدام الماسح.",
  "Unlock Food Scanner": "فتح ماسح الطعام",
  "Unlock Food Calorie": "فتح سعرات الطعام",
  "Unlimited Food Scanner To Calorie": "ماسح طعام غير محدود للسعرات",
  "scans_remaining": "مسح متبقي",

  // ==============================================================================
  // 5. Food Search & Custom Foods
  // ==============================================================================
  "Local Food": "طعام محلي",
  "Search Food": "ابحث عن طعام",
  "No Food Found": "لم يتم العثور على طعام",
  "Try searching with different keywords or browse our local food database":
      "جرّب البحث بكلمات مختلفة أو تصفح قاعدة بياناتنا للطعام المحلي",
  "Search by Food Name/Dish": "ابحث باسم الطعام/الطبق",
  "popular food items": "عناصر غذائية شائعة",
  "food items found": "نتيجة موجودة",
  "Add custom food": "إضافة طعام مخصص",
  "Edit food": "تعديل الطعام",
  "Name": "الاسم",
  "Quantity": "الكمية",
  "Calories": "السعرات الحرارية",
  "Proteins": "بروتينات",
  "Custom Food": "طعام مخصص",
  "Delete selected": "حذف المحدد",
  "Food added success": "تمت إضافة الطعام بنجاح",
  "Food updated success": "تم تحديث الطعام بنجاح",
  "Food deleted success": "تم حذف @count عنصر بنجاح",
  "Local food premium message": "إنشاء وتعديل الأطعمة المخصصة هي ميزة مميزة.",
  "Local food premium badge":
      "قم بالترقية إلى بريميوم لإنشاء أطعمة مخصصة غير محدودة!",
  "Barcode activated": "الباركود مفعّل",
  "Barcode deactivated": "الباركود غير مفعّل",
  "Product not found": "المنتج غير موجود في قاعدة البيانات",
  "Error fetching product": "خطأ في جلب معلومات المنتج",

  // ==============================================================================
  // 6. Profile, Body Metrics & Goals
  // ==============================================================================
  "Personal details": "المعلومات الشخصية",
  "Weight Goal": "الوزن المستهدف",
  "Current Weight": "الوزن الحالي",
  "Update Weight": "تحديث الوزن",
  "Update Weight Goal": "تحديث الوزن المستهدف",
  "Enter new weight (kg)": "أدخل وزنك الجديد (كغ)",
  "Try to update once a week so we can adjust your plan to ensure you hit your goal":
      "حاول التحديث مرة أسبوعيًا حتى نتمكن من تعديل خطتك لضمان تحقيق هدفك",
  "Try to update once a week to help us adjust your plan":
      "حاول التحديث مرة أسبوعيًا لمساعدتنا في تعديل خطتك",
  "Weight Overview": "نظرة عامة على الوزن",
  "Current": "الحالي",
  "Goal": "الهدف",
  "To go": "متبقي",
  "Invalid number": "الرجاء إدخال رقم صالح",
  "Weight out of range": "الرجاء إدخال وزن بين 20 و 300 كغ",
  "Age": "العمر",
  "Height": "الطول",
  "Gender": "الجنس",
  "Male": "ذكر",
  "Female": "أنثى",
  "Update Your Gender": "تحديث جنسك",
  "Adjust goals": "تعديل الأهداف",
  "Calories,carbs,fat and protein": "السعرات، الكربوهيدرات، الدهون والبروتين",
  "Adjust goals subtitle": "السعرات، الكربوهيدرات، الدهون والبروتين",
  "Update Calorie Goal": "تحديث هدف السعرات",
  "Calorie goal": "هدف السعرات",
  "Update Protein Goal": "تحديث هدف البروتين",
  "Protein goal": "هدف البروتين",
  "Update Carb Goal": "تحديث هدف الكربوهيدرات",
  "Carb goal": "هدف الكربوهيدرات",
  "Update Fat Goal": "تحديث هدف الدهون",
  "Auto Generate Goal": "إنشاء هدف تلقائي",
  "Update targets title": "تم تحديث الأهداف",
  "Update targets body":
      "لقد قمنا بإعادة حساب أهدافك اليومية من السعرات الحرارية والمغذيات الكبرى لتتناسب مع وزنك الجديد.",
  "Kg": "كغ",
  "Lb": "رطل",
  "Ft": "قدم",
  "In": "بوصة",
  "Cm": "سم",
  "Imperial": "إمبراطوري",
  "Metric": "متري",

  // ==============================================================================
  // 7. Calendar & Time
  // ==============================================================================
  "Week": "أسبوع",
  "Month": "شهر",
  "Year": "سنة",
  "Day": "يوم",
  "Sun": "الأحد",
  "Mon": "الاثنين",
  "Tue": "الثلاثاء",
  "Wed": "الأربعاء",
  "Thu": "الخميس",
  "Fri": "الجمعة",
  "Sat": "السبت",
  "Jan": "يناير",
  "Feb": "فبراير",
  "Mar": "مارس",
  "Apr": "أبريل",
  "May": "مايو",
  "Jun": "يونيو",
  "Jul": "يوليو",
  "Aug": "أغسطس",
  "Sep": "سبتمبر",
  "Oct": "أكتوبر",
  "Nov": "نوفمبر",
  "Dec": "ديسمبر",
  "January": "يناير",
  "February": "فبراير",
  "March": "مارس",
  "April": "أبريل",
  "June": "يونيو",
  "July": "يوليو",
  "August": "أغسطس",
  "September": "سبتمبر",
  "October": "أكتوبر",
  "November": "نوفمبر",
  "December": "ديسمبر",
  "Calorie Your Week :": "سعراتك الأسبوعية:",
  "Average Calorie Month :": "متوسط السعرات الشهري:",
  "Average Calorie Yearly :": "متوسط السعرات السنوي:",

  // ==============================================================================
  // 8. Settings & Legal
  // ==============================================================================
  "Customization": "تخصيص",
  "Dark Mode": "الوضع الداكن",
  "Language": "اللغة",
  "Language english": "English",
  "Language french": "Français",
  "Language arabic": "العربية",
  "Chat history": "سجل المحادثات",
  "The coach does not memorize chat history. Each interaction is independent.":
      "لا يقوم المدرب بحفظ سجل المحادثات. كل تفاعل مستقل.",
  "Legal": "قانوني",
  "Terms and Condition": "الشروط والأحكام",
  "Privacy Policy": "سياسة الخصوصية",
  "Reset Data?": "إعادة تعيين البيانات؟",
  "Confirm Reset": "تأكيد إعادة التعيين",
  "Are you sure you want to Reset Data?":
      "هل أنت متأكد من رغبتك في إعادة تعيين البيانات؟",
  "Reset": "إعادة تعيين",
  "You have been Reset Account": "تمت إعادة تعيين حسابك",
  "VERSION": "الإصدار",
  "Home Screen Widgets": "أدوات الشاشة الرئيسية",
  "Exit app title": "الخروج من التطبيق",
  "Exit app message": "هل أنت متأكد أنك تريد الخروج؟",
  "Account": "الحساب",
  "Tap to view details": "انقر لعرض التفاصيل",
  "Register login": "تسجيل الدخول / إنشاء حساب",
  "Access account sync data": "الوصول إلى حسابك ومزامنة بياناتك",
  "App info": "معلومات التطبيق",
  "Clear all app data": "مسح كافة بيانات التطبيق",
  "Account reset success": "تمت إعادة تعيين الحساب بنجاح",

  // ==============================================================================
  // 9. Premium & Subscriptions
  // ==============================================================================
  "Premium Features": "الميزات المميزة",
  "Choose Your Plan": "اختر خطتك",
  "Subscription": "الاشتراك",
  "BUY NOW": "اشترِ الآن",
  "Get Premium": "احصل على بريميوم",
  "Get All The New Exciting Features": "احصل على جميع الميزات الجديدة والمثيرة",
  "Unlock Unlimited Chat with Ai":
      "فتح الدردشة غير المحدودة مع الذكاء الاصطناعي",
  "Most Popular": "الأكثر شيوعًا",
  "Premium badge": "بريميوم",
  "Go premium title": "الترقية إلى بريميوم",
  "Go premium subtitle": "التجربة الكاملة لأفضل برنامج غذائي",
  "Feature ai scan title": "تحكم في وزنك وتناول طعامًا أفضل",
  "Feature ai scan subtitle": "مع مسح الوجبات بالذكاء الاصطناعي وملاحظات يومية",
  "Feature results title": "حقق نتائج طويلة الأمد",
  "Feature results subtitle": "مع الطيار الآلي وتتبع المغذيات",
  "Feature chatbot title": "الدردشة الذكية \"المدرب\"",
  "Feature chatbot subtitle": "إرشاد غذائي فوري",
  "Feature recipes title": "وصفات وخطط بريميوم",
  "Feature recipes subtitle": "ترشدك نحو النجاح",
  "Best value": "أفضل قيمة",
  "Save percent": "وفّر @percent%*",
  "Months 12": "12 شهرًا",
  "Month 1": "شهر واحد",
  "Billed annually": "تتم الفوترة سنويًا",
  "Billed monthly": "تتم الفوترة شهريًا",
  "Per month": "شهريًا",
  "Continue cta": "متابعة",
  "Compared to monthly": "*مقارنة بالدفع الشهري",
  "currency_dzd": "دج",
  "Premium required": "الترقية إلى بريميوم مطلوبة",
  "Premium feature": "ميزة مميزة",
  "Go premium": "الترقية إلى بريميوم",

  // ==============================================================================
  // 10. Authentication & Onboarding
  // ==============================================================================
  "Login": "تسجيل الدخول",
  "Register": "إنشاء حساب",
  "Email": "البريد الإلكتروني",
  "Password": "كلمة المرور",
  "Confirm password": "تأكيد كلمة المرور",
  "First name": "الاسم الأول",
  "Last name": "الاسم الأخير",
  "Forgot password": "هل نسيت كلمة المرور؟",
  "Continue with google": "المتابعة باستخدام جوجل",
  "Continue with apple": "المتابعة باستخدام آبل",
  "Auth login success": "تم تسجيل الدخول بنجاح",
  "Auth register success": "تم إنشاء الحساب بنجاح",
  "Auth password reset sent": "تم إرسال بريد إعادة تعيين كلمة المرور",
  "Auth wrong credentials": "البريد الإلكتروني أو كلمة المرور غير صحيحة",
  "Auth account not found": "الحساب غير موجود",
  "Auth email in use": "هذا البريد الإلكتروني مستخدم بالفعل",
  "Auth weak password": "كلمة المرور ضعيفة جدًا",
  "Auth account different provider": "الحساب مرتبط بمزود تسجيل آخر",
  "Auth network error": "خطأ في الشبكة. يرجى التحقق من اتصالك.",
  "Auth unknown error": "حدث خطأ غير معروف",
  "Auth authentication error": "خطأ في المصادقة",
  "Auth apple cancelled": "تم إلغاء تسجيل الدخول عبر Apple",
  "Auth apple not handled": "تعذر معالجة تسجيل الدخول عبر Apple",
  "Auth apple not interactive": "تسجيل الدخول عبر Apple يتطلب تفاعل المستخدم",
  "Auth unexpected error": "خطأ غير متوقع",
  "Auth logout success": "تم تسجيل الخروج بنجاح",
  "Auth logout failed": "فشل تسجيل الخروج",
  "Auth modal title": "سجل الدخول للمتابعة",
  "Sign out title": "تسجيل الخروج؟",
  "Sign out confirmation": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
  "Sign out": "تسجيل الخروج",
  "Welcome": "أهلاً بك",
  "Choose Your Gender": "اختر جنسك",
  "Calorie tracking made easy": "تتبع السعرات أصبح سهلاً",
  "Just snap a quick photo of your meal and we''ll do the rest":
      "التقط صورة سريعة لوجبتك وسنتكفل بالباقي",
  "In-depth nutrition analyses": "تحليلات غذائية معمقة",
  "We will keep your informed about your food choicer and their nutritional content":
      "سنبقيك على اطلاع بخياراتك الغذائية ومحتواها الغذائي",
  "Transform your body": "غيّر جسدك",
  "Today is best time to start working toward your dream body":
      "اليوم هو أفضل وقت للبدء بالعمل نحو جسم أحلامك",
  "Where were you born?": "أين ولدت؟",
  "This Will be used to calibrate your custom plan":
      "سيُستخدم هذا لمعايرة خطتك المخصصة",
  "What's stopping you from reaching your goals?":
      "ما الذي يمنعك من تحقيق أهدافك؟",
  "Lack of consistency": "قلة الاستمرارية",
  "Unhealthy eating habits": "عادات أكل غير صحية",
  "Lack of supports": "نقص الدعم",
  "Busy schedule": "جدول أعمال مزدحم",
  "Lack of meal inspiration": "قلة الإلهام للوجبات",
  "We're setting": "نحن نقوم بإعداد",
  "everything up for you": "كل شيء من أجلك",
  "Customizing health plan....": "جاري تخصيص خطتك الصحية...",
  "Welcome hi": "مرحبًا!",
  "Welcome subtitle prefix": "مرحبًا بك في مدربك الشخصي ",
  "Welcome subtitle highlight": "مدرب التغذية",
  "Plan intro title": "لنبدأ ببعض الأسئلة",
  "Plan intro subtitle": "سيساعدنا هذا في تخصيص خطتك",
  "Your Plan is Ready!": "خطتك جاهزة!",
  "We have customized your nutrition plan based on your goals":
      "لقد قمنا بإعادة حساب أهدافك اليومية من السعرات الحرارية والمغذيات الكبرى لتتناسب مع وزنك الجديد.",
  "Daily Calorie Goal": "هدف السعرات الحرارية اليومية",
  "Macronutrients Breakdown": "توزيع المغذيات الكبرى",
  "This plan is based on your age, weight, height, activity level, and goals. You can adjust your daily intake in settings anytime.":
      "تعتمد هذه الخطة على عمرك ووزنك وطولك ومستوى نشاطك وأهدافك. يمكنك تعديل كمية الطعام اليومية في الإعدادات في أي وقت.",
  "Continue to Premium": "الاستمرار إلى Premium",
  "How many workout do you per week?": "كم مرة تتمرن في الأسبوع؟",
  "This will used to calibrate your custom plan":
      "سيُستخدم هذا لمعايرة خطتك المخصصة",
  "Choose your height and weight": "اختر طولك ووزنك",
  "Select your height and weight to calibrate your custom plan":
      "حدد طولك ووزنك لمعايرة خطتك المخصصة",
  "Workout Now and then": "أحياناً",
  "A few workout per week": "بضع مرات في الأسبوع",
  "Dedicated athlete": "رياضي ملتزم",
  "What is your goal?": "ما هو هدفك؟",
  "This helps is generate a plan for your calorie intake.":
      "هذا يساعد في إنشاء خطة لاستهلاكك من السعرات الحرارية.",
  "Gain Weight": "زيادة الوزن",
  "Maintain Weight": "الحفاظ على الوزن",
  "Lose Weight": "خسارة الوزن",

  // ==============================================================================
  // 11. Email Verification & Account Management
  // ==============================================================================
  "Email verification title": "التحقق من بريدك الإلكتروني",
  "Email verification subtitle": "تحقق من بريدك الإلكتروني للمتابعة",
  "Email sent to": "لقد أرسلنا رابط التحقق إلى @email",
  "Email verification instructions":
      "انقر على الرابط في بريدك الإلكتروني للتحقق من حسابك. هذا يساعدنا في الحفاظ على أمان حسابك.",
  "Checking verification status": "جاري التحقق من الحالة...",
  "Resend verification email": "إعادة إرسال بريد التحقق",
  "Resend cooldown": "يمكنك إعادة الإرسال بعد @seconds ثانية",
  "Resend limit reached": "تبقى @attempts محاولات",
  "Verification attempts remaining": "تبقى @remaining من @total محاولات",
  "Email verification success":
      "تم التحقق من البريد الإلكتروني بنجاح! مرحبًا بك في ماكروآيز",
  "Email verification resent": "تم إرسال بريد التحقق! يرجى مراجعة بريدك الوارد",
  "Email verification resend error":
      "فشل إرسال بريد التحقق. يرجى المحاولة مرة أخرى",
  "Email verification max attempts":
      "لقد وصلت إلى الحد الأقصى للمحاولات. يرجى المحاولة لاحقًا",
  "Email verification cooldown":
      "يرجى الانتظار @seconds ثانية قبل طلب بريد آخر",
  "Skip verification title": "تخطي التحقق؟",
  "Skip verification warning":
      "سيسمح لك هذا بالوصول دون التحقق من البريد الإلكتروني. لا يوصى به لأسباب أمنية.",
  "Skip anyway": "تخطي على أي حال",
  "Skip verification": "تخطي التحقق",
  "Verify": "تحقق",
  "Email verification error":
      "فشل التحقق من البريد الإلكتروني. يرجى المحاولة مرة أخرى",
  "Auth required": "مطلوب تسجيل الدخول للمتابعة",
  "Email verification required for feature":
      "التحقق من البريد الإلكتروني مطلوب لاستخدام هذه الميزة",
  "Email verification required for premium":
      "التحقق من البريد الإلكتروني مطلوب للوصول إلى الميزات المميزة",
  "Email verification required for scan":
      "التحقق من البريد الإلكتروني مطلوب لاستخدام ماسح الطعام",
  "Email verification required for chat":
      "التحقق من البريد الإلكتروني مطلوب للدردشة مع المدرب الذكي",
  "Email verification required for app access":
      "التحقق من البريد الإلكتروني مطلوب للوصول إلى التطبيق",
  "Email verified status": "تم التحقق",
  "Email unverified status": "لم يتم التحقق",
  "Email verified": "تم التحقق من البريد الإلكتروني",
  "Email verification complete subtitle": "حسابك آمن وجاهز للاستخدام",
  "Email verification required": "التحقق من البريد الإلكتروني مطلوب",
  "Email verification required subtitle":
      "يرجى التحقق من @email للوصول إلى كافة الميزات",
  "Verify email": "التحقق من البريد الإلكتروني",
  "Verify now": "تحقق الآن",
  "Refresh": "تحديث",
  "Refresh failed": "فشل تحديث الحالة. يرجى المحاولة مرة أخرى",
  "Tap to verify email": "انقر للتحقق من بريدك الإلكتروني",
  "Account activation required": "تفعيل الحساب مطلوب",
  "Account activation required for chat":
      "يرجى تفعيل حسابك لاستخدام المدرب الذكي",
  "Account activation required for scanner":
      "يرجى تفعيل حسابك لاستخدام ماسح الطعام",
  "Account activation required for premium":
      "يرجى تفعيل حسابك لشراء النسخة المميزة",
  "Verify account to continue": "تحقق من حسابك للمتابعة",
  "Auth register verification required":
      "تم إنشاء الحساب! يرجى مراجعة بريدك الإلكتروني للتحقق من حسابك.",
  "Account details title": "تفاصيل الحساب",
  "No name": "لا يوجد اسم",
  "Name label": "الاسم",
  "Email label": "البريد الإلكتروني",
  "Change password": "تغيير كلمة المرور",
  "Logout": "تسجيل الخروج",
  "Display name updated": "تم تحديث اسم العرض",
  "Edit display name": "تعديل اسم العرض",
  "New display name": "اسم العرض الجديد",
  "Password changed message":
      "تم تغيير كلمة المرور بنجاح. يرجى تسجيل الدخول مرة أخرى.",
  "Current password incorrect": "كلمة المرور الحالية غير صحيحة.",
  "Too many attempts": "محاولات كثيرة جدًا. يرجى المحاولة لاحقًا.",
  "too_many_attempts": "محاولات كثيرة جدًا. يرجى المحاولة لاحقًا.",
  "please_relogin": "يرجى تسجيل الدخول مرة أخرى ثم المحاولة من جديد.",
  "Please relogin": "يرجى إعادة تسجيل الدخول والمحاولة مرة أخرى.",
  "Operation failed": "فشلت العملية.",
  "Current password label": "كلمة المرور الحالية",
  "New password label": "كلمة المرور الجديدة",
  "Confirm new password label": "تأكيد كلمة المرور الجديدة",
  "Min 8 chars": "8 أحرف على الأقل",
  "Password complexity hint":
      "استخدم حرفًا كبيرًا، حرفًا صغيرًا، رقمًا، ورمزًا",
  "Must differ from current": "يجب أن تكون مختلفة عن الحالية",
  "Does not match": "غير متطابق",
  "Change password cta": "تغيير كلمة المرور",
  "Email required": "البريد الإلكتروني مطلوب",
  "Required": "مطلوب",
  "Invalid email format": "صيغة البريد الإلكتروني غير صحيحة",
  "Password required": "كلمة المرور مطلوبة",
  "Password min length": "8 أحرف على الأقل",
  "Password complexity": "استخدم حروفًا كبيرة وصغيرة وأرقامًا ورموزًا",
  "Name required": "مطلوب",
  "Name too short": "قصير جدًا",
  "Passwords do not match": "كلمتا المرور غير متطابقتين",
  "Please fix errors": "يرجى إصلاح الأخطاء",
  "Accept terms of service": "يرجى قبول شروط الخدمة",
  "By registering agree": "بالتسجيل، فإنك توافق على ",
  "Terms of service": "شروط الخدمة",

  // ==============================================================================
  // 12. Influencer & Promo
  // ==============================================================================
  "influencer_program": "برنامج المؤثرين",
  "your_promo_code": "رمز الخصم الخاص بك",
  "copied": "تم النسخ",
  "current_balance": "الرصيد الحالي",
  "total_earned": "إجمالي الأرباح",
  "referrals_count": "عدد الإحالات",
  "request_withdrawal": "طلب سحب",
  "withdrawal_subtitle": "احصل على أرباحك المحولة إلى حسابك البنكي",
  "confirm_withdrawal": "تأكيد السحب",
  "rip_helper_text": "رقم حسابك البنكي المكون من 20 رقمًا (RIP)",
  "withdrawal_info_message":
      "سيتم معالجة طلب السحب الخاص بك خلال 3-5 أيام عمل. ستتلقى بريدًا إلكترونيًا للتأكيد بمجرد الانتهاء.",
  "minimum_withdrawal_amount": "الحد الأدنى للسحب: @amount دج",
  "withdrawal_history": "سجل السحوبات",
  "promo_code_expired": "انتهت صلاحية رمز الخصم",
  "promo_expires_in": "ينتهي الرمز خلال @days يوم",
  "promo_expires_on": "ينتهي الرمز في @date",
  "promo_code_copied": "تم نسخ رمز الخصم",
  "promo_code": "رمز الخصم",
  "enter_promo_code": "أدخل رمز الخصم",
  "apply_promo_code": "تطبيق",
  "skip_promo_code": "تخطي",
  "promo_code_applied": "تم تطبيق رمز الخصم بنجاح!",
  "promo_code_invalid": "رمز الخصم غير صالح",
  "promo_code_dialog_title": "هل لديك رمز خصم؟",
  "promo_code_dialog_subtitle": "أدخل رمز الخصم للاستفادة من الخصم",
  "Have a Promo Code?": "هل لديك رمز خصم؟",
  "Enter your promo code to get 3 days free trial":
      "أدخل رمز الخصم للحصول على 3 أيام تجربة مجانية",
  "ENTER CODE": "أدخل الرمز",
  "Validate Code": "تحقق من الرمز",
  "Promo code applied successfully!": "تم تطبيق رمز الخصم بنجاح!",
  "promo_code_linked_success": "تم ربط رمز الخصم! ستحصل على أيام إضافية.",
  "promo_code_title": "احصل على أيام إضافية!",
  "promo_code_subtitle": "أدخل رمز خصم للحصول على أيام مجانية إضافية",
  "promo_benefit_title": "مكافأتك",
  "promo_benefit_monthly": "+3 أيام إضافية للاشتراك الشهري",
  "promo_benefit_yearly": "+شهر إضافي للاشتراك السنوي",
  "promo_dialog_title": "هل لديك رمز خصم؟",
  "promo_dialog_benefit": "احصل على @days إضافية على اشتراكك!",
  "bonus_3_days": "+3 أيام",
  "bonus_1_month": "+1 شهر",
  "restore_in_progress": "جاري استعادة المشتريات...",
  "restore_success": "تم استعادة المشتريات بنجاح!",
  "restore_no_purchases": "لم يتم العثور على مشتريات سابقة.",
  "restore_failed": "فشل في استعادة المشتريات. يرجى المحاولة مرة أخرى.",
  "redeem_code": "استخدام رمز",
  "already_premium": "أنت بالفعل مشترك Premium",
  "already_premium_subscription": "لديك بالفعل اشتراك Premium نشط",
  "continue_for_free": "متابعة مجاناً",
  "restore_purchases": "استعادة المشتريات",
  "restore_purchases_info":
      "استعد مشترياتك إذا اشتركت في Premium من جهاز أو حساب آخر.",
  "no_offers_available": "لا توجد عروض متاحة",
  "no_offers_moment": "لا توجد عروض متاحة في الوقت الحالي.",
  "failed_load_offers": "فشل في تحميل العروض. يرجى المحاولة مرة أخرى.",
  "premium_offers_error_title": "خطط Premium غير متاحة حالياً",
  "premium_offers_empty_body":
      "لم نعثر على خطط اشتراك نشطة الآن. يرجى المحاولة مرة أخرى بعد قليل.",
  "premium_offers_fetch_failed_body":
      "تعذر تحديث الخطط الآن. تحقق من الاتصال ثم حاول مرة أخرى.",
  "premium_try_again_button": "حاول مرة أخرى",
  "purchase_successful_verifying": "تم الشراء بنجاح. جاري التحقق...",
  "subscription_active": "الاشتراك نشط!",
  "purchase_cancelled": "تم إلغاء الشراء",
  "purchase_failed": "فشل الشراء. يرجى المحاولة مرة أخرى.",
  "login_to_continue": "يرجى تسجيل الدخول للمتابعة",
  "auth_failed": "فشل المصادقة",
  "unable_verify_subscription":
      "تعذر التحقق من حالة الاشتراك. يرجى المحاولة مرة أخرى.",
  "subscription_already_active_play":
      "هذا الاشتراك نشط بالفعل على حساب Play هذا. يرجى تسجيل الدخول بحساب التطبيق الأصلي.",
  "subscription_temporarily_unavailable":
      "هذا الاشتراك غير متاح مؤقتاً. يرجى المحاولة لاحقاً أو الاتصال بالدعم.",
  "subscriptions_disabled":
      "الاشتراكات غير متاحة حالياً. يرجى المحاولة لاحقاً.",
  "manage_on_store": "إدارة على @store",
  "per_month_label": "شهرياً",
  "daily_usage": "الاستخدام اليومي",
  "go_premium": "اشترك Premium",
  "apply": "تطبيق",
  "invalid_promo_code": "رمز الخصم غير صالح",
  "Please enter a promo code": "الرجاء إدخال رمز الخصم",
  "Invalid promo code": "رمز الخصم غير صالح",
  "Login Required": "تسجيل الدخول مطلوب",
  "You need to login to activate this promo code":
      "تحتاج إلى تسجيل الدخول لتفعيل رمز الخصم هذا",
  "Your promo code will be saved and activated after login":
      "سيتم حفظ رمز الخصم الخاص بك وتفعيله بعد تسجيل الدخول",
  "Skip Login?": "تخطي تسجيل الدخول؟",
  "If you skip, the promo code will not be activated. Are you sure?":
      "إذا تخطيت، لن يتم تفعيل رمز الخصم. هل أنت متأكد؟",
  "Go Back": "العودة",
  "Skip Anyway": "تخطي على أي حال",
  "Login to Activate": "تسجيل الدخول للتفعيل",
  "promo_code_valid_title": "تم التحقق من رمز الخصم!",
  "promo_activation_required": "يتطلب تسجيل الدخول",
  "promo_login_required_message":
      "لتفعيل رمز الخصم هذا، يجب عليك تسجيل الدخول إلى حسابك الحالي. رمز الخصم لن يعمل مع حساب جديد.",
  "promo_must_login_note": "رموز الخصم متاحة فقط للمستخدمين الحاليين",
  "skip_login": "تخطي تسجيل الدخول",
  "login_to_activate": "تسجيل الدخول للتفعيل",
  "confirm_skip_login": "هل أنت متأكد؟",
  "promo_will_not_activate":
      "إذا تابعت دون تسجيل الدخول، لن يتم تفعيل رمز الخصم هذا. ستفقد الوصول إلى الخصم.",
  "go_back": "العودة",
  "skip_anyway": "تخطي على أي حال",
  "available_balance": "الرصيد المتاح",
  "withdrawal_amount": "مبلغ السحب",
  "enter_amount": "أدخل المبلغ",
  "bank_account_rip": "الحساب البنكي (RIP)",
  "enter_rip_number": "أدخل رقم RIP",
  "withdrawal_processing_info": "تتم معالجة السحوبات في غضون 5 أيام عمل.",
  "requested_on": "تم الطلب في @date",
  "unknown_date": "تاريخ غير معروف",
  "withdrawal_submitted": "تم إرسال طلب السحب",
  "request_id": "معرف الطلب: @id",
  "processing_time": "وقت المعالجة: @days أيام عمل",
  "withdrawal_email_confirmation":
      "ستصلك رسالة تأكيد عبر البريد الإلكتروني بمجرد معالجة طلب السحب.",
  "processing": "قيد المعالجة",
  "copy_failed": "فشل النسخ: @error",
  "request_id_short": "المعرف",
  "bank_account_short": "الحساب",
  "processing_date": "تاريخ المعالجة",
  "processing_deadline": "الموعد النهائي",
  "requested_date": "تاريخ الطلب",
  "completed": "مكتمل",
  "failed": "فشل",
  "email_verification_required_withdrawal":
      "التحقق من البريد الإلكتروني مطلوب للسحب",
  "showing_recent_withdrawals": "عرض @shown من @total سحوبات",
  "withdrawal_history_full": "سجل السحوبات",
  "no_withdrawal_history": "لا يوجد سجل سحوبات",
  "withdrawal_history_empty_description":
      "اطلب سحبك الأول لرؤية سجل معاملاتك هنا",
  "view_withdrawal_history": "عرض سجل السحوبات",
  "withdrawal_history_subtitle": "تتبع جميع طلبات السحب الخاصة بك",

  // ==============================================================================
  // 13. AI Coach & Chat
  // ==============================================================================
  "Ask anything": "اسأل أي شيء",
  "Ask The Coach": "اسأل المدرب",
  "This picture not available Calorie,Protein,Carbs and Fats,":
      "هذه الصورة لا تحتوي على معلومات السعرات الحرارية، البروتين، الكربوهيدرات والدهون.",
  "Ask Coach": "اسأل المدرب",
  "Write your message": "اكتب رسالتك",
  "Chat image premium message":
      "إرفاق الصور يتطلب اشتراكًا مميزًا. قم بالترقية الآن لفتح هذه الميزة.",
  "Chat image premium badge": "افتح إرفاق الصور للمدرب مع بريميوم",

  // ==============================================================================
  // 14. Recipes
  // ==============================================================================
  "Recipes title": "الوصفات",
  "Top recipes": "أفضل الوصفات",
  "All recipes": "كل الوصفات",
  "Less text": "أقل ^",
  "Macronutrients": "المغذيات الكبرى",
  "Ingredients": "المكونات",
  "Serving": "الحصة",
  "Directions": "الخطوات",
  "Add to plan": "أضف إلى الخطة",
  "Step": "خطوة",
  "Top recipes subtitle": "اكتشف وصفات صحية ولذيذة مصممة لأهدافك",
  "No recipes available": "لا توجد وصفات متاحة",
  "Search recipes by name or ingredient": "ابحث عن وصفات بالاسم أو المكونات",
  "Failed to load recipes": "فشل تحميل الوصفات. يرجى المحاولة مرة أخرى.",
  "Recipes premium message":
      "الوصول إلى الوصفات يتطلب اشتراكًا مميزًا. قم بالترقية الآن لفتح هذه الميزة.",
  "Recipes premium badge": "افتح جميع الوصفات والميزات مع بريميوم",

  // ==============================================================================
  // 15. Tutorials & Tips
  // ==============================================================================
  "App tips": "نصائح التطبيق",
  "Tip welcome title": "مرحباً بك في macroAize!",
  "Tip welcome description":
      "متتبع التغذية الشخصي الخاص بك المدعوم بالذكاء الاصطناعي. لنقم بجولة سريعة لمساعدتك على البدء في رحلتك الصحية.",
  "Tip track food title": "تتبع وجباتك",
  "Tip track food description":
      "اضغط على زر + في الشاشة الرئيسية لتسجيل وجباتك. اختر بين الإفطار أو الغداء أو العشاء أو الوجبات الخفيفة للحفاظ على سجلات دقيقة.",
  "Tip scan food title": "المسح بالذكاء الاصطناعي",
  "Tip scan food description":
      "التقط صورة لطعامك وسيقوم الذكاء الاصطناعي الخاص بنا بتحليل وحساب السعرات الحرارية والبروتين والكربوهيدرات والدهون على الفور.",
  "Tip ai coach title": "تحدث مع المدرب الذكي",
  "Tip ai coach description":
      "احصل على نصائح غذائية مخصصة واقتراحات للوجبات وإجابات على أسئلتك الصحية من مدربنا الذكي في أي وقت.",
  "Tip analytics title": "تتبع تقدمك",
  "Tip analytics description":
      "اعرض تحليلات مفصلة لاتجاهات التغذية الخاصة بك، وتقدم الوزن، وتوزيع الماكروز للبقاء على المسار الصحيح نحو أهدافك.",
  "Tutorial tap to continue": "اضغط في أي مكان للمتابعة",
  "Tutorial step": "خطوة",
  "Tutorial add food title": "تتبع وجباتك",
  "Tutorial add food description":
      "اضغط على زر '+' لإضافة طعام إلى سجلك اليومي. يمكنك البحث أو المسح أو إضافة أطعمة مخصصة.",
  "Tutorial scanner title": "ماسح الطعام بالذكاء الاصطناعي",
  "Tutorial scanner description":
      "استخدم الماسح الضوئي المدعوم بالذكاء الاصطناعي لتحليل طعامك على الفور والحصول على معلومات غذائية دقيقة.",
  "Tutorial ai coach title": "مدرب التغذية بالذكاء الاصطناعي",
  "Tutorial ai coach description":
      "تحدث مع مدربك الشخصي بالذكاء الاصطناعي للحصول على نصائح مخصصة واقتراحات وجبات وإرشادات غذائية.",
  "Tutorial analytics title": "تتبع تقدمك",
  "Tutorial analytics description":
      "اعرض تحليلاتك الغذائية وتقدم وزنك واتجاهاتك اليومية لتبقى على المسار الصحيح نحو أهدافك.",
  "Tutorial profile title": "ملفك الشخصي",
  "Tutorial profile description":
      "الوصول إلى إعداداتك، وضبط أهدافك، وتخصيص تجربتك في قسم الملف الشخصي.",
  "Widget promo title": "إضافة أداة إلى الشاشة الرئيسية",
  "Widget promo android instructions":
      "اضغط مطولاً على شاشتك الرئيسية، اختر 'Widgets' وابحث عن 'macroAize' لإضافته للوصول السريع!",
  "Widget promo ios step1": "اضغط مطولاً في أي مكان على شاشتك الرئيسية.",
  "Widget promo ios step2": "اضغط على زر '+' في الزاوية العلوية اليسرى.",
  "Widget promo ios step3": "ابحث عن 'macroAize' واختر الأداة الخاصة بك.",
  "Widget promo got it": "حسنًا!",

  // ==============================================================================
  // 16. Units & Labels
  // ==============================================================================
  "Kcal unit": "سعرة",
  "Gram unit": "غ",
  "Unit piece": "قطعة",
  "Protein unit": "غ",
  "Carbs unit": "غ",
  "Fat unit": "غ",
  "Cals": "سعرات",
  "Prot": "بروتين",
  "Nut prt": "بروتين",
  "Nut carb": "كربوهيدرات",
  "Nut cal": "سعرات",
  "Nut fat": "دهون",
  "Min": "دقيقة",
  "Cal": "سعرة",
  "Success": "نجاح",
  "Nutrition details": "تفاصيل التغذية",
  "Fats label": "الدهون",
  "Log": "سجل",
  "Unknown meal": "وجبة غير معروفة",
  "Goal achieved message": "لقد حققت هدفك! استمر في التقدم.",
  "On a roll message": "أنت على المسار الصحيح — كل خطوة مهمة!",
  "Keep momentum message": "أنت تحرز تقدمًا — حافظ على هذا الزخم!",

  // ==============================================================================
  // 17. Food Items Database
  // ==============================================================================
  "Boiled Egg": "بيضة مسلوقة",
  "Oatmeal": "شوفان",
  "Banana": "موز",
  "Paratha": "باراثا",
  "Idli": "إدلي",
  "Dosa": "دوسا",
  "Upma": "أبما",
  "Poha": "بواها",
  "Bread Butter": "خبز وزبدة",
  "Cornflakes with Milk": "رقائق الذرة مع الحليب",
  "Chilla (Besan)": "تشيلا (بيسان)",
  "Sprouts Salad": "سلطة براعم",
  "Pancakes": "بان كيك",
  "Apple": "تفاح",
  "Milk": "حليب",
  "Almonds": "لوز",
  "Smoothie (Fruit)": "سموذي (فواكه)",
  "Yogurt (Plain)": "زبادي (طبيعي)",
  "Khichdi": "كيتشدي",
  "Thepla": "ثيبلا",
  "Cheela (Moong dal)": "تشيلا (عدس)",
  "Pav Bhaji": "باف باجي",
  "Sabudana Khichdi": "سابودانا كيتشدي",
  "Roti with Sabzi": "روتي مع خضروات",
  "Peanut Butter Bread": "خبز بزبدة الفول السوداني",
  "Fruit Bowl": "وعاء فواكه",
  "Vegetable Sandwich": "ساندويتش خضروات",
  "Rice Idli with Sambar": "إدلي أرز مع سامبار",
  "Boiled Corn": "ذرة مسلوقة",
  "Paneer Bhurji": "بانير بهورجي",
  "Protein Shake": "مشروب بروتين",
  "Muesli with Milk": "ميوسلي مع الحليب",
  "Chapati with Curd": "تشاباتي مع زبادي",
  "Porridge (Daliya)": "عصيدة (داليا)",
  "Rava Upma": "رافا أبما",
  "Chickpea Salad": "سلطة حمص",
  "Boiled Sweet Potato": "بطاطا حلوة مسلوقة",
  "Coconut Water": "ماء جوز الهند",
  "Masala Omelette": "أومليت ماسالا",
  "Vegetable Poha": "بوها بالخضروات",
  "1 egg": "بيضة واحدة",
  "1 bowl": "وعاء واحد",
  "1 medium": "واحدة متوسطة",
  "1 piece": "قطعة واحدة",
  "1 cup": "كوب واحد",
  "2 slices": "شريحتان",
  "2 small pieces": "قطعتان صغيرتان",
  "10 pieces": "10 قطع",
  "1 glass": "كأس واحد",
  "2 pavs + bhaji": "2 باف + باجي",
  "1 roti + sabzi": "1 روتي + خضروات",
  "1 sandwich": "ساندويتش واحد",
  "2 idlis + sambar'": "2 إدلي + سامبار",
  "1 chapati + ½ cup curd": "1 تشاباتي + نصف كوب زبادي",
  "Rice with Dal": "أرز مع عدس",
  "Grilled Chicken": "دجاج مشوي",
  "Paneer Curry": "كاري بانير",
  "Mixed Vegetable Curry": "كاري خضروات مشكلة",
  "Chapati with Daal": "تشاباتي مع عدس",
  "Fish Curry with Rice": "كاري سمك مع أرز",
  "Rajma Chawal": "راجما تشاول",
  "Chole Bhature": "تشولي بهاتور",
  "Kadhi with Rice": "كادهي مع أرز",
  "Palak Paneer": "بانير بالسبانخ",
  "Stuffed Paratha": "باراثا محشوة",
  "Veg Pulao": "بيلاف نباتي",
  "Biryani with Raita": "برياني مع رايتا",
  "Tofu Stir Fry": "توفو مقلي",
  "Chicken Tikka": "دجاج تكا",
  "Veg Fried Rice": "أرز مقلي بالخضروات",
  "Aloo Gobi with Roti": "بطاطا وقرنبيط مع روتي",
  "Baingan Bharta": "باذنجان بهارتا",
  "Sambar with Rice": "سامبار مع أرز",
  "Chicken Curry with Roti": "كاري دجاج مع روتي",
  "Bhindi Masala with Roti": "بامية ماسالا مع روتي",
  "Egg Curry with Rice": "كاري بيض مع أرز",
  "Lentil Soup with Bread": "شوربة عدس مع خبز",
  "Methi Thepla with Curd": "ثيبلا مع زبادي",
  "Soybean Curry with Rice": "كاري صويا مع أرز",
  "Cabbage Sabzi with Chapati": "ملفوف مع تشاباتي",
  "Dal Makhani with Naan": "دال مخني مع نان",
  "Vegetable Korma with Roti": "كورما خضروات مع روتي",
  "Tandoori Roti with Paneer": "روتي تندوري مع بانير",
  "Mixed Dal with Rice": "عدس مشكل مع أرز",
  "Bottle Gourd Curry with Roti": "كاري قرع مع روتي",
  "Kofta Curry with Roti": "كاري كفتة مع روتي",
  "Paneer Bhurji with Bread": "بانير بهورجي مع خبز",
  "Chana Masala with Rice": "حمص ماسالا مع أرز",
  "Curd Rice": "أرز بالزبادي",
  "Tomato Rice": "أرز بالطماطم",
  "Vegetable Stew with Appam": "يخنة خضروات مع أبام",
  "Dhokla with Green Chutney": "دوكلا بصلصة خضراء",
  "Besan Chilla with Salad": "بيسان تشيلا مع سلطة",
  "Lauki Chana Dal": "قرع بعدس الحمص",
  "Spinach Corn Curry": "كاري سبانخ بالذرة",
  "Tinda Masala with Roti": "تيندا ماسالا مع روتي",
  "Masoor Dal with Rice": "عدس ماسور مع أرز",
  "Vegetable Handi with Naan": "هندي خضروات مع نان",
  "Egg Bhurji with Chapati": "بيض بهورجي مع تشاباتي",
  "Pumpkin Curry with Rice": "كاري يقطين مع أرز",
  "2 rotis + sabzi": "2 روتي + خضروات",
  "1 cup rice + 1 cup dal": "1 كوب أرز + 1 كوب عدس",
  "1 breast": "صدر واحد",
  "2 chapatis + dal'": "2 تشاباتي + عدس",
  "1 bowl curry + 1 cup rice": "وعاء كاري + كوب أرز",
  "1 bhatura + chole": "1 بهاتورا + تشولي",
  "1 paratha": "1 باراثا",
  "1 bowl + 2 rotis": "وعاء + 2 روتي",
  "1 cup + 1 bowl": "كوب + وعاء",
  "1 bowl + 1 cup rice": "وعاء + كوب أرز",
  "1 bowl + 1 bread slice": "وعاء + شريحة خبز",
  "2 theplas + ½ cup curd": "2 ثيبلا + نصف كوب زبادي",
  "1 bowl + 2 chapatis": "وعاء + 2 تشاباتي",
  "1 bowl + 1 naan": "وعاء + 1 نان",
  "2 rotis + paneer": "2 روتي + بانير",
  "1 bowl + 2 slices": "وعاء + شريحتان",
  "1 bowl + 2 appams": "وعاء + 2 أبام",
  "3 pieces": "3 قطع",
  "2 chillas + salad": "2 تشيلا + سلطة",
  "Fruit Salad": "سلطة فواكه",
  "Roasted Chickpeas": "حمص محمص",
  "Mixed Nuts": "مكسرات مشكلة",
  "Yogurt with Honey": "زبادي بالعسل",
  "Apple with Peanut Butter": "تفاحة مع زبدة الفول السوداني",
  "Protein Bar": "بار بروتين",
  "Whole Wheat Crackers": "مقرمشات القمح الكامل",
  "Granola Bar": "بار جرانولا",
  "Peanut Chikki": "شيكي الفول السوداني",
  "Bhel Puri": "بيل بوري",
  "Khakra": "خاكرا",
  "Masala Makhana": "ماسالا ماخانا",
  "Hummus with Veggies": "حمص مع خضروات",
  "Paneer Cubes": "مكعبات بانير",
  "Milkshake (Low Sugar)": "ميلك شيك (قليل السكر)",
  "Dhokla": "دوكلا",
  "Vegetable Soup": "شوربة خضروات",
  "Idli with Chutney": "إيدلي مع صلصة",
  "Cheese Slice": "شريحة جبن",
  "Chana Chaat": "شانا شات",
  "Moong Dal Chilla": "مونج دال تشيلا",
  "Rice Cake with Peanut Butter": "كعكة أرز مع زبدة الفول السوداني",
  "Popcorn (Air-popped)": "فشار",
  "Avocado Toast": "توست الأفوكادو",
  "Stuffed Dates": "تمر محشي",
  "Oats Cookies": "كوكيز الشوفان",
  "Fruit Smoothie": "سموذي فواكه",
  "Carrot Sticks with Hummus": "أصابع الجزر مع الحمص",
  "Soy Nuts": "مكسرات الصويا",
  "Trail Mix": "مكسرات مشكلة",
  "Besan Ladoo": "بسان لادو",
  "Upma (small portion)": "أبما (كمية صغيرة)",
  "Egg Roll (Mini)": "رول بيض (صغير)",
  "Rice Idli": "إيدلي أرز",
  "Cucumber Sandwich": "ساندويتش خيار",
  "Fruit Chaat": "فواكه شات",
  "Lassi (Sweet)": "لاسي (حلو)",
  "Cold Coffee (Low Sugar)": "قهوة باردة (قليلة السكر)",
  "Rava Dhokla": "رافا دوكلا",
  "Vegetable Cutlet": "كوتليت خضروات",
  "Chikki with Jaggery": "شيكي مع جاجري",
  "Milk (Low Fat)": "حليب (قليل الدسم)",
  "Baked Samosa": "ساموسا مخبوزة",
  "Vegetable Wrap": "راب خضروات",
  "Roasted Soybeans": "فول الصويا المحمص",
  "1/2 cup": "نصف كوب",
  "1 handful": "حفنة",
  "1 apple + 1 tbsp PB": "تفاحة + 1 ملعقة كبيرة زبدة فول سوداني",
  "1 bar": "بار واحد",
  "5 pieces": "5 قطع",
  "½ cup hummus + veggies": "نصف كوب حمص + خضروات",
  "50g": "50 جرام",
  "1 idli + chutney": "1 إيدلي + صلصة",
  "1 slice": "شريحة واحدة",
  "1 chilla": "1 تشيلا",
  "1 cake + 1 tbsp PB": "1 كعكة + 1 ملعقة كبيرة زبدة فول سوداني",
  "2 cups": "كوبان",
  "1 toast": "شريحة توست واحدة",
  "3 dates": "3 تمرات",
  "2 cookies": "قطعتان كوكيز",
  "½ cup": "نصف كوب",
  "1 small bowl": "وعاء صغير",
  "1 roll": "رول واحد",
  "1 wrap": "راب واحد",
  "Chapati with Sabzi": "شاباتي مع سبزي",
  "Grilled Fish": "سمك مشوي",
  "Moong Dal Khichdi": "مونج دال كيتشدي",
  "Paneer Bhurji with Roti": "بانير بهورجي مع روتي",
  "Brown Rice with Veg Curry": "أرز بني مع كاري الخضروات",
  "Quinoa with Stir Fry Veggies": "كينوا مع خضروات مقلية",
  "Grilled Tofu with Salad": "توفو مشوي مع سلطة",
  "Vegetable Pulao": "بولاو خضروات",
  "Palak Paneer with Chapati": "بالاك بانير مع شاباتي",
  "Mixed Vegetable Soup": "شوربة خضروات مشكلة",
  "Stuffed Paratha with Curd": "باراثا محشوة مع زبادي",
  "Oats Khichdi": "كيتشدي الشوفان",
  "Roti with Bhindi": "روتي مع بامية",
  "Dal Tadka with Jeera Rice": "دال تادكا مع أرز جيرا",
  "Vegetable Handvo": "خضروات هاندفو",
  "Kadhi with Bajra Roti": "كادهي مع روتي باجرا",
  "Tofu Curry with Quinoa": "كاري توفو مع كينوا",
  "Bhakri with Thecha": "باكري مع ثيتشا",
  "Biryani (Veg)": "برياني (نباتي)",
  "Rajma with Brown Rice": "راجما مع أرز بني",
  "Daliya (Broken Wheat Porridge)": "داليا (عصيدة قمح)",
  "Pumpkin Sabzi with Chapati": "سبزي يقطين مع شاباتي",
  "Cauliflower Stir Fry": "قرنبيط مقلي",
  "Boiled Egg Salad": "سلطة بيض مسلوق",
  "Tomato Rasam with Rice": "طماطم راسام مع أرز",
  "Sweet Potato with Curd": "بطاطا حلوة مع زبادي",
  "Stuffed Capsicum": "فلفل محشي",
  "Paneer Tikka with Mint Chutney": "بانير تكا بصلصة النعناع",
  "Rice with Sambar": "أرز مع سامبار",
  "Vegetable Thepla with Dahi": "ثيبلا بالخضروات مع زبادي",
  "Grilled Mushroom Skewers": "أسياخ فطر مشوي",
  "Beetroot Sabzi with Roti": "سبزي شمندر مع روتي",
  "Spinach Dal with Rice": "دال سبانخ مع أرز",
  "Lentil Soup with Toast": "شوربة عدس مع توست",
  "Tinda Curry with Chapati": "كاري تيندا مع شاباتي",
  "Egg Bhurji with Roti": "بهورجي بيض مع روتي",
  "Karela Sabzi with Roti": "سبزي كاريلا مع روتي",
  "Zucchini Stir Fry": "كوسة مقلية",
  "Low Carb Paneer Bowl": "وعاء بانير قليل الكربوهيدرات",
  "Stuffed Tomato": "طماطم محشوة",
  "Vegetable Rava Upma": "أوبما سميد بالخضروات",
  "2 chapatis + sabzi": "2 شاباتي + سبزي",
  "1 fillet": "فيليه واحد",
  "1 bowl + 1 roti": "وعاء + 1 روتي",
  "1 plate": "طبق واحد",
  "1 cup rice + dal": "كوب أرز + عدس",
  "1 paratha + ½ cup curd": "1 باراثا + نصف كوب زبادي",
  "2 rotis + bhindi": "2 روتي + بامية",
  "1 roti + 1 bowl kadhi": "1 روتي + وعاء كادهي",
  "1 bhakri + chutney": "1 باخري + صلصة",
  "1 bowl curry + 1 roti": "وعاء كاري + 1 روتي",
  "2 chillas": "2 تشيلا",
  "1 bowl + ½ cup curd": "وعاء + نصف كوب زبادي",
  "1 serving": "حصة واحدة",
  "1 cup rice + sambar": "كوب أرز + سامبار",
  "1 thepla + curd": "1 ثيبلا + زبادي",
  "1 skewer": "سيخ واحد",
  "1 bowl + 1 toast": "وعاء + 1 توست",
  "1 bowl + 1 appam": "وعاء + 1 أبام",
  "1 tomato": "حبة طماطم واحدة",

  // AI Workout Parsing
  "analyze_with_ai": "تحليل بالذكاء الاصطناعي",
  "analyzing": "جاري التحليل...",
  "parsed_successfully": "تم التحليل بنجاح",
  "edit": "تعديل",
  "upgrade": "ترقية",
  "premium_feature_workout_ai":
      "تسجيل التمارين بالذكاء الاصطناعي ميزة مميزة. قم بالترقية للوصول!",
  "failed_to_parse_workout": "فشل في تحليل التمرين. يرجى إعادة الصياغة.",
  "please_analyze_or_select_type": "يرجى التحليل بالذكاء الاصطناعي قبل الحفظ",
  "failed_to_save_workout": "تعذر حفظ التمرين. يرجى المحاولة مرة أخرى.",
  "confirm_workout": "تأكيد التمرين",
  "calories_burned_label": "السعرات الحرارية التي ستحرقها",
  "calories_explanation":
      "سيحرق هذا التمرين السعرات الحرارية ويزيد من مخصصك اليومي من السعرات الحرارية.",
  "remaining_calories_increase": "ستزيد السعرات الحرارية المتبقية لديك",
  "confirm_save": "تأكيد وحفظ",
  "workout_cal_burned_msg": "+@cal سعرة حرارية أضيفت إلى السعرات المحروقة",
  "description_too_short": "الوصف قصير جداً. يرجى تقديم المزيد من التفاصيل.",
  "workout_saved": "تم حفظ التمرين بنجاح!",

  // Error Messages & Limits
  "daily_scan_limit_reached":
      "لقد وصلت إلى الحد اليومي للمسح. اشترك في بريميوم لمسح غير محدود!",
  "daily_chat_limit_reached":
      "تم الوصول إلى الحد اليومي للدردشة. قم بالترقية للدردشة بلا حدود!",
  "hmm_something_went_wrong": "همم، حدث خطأ ما. يرجى المحاولة مرة أخرى.",
  "invalid_action": "طلب غير صالح.",
  "daily_limit_reached_try_again":
      "تم الوصول إلى الحد اليومي. يرجى المحاولة مرة أخرى غدًا.",
  "unable_to_process_scan_try_again":
      "تعذر معالجة المسح. يرجى المحاولة مرة أخرى.",
  "unable_to_send_message_try_again":
      "تعذر إرسال الرسالة. يرجى المحاولة مرة أخرى.",
  "amount_exceeds_balance": "المبلع يتجاوز الرصيد المتاح",
  "enter_withdrawal_amount": "يرجى إدخال مبلغ السحب",
  "enter_valid_amount": "يرجى إدخال مبلغ صالح",
  "enter_rip_number_error": "يرجى إدخال رقم RIP الخاص بك",
  "rip_invalid_format": "يجب أن يتكون RIP من 20 رقمًا بالضبط",
  "auth_scan_success": "يمكنك الآن استخدام الماسح. يرجى محاولة المسح مرة أخرى.",
  "auth_scan_required": "يرجى تسجيل الدخول لاستخدام ميزة ماسح الطعام",
  "auth_chat_success":
      "يمكنك الآن استخدام الدردشة. يرجى محاولة إرسال رسالتك مرة أخرى.",
  "auth_chat_required": "يرجى تسجيل الدخول لاستخدام ميزة مدرب الذكاء الاصطناعي",

  // Withdrawal Errors
  "withdrawal_request_failed":
      "تعذر معالجة طلب السحب. يرجى المحاولة مرة أخرى لاحقاً.",
  "withdrawal_service_unavailable":
      "خدمة السحب غير متاحة مؤقتاً. يرجى المحاولة مرة أخرى لاحقاً.",
  "withdrawal_permission_denied": "ليس لديك صلاحية لطلب السحب.",
  "withdrawal_minimum_not_met": "المبلغ أقل من الحد الأدنى للسحب.",

  // App Update
  "update_required_title": "تحديث مطلوب",
  "update_now": "تحديث الآن",
  "update_default_message":
      "يلزم تحديث التطبيق للمتابعة. يرجى التحديث إلى أحدث إصدار.",

  // Notification Settings
  "notification_settings": "إعدادات الإشعارات",
  "enable_notifications": "تفعيل الإشعارات",
  "enable_notifications_desc": "استلم تذكيرات وتحديثات من macroAize",
  "meal_reminders": "تذكيرات الوجبات",
  "meal_reminders_desc": "تذكير بتسجيل وجباتك",
  "breakfast_time": "الفطور",
  "lunch_time": "الغداء",
  "dinner_time": "العشاء",
  "water_reminders": "تذكيرات الماء",
  "water_reminders_desc": "حافظ على ترطيب جسمك طوال اليوم",
  "enter_valid_number": "يرجى إدخال رقم صحيح",
  "minimum_value": "الحد الأدنى:",
  "maximum_value": "الحد الأقصى:",
  "water_interval": "فترة التذكير",
  "water_interval_desc": "كم مرة تريد تذكيرك بشرب الماء",
  "other_notifications": "إشعارات أخرى",
  "streak_reminders": "حماية السلسلة",
  "streak_reminders_desc": "تنبيه عندما تكون سلسلتك في خطر",
  "goal_notifications": "تقدم الهدف",
  "goal_notifications_desc": "احتفل عند تحقيق الإنجازات",
  "weekly_summary": "الملخص الأسبوعي",
  "weekly_summary_desc": "احصل على تقرير تقدمك الأسبوعي",
  "weight_reminders": "تسجيل الوزن",
  "weight_reminders_desc": "تذكير أسبوعي لتحديث وزنك",

  // Test Notifications
  "test_notification": "إرسال إشعار تجريبي",
  "test_notification_desc": "تحقق من عمل الإشعارات",
  "test_notification_sent": "تم الإرسال!",
  "test_notification_sent_desc": "يجب أن ترى إشعاراً الآن",
  "test_scheduled_notification": "إرسال إشعار مجدول",
  "test_scheduled_notification_desc": "إرسال إشعار بعد 10 ثوانٍ",
  "test_scheduled_sent": "تم الجدولة!",
  "test_scheduled_sent_desc": "ستستلم إشعاراً بعد 10 ثوانٍ",

  // ==============================================================================
  // 20. Water Tracker
  // ==============================================================================
  "water_title": "ماء",
  "water_ml_label": "مل",
  "water_cups_label": "أكواب",
  "water_goal_label": "تعديل هدف شرب الماء",
  "water_goal_min_error": "الحد الأدنى: 2000 مل (8 أكواب)",
  "water_goal_max_error": "الحد الأقصى: 4000 مل (16 كوبًا)",
  "water_goal_reached": "تم الوصول للهدف!",
};
