const Map<String, String> arabic = {
  "Home": "الرئيسية",
  "Calorie": "السعرات الحرارية",
  "Analytics": "التحليلات",
  "Setting": "الإعدادات",
  "Track Food": "تتبع الطعام",
  "Consumed": "المستهلك",
  "Remaining": "المتبقي",
  "Protein": "البروتين",
  "Carbs": "الكربوهيدرات",
  "Fats": "الدهون",
  "History": "السجل",
  "View All": "عرض الكل",
  "BreakFast": "فطور",
  "Lunch": "غداء",
  "snack(s)": "وجبة خفيفة",
  "Dinner": "عشاء",
  "Which meal would you like to track?": "أي وجبة ترغب في تتبعها؟",
  "Snap Tips": "نصائح للتصوير",
  "Too close": "قريب جدًا",
  "Too far": "بعيد جدًا",
  "Multi-species": "أصناف متعددة",
  "Continue": "متابعة",
  "Previous": "السابق",
  "Gallery": "معرض الصور",
  "Tips": "نصائح",
  "Perfect Shot": "لقطة مثالية",
  "Well-lit, centered food": "طعام مضاء جيدًا وفي المنتصف",
  "Move camera back": "أبعد الكاميرا للخلف",
  "Move camera closer": "قرّب الكاميرا أكثر",
  "Center food in the frame and tap to scan":
      "ضع الطعام في منتصف الإطار واضغط للمسح",
  "Analyzing food...": "جاري تحليل الطعام...",
  "No History Yet": "لا يوجد سجل بعد",
  "Start tracking your meals to see your nutrition history here":
      "ابدأ بتتبع وجباتك لرؤية سجلك الغذائي هنا",
  "Local Food": "طعام محلي",
  "Search Food": "ابحث عن طعام",
  "No Food Found": "لم يتم العثور على طعام",
  "Try searching with different keywords or browse our local food database":
      "جرّب البحث بكلمات مختلفة أو تصفح قاعدة بياناتنا للطعام المحلي",
  // Local Food add / edit dialog keys
  "add_custom_food": "إضافة طعام مخصص",
  "edit_food": "تعديل الطعام",
  "name": "الاسم",
  "quantity": "الكمية",
  "calories": "السعرات الحرارية",
  "add": "إضافة",
  "save": "حفظ",
  "Custom Food": "طعام مخصص",
  "delete_selected": "حذف المحدد",
  "proteins": "بروتينات",

  "Clear Search": "مسح البحث",
  "Premium Features": "الميزات المميزة",
  "Choose Your Plan": "اختر خطتك",
  "OverView": "نظرة عامة",
  "Weight Goal": "الوزن المستهدف",
  "Update": "تحديث",
  "Current Weight": "الوزن الحالي",
  "kg": "كغ",
  "Try to update once a week so we can adjust your plan to ensure you hit your goal":
      "حاول التحديث مرة أسبوعيًا حتى نتمكن من تعديل خطتك لضمان تحقيق هدفك",
  "Update Weight": "تحديث الوزن",
  "Week": "أسبوع",
  "Month": "شهر",
  "Profile": "الملف الشخصي",
  "Year": "سنة",
  "Update Weight Goal": "تحديث الوزن المستهدف",
  "Enter new weight (kg)": "أدخل وزنك الجديد (كغ)",
  "Cancel": "إلغاء",
  "Exit": "خروج",

  "Calorie Your Week :": "سعراتك الأسبوعية:",
  "Sun": "الأحد",
  "Mon": "الاثنين",
  "Tue": "الثلاثاء",
  "Wed": "الأربعاء",
  "Thu": "الخميس",
  "Fri": "الجمعة",
  "Sat": "السبت",
  "Average Calorie Month :": "متوسط السعرات الشهري:",
  "Average Calorie Yearly :": "متوسط السعرات السنوي:",
  "Jan": "يناير",
  "Feb": "فبراير",
  "Mar": "مارس",
  "Apr": "أبريل",
  "May": "مايو",
  "Jun": "يونيو",
  "Jul": "يوليو",
  "Aug": "أغسطس",
  "Sep": "سبتمبر",
  "Oct": "أكتوبر",
  "Nov": "نوفمبر",
  "Dec": "ديسمبر",
  "Age": "العمر",
  "Height": "الطول",
  "Customization": "تخصيص",
  "Dark Mode": "الوضع الداكن",
  "Language": "اللغة",
  "Personal details": "المعلومات الشخصية",
  "Adjust goals": "تعديل الأهداف",
  "Calories,carbs,fat and protein": "السعرات، الكربوهيدرات، الدهون والبروتين",
  // Subtitle for Adjust Goals in Settings
  "adjust_goals_subtitle": "السعرات، الكربوهيدرات، الدهون والبروتين",
  "Chat history": "سجل المحادثات",
  "The coach does not memorize chat history. Each interaction is independent.":
      "لا يقوم المدرب بحفظ سجل المحادثات. كل تفاعل مستقل.",
  "Legal": "قانوني",
  "Terms and Condition": "الشروط والأحكام",
  "Privacy Policy": "سياسة الخصوصية",
  "Reset Data?": "إعادة تعيين البيانات؟",
  "VERSION": "الإصدار",
  "History not found": "لم يتم العثور على سجل",
  "Delete Item": "حذف العنصر",
  "Are you sure you want to delete this item?":
      "هل أنت متأكد من رغبتك في حذف هذا العنصر؟",
  "Delete": "حذف",
  "Search by Food Name/Dish": "ابحث باسم الطعام/الطبق",
  "Calorie Goal Reached": "تم الوصول للهدف من السعرات",
  "You've completed your calorie goal for today. Would you like to add more?":
      "لقد أكملت هدفك من السعرات الحرارية لهذا اليوم. هل ترغب في إضافة المزيد؟",
  "Done": "تم",
  "Add More Calories": "إضافة المزيد من السعرات",
  "Boiled Egg": "بيضة مسلوقة",
  "Oatmeal": "شوفان",
  "Banana": "موز",
  "Paratha": "باراثا",
  "Idli": "إدلي",
  "Dosa": "دوسا",
  "Upma": "أبما",
  "Poha": "بواها",
  "Bread Butter": "خبز وزبدة",
  "Cornflakes with Milk": "رقائق الذرة مع الحليب",
  "Chilla (Besan)": "تشيلا (بيسان)",
  "Sprouts Salad": "سلطة براعم",
  "Pancakes": "بان كيك",
  "Apple": "تفاح",
  "Milk": "حليب",
  "Almonds": "لوز",
  "Smoothie (Fruit)": "سموذي (فواكه)",
  "Yogurt (Plain)": "زبادي (طبيعي)",
  "Khichdi": "كيتشدي",
  "Thepla": "ثيبلا",
  "Cheela (Moong dal)": "تشيلا (عدس)",
  "Pav Bhaji": "باف باجي",
  "Sabudana Khichdi": "سابودانا كيتشدي",
  "Roti with Sabzi": "روتي مع خضروات",
  "Peanut Butter Bread": "خبز بزبدة الفول السوداني",
  "Fruit Bowl": "وعاء فواكه",
  "Vegetable Sandwich": "ساندويتش خضروات",
  "Rice Idli with Sambar": "إدلي أرز مع سامبار",
  "Boiled Corn": "ذرة مسلوقة",
  "Paneer Bhurji": "بانير بهورجي",
  "Protein Shake": "مشروب بروتين",
  "Muesli with Milk": "ميوسلي مع الحليب",
  "Chapati with Curd": "تشاباتي مع زبادي",
  "Porridge (Daliya)": "عصيدة (داليا)",
  "Rava Upma": "رافا أبما",
  "Chickpea Salad": "سلطة حمص",
  "Boiled Sweet Potato": "بطاطا حلوة مسلوقة",
  "Coconut Water": "ماء جوز الهند",
  "Masala Omelette": "أومليت ماسالا",
  "Vegetable Poha": "بوها بالخضروات",
  "1 egg": "بيضة واحدة",
  "1 bowl": "وعاء واحد",
  "1 medium": "واحدة متوسطة",
  "1 piece": "قطعة واحدة",
  "1 cup": "كوب واحد",
  "2 slices": "شريحتان",
  "2 small pieces": "قطعتان صغيرتان",
  "10 pieces": "10 قطع",
  "1 glass": "كأس واحد",
  "2 pavs + bhaji": "2 باف + باجي",
  "1 roti + sabzi": "1 روتي + خضروات",
  "1 sandwich": "ساندويتش واحد",
  "2 idlis + sambar'": "2 إدلي + سامبار",
  "1 chapati + ½ cup curd": "1 تشاباتي + نصف كوب زبادي",
  "Rice with Dal": "أرز مع عدس",
  "Grilled Chicken": "دجاج مشوي",
  "Paneer Curry": "كاري بانير",
  "Mixed Vegetable Curry": "كاري خضروات مشكلة",
  "Chapati with Daal": "تشاباتي مع عدس",
  "Fish Curry with Rice": "كاري سمك مع أرز",
  "Rajma Chawal": "راجما تشاول",
  "Chole Bhature": "تشولي بهاتور",
  "Kadhi with Rice": "كادهي مع أرز",
  "Palak Paneer": "بانير بالسبانخ",
  "Stuffed Paratha": "باراثا محشوة",
  "Veg Pulao": "بيلاف نباتي",
  "Biryani with Raita": "برياني مع رايتا",
  "Tofu Stir Fry": "توفو مقلي",
  "Chicken Tikka": "دجاج تكا",
  "Veg Fried Rice": "أرز مقلي بالخضروات",
  "Aloo Gobi with Roti": "بطاطا وقرنبيط مع روتي",
  "Baingan Bharta": "باذنجان بهارتا",
  "Sambar with Rice": "سامبار مع أرز",
  "Chicken Curry with Roti": "كاري دجاج مع روتي",
  "Bhindi Masala with Roti": "بامية ماسالا مع روتي",
  "Egg Curry with Rice": "كاري بيض مع أرز",
  "Lentil Soup with Bread": "شوربة عدس مع خبز",
  "Methi Thepla with Curd": "ثيبلا مع زبادي",
  "Soybean Curry with Rice": "كاري صويا مع أرز",
  "Cabbage Sabzi with Chapati": "ملفوف مع تشاباتي",
  "Dal Makhani with Naan": "دال مخني مع نان",
  "Vegetable Korma with Roti": "كورما خضروات مع روتي",
  "Tandoori Roti with Paneer": "روتي تندوري مع بانير",
  "Mixed Dal with Rice": "عدس مشكل مع أرز",
  "Bottle Gourd Curry with Roti": "كاري قرع مع روتي",
  "Kofta Curry with Roti": "كاري كفتة مع روتي",
  "Paneer Bhurji with Bread": "بانير بهورجي مع خبز",
  "Chana Masala with Rice": "حمص ماسالا مع أرز",
  "Curd Rice": "أرز بالزبادي",
  "Tomato Rice": "أرز بالطماطم",
  "Vegetable Stew with Appam": "يخنة خضروات مع أبام",
  "Dhokla with Green Chutney": "دوكلا بصلصة خضراء",
  "Besan Chilla with Salad": "بيسان تشيلا مع سلطة",
  "Lauki Chana Dal": "قرع بعدس الحمص",
  "Spinach Corn Curry": "كاري سبانخ بالذرة",
  "Tinda Masala with Roti": "تيندا ماسالا مع روتي",
  "Masoor Dal with Rice": "عدس ماسور مع أرز",
  "Vegetable Handi with Naan": "هندي خضروات مع نان",
  "Egg Bhurji with Chapati": "بيض بهورجي مع تشاباتي",
  "Pumpkin Curry with Rice": "كاري يقطين مع أرز",
  "2 rotis + sabzi": "2 روتي + خضروات",
  "1 cup rice + 1 cup dal": "1 كوب أرز + 1 كوب عدس",
  "1 breast": "صدر واحد",
  "2 chapatis + dal'": "2 تشاباتي + عدس",
  "1 bowl curry + 1 cup rice": "وعاء كاري + كوب أرز",
  "1 bhatura + chole": "1 بهاتورا + تشولي",
  "1 paratha": "1 باراثا",
  "1 bowl + 2 rotis": "وعاء + 2 روتي",
  "1 cup + 1 bowl": "كوب + وعاء",
  "1 bowl + 1 cup rice": "وعاء + كوب أرز",
  "1 bowl + 1 bread slice": "وعاء + شريحة خبز",
  "2 theplas + ½ cup curd": "2 ثيبلا + نصف كوب زبادي",
  "1 bowl + 2 chapatis": "وعاء + 2 تشاباتي",
  "1 bowl + 1 naan": "وعاء + 1 نان",
  "2 rotis + paneer": "2 روتي + بانير",
  "1 bowl + 2 slices": "وعاء + شريحتان",
  "1 bowl + 2 appams": "وعاء + 2 أبام",

  "3 pieces": "3 قطع",
  "2 chillas + salad": "2 تشيلا + سلطة",
  "Cal": "سعرة",
  "Cropper": "قص",
  "Calorie Tracker": "متتبع السعرات",
  "Add Calorie": "إضافة سعرات",
  "Quantity": "الكمية",
  "Ask anything": "اسأل أي شيء",
  "Ask The Coach": "اسأل المدرب",
  "This picture not available Calorie,Protein,Carbs and Fats,":
      "هذه الصورة لا تحتوي على معلومات السعرات الحرارية، البروتين، الكربوهيدرات والدهون.",
  "Ask Coach": "اسأل المدرب",
  "Write your message": "اكتب رسالتك",
  "Confirm Reset": "تأكيد إعادة التعيين",
  "Are you sure you want to Reset Data?": "هل أنت متأكد من رغبتك في إعادة تعيين البيانات؟",
  "Reset": "إعادة تعيين",
  "You have been Reset Account": "تمت إعادة تعيين حسابك",
  "Personal Details": "التفاصيل الشخصية",
  "Goal Weight": "الوزن المستهدف",
  "cm": "سم",
  "Date Of Birth": "تاريخ الميلاد",
  "Gender": "الجنس",
  "Male": "ذكر",
  "Female": "أنثى",
  "Choose your desired weight?": "اختر وزنك المرغوب",
  "Imperial": "إمبراطوري",
  "Metric": "متري",
  "Weight": "الوزن",
  "lb": "رطل",
  "ft": "قدم",
  "in": "بوصة",
  "Day": "يوم",
  "January": "يناير",
  "February": "فبراير",
  "March": "مارس",
  "April": "أبريل",
  "June": "يونيو",
  "July": "يوليو",
  "August": "أغسطس",
  "September": "سبتمبر",
  "October": "أكتوبر",
  "November": "نوفمبر",
  "December": "ديسمبر",
  "Update Your Gender": "تحديث جنسك",
  "Adjust Goals": "تعديل الأهداف",
  "How many workout do you per week?": "كم مرة تتمرن في الأسبوع؟",
  "This will used to calibrate your custom plan":
      "سيُستخدم هذا لمعايرة خطتك المخصصة",
  "Choose your height and weight": "اختر طولك ووزنك",
  "Select your height and weight to calibrate your custom plan":
      "حدد طولك ووزنك لمعايرة خطتك المخصصة",
  "Workout Now and then": "أحياناً",
  "A few workout per week": "بضع مرات في الأسبوع",
  "Dedicated athlete": "رياضي ملتزم",
  "What is your goal?": "ما هو هدفك؟",
  "This helps is generate a plan for your calorie intake.":
      "هذا يساعد في إنشاء خطة لاستهلاكك من السعرات الحرارية.",
  "Gain Weight": "زيادة الوزن",
    "Maintain Weight": "الحفاظ على الوزن",
  "Lose Weight": "خسارة الوزن",
  "Update Calorie Goal": "تحديث هدف السعرات",
  "Calorie goal": "هدف السعرات",
  "Save": "حفظ",
  "Calorie Goal": "هدف السعرات الحرارية",
  "Update Protein Goal": "تحديث هدف البروتين",
  "Protein goal": "هدف البروتين",
  "Update Carb Goal": "تحديث هدف الكربوهيدرات",
  "Carb goal": "هدف الكربوهيدرات",
  "Update Fat Goal": "تحديث هدف الدهون",
  "Auto Generate Goal": "إنشاء هدف تلقائي",
  "Fruit Salad": "سلطة فواكه",
  "Roasted Chickpeas": "حمص محمص",
  "Mixed Nuts": "مكسرات مشكلة",
  "Yogurt with Honey": "زبادي بالعسل",
  "Apple with Peanut Butter": "تفاحة مع زبدة الفول السوداني",
  "Protein Bar": "بار بروتين",
  "Whole Wheat Crackers": "مقرمشات القمح الكامل",
  "Granola Bar": "بار جرانولا",
  "Peanut Chikki": "شيكي الفول السوداني",
  "Bhel Puri": "بيل بوري",
  "Khakra": "خاكرا",
  "Masala Makhana": "ماسالا ماخانا",
  "Hummus with Veggies": "حمص مع خضروات",
  "Paneer Cubes": "مكعبات بانير",
  "Milkshake (Low Sugar)": "ميلك شيك (قليل السكر)",
  "Dhokla": "دوكلا",
  "Vegetable Soup": "شوربة خضروات",
  "Idli with Chutney": "إيدلي مع صلصة",
  "Cheese Slice": "شريحة جبن",
  "Chana Chaat": "شانا شات",
  "Moong Dal Chilla": "مونج دال تشيلا",
  "Rice Cake with Peanut Butter": "كعكة أرز مع زبدة الفول السوداني",
  "Popcorn (Air-popped)": "فشار",
  "Avocado Toast": "توست الأفوكادو",
  "Stuffed Dates": "تمر محشي",
  "Oats Cookies": "كوكيز الشوفان",
  "Fruit Smoothie": "سموذي فواكه",
  "Carrot Sticks with Hummus": "أصابع الجزر مع الحمص",
  "Soy Nuts": "مكسرات الصويا",
  "Trail Mix": "مكسرات مشكلة",
  "Besan Ladoo": "بسان لادو",
  "Upma (small portion)": "أبما (كمية صغيرة)",
  "Egg Roll (Mini)": "رول بيض (صغير)",
  "Rice Idli": "إيدلي أرز",
  "Cucumber Sandwich": "ساندويتش خيار",
  "Fruit Chaat": "فواكه شات",
  "Lassi (Sweet)": "لاسي (حلو)",
  "Cold Coffee (Low Sugar)": "قهوة باردة (قليلة السكر)",
  "Rava Dhokla": "رافا دوكلا",
  "Vegetable Cutlet": "كوتليت خضروات",
  "Chikki with Jaggery": "شيكي مع جاجري",
  "Milk (Low Fat)": "حليب (قليل الدسم)",
  "Baked Samosa": "ساموسا مخبوزة",
  "Vegetable Wrap": "راب خضروات",
  "Roasted Soybeans": "فول الصويا المحمص",
  "1/2 cup": "نصف كوب",
  "1 handful": "حفنة",
  "1 apple + 1 tbsp PB": "تفاحة + 1 ملعقة كبيرة زبدة فول سوداني",
  "1 bar": "بار واحد",
  "5 pieces": "5 قطع",
  "½ cup hummus + veggies": "نصف كوب حمص + خضروات",
  "50g": "50 جرام",
  "1 idli + chutney": "1 إيدلي + صلصة",
  "1 slice": "شريحة واحدة",
  "1 chilla": "1 تشيلا",
  "1 cake + 1 tbsp PB": "1 كعكة + 1 ملعقة كبيرة زبدة فول سوداني",
  "2 cups": "كوبان",
  "1 toast": "شريحة توست واحدة",
  "3 dates": "3 تمرات",
  "2 cookies": "قطعتان كوكيز",
  "½ cup": "نصف كوب",
  "1 small bowl": "وعاء صغير",
  "1 roll": "رول واحد",
  "1 wrap": "راب واحد",
  "Chapati with Sabzi": "شاباتي مع سبزي",
  "Grilled Fish": "سمك مشوي",
  "Moong Dal Khichdi": "مونج دال كيتشدي",
  "Paneer Bhurji with Roti": "بانير بهورجي مع روتي",
  "Brown Rice with Veg Curry": "أرز بني مع كاري الخضروات",
  "Quinoa with Stir Fry Veggies": "كينوا مع خضروات مقلية",
  "Grilled Tofu with Salad": "توفو مشوي مع سلطة",
  "Vegetable Pulao": "بولاو خضروات",
  "Palak Paneer with Chapati": "بالاك بانير مع شاباتي",
  "Mixed Vegetable Soup": "شوربة خضروات مشكلة",
  "Stuffed Paratha with Curd": "باراثا محشوة مع زبادي",
  "Oats Khichdi": "كيتشدي الشوفان",
  "Roti with Bhindi": "روتي مع بامية",
  "Dal Tadka with Jeera Rice": "دال تادكا مع أرز جيرا",
  "Vegetable Handvo": "خضروات هاندفو",
  "Kadhi with Bajra Roti": "كادهي مع روتي باجرا",
  "Tofu Curry with Quinoa": "كاري توفو مع كينوا",
  "Bhakri with Thecha": "باكري مع ثيتشا",
  "Biryani (Veg)": "برياني (نباتي)",
  "Rajma with Brown Rice": "راجما مع أرز بني",
  "Daliya (Broken Wheat Porridge)": "داليا (عصيدة قمح)",
  "Pumpkin Sabzi with Chapati": "سبزي يقطين مع شاباتي",
  "Cauliflower Stir Fry": "قرنبيط مقلي",
  "Boiled Egg Salad": "سلطة بيض مسلوق",
  "Tomato Rasam with Rice": "طماطم راسام مع أرز",
  "Sweet Potato with Curd": "بطاطا حلوة مع زبادي",
  "Stuffed Capsicum": "فلفل محشي",
  "Paneer Tikka with Mint Chutney": "بانير تكا بصلصة النعناع",
  "Rice with Sambar": "أرز مع سامبار",
  "Vegetable Thepla with Dahi": "ثيبلا بالخضروات مع زبادي",
  "Grilled Mushroom Skewers": "أسياخ فطر مشوي",
  "Beetroot Sabzi with Roti": "سبزي شمندر مع روتي",
  "Spinach Dal with Rice": "دال سبانخ مع أرز",
  "Lentil Soup with Toast": "شوربة عدس مع توست",
  "Tinda Curry with Chapati": "كاري تيندا مع شاباتي",
  "Egg Bhurji with Roti": "بهورجي بيض مع روتي",
  "Karela Sabzi with Roti": "سبزي كاريلا مع روتي",
  "Zucchini Stir Fry": "كوسة مقلية",
  "Low Carb Paneer Bowl": "وعاء بانير قليل الكربوهيدرات",
  "Stuffed Tomato": "طماطم محشوة",
  "Vegetable Rava Upma": "أوبما سميد بالخضروات",
  "2 chapatis + sabzi": "2 شاباتي + سبزي",
  "1 fillet": "فيليه واحد",
  "1 bowl + 1 roti": "وعاء + 1 روتي",
  "1 plate": "طبق واحد",
  "1 cup rice + dal": "كوب أرز + عدس",
  "1 paratha + ½ cup curd": "1 باراثا + نصف كوب زبادي",
  "2 rotis + bhindi": "2 روتي + بامية",
  "1 roti + 1 bowl kadhi": "1 روتي + وعاء كادهي",
  "1 bhakri + chutney": "1 باخري + صلصة",
  "1 bowl curry + 1 roti": "وعاء كاري + 1 روتي",
  "2 chillas": "2 تشيلا",
  "1 bowl + ½ cup curd": "وعاء + نصف كوب زبادي",
  "1 serving": "حصة واحدة",
  "1 cup rice + sambar": "كوب أرز + سامبار",
  "1 thepla + curd": "1 ثيبلا + زبادي",
  "1 skewer": "سيخ واحد",
  "1 bowl + 1 toast": "وعاء + 1 توست",
  "1 bowl + 1 appam": "وعاء + 1 أبام",
  "1 tomato": "حبة طماطم واحدة",
  "Restore": "استعادة",
  "Get Premium": "احصل على بريميوم",
  "Get All The New Exciting Features": "احصل على جميع الميزات الجديدة والمثيرة",
  "Unlock Food Scanner": "فتح ماسح الطعام",
  "Unlock Food Calorie": "فتح سعرات الطعام",
  "Unlock Unlimited Chat with Ai": "فتح الدردشة غير المحدودة مع الذكاء الاصطناعي",
  "Unlimited Food Scanner To Calorie": "ماسح طعام غير محدود للسعرات",
  "Most Popular": "الأكثر شيوعًا",
  "Subscription": "الاشتراك",
  "BUY NOW": "اشترِ الآن",
  "Terms of Condition": "شروط الاستخدام",
  "Welcome": "أهلاً بك",
  "Choose Your Gender": "اختر جنسك",
  "Calorie tracking made easy": "تتبع السعرات أصبح سهلاً",
  "Just snap a quick photo of your meal and we''ll do the rest":
      "التقط صورة سريعة لوجبتك وسنتكفل بالباقي",
  "In-depth nutrition analyses": "تحليلات غذائية معمقة",
  "We will keep your informed about your food choicer and their nutritional content":
      "سنبقيك على اطلاع بخياراتك الغذائية ومحتواها الغذائي",
  "Transform your body": "غيّر جسدك",
  "Today is best time to start working toward your dream body":
      "اليوم هو أفضل وقت للبدء بالعمل نحو جسم أحلامك",
  "Where were you born?": "أين ولدت؟",
  "This Will be used to calibrate your custom plan":
      "سيُستخدم هذا لمعايرة خطتك المخصصة",
  "What's stopping you from reaching your goals?":
      "ما الذي يمنعك من تحقيق أهدافك؟",
  "Lack of consistency": "قلة الاستمرارية",
  "Unhealthy eating habits": "عادات أكل غير صحية",
  "Lack of supports": "نقص الدعم",
  "Busy schedule": "جدول أعمال مزدحم",
  "Lack of meal inspiration": "قلة الإلهام للوجبات",
  "We're setting": "نحن نقوم بإعداد",
  "everything up for you": "كل شيء من أجلك",
  "Customizing health plan....": "جاري تخصيص خطتك الصحية...",
  "welcome_hi": "مرحبًا!",
  "welcome_subtitle_prefix": "مرحبًا بك في مدربك الشخصي ",
  "welcome_subtitle_highlight": "مدرب التغذية",
  "plan_intro_title": "لنبدأ ببعض الأسئلة",
  "plan_intro_subtitle": "سيساعدنا هذا في تخصيص خطتك",

  // Dynamic meal description components
  "meal_contains": "هذه الوجبة تحتوي على",
  "conjunction_and": "و",

  // Units and labels
  "kcal_unit": "سعرة",
  "gram_unit": "غ",
  "unit_piece": "قطعة",
  "protein_unit": "غ",
  "carbs_unit": "غ",
  "fat_unit": "غ",
  "Cal Left": "السعرات المتبقية",
  "meal_label": "الوجبة",

  // Abbreviations for compact badges
  "cals": "سعرات",
  "prot": "بروتين",
  "carbs": "كربوهيدرات",
  "fats": "دهون",

  // Modern UI labels
  "track_subtitle": "تتبع تغذيتك اليومية",
  "goal_label": "الهدف",
  // Localized language display names
  "language_english": "English",
  "language_french": "Français",
  "language_arabic": "العربية",
  "Analyzing nutrition...": "جاري تحليل التغذية...",
  // Influencer / promo keys
  "influencer_program": "برنامج المؤثرين",
  "your_promo_code": "رمز الخصم الخاص بك",
  "copied": "تم النسخ",
  "current_balance": "الرصيد الحالي",
  "total_earned": "إجمالي الأرباح",
  "referrals_count": "عدد الإحالات",
  "request_withdrawal": "طلب سحب",
  "minimum_withdrawal_amount": "الحد الأدنى للسحب: @amount دج",
  "withdrawal_history": "سجل السحوبات",
  "promo_code_expired": "انتهت صلاحية رمز الخصم",
  "promo_expires_in": "ينتهي الرمز خلال @days يوم",
  "promo_expires_on": "ينتهي الرمز في @date",
  "promo_code_copied": "تم نسخ رمز الخصم",
  "promo_code": "رمز الخصم",
  "enter_promo_code": "أدخل رمز الخصم",
  "apply_promo_code": "تطبيق",
  "skip_promo_code": "تخطي",
  "promo_code_applied": "تم تطبيق رمز الخصم بنجاح!",
  "promo_code_invalid": "رمز الخصم غير صالح",
  "promo_code_dialog_title": "هل لديك رمز خصم؟",
  "promo_code_dialog_subtitle": "أدخل رمز الخصم للاستفادة من الخصم",
  
  // Promo Code View (Sign Up)
  "Have a Promo Code?": "هل لديك رمز خصم؟",
  "Enter your promo code to get 3 days free trial": "أدخل رمز الخصم للحصول على 3 أيام تجربة مجانية",
  "ENTER CODE": "أدخل الرمز",
  "Validate Code": "تحقق من الرمز",
  "Promo code applied successfully!": "تم تطبيق رمز الخصم بنجاح!",
  "Please enter a promo code": "الرجاء إدخال رمز الخصم",
    "Invalid promo code": "رمز الخصم غير صالح",

  // Plan review page translations
  "Your Plan is Ready!": "خطتك جاهزة!",
  "We have customized your nutrition plan based on your goals": "لقد قمنا بتخصيص خطة التغذية الخاصة بك بناءً على أهدافك",
  "Daily Calorie Goal": "هدف السعرات الحرارية اليومية",
  "Macronutrients Breakdown": "توزيع المغذيات الكبرى",
  "This plan is based on your age, weight, height, activity level, and goals. You can adjust your daily intake in settings anytime.": "تعتمد هذه الخطة على عمرك ووزنك وطولك ومستوى نشاطك وأهدافك. يمكنك تعديل كمية الطعام اليومية في الإعدادات في أي وقت.",
  "Continue to Premium": "الاستمرار إلى Premium",

  // App Tips/Tutorial translations
  "app_tips": "نصائح التطبيق",
  "skip": "تخطي",
  "next": "التالي",
  "previous": "السابق",
  "get_started": "ابدأ الآن",
  "tip_welcome_title": "مرحباً بك في macroAize!",
  "tip_welcome_description": "متتبع التغذية الشخصي الخاص بك المدعوم بالذكاء الاصطناعي. لنقم بجولة سريعة لمساعدتك على البدء في رحلتك الصحية.",
  "tip_track_food_title": "تتبع وجباتك",
  "tip_track_food_description": "اضغط على زر + في الشاشة الرئيسية لتسجيل وجباتك. اختر بين الإفطار أو الغداء أو العشاء أو الوجبات الخفيفة للحفاظ على سجلات دقيقة.",
  "tip_scan_food_title": "المسح بالذكاء الاصطناعي",
  "tip_scan_food_description": "التقط صورة لطعامك وسيقوم الذكاء الاصطناعي الخاص بنا بتحليل وحساب السعرات الحرارية والبروتين والكربوهيدرات والدهون على الفور.",
  "tip_ai_coach_title": "تحدث مع المدرب الذكي",
  "tip_ai_coach_description": "احصل على نصائح غذائية مخصصة واقتراحات للوجبات وإجابات على أسئلتك الصحية من مدربنا الذكي في أي وقت.",
  "tip_analytics_title": "تتبع تقدمك",
  "tip_analytics_description": "اعرض تحليلات مفصلة لاتجاهات التغذية الخاصة بك، وتقدم الوزن، وتوزيع الماكروز للبقاء على المسار الصحيح نحو أهدافك.",

  // Email verification translations
  
  "available_balance": "الرصيد المتاح",
  "withdrawal_amount": "مبلغ السحب",
  "enter_amount": "أدخل المبلغ",
  "bank_account_rip": "الحساب البنكي (RIP)",
  "enter_rip_number": "أدخل رقم RIP",
  "withdrawal_processing_info": "تتم معالجة السحوبات في غضون 5 أيام عمل.",
  "requested_on": "تم الطلب في @date",
  "unknown_date": "تاريخ غير معروف",
  // Withdrawal specific translations
  "withdrawal_submitted": "تم إرسال طلب السحب",
  "request_id": "معرف الطلب: @id",
  "processing_time": "وقت المعالجة: @days أيام عمل",
  "withdrawal_email_confirmation":
      "ستصلك رسالة تأكيد عبر البريد الإلكتروني بمجرد معالجة طلب السحب.",
  "got_it": "حسنًا",
  "processing": "قيد المعالجة",
  "copy_failed": "فشل النسخ: @error",
  "request_id_short": "المعرف",
  "bank_account_short": "الحساب",
  "processing_date": "تاريخ المعالجة",
  "processing_deadline": "الموعد النهائي",
  "requested_date": "تاريخ الطلب",
  "completed": "مكتمل",
  "failed": "فشل",
  "email_verification_required_withdrawal":
      "التحقق من البريد الإلكتروني مطلوب للسحب",
  "view_all": "عرض الكل",
  "showing_recent_withdrawals": "عرض @shown من @total سحوبات",
  "withdrawal_history_full": "سجل السحوبات",
  "no_withdrawal_history": "لا يوجد سجل سحوبات",
  "withdrawal_history_empty_description":
      "اطلب سحبك الأول لرؤية سجل معاملاتك هنا",
  "view_withdrawal_history": "عرض سجل السحوبات",
  "withdrawal_history_subtitle": "تتبع جميع طلبات السحب الخاصة بك",
  // Permission UI
  "grant_camera_access_in_scanner": "اضغط على الإطار لمنح الوصول إلى الكاميرا",
  "camera_permission_denied_title": "إذن الكاميرا مطلوب",
  "camera_permission_denied_message":
      "تم رفض الوصول إلى الكاميرا. يرجى تفعيل إذن الكاميرا من إعدادات الجهاز لاستخدام الماسح.",
  "ok": "حسنًا",

  // Exit confirmation dialog
  "exit_app_title": "الخروج من التطبيق",
  "exit_app_message": "هل أنت متأكد أنك تريد الخروج؟",

  // Nutrition details dialog
  "nutrition_details": "تفاصيل التغذية",
  "fats_label": "الدهون",
  "log": "سجل",

  // Premium paywall (modern)
  'premium_badge': 'بريميوم',
  'go_premium_title': 'الترقية إلى بريميوم',
  'go_premium_subtitle': 'التجربة الكاملة لأفضل برنامج غذائي',
  'feature_ai_scan_title': 'تحكم في وزنك وتناول طعامًا أفضل',
  'feature_ai_scan_subtitle':
      'مع مسح الوجبات بالذكاء الاصطناعي وملاحظات يومية',
  'feature_results_title': 'حقق نتائج طويلة الأمد',
  'feature_results_subtitle': 'مع الطيار الآلي وتتبع المغذيات',
  'feature_chatbot_title': 'الدردشة الذكية "المدرب"',
  'feature_chatbot_subtitle': 'إرشاد غذائي فوري',
  'feature_recipes_title': 'وصفات وخطط بريميوم',
  'feature_recipes_subtitle': 'ترشدك نحو النجاح',
  'best_value': 'أفضل قيمة',
  'save_percent': 'وفّر @percent%*',
  'months_12': '12 شهرًا',
  'month_1': 'شهر واحد',
  'billed_annually': 'تتم الفوترة سنويًا',
  'billed_monthly': 'تتم الفوترة شهريًا',
  'per_month': 'شهريًا',
  'continue_cta': 'متابعة',
  'compared_to_monthly': '*مقارنة بالدفع الشهري',
  'currency_dzd': 'دج',

  // Weight tracking UI
  "Target Weight": "الوزن المستهدف",
  "to go": "متبقي",
  "Try to update once a week to help us adjust your plan":
      "حاول التحديث مرة أسبوعيًا لمساعدتنا في تعديل خطتك",
  "Weight Overview": "نظرة عامة على الوزن",
  "Current": "الحالي",
  "Goal": "الهدف",
  "invalid_number": "الرجاء إدخال رقم صالح",
  "weight_out_of_range": "الرجاء إدخال وزن بين 20 و 300 كغ",

  // Celebration strip messages
  "goal_achieved_message": "لقد حققت هدفك! استمر في التقدم.",
  "on_a_roll_message": "أنت على المسار الصحيح — كل خطوة مهمة!",
  "keep_momentum_message": "أنت تحرز تقدمًا — حافظ على هذا الزخم!",

  // Notifications
  "update_targets_title": "تم تحديث الأهداف",
  "update_targets_body":
      "لقد قمنا بإعادة حساب أهدافك اليومية من السعرات الحرارية والمغذيات الكبرى لتتناسب مع وزنك الجديد.",

  // Donut chart center texts
  "daily_macros": "المغذيات اليومية",
  "daily_macros_reached": "تم تحقيق أهداف المغذيات اليومية",

  // Recipes Section
  "recipes_title": "الوصفات",
  "top_recipes": "أفضل الوصفات",
  "all_recipes": "كل الوصفات",
  // Recipe Detail specific keys
  "less_text": "أقل ^",
  "macronutrients": "المغذيات الكبرى",
  "ingredients": "المكونات",
  "serving": "الحصة",
  "directions": "الخطوات",
  "add_to_plan": "أضف إلى الخطة",
  "step": "خطوة",
  "top_recipes_subtitle": "اكتشف وصفات صحية ولذيذة مصممة لأهدافك",
  "no_recipes_available": "لا توجد وصفات متاحة",
  "Search recipes by name or ingredient": "ابحث عن وصفات بالاسم أو المكونات",
  "failed_to_load_recipes": "فشل تحميل الوصفات. يرجى المحاولة مرة أخرى.",
  "min": "دقيقة",
  "cal": "سعرة",
  "close": "إغلاق",

  "food items found": "عناصر طعام موجودة",

  // Meal Breakdown
  "meal_breakdown": "تفاصيل الوجبة",
  "tap_to_edit_portions": "اضغط لتعديل الحصص",
  "items": "عناصر",
  "verified": "مؤكد",
  "estimated": "تقديري",
  // Centralized success messages
  "success": "نجاح",
  "food_added_success": "تمت إضافة الطعام بنجاح",
  "food_updated_success": "تم تحديث الطعام بنجاح",
  "food_deleted_success": "تم حذف @count عنصر بنجاح",
  // Nutrient short labels
  "nut_prt": "بروتين",
  "nut_carb": "كربوهيدرات",
  "nut_cal": "سعرات",
  "nut_fat": "دهون",
  // Authentication messages
  "auth_login_success": "تم تسجيل الدخول بنجاح",
  "auth_register_success": "تم إنشاء الحساب بنجاح",
  "auth_password_reset_sent": "تم إرسال بريد إعادة تعيين كلمة المرور",
  "auth_wrong_credentials": "البريد الإلكتروني أو كلمة المرور غير صحيحة",
  "auth_account_not_found": "الحساب غير موجود",
  "auth_email_in_use": "هذا البريد الإلكتروني مستخدم بالفعل",
  "auth_weak_password": "كلمة المرور ضعيفة جدًا",
  "auth_account_different_provider": "الحساب مرتبط بمزود تسجيل آخر",
  "auth_network_error": "خطأ في الشبكة. يرجى التحقق من اتصالك.",
  "auth_unknown_error": "حدث خطأ غير معروف",
  "auth_authentication_error": "خطأ في المصادقة",
  "auth_unexpected_error": "خطأ غير متوقع",
  "auth_logout_success": "تم تسجيل الخروج بنجاح",
  "auth_logout_failed": "فشل تسجيل الخروج",
  // Title used for the authentication/modal which prompts users to sign in
  "auth_modal_title": "سجل الدخول للمتابعة",
  // Daily usage labels
  "Daily Usage": "الاستخدام اليومي",
  "Scans": "المسح",
  "Chat": "الدردشة",
  "left": "متبقي",
  "login_to_view_usage": "سجل الدخول لعرض استخدامك",

  // Email verification translations
  "email_verification_title": "التحقق من بريدك الإلكتروني",
  "email_verification_subtitle": "تحقق من بريدك الإلكتروني للمتابعة",
  "email_sent_to": "لقد أرسلنا رابط التحقق إلى @email",
  "email_verification_instructions":
      "انقر على الرابط في بريدك الإلكتروني للتحقق من حسابك. هذا يساعدنا في الحفاظ على أمان حسابك.",
  "checking_verification_status": "جاري التحقق من الحالة...",
  "resend_verification_email": "إعادة إرسال بريد التحقق",
  "resend_cooldown": "يمكنك إعادة الإرسال بعد @seconds ثانية",
  "resend_limit_reached": "تبقى @attempts محاولات",
  "verification_attempts_remaining": "تبقى @remaining من @total محاولات",
  "email_verification_success":
      "تم التحقق من البريد الإلكتروني بنجاح! مرحبًا بك في ماكروآيز",
  "email_verification_resent":
      "تم إرسال بريد التحقق! يرجى مراجعة بريدك الوارد",
  "email_verification_resend_error":
      "فشل إرسال بريد التحقق. يرجى المحاولة مرة أخرى",
  "email_verification_max_attempts":
      "لقد وصلت إلى الحد الأقصى للمحاولات. يرجى المحاولة لاحقًا",
  "email_verification_cooldown":
      "يرجى الانتظار @seconds ثانية قبل طلب بريد آخر",
  "skip_verification_title": "تخطي التحقق؟",
  "skip_verification_warning":
      "سيسمح لك هذا بالوصول دون التحقق من البريد الإلكتروني. لا يوصى به لأسباب أمنية.",
  "skip_anyway": "تخطي على أي حال",
  "skip_verification": "تخطي التحقق",
  "verify": "تحقق",
  "sign_out_title": "تسجيل الخروج؟",
  "sign_out_confirmation": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
  "sign_out": "تسجيل الخروج",
  "cancel": "إلغاء",
  "email_verification_error":
      "فشل التحقق من البريد الإلكتروني. يرجى المحاولة مرة أخرى",

  // Email verification guard messages
  "auth_required": "مطلوب تسجيل الدخول للمتابعة",
  "email_verification_required_for_feature":
      "التحقق من البريد الإلكتروني مطلوب لاستخدام هذه الميزة",
  "email_verification_required_for_premium":
      "التحقق من البريد الإلكتروني مطلوب للوصول إلى الميزات المميزة",
  "email_verification_required_for_scan":
      "التحقق من البريد الإلكتروني مطلوب لاستخدام ماسح الطعام",
  "email_verification_required_for_chat":
      "التحقق من البريد الإلكتروني مطلوب للدردشة مع المدرب الذكي",
  "email_verification_required_for_app_access":
      "التحقق من البريد الإلكتروني مطلوب للوصول إلى التطبيق",

  // UI status indicators
  "email_verified_status": "تم التحقق",
  "email_unverified_status": "لم يتم التحقق",
  "email_verified": "تم التحقق من البريد الإلكتروني",
  "email_verification_complete_subtitle": "حسابك آمن وجاهز للاستخدام",
  "email_verification_required": "التحقق من البريد الإلكتروني مطلوب",
  "email_verification_required_subtitle":
      "يرجى التحقق من @email للوصول إلى كافة الميزات",
  "verify_email": "التحقق من البريد الإلكتروني",
  "verify_now": "تحقق الآن",
  "refresh": "تحديث",
  "refresh_failed": "فشل تحديث الحالة. يرجى المحاولة مرة أخرى",
  "tap_to_verify_email": "انقر للتحقق من بريدك الإلكتروني",

  // Account activation gating warnings
  "account_activation_required": "تفعيل الحساب مطلوب",
  "account_activation_required_for_chat":
      "يرجى تفعيل حسابك لاستخدام المدرب الذكي",
  "account_activation_required_for_scanner":
      "يرجى تفعيل حسابك لاستخدام ماسح الطعام",
  "account_activation_required_for_premium":
      "يرجى تفعيل حسابك لشراء النسخة المميزة",
  "verify_account_to_continue": "تحقق من حسابك للمتابعة",

  // Premium Required Messages
  "premium_required": "الترقية إلى بريميوم مطلوبة",
  "premium_feature": "ميزة مميزة",
  "recipes_premium_message":
      "الوصول إلى الوصفات يتطلب اشتراكًا مميزًا. قم بالترقية الآن لفتح هذه الميزة.",
  "recipes_premium_badge": "افتح جميع الوصفات والميزات مع بريميوم",
  "local_food_premium_message":
      "إنشاء وتعديل الأطعمة المخصصة هي ميزة مميزة.",
  "local_food_premium_badge":
      "قم بالترقية إلى بريميوم لإنشاء أطعمة مخصصة غير محدودة!",
  "chat_image_premium_message":
      "إرفاق الصور يتطلب اشتراكًا مميزًا. قم بالترقية الآن لفتح هذه الميزة.",
  "chat_image_premium_badge": "افتح إرفاق الصور للمدرب مع بريميوم",
  "go_premium": "الترقية إلى بريميوم",
  "maybe_later": "ربما لاحقًا",
  // History fallbacks
  "unknown_meal": "وجبة غير معروفة",

  // Login/Register Form Labels
  "login": "تسجيل الدخول",
  "register": "إنشاء حساب",
  "email": "البريد الإلكتروني",
  "password": "كلمة المرور",
  "confirm_password": "تأكيد كلمة المرور",
  "first_name": "الاسم الأول",
  "last_name": "الاسم الأخير",
  "forgot_password": "هل نسيت كلمة المرور؟",
  "continue_with_google": "المتابعة باستخدام جوجل",
  "continue_with_apple": "المتابعة باستخدام آبل",

  // Validation Messages
  "email_required": "البريد الإلكتروني مطلوب",
  "required": "مطلوب",
  "invalid_email_format": "صيغة البريد الإلكتروني غير صحيحة",
  "password_required": "كلمة المرور مطلوبة",
  "password_min_length": "8 أحرف على الأقل",
  "password_complexity": "استخدم حروفًا كبيرة وصغيرة وأرقامًا ورموزًا",
  "name_required": "مطلوب",
  "name_too_short": "قصير جدًا",
  "passwords_do_not_match": "كلمتا المرور غير متطابقتين",
  "please_fix_errors": "يرجى إصلاح الأخطاء",
  "accept_terms_of_service": "يرجى قبول شروط الخدمة",

  // Terms of Service
  "by_registering_agree": "بالتسجيل، فإنك توافق على ",
  "terms_of_service": "شروط الخدمة",

  // Registration Success
  "auth_register_verification_required":
      "تم إنشاء الحساب! يرجى مراجعة بريدك الإلكتروني للتحقق من حسابك.",

  // Settings - Account Section
  "account": "الحساب",
  "tap_to_view_details": "انقر لعرض التفاصيل",
  "register_login": "تسجيل الدخول / إنشاء حساب",
  "access_account_sync_data": "الوصول إلى حسابك ومزامنة بياناتك",

  // Settings - App Info Section
  "app_info": "معلومات التطبيق",
  "version": "الإصدار",
  "reset_data": "إعادة تعيين البيانات",
  "clear_all_app_data": "مسح كافة بيانات التطبيق",
  "account_reset_success": "تمت إعادة تعيين الحساب بنجاح",

  // Account Details page translations
  "account_details_title": "تفاصيل الحساب",
  "no_name": "لا يوجد اسم",
  "name_label": "الاسم",
  "email_label": "البريد الإلكتروني",
  "change_password": "تغيير كلمة المرور",
  "logout": "تسجيل الخروج",
  "display_name_updated": "تم تحديث اسم العرض",
  "edit_display_name": "تعديل اسم العرض",
  "new_display_name": "اسم العرض الجديد",
  "password_changed_message":
      "تم تغيير كلمة المرور بنجاح. يرجى تسجيل الدخول مرة أخرى.",
  "current_password_incorrect": "كلمة المرور الحالية غير صحيحة.",
  "too_many_attempts": "محاولات كثيرة جدًا. يرجى المحاولة لاحقًا.",
  "please_relogin": "يرجى إعادة تسجيل الدخول والمحاولة مرة أخرى.",
  "operation_failed": "فشلت العملية.",
  // Change Password page translations
  "current_password_label": "كلمة المرور الحالية",
  "new_password_label": "كلمة المرور الجديدة",
  "confirm_new_password_label": "تأكيد كلمة المرور الجديدة",
  "min_8_chars": "8 أحرف على الأقل",
  "password_complexity_hint": "استخدم حرفًا كبيرًا، حرفًا صغيرًا، رقمًا، ورمزًا",
  "must_differ_from_current": "يجب أن تكون مختلفة عن الحالية",
  "does_not_match": "غير متطابق",
  "change_password_cta": "تغيير كلمة المرور",

  // Interactive Tutorial
  "tutorial_tap_to_continue": "اضغط في أي مكان للمتابعة",
  "tutorial_step": "خطوة",
  "tutorial_add_food_title": "تتبع وجباتك",
  "tutorial_add_food_description": "اضغط على زر '+' لإضافة طعام إلى سجلك اليومي. يمكنك البحث أو المسح أو إضافة أطعمة مخصصة.",
  "tutorial_scanner_title": "ماسح الطعام بالذكاء الاصطناعي",
  "tutorial_scanner_description": "استخدم الماسح الضوئي المدعوم بالذكاء الاصطناعي لتحليل طعامك على الفور والحصول على معلومات غذائية دقيقة.",
  "tutorial_ai_coach_title": "مدرب التغذية بالذكاء الاصطناعي",
  "tutorial_ai_coach_description": "تحدث مع مدربك الشخصي بالذكاء الاصطناعي للحصول على نصائح مخصصة واقتراحات وجبات وإرشادات غذائية.",
  "tutorial_analytics_title": "تتبع تقدمك",
  "tutorial_analytics_description": "اعرض تحليلاتك الغذائية وتقدم وزنك واتجاهاتك اليومية لتبقى على المسار الصحيح نحو أهدافك.",
  "tutorial_profile_title": "ملفك الشخصي",
  "tutorial_profile_description": "الوصول إلى إعداداتك، وضبط أهدافك، وتخصيص تجربتك في قسم الملف الشخصي.",
};

