const Map<String, String> chinese = {
  "Home": "首页",
  "Calorie": "卡路里",
  "Analytics": "分析",
  "Setting": "设置",
  "Track Food": "记录食物",
  "Consumed": "已摄入",
  "Remaining": "剩余",
  "Protein": "蛋白质",
  "Carbs": "碳水化合物",
  "Fats": "脂肪",
  "History": "历史",
  "View All": "查看全部",
  "BreakFast": "早餐",
  "Lunch": "午餐",
  "snack(s)": "加餐",
  "Dinner": "晚餐",
  "Which meal would you like to track?": "你想记录哪一餐？",
  "Snap Tips": "拍照提示",
  "Too close": "太近了",
  "Too far": "太远了",
  "Multi-species": "多种类",
  "Continue": "继续",
  "OverView": "概览",
  "Weight Goal": "体重目标",
  "Update": "更新",
  "Current Weight": "当前体重",
  "kg": "千克",
  "Try to update once a week so we can adjust your plan to ensure you hit your goal": "请每周更新一次，我们将调整计划帮助你达成目标",
  "Update Weight": "更新体重",
  "Week": "周",
  "Month": "月",
  "Year": "年",
  "Update Weight Goal": "更新体重目标",
  "Enter new weight (kg)": "输入新体重（千克）",
  "Cancel": "取消",
  "Calorie Your Week :": "本周卡路里：",
  "Sun": "周日",
  "Mon": "周一",
  "Tue": "周二",
  "Wed": "周三",
  "Thu": "周四",
  "Fri": "周五",
  "Sat": "周六",
  "Average Calorie Month :": "月均卡路里：",
  "Average Calorie Yearly :": "年均卡路里：",
  "Jan": "一月",
  "Feb": "二月",
  "Mar": "三月",
  "Apr": "四月",
  "May": "五月",
  "Jun": "六月",
  "Jul": "七月",
  "Aug": "八月",
  "Sep": "九月",
  "Oct": "十月",
  "Nov": "十一月",
  "Dec": "十二月",
  "Age": "年龄",
  "Height": "身高",
  "Customization": "自定义",
  "Dark Mode": "深色模式",
  "Language": "语言",
  "Personal details": "个人信息",
  "Adjust goals": "调整目标",
  "Calories,carbs,fat and protein": "卡路里、碳水、脂肪和蛋白质",
  "Chat history": "聊天记录",
  "Legal": "法律条款",
  "Terms and Condition": "条款与条件",
  "Privacy Policy": "隐私政策",
  "Reset Data?": "重置账户？",
  "VERSION": "版本",
  "History not found": "未找到记录",
  "Delete Item": "删除项目",
  "Are you sure you want to delete this item?": "你确定要删除此项目吗？",
  "Delete": "删除",
  "Search by Food Name/Dish": "按食物名称/菜名搜索",
  "🎯 Calorie Goal Reached": "🎯 达到卡路里目标",
  "You've completed your calorie goal for today. Would you like to add more?": "你已完成今天的卡路里目标。还想继续添加吗？",
  "Done": "完成",
  "Add More Calories": "添加更多卡路里",
  "Boiled Egg": "水煮蛋",
  "Oatmeal": "燕麦粥",
  "Banana": "香蕉",
  "Paratha": "帕拉塔",
  "Idli": "伊德利",
  "Dosa": "多萨",
  "Upma": "乌普玛",
  "Poha": "波哈",
  "Bread Butter": "黄油面包",
  "Cornflakes with Milk": "玉米片加牛奶",
  "Chilla (Besan)": "鹰嘴豆煎饼",
  "Sprouts Salad": "芽菜沙拉",
  "Pancakes": "煎饼",
  "Apple": "苹果",
  "Milk": "牛奶",
  "Almonds": "杏仁",
  "Smoothie (Fruit)": "水果奶昔",
  "Yogurt (Plain)": "原味酸奶",
  "Khichdi": "克奇迪",
  "Thepla": "印度香煎饼",
  "Cheela (Moong dal)": "绿豆煎饼",
  "Pav Bhaji": "蔬菜咖喱配面包",
  "Sabudana Khichdi": "木薯珍珠炒饭",
  "Roti with Sabzi": "印度薄饼配蔬菜",
  "Peanut Butter Bread": "花生酱面包",
  "Fruit Bowl": "水果碗",
  "Vegetable Sandwich": "蔬菜三明治",
  "Rice Idli with Sambar": "米发糕配酸辣汤",
  "Boiled Corn": "煮玉米",
  "Paneer Bhurji": "炒奶酪碎",
  "Protein Shake": "蛋白奶昔",
  "Muesli with Milk": "麦片配牛奶",
  "Chapati with Curd": "印度面饼配酸奶",
  "Porridge (Daliya)": "小麦粥",
  "Rava Upma": "粗麦粉炒饭",
  "Chickpea Salad": "鹰嘴豆沙拉",
  "Boiled Sweet Potato": "煮红薯",
  "Coconut Water": "椰子水",
  "Masala Omelette": "香料煎蛋卷",
  "Vegetable Poha": "炒扁米",
  "1 egg": "1 个鸡蛋",
  "1 bowl": "1 碗",
  "1 medium": "1 个中等大小",
  "1 piece": "1 块",
  "1 cup": "1 杯",
  "2 slices": "2 片",
  "2 small pieces": "2 小块",
  "10 pieces": "10 块",
  "1 glass": "1 杯玻璃杯",
  "2 pavs + bhaji": "2 块面包 + 咖喱",
  "1 roti + sabzi": "1 张薄饼 + 蔬菜",
  "1 sandwich": "1 个三明治",
  "2 idlis + sambar'": "2 个米发糕 + 酸辣汤",
  "1 chapati + ½ cup curd": "1 张面饼 + 半杯酸奶",
  "Rice with Dal": "米饭配扁豆汤",
  "Grilled Chicken": "烤鸡胸",
  "Paneer Curry": "奶酪咖喱",
  "Mixed Vegetable Curry": "什锦蔬菜咖喱",
  "Chapati with Daal": "印度饼配扁豆汤",
  "Fish Curry with Rice": "鱼咖喱配米饭",
  "Rajma Chawal": "红豆米饭",
  "Chole Bhature": "咖喱鹰嘴豆配炸面饼",
  "Kadhi with Rice": "酸奶咖喱配米饭",
  "Palak Paneer": "菠菜奶酪",
  "Stuffed Paratha": "馅饼",
  "Veg Pulao": "蔬菜炒饭",
  "Biryani with Raita": "香料炒饭配酸奶酱",
  "Tofu Stir Fry": "炒豆腐",
  "Chicken Tikka": "鸡肉块",
  "Veg Fried Rice": "蔬菜炒饭",
  "Aloo Gobi with Roti": "土豆花菜配印度饼",
  "Baingan Bharta": "烤茄子泥",
  "Sambar with Rice": "酸辣汤配米饭",
  "Chicken Curry with Roti": "鸡肉咖喱配印度饼",
  "Bhindi Masala with Roti": "秋葵香料炒配印度饼",
  "Egg Curry with Rice": "鸡蛋咖喱配米饭",
  "Lentil Soup with Bread": "扁豆汤配面包",
  "Methi Thepla with Curd": "香菜煎饼配酸奶",
  "Soybean Curry with Rice": "黄豆咖喱配米饭",
  "Cabbage Sabzi with Chapati": "炒卷心菜配印度饼",
  "Dal Makhani with Naan": "奶油扁豆配烤饼",
  "Vegetable Korma with Roti": "蔬菜果仁咖喱配印度饼",
  "Tandoori Roti with Paneer": "炭烤面饼配奶酪",
  "Mixed Dal with Rice": "混合扁豆配米饭",
  "Bottle Gourd Curry with Roti": "葫芦咖喱配印度饼",
  "Kofta Curry with Roti": "蔬菜丸子咖喱配印度饼",
  "Paneer Bhurji with Bread": "炒奶酪碎配面包",
  "Chana Masala with Rice": "香辣鹰嘴豆配米饭",
  "Curd Rice": "酸奶拌饭",
  "Tomato Rice": "番茄饭",
  "Vegetable Stew with Appam": "蔬菜炖菜配米发饼",
  "Dhokla with Green Chutney": "蒸米糕配青酱",
  "Besan Chilla with Salad": "鹰嘴豆粉煎饼配沙拉",
  "Lauki Chana Dal": "葫芦配扁豆",
  "Spinach Corn Curry": "菠菜玉米咖喱",
  "Tinda Masala with Roti": "印度瓜香料配印度饼",
  "Masoor Dal with Rice": "红扁豆配米饭",
  "Vegetable Handi with Naan": "陶锅炖菜配烤饼",
  "Egg Bhurji with Chapati": "炒鸡蛋碎配印度饼",
  "Pumpkin Curry with Rice": "南瓜咖喱配米饭",
  "2 rotis + sabzi": "2 张面饼 + 蔬菜",
  "1 cup rice + 1 cup dal": "1 杯米饭 + 1 杯扁豆汤",
  "1 breast": "1 块鸡胸",
  "2 chapatis + dal'": "2 张印度饼 + 扁豆汤",
  "1 bowl curry + 1 cup rice": "1 碗咖喱 + 1 杯米饭",
  "1 bhatura + chole": "1 张炸饼 + 咖喱鹰嘴豆",
  "1 paratha": "1 张馅饼",
  "1 bowl + 2 rotis": "1 碗 + 2 张面饼",
  "1 cup + 1 bowl": "1 杯 + 1 碗",
  "1 bowl + 1 cup rice": "1 碗 + 1 杯米饭",
  "1 bowl + 1 bread slice": "1 碗 + 1 片面包",
  "2 theplas + ½ cup curd": "2 张香煎饼 + 半杯酸奶",
  "1 bowl + 2 chapatis": "1 碗 + 2 张印度饼",
  "1 bowl + 1 naan": "1 碗 + 1 张烤饼",
  "2 rotis + paneer": "2 张面饼 + 奶酪",
  "1 bowl + 2 slices": "1 碗 + 2 片",
  "1 bowl + 2 appams": "1 碗 + 2 张米发饼",


  "3 pieces": "3块",
  "2 chillas + salad": "2张Chilla + 沙拉",
  "Cal": "卡尔",
  "Cropper": "克罗珀",
  "Calorie Tracker": "卡路里追踪器",
  "Add Calorie": "添加卡路里",
  "Quantity": "数量",
  "Ask With Open AI": "向Open AI提问",
  "This picture not available Calorie,Protein,Carbs and Fats,": "此图片不可用 卡路里、蛋白质、碳水化合物和脂肪。",
  "Ask Botanist": "问植物学家",
  "Write your message": "写下你的信息",
  "Confirm Reset": "确认重置",
  "Are you sure you want to Reset Data?": "你确定要重置账户吗？",
  "Reset": "重置",
  "You have been Reset Account": "您的账户已重置",
  "Personal Details": "个人资料",
  "Goal Weight": "目标体重",
  "cm": "厘米",
  "Date Of Birth": "出生日期",
  "Gender": "性别",
  "Male": "男性",
  "Female": "女性",
  "Choose your desired weight?": "选择您想要的体重？",
  "Imperial": "英制",
  "Metric": "公制",
  "Weight": "体重",
  "lb": "磅",
  "ft": "英尺",
  "in": "英寸",
  "Day": "天",
  "January": "一月",
  "February": "二月",
  "March": "三月",
  "April": "四月",
  "June": "六月",
  "July": "七月",
  "August": "八月",
  "September": "九月",
  "October": "十月",
  "November": "十一月",
  "December": "十二月",
  "Update Your Gender": "更新您的性别",
  "Other": "其他",
  "Adjust Goals": "调整目标",
  "How many workout do you per week?": "您每周锻炼多少次？",
  "This will used to calibrate your custom plan": "这将用于校准您的自定义计划",
  "Workout Now and then": "偶尔锻炼",
  "A few workout per week": "每周锻炼几次",
  "Dedicated athlete": "专注运动员",
  "What is your goal?": "你的目标是什么？",
  "This helps is generate a plan for your calorie intake.": "这有助于生成您的卡路里摄入计划。",
  "Gain Weight": "增重",
  "Lose Weight": "减重",
  "Update Calorie Goal": "更新卡路里目标",
  "Save": "保存",
  "Calorie Goal": "卡路里目标",
  "Update Protein Goal": "更新蛋白质目标",
  "Protein goal": "蛋白质目标",
  "Update Carb Goal": "更新碳水化合物目标",
  "Carb goal": "碳水化合物目标",
  "Update Fat Goal": "更新脂肪目标",
  "Auto Generate Goal": "自动生成目标",
  "Fruit Salad": "水果沙拉",
  "Roasted Chickpeas": "烤鹰嘴豆",
  "Mixed Nuts": "混合坚果",
  "Yogurt with Honey": "蜂蜜酸奶",
  "Apple with Peanut Butter": "苹果配花生酱",
  "Protein Bar": "蛋白棒",
  "Whole Wheat Crackers": "全麦饼干",
  "Granola Bar": "格兰诺拉能量棒",
  "Peanut Chikki": "花生芝麻糖",
  "Bhel Puri": "贝尔普里",
  "Khakra": "卡克拉",
  "Masala Makhana": "麻辣玛卡纳",
  "Hummus with Veggies": "鹰嘴豆泥配蔬菜",
  "Paneer Cubes": "帕尼尔立方体",
  "Milkshake (Low Sugar)": "奶昔（低糖）",
  "Dhokla": "多克拉",
  "Vegetable Soup": "蔬菜汤",
  "Idli with Chutney": "印多里配酸辣酱",
  "Cheese Slice": "奶酪片",
  "Chana Chaat": "鹰嘴豆沙拉",
  "Moong Dal Chilla": "黄豆饼",
  "Rice Cake with Peanut Butter": "米饼配花生酱",
  "Popcorn (Air-popped)": "爆米花（空气爆米）",
  "Avocado Toast": "鳄梨吐司",
  "Stuffed Dates": "夹心枣",
  "Oats Cookies": "燕麦饼干",
  "Fruit Smoothie": "水果冰沙",
  "Carrot Sticks with Hummus": "胡萝卜条配鹰嘴豆泥",
  "Soy Nuts": "大豆坚果",
  "Trail Mix": "混合干果",
  "Besan Ladoo": "贝桑拉多",
  "Upma (small portion)": "小份乌帕马",
  "Egg Roll (Mini)": "迷你蛋卷",
  "Rice Idli": "米饭伊德里",
  "Cucumber Sandwich": "黄瓜三明治",
  "Fruit Chaat": "水果沙拉",
  "Lassi (Sweet)": "甜味拉西",
  "Cold Coffee (Low Sugar)": "冷咖啡（低糖）",
  "Rava Dhokla": "拉瓦多克拉",
  "Vegetable Cutlet": "蔬菜切尔特",
  "Chikki with Jaggery": "胡椒糖",
  "Milk (Low Fat)": "低脂牛奶",
  "Baked Samosa": "烤三角饺子",
  "Vegetable Wrap": "蔬菜卷",
  "Roasted Soybeans": "烤大豆",
  "1/2 cup": "半杯",
  "1 handful": "一把",
  "1 apple + 1 tbsp PB": "1个苹果 + 1汤匙花生酱",
  "1 bar": "1条",
  "5 pieces": "5块",
  "½ cup hummus + veggies": "半杯鹰嘴豆泥 + 蔬菜",
  "50g": "50克",
  "1 idli + chutney": "1个伊德里 + 酸辣酱",
  "1 slice": "1片",
  "1 chilla": "1个Chilla",
  "1 cake + 1 tbsp PB": "1块蛋糕 + 1汤匙花生酱",
  "2 cups": "2杯",
  "1 toast": "1片吐司",
  "3 dates": "3颗枣",
  "2 cookies": "2块饼干",
  "½ cup": "半杯",
  "1 small bowl": "1小碗",
  "1 roll": "1个卷",
  "1 wrap": "1个卷饼",
  "Chapati with Sabzi": "薄饼配蔬菜",
  "Grilled Fish": "烤鱼",
  "Moong Dal Khichdi": "黄豆杂烩",
  "Paneer Bhurji with Roti": "帕尼尔卤菜配罗蒂",
  "Brown Rice with Veg Curry": "糙米配蔬菜咖喱",
  "Quinoa with Stir Fry Veggies": "藜麦配炒蔬菜",
  "Grilled Tofu with Salad": "烤豆腐配沙拉",
  "Vegetable Pulao": "蔬菜普劳",
  "Palak Paneer with Chapati": "菠菜帕尼尔配薄饼",
  "Mixed Vegetable Soup": "混合蔬菜汤",
  "Stuffed Paratha with Curd": "夹心薄饼配酸奶",
  "Oats Khichdi": "燕麦杂烩",
  "Roti with Bhindi": "罗蒂配秋葵",
  "Dal Tadka with Jeera Rice": "达尔塔卡配孜然米饭",
  "Vegetable Handvo": "蔬菜汉德沃",
  "Kadhi with Bajra Roti": "酸奶咖喱配高粱饼",
  "Tofu Curry with Quinoa": "豆腐咖喱配藜麦",
  "Bhakri with Thecha": "巴克里配莎奇",
  "Biryani (Veg)": "素菜比尔亚尼",
  "Rajma with Brown Rice": "拉吉玛配糙米",
  "Daliya (Broken Wheat Porridge)": "达利亚（碎小麦粥）",
  "Pumpkin Sabzi with Chapati": "南瓜蔬菜配薄饼",
  "Cauliflower Stir Fry": "炒菜花",
  "Boiled Egg Salad": "煮蛋沙拉",
  "Tomato Rasam with Rice": "番茄拉萨姆配米饭",
  "Sweet Potato with Curd": "地瓜配酸奶",
  "Stuffed Capsicum": "填充辣椒",
  "Paneer Tikka with Mint Chutney": "印度奶酪提卡配薄荷酸辣酱",
  "Rice with Sambar": "米饭配桑巴尔",
  "Vegetable Thepla with Dahi": "蔬菜赛普拉配酸奶",
  "Grilled Mushroom Skewers": "烤蘑菇串",
  "Beetroot Sabzi with Roti": "甜菜蔬菜配印度烤饼",
  "Spinach Dal with Rice": "菠菜达尔配米饭",
  "Lentil Soup with Toast": "扁豆汤配烤面包",
  "Tinda Curry with Chapati": "甜瓜咖喱配印度薄饼",
  "Egg Bhurji with Roti": "炒蛋配印度烤饼",
  "Karela Sabzi with Roti": "苦瓜蔬菜配印度烤饼",
  "Zucchini Stir Fry": "炒西葫芦",
  "Low Carb Paneer Bowl": "低碳印度奶酪碗",
  "Stuffed Tomato": "填充番茄",
  "Vegetable Rava Upma": "蔬菜沙米乌帕玛",
  "2 chapatis + sabzi": "2个印度烤饼 + 蔬菜",
  "1 fillet": "1块鱼柳",
  "1 bowl + 1 roti": "1碗 + 1个印度烤饼",
  "1 plate": "1盘",
  "1 cup rice + dal": "1杯米饭 + 达尔",
  "1 paratha + ½ cup curd": "1个印度煎饼 + 半杯酸奶",
  "2 rotis + bhindi": "2个印度烤饼 + 秋葵",
  "1 roti + 1 bowl kadhi": "1个印度烤饼 + 1碗卡迪",
  "1 bhakri + chutney": "1个巴克里 + 酱",
  "1 bowl curry + 1 roti": "1碗咖喱 + 1个印度烤饼",
  "2 chillas": "2个切拉",
  "1 bowl + ½ cup curd": "1碗 + 半杯酸奶",
  "1 serving": "1份",
  "1 cup rice + sambar": "1杯米饭 + 桑巴尔",
  "1 thepla + curd": "1个赛普拉 + 酸奶",
  "1 skewer": "1串",
  "1 bowl + 1 toast": "1碗 + 1片烤面包",
  "1 bowl + 1 appam": "1碗 + 1个阿帕姆",
  "1 tomato": "1个番茄",
  "Restore": "恢复",
  "Get Premium": "获得高级版",
  "Get All The New Exciting Features": "获得所有新的令人兴奋的功能",
  "Unlock Food Scanner": "解锁食品扫描器",
  "Unlock Food Calorie": "解锁食品卡路里",
  "Unlock Unlimited Chat with Ai": "解锁与AI无限聊天",
  "Unlimited Food Scanner To Calorie": "无限食品扫描到卡路里",
  "Most Popular": "最受欢迎",
  "Subscription": "订阅",
  "BUY NOW": "立即购买",
  "Terms of Condition": "条款与条件",
  "Welcome": "欢迎",
  "Calorie tracking made easy": "卡路里跟踪变得简单",
  "Just snap a quick photo of your meal and we''ll do the rest": "只需快速拍摄您的餐点照片，其余的交给我们",
  "In-depth nutrition analyses": "深入的营养分析",
  "We will keep your informed about your food choicer and their nutritional content": "我们将保持您对食物选择及其营养成分的了解",
  "Transform your body": "改变你的身体",
  "Today is best time to start working toward your dream body": "今天是朝着梦想身体迈进的最佳时机",
  "Where were you born?": "你出生在哪里？",
  "This Will be used to calibrate your custom plan": "这将用于校准您的自定义计划",
  "What's stopping you from reaching your goals?": "是什么阻止你实现目标？",
  "Lack of consistency": "缺乏一致性",
  "Unhealthy eating habits": "不健康的饮食习惯",
  "Lack of supports": "缺乏支持",
  "Busy schedule": "忙碌的日程",
  "Lack of meal inspiration": "缺乏餐点灵感",
  "We're setting": "我们正在设置",
  "everything up for you": "为您准备一切",
  "Customizing health plan....": "正在定制健康计划...."
};
