const Map<String, String> dutch = {
  "Home": "Startpagina",
  "Calorie": "Calorie",
  "Analytics": "Analyse",
  "Setting": "Instellingen",
  "Track Food": "Eten bijhouden",
  "Consumed": "Geconsumeerd",
  "Remaining": "Resterend",
  "Protein": "Eiwit",
  "Carbs": "Koolhydraten",
  "Fats": "Vetten",
  "History": "Geschiedenis",
  "View All": "Alles bekijken",
  "BreakFast": "Ontbijt",
  "Lunch": "Lunch",
  "snack(s)": "Tussendoortje",
  "Dinner": "Diner",
  "Which meal would you like to track?": "Welke maaltijd wil je bijhouden?",
  "Snap Tips": "Fototips",
  "Too close": "Te dichtbij",
  "Too far": "Te ver weg",
  "Multi-species": "Meerdere soorten",
  "Continue": "Doorgaan",
  "OverView": "Overzicht",
  "Weight Goal": "Gewichtsdoel",
  "Update": "Bijwerken",
  "Current Weight": "Huidig gewicht",
  "kg": "kg",
  "Try to update once a week so we can adjust your plan to ensure you hit your goal": "Probeer eenmaal per week bij te werken zodat we je plan kunnen aanpassen om je doel te behalen",
  "Update Weight": "Gewicht bijwerken",
  "Week": "Week",
  "Month": "Maand",
  "Year": "Jaar",
  "Update Weight Goal": "Gewichtsdoel bijwerken",
  "Enter new weight (kg)": "Voer nieuw gewicht in (kg)",
  "Cancel": "Annuleren",
  "Calorie Your Week :": "Je week in calorieën:",
  "Sun": "Zo",
  "Mon": "Ma",
  "Tue": "Di",
  "Wed": "Wo",
  "Thu": "Do",
  "Fri": "Vr",
  "Sat": "Za",
  "Average Calorie Month :": "Gemiddelde calorieën per maand:",
  "Average Calorie Yearly :": "Gemiddelde calorieën per jaar:",
  "Jan": "Jan",
  "Feb": "Feb",
  "Mar": "Mrt",
  "Apr": "Apr",
  "May": "Mei",
  "Jun": "Jun",
  "Jul": "Jul",
  "Aug": "Aug",
  "Sep": "Sep",
  "Oct": "Okt",
  "Nov": "Nov",
  "Dec": "Dec",
  "Age": "Leeftijd",
  "Height": "Lengte",
  "Customization": "Personalisatie",
  "Dark Mode": "Donkere modus",
  "Language": "Taal",
  "Personal details": "Persoonlijke gegevens",
  "Adjust goals": "Doelen aanpassen",
  "Calories,carbs,fat and protein": "Calorieën, koolhydraten, vetten en eiwitten",
  "Chat history": "Chatgeschiedenis",
  "Legal": "Juridisch",
  "Terms and Condition": "Algemene voorwaarden",
  "Privacy Policy": "Privacybeleid",
  "Reset Data?": "Account resetten?",
  "VERSION": "VERSIE",
  "History not found": "Geschiedenis niet gevonden",
  "Delete Item": "Item verwijderen",
  "Are you sure you want to delete this item?": "Weet je zeker dat je dit item wilt verwijderen?",
  "Delete": "Verwijderen",
  "Search by Food Name/Dish": "Zoeken op voedselnaam/gerecht",
  "🎯 Calorie Goal Reached": "🎯 Caloriedoel bereikt",
  "You've completed your calorie goal for today. Would you like to add more?": "Je hebt je caloriedoel voor vandaag bereikt. Wil je meer toevoegen?",
  "Done": "Klaar",
  "Add More Calories": "Meer calorieën toevoegen",
  "Boiled Egg": "Gekookt ei",
  "Oatmeal": "Havermout",
  "Banana": "Banaan",
  "Paratha": "Paratha",
  "Idli": "Idli",
  "Dosa": "Dosa",
  "Upma": "Upma",
  "Poha": "Poha",
  "Bread Butter": "Brood met boter",
  "Cornflakes with Milk": "Cornflakes met melk",
  "Chilla (Besan)": "Chilla (kikkererwtenmeel)",
  "Sprouts Salad": "Kiemgroentesalade",
  "Pancakes": "Pannenkoeken",
  "Apple": "Appel",
  "Milk": "Melk",
  "Almonds": "Amandelen",
  "Smoothie (Fruit)": "Smoothie (fruit)",
  "Yogurt (Plain)": "Yoghurt (naturel)",
  "Khichdi": "Khichdi",
  "Thepla": "Thepla (gekruide Indiase pannenkoek)",
  "Cheela (Moong dal)": "Cheela (mungbonenpannenkoek)",
  "Pav Bhaji": "Pav Bhaji (groentecurry met broodjes)",
  "Sabudana Khichdi": "Sabudana Khichdi (tapioca gerecht)",
  "Roti with Sabzi": "Roti met groenten",
  "Peanut Butter Bread": "Brood met pindakaas",
  "Fruit Bowl": "Fruitschaal",
  "Vegetable Sandwich": "Groentesandwich",
  "Rice Idli with Sambar": "Rijstidli met sambar",
  "Boiled Corn": "Gekookte maïs",
  "Paneer Bhurji": "Paneer Bhurji (gekruimelde kaas met kruiden)",
  "Protein Shake": "Eiwitshake",
  "Muesli with Milk": "Muesli met melk",
  "Chapati with Curd": "Chapati met yoghurt",
  "Porridge (Daliya)": "Pap (gebroken tarwe)",
  "Rava Upma": "Rava Upma (hartig griesmeelgerecht)",
  "Chickpea Salad": "Kikkererwtensalade",
  "Boiled Sweet Potato": "Gekookte zoete aardappel",
  "Coconut Water": "Kokoswater",
  "Masala Omelette": "Masala omelet",
  "Vegetable Poha": "Groente Poha (plat rijstgerecht)",
  "1 egg": "1 ei",
  "1 bowl": "1 kom",
  "1 medium": "1 middelgroot",
  "1 piece": "1 stuk",
  "1 cup": "1 kopje",
  "2 slices": "2 sneetjes",
  "2 small pieces": "2 kleine stukjes",
  "10 pieces": "10 stukjes",
  "1 glass": "1 glas",
  "2 pavs + bhaji": "2 broodjes + bhaji",
  "1 roti + sabzi": "1 roti + groenten",
  "1 sandwich": "1 sandwich",
  "2 idlis + sambar'": "2 idli's + sambar",
  "1 chapati + ½ cup curd": "1 chapati + ½ kopje yoghurt",
  "Rice with Dal": "Rijst met linzen",
  "Grilled Chicken": "Gegrilde kip",
  "Paneer Curry": "Paneer curry",
  "Mixed Vegetable Curry": "Gemengde groentecurry",
  "Chapati with Daal": "Chapati met linzensoep",
  "Fish Curry with Rice": "Viscurry met rijst",
  "Rajma Chawal": "Rajma Chawal (kidneybonen met rijst)",
  "Chole Bhature": "Chole Bhature (kikkererwten met gefrituurd brood)",
  "Kadhi with Rice": "Kadhi met rijst (yoghurtsaus)",
  "Palak Paneer": "Palak Paneer (spinazie met kaas)",
  "Stuffed Paratha": "Gevulde paratha",
  "Veg Pulao": "Groente Pulao (rijstgerecht)",
  "Biryani with Raita": "Biryani met raita",
  "Tofu Stir Fry": "Roerbaktofu",
  "Chicken Tikka": "Kip Tikka",
  "Veg Fried Rice": "Groente gebakken rijst",
  "Aloo Gobi with Roti": "Aloo Gobi met roti",
  "Baingan Bharta": "Baingan Bharta (geroosterde aubergine)",
  "Sambar with Rice": "Sambar met rijst",
  "Chicken Curry with Roti": "Kipkerrie met roti",
  "Bhindi Masala with Roti": "Okra Masala met roti",
  "Egg Curry with Rice": "Eiercurry met rijst",
  "Lentil Soup with Bread": "Linzensoep met brood",
  "Methi Thepla with Curd": "Methi Thepla met yoghurt",
  "Soybean Curry with Rice": "Sojabonencurry met rijst",
  "Cabbage Sabzi with Chapati": "Koolgroente met chapati",
  "Dal Makhani with Naan": "Dal Makhani met naan",
  "Vegetable Korma with Roti": "Groentekorma met roti",
  "Tandoori Roti with Paneer": "Tandoori roti met paneer",
  "Mixed Dal with Rice": "Gemengde linzen met rijst",
  "Bottle Gourd Curry with Roti": "Kalebascurry met roti",
  "Kofta Curry with Roti": "Kofta curry met roti",
  "Paneer Bhurji with Bread": "Paneer Bhurji met brood",
  "Chana Masala with Rice": "Chana Masala met rijst",
  "Curd Rice": "Yoghurtrijst",
  "Tomato Rice": "Tomatenrijst",
  "Vegetable Stew with Appam": "Groentenstoofpot met appam",
  "Dhokla with Green Chutney": "Dhokla met groene chutney",
  "Besan Chilla with Salad": "Kikkererwtenpannenkoek met salade",
  "Lauki Chana Dal": "Flespompoen met linzen",
  "Spinach Corn Curry": "Spinazie-maïscurry",
  "Tinda Masala with Roti": "Tinda Masala met roti",
  "Masoor Dal with Rice": "Rode linzen met rijst",
  "Vegetable Handi with Naan": "Groentestoofpot met naan",
  "Egg Bhurji with Chapati": "Roerei met chapati",
  "Pumpkin Curry with Rice": "Pompoencurry met rijst",
  "2 rotis + sabzi": "2 rotis + groenten",
  "1 cup rice + 1 cup dal": "1 kop rijst + 1 kop linzen",
  "1 breast": "1 kipfilet",
  "2 chapatis + dal'": "2 chapati's + linzen",
  "1 bowl curry + 1 cup rice": "1 kom curry + 1 kop rijst",
  "1 bhatura + chole": "1 bhatura + chole",
  "1 paratha": "1 paratha",
  "1 bowl + 2 rotis": "1 kom + 2 rotis",
  "1 cup + 1 bowl": "1 kop + 1 kom",
  "1 bowl + 1 cup rice": "1 kom + 1 kop rijst",
  "1 bowl + 1 bread slice": "1 kom + 1 sneetje brood",
  "2 theplas + ½ cup curd": "2 theplas + ½ kop yoghurt",
  "1 bowl + 2 chapatis": "1 kom + 2 chapati's",
  "1 bowl + 1 naan": "1 kom + 1 naan",
  "2 rotis + paneer": "2 rotis + paneer",
  "1 bowl + 2 slices": "1 kom + 2 sneetjes",
  "1 bowl + 2 appams": "1 kom + 2 appams",


  "3 pieces": "3 stukken",
  "2 chillas + salad": "2 chillas + salade",
  "Cal": "Cal",
  "Cropper": "Cropper",
  "Calorie Tracker": "Calorie Tracker",
  "Add Calorie": "Voeg Calorie toe",
  "Quantity": "Hoeveelheid",
  "Ask With Open AI": "Vraag met Open AI",
  "This picture not available Calorie,Protein,Carbs and Fats,": "Deze afbeelding is niet beschikbaar voor Calorieën, Eiwitten, Koolhydraten en Vetten.",
  "Ask Botanist": "Vraag Botanist",
  "Write your message": "Schrijf je bericht",
  "Confirm Reset": "Bevestig Reset",
  "Are you sure you want to Reset Data?": "Weet je zeker dat je het account wilt resetten?",
  "Reset": "Reset",
  "You have been Reset Account": "Je hebt het account gereset",
  "Personal Details": "Persoonlijke gegevens",
  "Goal Weight": "Doelgewicht",
  "cm": "cm",
  "Date Of Birth": "Geboortedatum",
  "Gender": "Geslacht",
  "Male": "Man",
  "Female": "Vrouw",
  "Choose your desired weight?": "Kies je gewenste gewicht?",
  "Imperial": "Imperiaal",
  "Metric": "Metrisch",
  "Weight": "Gewicht",
  "lb": "lb",
  "ft": "ft",
  "in": "in",
  "Day": "Dag",
  "January": "Januari",
  "February": "Februari",
  "March": "Maart",
  "April": "April",
  "June": "Juni",
  "July": "Juli",
  "August": "Augustus",
  "September": "September",
  "October": "Oktober",
  "November": "November",
  "December": "December",
  "Update Your Gender": "Werk je geslacht bij",
  "Other": "Anders",
  "Adjust Goals": "Pas doelen aan",
  "How many workout do you per week?": "Hoeveel keer per week sport je?",
  "This will used to calibrate your custom plan": "Dit wordt gebruikt om je aangepaste plan te kalibreren",
  "Workout Now and then": "Af en toe sporten",
  "A few workout per week": "Een paar keer per week sporten",
  "Dedicated athlete": "Toegewijde atleet",
  "What is your goal?": "Wat is je doel?",
  "This helps is generate a plan for your calorie intake.": "Dit helpt om een plan voor je calorie-inname te genereren.",
  "Gain Weight": "Gewicht aankomen",
  "Lose Weight": "Afvallen",
  "Update Calorie Goal": "Werk calorie doel bij",
  "Save": "Opslaan",
  "Calorie Goal": "Calorie doel",
  "Update Protein Goal": "Werk eiwit doel bij",
  "Protein goal": "Eiwit doel",
  "Update Carb Goal": "Werk koolhydraat doel bij",
  "Carb goal": "Koolhydraat doel",
  "Update Fat Goal": "Werk vet doel bij",
  "Auto Generate Goal": "Automatisch doel genereren",
  "Fruit Salad": "Fruit salade",
  "Roasted Chickpeas": "Geroosterde kikkererwten",
  "Mixed Nuts": "Gemengde noten",
  "Yogurt with Honey": "Yoghurt met honing",
  "Apple with Peanut Butter": "Appel met pindakaas",
  "Protein Bar": "Eiwit reep",
  "Whole Wheat Crackers": "Volkoren crackers",
  "Granola Bar": "Granola reep",
  "Peanut Chikki": "Pinda Chikki",
  "Bhel Puri": "Bhel Puri",
  "Khakra": "Khakra",
  "Masala Makhana": "Masala Makhana",
  "Hummus with Veggies": "Hummus met groenten",
  "Paneer Cubes": "Paneer blokjes",
  "Milkshake (Low Sugar)": "Milkshake (Weinig suiker)",
  "Dhokla": "Dhokla",
  "Vegetable Soup": "Groentesoep",
  "Idli with Chutney": "Idli met chutney",
  "Cheese Slice": "Kaas plakje",
  "Chana Chaat": "Chana Chaat",
  "Moong Dal Chilla": "Moong Dal Chilla",
  "Rice Cake with Peanut Butter": "Rijstcake met pindakaas",
  "Popcorn (Air-popped)": "Popcorn (lucht gebakken)",
  "Avocado Toast": "Avocado toast",
  "Stuffed Dates": "Vervulde dadels",
  "Oats Cookies": "Havermout koekjes",
  "Fruit Smoothie": "Fruit smoothie",
  "Carrot Sticks with Hummus": "Wortelstokken met hummus",
  "Soy Nuts": "Soja noten",
  "Trail Mix": "Trail mix",
  "Besan Ladoo": "Besan Ladoo",
  "Upma (small portion)": "Upma (kleine portie)",
  "Egg Roll (Mini)": "Eierrol (mini)",
  "Rice Idli": "Rijst idli",
  "Cucumber Sandwich": "Komkommer sandwich",
  "Fruit Chaat": "Fruit Chaat",
  "Lassi (Sweet)": "Lassi (Zoet)",
  "Cold Coffee (Low Sugar)": "Ijskoffie (weinig suiker)",
  "Rava Dhokla": "Rava Dhokla",
  "Vegetable Cutlet": "Groente cutlet",
  "Chikki with Jaggery": "Chikki met jaggery",
  "Milk (Low Fat)": "Melk (Low Fat)",
  "Baked Samosa": "Gepofte samosa",
  "Vegetable Wrap": "Groente wrap",
  "Roasted Soybeans": "Geroosterde sojabonen",
  "1/2 cup": "1/2 kop",
  "1 handful": "1 handvol",
  "1 apple + 1 tbsp PB": "1 appel + 1 eetlepel pindakaas",
  "1 bar": "1 reep",
  "5 pieces": "5 stukken",
  "½ cup hummus + veggies": "½ kop hummus + groenten",
  "50g": "50g",
  "1 idli + chutney": "1 idli + chutney",
  "1 slice": "1 plakje",
  "1 chilla": "1 chilla",
  "1 cake + 1 tbsp PB": "1 cake + 1 eetlepel pindakaas",
  "2 cups": "2 kopjes",
  "1 toast": "1 toast",
  "3 dates": "3 dadels",
  "2 cookies": "2 koekjes",
  "½ cup": "½ kop",
  "1 small bowl": "1 klein kom",
  "1 roll": "1 rol",
  "1 wrap": "1 wrap",
  "Chapati with Sabzi": "Chapati met Sabzi",
  "Grilled Fish": "Gegrilde vis",
  "Moong Dal Khichdi": "Moong Dal Khichdi",
  "Paneer Bhurji with Roti": "Paneer Bhurji met Roti",
  "Brown Rice with Veg Curry": "Bruine rijst met groente curry",
  "Quinoa with Stir Fry Veggies": "Quinoa met roergebakken groenten",
  "Grilled Tofu with Salad": "Gegrilde tofu met salade",
  "Vegetable Pulao": "Groente Pulao",
  "Palak Paneer with Chapati": "Palak Paneer met Chapati",
  "Mixed Vegetable Soup": "Gemengde groentesoep",
  "Stuffed Paratha with Curd": "Gevulde Paratha met Yoghurt",
  "Oats Khichdi": "Havermout Khichdi",
  "Roti with Bhindi": "Roti met Bhindi",
  "Dal Tadka with Jeera Rice": "Dal Tadka met Jeera rijst",
  "Vegetable Handvo": "Groente Handvo",
  "Kadhi with Bajra Roti": "Kadhi met Bajra Roti",
  "Tofu Curry with Quinoa": "Tofu curry met Quinoa",
  "Bhakri with Thecha": "Bhakri met Thecha",
  "Biryani (Veg)": "Biryani (Vegetarisch)",
  "Rajma with Brown Rice": "Rajma met bruine rijst",
  "Daliya (Broken Wheat Porridge)": "Daliya (Gebroken tarwe pap)",
  "Pumpkin Sabzi with Chapati": "Pompoen Sabzi met Chapati",
  "Cauliflower Stir Fry": "Bloemkool roerbak",
  "Boiled Egg Salad": "Kookeiersalade",
  "Tomato Rasam with Rice": "Tomaten Rasam met Rijst",
  "Sweet Potato with Curd": "Zoete Aardappel met Yoghurt",
  "Stuffed Capsicum": "Gevulde Paprika",
  "Paneer Tikka with Mint Chutney": "Paneer Tikka met Munt Chutney",
  "Rice with Sambar": "Rijst met Sambar",
  "Vegetable Thepla with Dahi": "Groente Thepla met Yoghurt",
  "Grilled Mushroom Skewers": "Gegrilde Champignon Spiezen",
  "Beetroot Sabzi with Roti": "Bieten Sabzi met Roti",
  "Spinach Dal with Rice": "Spinazie Dal met Rijst",
  "Lentil Soup with Toast": "Linzen Soep met Toast",
  "Tinda Curry with Chapati": "Tinda Curry met Chapati",
  "Egg Bhurji with Roti": "Ei Bhurji met Roti",
  "Karela Sabzi with Roti": "Karela Sabzi met Roti",
  "Zucchini Stir Fry": "Courgette Roerbak",
  "Low Carb Paneer Bowl": "Low Carb Paneer Kom",
  "Stuffed Tomato": "Gevulde Tomaat",
  "Vegetable Rava Upma": "Groente Rava Upma",
  "2 chapatis + sabzi": "2 chapati + sabzi",
  "1 fillet": "1 filet",
  "1 bowl + 1 roti": "1 kom + 1 roti",
  "1 plate": "1 bord",
  "1 cup rice + dal": "1 kop rijst + dal",
  "1 paratha + ½ cup curd": "1 paratha + ½ kop yoghurt",
  "2 rotis + bhindi": "2 rotis + bhindi",
  "1 roti + 1 bowl kadhi": "1 roti + 1 kom kadhi",
  "1 bhakri + chutney": "1 bhakri + chutney",
  "1 bowl curry + 1 roti": "1 kom curry + 1 roti",
  "2 chillas": "2 chillas",
  "1 bowl + ½ cup curd": "1 kom + ½ kop yoghurt",
  "1 serving": "1 portie",
  "1 cup rice + sambar": "1 kop rijst + sambar",
  "1 thepla + curd": "1 thepla + yoghurt",
  "1 skewer": "1 spies",
  "1 bowl + 1 toast": "1 kom + 1 toast",
  "1 bowl + 1 appam": "1 kom + 1 appam",
  "1 tomato": "1 tomaat",
  "Restore": "Herstellen",
  "Get Premium": "Krijg Premium",
  "Get All The New Exciting Features": "Krijg alle nieuwe opwindende functies",
  "Unlock Food Scanner": "Ontgrendel Voedsel Scanner",
  "Unlock Food Calorie": "Ontgrendel Voedsel Calorieën",
  "Unlock Unlimited Chat with Ai": "Ontgrendel Onbeperkte Chat met AI",
  "Unlimited Food Scanner To Calorie": "Onbeperkte Voedsel Scanner naar Calorieën",
  "Most Popular": "Meest Populair",
  "Subscription": "Abonnement",
  "BUY NOW": "Koop Nu",
  "Terms of Condition": "Voorwaarden",
  "Welcome": "Welkom",
  "Calorie tracking made easy": "Calorie tracking eenvoudig gemaakt",
  "Just snap a quick photo of your meal and we''ll do the rest": "Maak snel een foto van je maaltijd en wij doen de rest",
  "In-depth nutrition analyses": "Diepgaande voedingsanalyse",
  "We will keep your informed about your food choicer and their nutritional content": "We houden je op de hoogte van je voedselkeuzes en hun voedingswaarde",
  "Transform your body": "Transformeer je lichaam",
  "Today is best time to start working toward your dream body": "Vandaag is de beste tijd om te beginnen met werken aan je droomlichaam",
  "Where were you born?": "Waar ben je geboren?",
  "This Will be used to calibrate your custom plan": "Dit wordt gebruikt om je persoonlijke plan te kalibreren",
  "What's stopping you from reaching your goals?": "Wat houdt je tegen om je doelen te bereiken?",
  "Lack of consistency": "Gebrek aan consistentie",
  "Unhealthy eating habits": "Ongezonde eetgewoonten",
  "Lack of supports": "Gebrek aan ondersteuning",
  "Busy schedule": "Druk schema",
  "Lack of meal inspiration": "Gebrek aan maaltijdinspiratie",
  "We're setting": "We zijn bezig met instellen",
  "everything up for you": "alles voor je in te stellen",
  "Customizing health plan....": "Gezondheidsplan aanpassen...."
};
