const Map<String, String> english = {
  "Home": "Home",
  "Calorie": "Calorie",
  "Analytics": "Analytics",
  "Setting": "Setting",
  "Track Food": "Track Food",
  "Consumed": "Consumed",
  "Remaining": "Remaining",
  "Protein": "Protein",
  "Carbs": "Carbs",
  "Fats": "Fats",
  "History": "History",
  "View All": "View All",
  "BreakFast": "BreakFast",
  "Lunch": "Lunch",
  "snack(s)": "snack(s)",
  "Dinner": "Dinner",
  "Which meal would you like to track?": "Which meal would you like to track?",
  "Snap Tips": "Snap Tips",
  "Too close": "Too close",
  "Too far": "Too far",
  "Multi-species": "Multi-species",
  "Continue": "Continue",
  "OverView": "OverView",
  "Weight Goal": "Weight Goal",
  "Update": "Update",
  "Current Weight": "Current Weight",
  "kg": "kg",
  "Try to update once a week so we can adjust your plan to ensure you hit your goal" : "Try to update once a week so we can adjust your plan to ensure you hit your goal",
  "Update Weight": "Update Weight",
  "Week": "Week",
  "Month": "Month",
  "Year": "Year",
  "Update Weight Goal": "Update Weight Goal",
  "Enter new weight (kg)": "Enter new weight (kg)",
  "Cancel": "Cancel",
  "Calorie Your Week :": "Calorie Your Week :",
  'Sun': 'Sun',
  'Mon': 'Mon',
  'Tue': 'Tue',
  'Wed': 'Wed',
  'Thu': 'Thu',
  'Fri': 'Fri',
  'Sat': 'Sat',
  "Average Calorie Month :" : "Average Calorie Month :",
  "Average Calorie Yearly :" : "Average Calorie Year :",
  "Jan" : "Jan",
  "Feb" : "Feb",
  "Mar" : "Mar",
  "Apr" : "Apr",
  "May" : "May",
  "Jun" : "Jun",
  "Jul" : "Jul",
  "Aug" : "Aug",
  "Sep" : "Sep",
  "Oct" : "Oct",
  "Nov" : "Nov",
  "Dec" : "Dec",
  "Age" : "Age",
  "Height" : "Height",
  "Customization" : "Customization",
  "Dark Mode" : "Dark Mode",
  "Language" : "Language",
  "Personal details" : "Personal details",
  "Adjust goals" : "Adjust goals",
  "Calories,carbs,fat and protein" : "Calories,carbs,fat and protein",
  "Chat history" : "Chat history",
  "Legal" : "Legal",
  "Terms and Condition" : "Terms and Condition",
  "Privacy Policy" : "Privacy Policy",
  "Reset Data?" : "Reset Data?",
  "VERSION" : "VERSION",
  "History not found" : "History not found",
  "Delete Item" : "Delete Item",
  "Are you sure you want to delete this item?" : "Are you sure you want to delete this item?",
  "Delete" : "Delete",
  "Search by Food Name/Dish" : "Search by Food Name/Dish",
  "🎯 Calorie Goal Reached" : "🎯 Calorie Goal Reached",
  "You've completed your calorie goal for today. Would you like to add more?" : "You've completed your calorie goal for today. Would you like to add more?",
  "Done" : "Done",
  "Add More Calories" : "Add More Calories",
  "Boiled Egg" :"Boiled Egg",
  "Oatmeal" : "Oatmeal",
  "Banana" : "Banana",
  "Paratha"  : "Paratha",
  "Idli" : "Idli",
  "Dosa" : "Dosa",
  "Upma" : "Upma",
  "Poha" : "Poha",
  "Bread Butter" : "Bread Butter",
  "Cornflakes with Milk" : "Cornflakes with Milk",
  "Chilla (Besan)" : "Chilla (Besan)",
  "Sprouts Salad" : "Sprouts Salad",
  "Pancakes" : "Pancakes",
  "Apple" : "Apple",
  "Milk" : "Milk",
  "Almonds" : "Almonds",
  "Smoothie (Fruit)" : "Smoothie (Fruit)",
  "Yogurt (Plain)" : "Yogurt (Plain)",
  "Khichdi" : "Khichdi",

  "Thepla" : "Thepla",
  "Cheela (Moong dal)" : "Cheela (Moong dal)",
  "Pav Bhaji" : "Pav Bhaji",
  "Sabudana Khichdi" : "Sabudana Khichdi",
  "Roti with Sabzi" : "Roti with Sabzi",
  "Peanut Butter Bread" : "Peanut Butter Bread",
  "Fruit Bowl" : "Fruit Bowl",
  "Vegetable Sandwich" : "Vegetable Sandwich",
  "Rice Idli with Sambar" : "Rice Idli with Sambar",
  "Boiled Corn" : "Boiled Corn",
  "Paneer Bhurji" : "Paneer Bhurji",
  "Protein Shake" : "Protein Shake",
  "Muesli with Milk" : "Muesli with Milk",
  "Chapati with Curd" : "Chapati with Curd",
  "Porridge (Daliya)" : "Porridge (Daliya)",
  "Rava Upma" : "Rava Upma",
  "Chickpea Salad" : "Chickpea Salad",
  "Boiled Sweet Potato" : "Boiled Sweet Potato",
  "Coconut Water" : "Coconut Water",
  "Masala Omelette" : "Masala Omelette",
  "Vegetable Poha" : "Vegetable Poha",
  "1 egg" : "1 egg",
  "1 bowl" : "1 bowl",
  "1 medium" : "1 medium",
  "1 piece" : "1 piece",
  "1 cup" : "1 cup",
  "2 slices" : "2 slices",
  "2 small pieces" : "2 small pieces",
  "10 pieces" : "10 pieces",
  "1 glass" : "1 glass",
  "2 pavs + bhaji" : "2 pavs + bhaji",
  "1 roti + sabzi" : "1 roti + sabzi",
  "1 sandwich" : "1 sandwich",
  "2 idlis + sambar'" : "2 idlis + sambar'",
  "1 chapati + ½ cup curd" : "1 chapati + ½ cup curd",
  "Rice with Dal" : "Rice with Dal",
  "Grilled Chicken" : "Grilled Chicken",
  "Paneer Curry" : "Paneer Curry",
  "Mixed Vegetable Curry" : "Mixed Vegetable Curry",
  "Chapati with Daal" : "Chapati with Daal",
  "Fish Curry with Rice" : "Fish Curry with Rice",
  "Rajma Chawal" : "Rajma Chawal",
  "Chole Bhature" : "Chole Bhature",
  "Kadhi with Rice" : "Kadhi with Rice",
  "Palak Paneer" : "Palak Paneer",
  "Stuffed Paratha" : "Stuffed Paratha",
  "Veg Pulao" : "Veg Pulao",
  "Biryani with Raita" : "Biryani with Raita",
  "Tofu Stir Fry" : "Tofu Stir Fry",
  "Chicken Tikka" : "Chicken Tikka",
  "Veg Fried Rice" : "Veg Fried Rice",
  "Aloo Gobi with Roti": "Aloo Gobi with Roti",
  "Baingan Bharta" : "Baingan Bharta",
  "Sambar with Rice" : "Sambar with Rice",
  "Chicken Curry with Roti" : "Chicken Curry with Roti",
  "Bhindi Masala with Roti" : "Bhindi Masala with Roti",
  "Egg Curry with Rice" : "Egg Curry with Rice",
  "Lentil Soup with Bread" : "Lentil Soup with Bread",
  "Methi Thepla with Curd" : "Methi Thepla with Curd",
  "Soybean Curry with Rice" : "Soybean Curry with Rice",
  "Cabbage Sabzi with Chapati" : "Cabbage Sabzi with Chapati",
  "Dal Makhani with Naan" : "Dal Makhani with Naan",
  "Vegetable Korma with Roti" : "Vegetable Korma with Roti",
  "Tandoori Roti with Paneer" : "Tandoori Roti with Paneer",
  "Mixed Dal with Rice" : "Mixed Dal with Rice",
  "Bottle Gourd Curry with Roti" : "Bottle Gourd Curry with Roti",
  "Kofta Curry with Roti" : "Kofta Curry with Roti",
  "Paneer Bhurji with Bread" : "Paneer Bhurji with Bread",
  "Chana Masala with Rice" : "Chana Masala with Rice",
  "Curd Rice" : "Curd Rice",
  "Tomato Rice" : "Tomato Rice",
  "Vegetable Stew with Appam" : "Vegetable Stew with Appam",
  "Dhokla with Green Chutney" : "Dhokla with Green Chutney",
  "Besan Chilla with Salad" : "Besan Chilla with Salad",
  "Lauki Chana Dal" : "Lauki Chana Dal",
  "Spinach Corn Curry" :"Spinach Corn Curry",
  "Tinda Masala with Roti" : "Tinda Masala with Roti",
  "Masoor Dal with Rice" : "Masoor Dal with Rice",
  "Vegetable Handi with Naan" : "Vegetable Handi with Naan",
  "Egg Bhurji with Chapati" : "Egg Bhurji with Chapati",
  "Pumpkin Curry with Rice" : "Pumpkin Curry with Rice",
  "2 rotis + sabzi" : "2 rotis + sabzi",
  "1 cup rice + 1 cup dal" : "1 cup rice + 1 cup dal",
  "1 breast" : "1 breast",
  "2 chapatis + dal'" : "2 chapatis + dal'",
  "1 bowl curry + 1 cup rice" : "1 bowl curry + 1 cup rice",
  "1 bhatura + chole" : "1 bhatura + chole",
  "1 paratha" : "1 paratha",
  "1 bowl + 2 rotis" : "1 bowl + 2 rotis",
  "1 cup + 1 bowl" : "1 cup + 1 bowl",
  "1 bowl + 1 cup rice" : "1 bowl + 1 cup rice",
  "1 bowl + 1 bread slice" : "1 bowl + 1 bread slice",
  "2 theplas + ½ cup curd" : "2 theplas + ½ cup curd",
  "1 bowl + 2 chapatis" : "1 bowl + 2 chapatis",
  "1 bowl + 1 naan" : "1 bowl + 1 naan",
  "2 rotis + paneer" : "2 rotis + paneer",
  "1 bowl + 2 slices" : "1 bowl + 2 slices",
  "1 bowl + 2 appams" : "1 bowl + 2 appams",

  "3 pieces" : "3 pieces",
  "2 chillas + salad" : "2 chillas + salad",
  "Cal" : "Cal",
  "Cropper" : "Cropper",
  "Calorie Tracker" : "Calorie Tracker",
  "Add Calorie" : "Add Calorie",
  "Quantity" : "Quantity",
  "Ask With Open AI" : "Ask With Open AI",
  "This picture not available Calorie,Protein,Carbs and Fats," : "This picture not available Calorie,Protein,Carbs and Fats,",
  "Ask Botanist" : "Ask Botanist",
  "Write your message" : "Write your message",
  "Confirm Reset" : "Confirm Reset",
  "Are you sure you want to Reset Data?" : "Are you sure you want to Reset Data?",
  "Reset" : "Reset",
  "You have been Reset Account" : "You have been Reset Account",
  "Personal Details" : "Personal Details",
  "Goal Weight" : "Goal Weight",
  "cm" : "cm",
  "Date Of Birth" : "Date Of Birth",
  "Gender" : "Gender",
  "Male" : "Male",
  "Female" : "Female",
  "Choose your desired weight?" : "Choose your desired weight?",
  "Imperial" : "Imperial",
  "Metric" : "Metric",
  "Weight" : "Weight",
  "lb" : "lb",
  "ft" : "ft",
  "in" : "in",
  "Day" : "Day",
  'January' : 'January',
  'February' : 'February',
  'March' : 'March',
  'April' : 'April',
  'June' : 'June',
  'July' : 'July',
  'August' : 'August',
  'September' : 'September',
  'October' : 'October',
  'November' : 'November',
  'December' : 'December',
  "Update Your Gender" : "Update Your Gender",
  "Adjust Goals" : "Adjust Goals",
  "How many workout do you per week?" : "How many workout do you per week?",
  "This will used to calibrate your custom plan" : "This will used to calibrate your custom plan",
  "Workout Now and then" : "Workout Now and then",
  "A few workout per week" : "A few workout per week",
  "Dedicated athlete" : "Dedicated athlete",
  "What is your goal?" : "What is your goal?",
  "This helps is generate a plan for your calorie intake." : "This helps is generate a plan for your calorie intake.",
  "Gain Weight" : "Gain Weight",
  "Lose Weight" : "Lose Weight",
  "Update Calorie Goal" : "Update Calorie Goal",
  "Save" : "Save",
  "Calorie Goal" : "Calorie Goal",
  "Update Protein Goal" : "Update Protein Goal",
  "Protein goal" : "Protein goal",
  "Update Carb Goal" : "Update Carb Goal",
  "Carb goal" : "Carb goal",
  "Update Fat Goal" : "Update Fat Goal",
  "Auto Generate Goal" : "Auto Generate Goal",
  "Fruit Salad" : "Fruit Salad",
  "Roasted Chickpeas" : "Roasted Chickpeas",
  "Mixed Nuts" : "Mixed Nuts",
  "Yogurt with Honey" : "Yogurt with Honey",
  "Apple with Peanut Butter" : "Apple with Peanut Butter",
  "Protein Bar" : "Protein Bar",
  "Whole Wheat Crackers" : "Whole Wheat Crackers",
  "Granola Bar" : "Granola Bar",
  "Peanut Chikki" : "Peanut Chikki",
  "Bhel Puri" : "Bhel Puri",
  "Khakra" : "Khakra",
  "Masala Makhana" : "Masala Makhana",
  "Hummus with Veggies" : "Hummus with Veggies",
  "Paneer Cubes" : "Paneer Cubes",
  "Milkshake (Low Sugar)" : "Milkshake (Low Sugar)",
  "Dhokla" : "Dhokla",
  "Vegetable Soup" : "Vegetable Soup",
  "Idli with Chutney" : "Idli with Chutney",
  "Cheese Slice" : "Cheese Slice",
  "Chana Chaat" : "Chana Chaat",
  "Moong Dal Chilla" : "Moong Dal Chilla",
  "Rice Cake with Peanut Butter" : "Rice Cake with Peanut Butter",
  "Popcorn (Air-popped)" : "Popcorn (Air-popped)",
  "Avocado Toast" : "Avocado Toast",
  "Stuffed Dates" : "Stuffed Dates",
  "Oats Cookies" : "Oats Cookies",
  "Fruit Smoothie" : "Fruit Smoothie",
  "Carrot Sticks with Hummus" : "Carrot Sticks with Hummus",
  "Soy Nuts" : "Soy Nuts",
  "Trail Mix" : "Trail Mix",
  "Besan Ladoo" : "Besan Ladoo",
  "Upma (small portion)" : "Upma (small portion)",
  "Egg Roll (Mini)" : "Egg Roll (Mini)",
  "Rice Idli" : "Rice Idli",
  "Cucumber Sandwich" : "Cucumber Sandwich",
  "Fruit Chaat" : "Fruit Chaat",
  "Lassi (Sweet)" : "Lassi (Sweet)",
  "Cold Coffee (Low Sugar)" : "Cold Coffee (Low Sugar)",
  "Rava Dhokla" : "Rava Dhokla",
  "Vegetable Cutlet" : "Vegetable Cutlet",
  "Chikki with Jaggery" : "Chikki with Jaggery",
  "Milk (Low Fat)" : "Milk (Low Fat)",
  "Baked Samosa" : "Baked Samosa",
  "Vegetable Wrap" : "Vegetable Wrap",
  "Roasted Soybeans" : "Roasted Soybeans",
  "1/2 cup" : "1/2 cup",
  "1 handful" : "1 handful",
  "1 apple + 1 tbsp PB" : "1 apple + 1 tbsp PB",
  "1 bar" : "1 bar",
  "5 pieces" : "5 pieces",
  "½ cup hummus + veggies" : "½ cup hummus + veggies",
  "50g" : "50g",
  "1 idli + chutney" : "1 idli + chutney",
  "1 slice" : "1 slice",
  "1 chilla" : "1 chilla",
  "1 cake + 1 tbsp PB" : "1 cake + 1 tbsp PB",
  "2 cups" : "2 cups",
  "1 toast" : "1 toast",
  "3 dates" : "3 dates",
  "2 cookies" : "2 cookies",
  "½ cup" : "½ cup",
  "1 small bowl" : "1 small bowl",
  "1 roll" : "1 roll",
  "1 wrap" : "1 wrap",
  "Chapati with Sabzi" : "Chapati with Sabzi",
  "Grilled Fish" : "Grilled Fish",
  "Moong Dal Khichdi" : "Moong Dal Khichdi",
  "Paneer Bhurji with Roti" : "Paneer Bhurji with Roti",
  "Brown Rice with Veg Curry" : "Brown Rice with Veg Curry",
  "Quinoa with Stir Fry Veggies" : "Quinoa with Stir Fry Veggies",
  "Grilled Tofu with Salad" : "Grilled Tofu with Salad",
  "Vegetable Pulao" : "Vegetable Pulao",
  "Palak Paneer with Chapati" : "Palak Paneer with Chapati",
  "Mixed Vegetable Soup" : "Mixed Vegetable Soup",
  "Stuffed Paratha with Curd" : "Stuffed Paratha with Curd",
  "Oats Khichdi" : "Oats Khichdi",
  "Roti with Bhindi" : "Roti with Bhindi",
  "Dal Tadka with Jeera Rice" : "Dal Tadka with Jeera Rice",
  "Vegetable Handvo" : "Vegetable Handvo",
  "Kadhi with Bajra Roti" : "Kadhi with Bajra Roti",
  "Tofu Curry with Quinoa" : "Tofu Curry with Quinoa",
  "Bhakri with Thecha" : "Bhakri with Thecha",
  "Biryani (Veg)" : "Biryani (Veg)",
  "Rajma with Brown Rice" : "Rajma with Brown Rice",
  "Daliya (Broken Wheat Porridge)" : "Daliya (Broken Wheat Porridge)",
  "Pumpkin Sabzi with Chapati" : "Pumpkin Sabzi with Chapati",
  "Cauliflower Stir Fry" : "Cauliflower Stir Fry",
  "Boiled Egg Salad" : "Boiled Egg Salad",
  "Tomato Rasam with Rice" : "Tomato Rasam with Rice",
  "Sweet Potato with Curd" : "Sweet Potato with Curd",
  "Stuffed Capsicum" : "Stuffed Capsicum",
  "Paneer Tikka with Mint Chutney" : "Paneer Tikka with Mint Chutney",
  "Rice with Sambar" : "Rice with Sambar",
  "Vegetable Thepla with Dahi" : "Vegetable Thepla with Dahi",
  "Grilled Mushroom Skewers" : "Grilled Mushroom Skewers",
  "Beetroot Sabzi with Roti" : "Beetroot Sabzi with Roti",
  "Spinach Dal with Rice" : "Spinach Dal with Rice",
  "Lentil Soup with Toast" : "Lentil Soup with Toast",
  "Tinda Curry with Chapati" : "Tinda Curry with Chapati",
  "Egg Bhurji with Roti" : "Egg Bhurji with Roti",
  "Karela Sabzi with Roti" : "Karela Sabzi with Roti",
  "Zucchini Stir Fry" : "Zucchini Stir Fry",
  "Low Carb Paneer Bowl" : "Low Carb Paneer Bowl",
  "Stuffed Tomato" : "Stuffed Tomato",
  "Vegetable Rava Upma" : "Vegetable Rava Upma",
  "2 chapatis + sabzi" : "2 chapatis + sabzi",
  "1 fillet" : "1 fillet",
  "1 bowl + 1 roti" : "1 bowl + 1 roti",
  "1 plate" : "1 plate",
  "1 cup rice + dal" : "1 cup rice + dal",
  "1 paratha + ½ cup curd" : "1 paratha + ½ cup curd",
  "2 rotis + bhindi" : "2 rotis + bhindi",
  "1 roti + 1 bowl kadhi" : "1 roti + 1 bowl kadhi",
  "1 bhakri + chutney" : "1 bhakri + chutney",
  "1 bowl curry + 1 roti" : "1 bowl curry + 1 roti",
  "2 chillas" : "2 chillas",
  "1 bowl + ½ cup curd" : "1 bowl + ½ cup curd",
  "1 serving" : "1 serving",
  "1 cup rice + sambar" : "1 cup rice + sambar",
  "1 thepla + curd" : "1 thepla + curd",
  "1 skewer" : "1 skewer",
  "1 bowl + 1 toast" : "1 bowl + 1 toast",
  "1 bowl + 1 appam" : "1 bowl + 1 appam",
  "1 tomato" : "1 tomato",
  "Restore" : "Restore",
  "Get Premium" : "Get Premium",
  "Get All The New Exciting Features" : "Get All The New Exciting Features",
  "Unlock Food Scanner" : "Unlock Food Scanner",
  "Unlock Food Calorie" : "Unlock Food Calorie",
  "Unlock Unlimited Chat with Ai" : "Unlock Unlimited Chat with Ai",
  "Unlimited Food Scanner To Calorie" : "Unlimited Food Scanner To Calorie",
  "Most Popular" : "Most Popular",
  "Subscription" : "Subscription",
  "BUY NOW" : "BUY NOW",
  "Terms of Condition" : "Terms of Condition",
  "Welcome" : "Welcome",
  "Calorie tracking made easy" : "Calorie tracking made easy",
  "Just snap a quick photo of your meal and we''ll do the rest" : "Just snap a quick photo of your meal and we''ll do the rest",
  "In-depth nutrition analyses" : "In-depth nutrition analyses",
  "We will keep your informed about your food choicer and their nutritional content" : "We will keep your informed about your food choicer and their nutritional content",
  "Transform your body" : "Transform your body",
  "Today is best time to start working toward your dream body" : "Today is best time to start working toward your dream body",
  "Where were you born?" : "Where were you born?",
  "This Will be used to calibrate your custom plan" : "This Will be used to calibrate your custom plan",
 "What's stopping you from reaching your goals?" : "What's stopping you from reaching your goals?",
  "Lack of consistency" : "Lack of consistency",
  "Unhealthy eating habits" : "Unhealthy eating habits",
  "Lack of supports" : "Lack of supports",
  "Busy schedule" : "Busy schedule",
  "Lack of meal inspiration" : "Lack of meal inspiration",
  "We're setting" : "We're setting",
  "everything up for you" : "everything up for you",
  "Customizing health plan...." : "Customizing health plan....",

  // Scan result description
  "meal_description": "This meal contains {cal} kcal, {protein}g protein, {carbs}g carbs, and {fat}g fat.",

  // Units and labels
  "kcal_unit": "kcal",
  "gram_unit": "g",
  "meal_label": "Meal",


};
