const Map<String, String> french = {
  "Home": "Accueil",
  "Calorie": "Calorie",
  "Analytics": "Analytique",
  "Setting": "Paramètres",
  "Track Food": "Suivi alimentaire",
  "Consumed": "Consommé",
  "Remaining": "Restant",
  "Protein": "Protéines",
  "Carbs": "Glucides",
  "Fats": "Lipides",
  "History": "Historique",
  "View All": "Voir tout",
  "BreakFast": "Petit-déjeuner",
  "Lunch": "Déjeuner",
  "snack(s)": "Collation",
  "Dinner": "Dîner",
  "Which meal would you like to track?": "Quel repas souhaitez-vous suivre ?",
  "Snap Tips": "Conseils photo",
  "Too close": "Trop près",
  "Too far": "Trop loin",
  "Multi-species": "Multi-espèces",
  "Continue": "Continuer",
  "OverView": "Vue d'ensemble",
  "Weight Goal": "Objectif de poids",
  "Update": "Mettre à jour",
  "Current Weight": "Poids actuel",
  "kg": "kg",
  "Try to update once a week so we can adjust your plan to ensure you hit your goal": "Essayez de mettre à jour une fois par semaine pour que nous puissions ajuster votre plan et atteindre votre objectif",
  "Update Weight": "Mettre à jour le poids",
  "Week": "Semaine",
  "Month": "Mois",
  "Year": "Année",
  "Update Weight Goal": "Mettre à jour l'objectif de poids",
  "Enter new weight (kg)": "Entrez le nouveau poids (kg)",
  "Cancel": "Annuler",
  "Calorie Your Week :": "Calories de votre semaine :",
  "Sun": "Dim",
  "Mon": "Lun",
  "Tue": "Mar",
  "Wed": "Mer",
  "Thu": "Jeu",
  "Fri": "Ven",
  "Sat": "Sam",
  "Average Calorie Month :": "Moyenne mensuelle de calories :",
  "Average Calorie Yearly :": "Moyenne annuelle de calories :",
  "Jan": "Janv",
  "Feb": "Févr",
  "Mar": "Mars",
  "Apr": "Avr",
  "May": "Mai",
  "Jun": "Juin",
  "Jul": "Juil",
  "Aug": "Août",
  "Sep": "Sept",
  "Oct": "Oct",
  "Nov": "Nov",
  "Dec": "Déc",
  "Age": "Âge",
  "Height": "Taille",
  "Customization": "Personnalisation",
  "Dark Mode": "Mode sombre",
  "Language": "Langue",
  "Personal details": "Détails personnels",
  "Adjust goals": "Ajuster les objectifs",
  "Calories,carbs,fat and protein": "Calories, glucides, lipides et protéines",
  "Chat history": "Historique de chat",
  "The coach does not memorize chat history. Each interaction is independent.": "Le coach ne mémorise pas l'historique des discussions. Chaque interaction est indépendante.",
  "Legal": "Mentions légales",
  "Terms and Condition": "Conditions générales",
  "Privacy Policy": "Politique de confidentialité",
  "Reset Data?": "Réinitialiser le compte ?",
  "VERSION": "VERSION",
  "History not found": "Historique introuvable",
  "Delete Item": "Supprimer l'élément",
  "Are you sure you want to delete this item?": "Êtes-vous sûr de vouloir supprimer cet élément ?",
  "Delete": "Supprimer",
  "Search by Food Name/Dish": "Rechercher par nom de plat/aliment",
  "Calorie Goal Reached": "Objectif calorique atteint",
  "You've completed your calorie goal for today. Would you like to add more?": "Vous avez atteint votre objectif calorique pour aujourd'hui. Souhaitez-vous en ajouter davantage ?",
  "Done": "Terminé",
  "Add More Calories": "Ajouter plus de calories",
  "Boiled Egg": "Œuf dur",
  "Oatmeal": "Flocons d'avoine",
  "Banana": "Banane",
  "Paratha": "Paratha",
  "Idli": "Idli",
  "Dosa": "Dosa",
  "Upma": "Upma",
  "Poha": "Poha",
  "Bread Butter": "Pain et beurre",
  "Cornflakes with Milk": "Cornflakes avec lait",
  "Chilla (Besan)": "Chilla (pois chiches)",
  "Sprouts Salad": "Salade de germes",
  "Pancakes": "Crêpes",
  "Apple": "Pomme",
  "Milk": "Lait",
  "Almonds": "Amandes",
  "Smoothie (Fruit)": "Smoothie (fruit)",
  "Yogurt (Plain)": "Yaourt nature",
  "Khichdi": "Khichdi",
  "Thepla": "Thepla (crêpe indienne épicée)",
  "Cheela (Moong dal)": "Cheela (galette de lentilles jaunes)",
  "Pav Bhaji": "Pav Bhaji (curry de légumes avec pain)",
  "Sabudana Khichdi": "Sabudana Khichdi (plat au tapioca)",
  "Roti with Sabzi": "Roti avec légumes",
  "Peanut Butter Bread": "Pain au beurre de cacahuète",
  "Fruit Bowl": "Bol de fruits",
  "Vegetable Sandwich": "Sandwich aux légumes",
  "Rice Idli with Sambar": "Idli de riz avec sambar",
  "Boiled Corn": "Maïs bouilli",
  "Paneer Bhurji": "Paneer Bhurji (fromage émietté aux épices)",
  "Protein Shake": "Shake protéiné",
  "Muesli with Milk": "Muesli avec lait",
  "Chapati with Curd": "Chapati avec yaourt",
  "Porridge (Daliya)": "Bouillie (blé concassé)",
  "Rava Upma": "Rava Upma (plat salé à la semoule)",
  "Chickpea Salad": "Salade de pois chiches",
  "Boiled Sweet Potato": "Patate douce bouillie",
  "Coconut Water": "Eau de coco",
  "Masala Omelette": "Omelette masala",
  "Vegetable Poha": "Poha aux légumes (riz aplati)",
  "1 egg": "1 œuf",
  "1 bowl": "1 bol",
  "1 medium": "1 moyen",
  "1 piece": "1 pièce",
  "1 cup": "1 tasse",
  "2 slices": "2 tranches",
  "2 small pieces": "2 petits morceaux",
  "10 pieces": "10 morceaux",
  "1 glass": "1 verre",
  "2 pavs + bhaji": "2 pains + bhaji",
  "1 roti + sabzi": "1 roti + légumes",
  "1 sandwich": "1 sandwich",
  "2 idlis + sambar'": "2 idlis + sambar",
  "1 chapati + ½ cup curd": "1 chapati + ½ tasse de yaourt",
  "Rice with Dal": "Riz avec lentilles",
  "Grilled Chicken": "Poulet grillé",
  "Paneer Curry": "Curry de paneer",
  "Mixed Vegetable Curry": "Curry de légumes mixtes",
  "Chapati with Daal": "Chapati avec daal",
  "Fish Curry with Rice": "Curry de poisson avec riz",
  "Rajma Chawal": "Rajma Chawal (haricots rouges avec riz)",
  "Chole Bhature": "Chole Bhature (pois chiches avec pain frit)",
  "Kadhi with Rice": "Kadhi avec riz (sauce au yaourt)",
  "Palak Paneer": "Palak Paneer (épinards avec paneer)",
  "Stuffed Paratha": "Paratha farci",
  "Veg Pulao": "Pulao aux légumes",
  "Biryani with Raita": "Biryani avec raita",
  "Tofu Stir Fry": "Tofu sauté",
  "Chicken Tikka": "Poulet Tikka",
  "Veg Fried Rice": "Riz sauté aux légumes",
  "Aloo Gobi with Roti": "Aloo Gobi avec roti",
  "Baingan Bharta": "Baingan Bharta (aubergine rôtie)",
  "Sambar with Rice": "Sambar avec riz",
  "Chicken Curry with Roti": "Curry de poulet avec roti",
  "Bhindi Masala with Roti": "Okra masala avec roti",
  "Egg Curry with Rice": "Curry d'œuf avec riz",
  "Lentil Soup with Bread": "Soupe de lentilles avec pain",
  "Methi Thepla with Curd": "Methi Thepla avec yaourt",
  "Soybean Curry with Rice": "Curry de soja avec riz",
  "Cabbage Sabzi with Chapati": "Chou sauté avec chapati",
  "Dal Makhani with Naan": "Dal Makhani avec naan",
  "Vegetable Korma with Roti": "Korma de légumes avec roti",
  "Tandoori Roti with Paneer": "Roti tandoori avec paneer",
  "Mixed Dal with Rice": "Mélange de lentilles avec riz",
  "Bottle Gourd Curry with Roti": "Curry de calebasse avec roti",
  "Kofta Curry with Roti": "Curry de kofta avec roti",
  "Paneer Bhurji with Bread": "Paneer Bhurji avec pain",
  "Chana Masala with Rice": "Chana Masala avec riz",
  "Curd Rice": "Riz au yaourt",
  "Tomato Rice": "Riz à la tomate",
  "Vegetable Stew with Appam": "Ragoût de légumes avec appam",
  "Dhokla with Green Chutney": "Dhokla avec chutney vert",
  "Besan Chilla with Salad": "Galette de pois chiches avec salade",
  "Lauki Chana Dal": "Courge bouteille avec lentilles",
  "Spinach Corn Curry": "Curry d'épinards et maïs",
  "Tinda Masala with Roti": "Tinda masala avec roti",
  "Masoor Dal with Rice": "Lentilles corail avec riz",
  "Vegetable Handi with Naan": "Handi de légumes avec naan",
  "Egg Bhurji with Chapati": "Œufs brouillés masala avec chapati",
  "Pumpkin Curry with Rice": "Curry de potiron avec riz",
  "2 rotis + sabzi": "2 rotis + légumes",
  "1 cup rice + 1 cup dal": "1 tasse de riz + 1 tasse de lentilles",
  "1 breast": "1 poitrine de poulet",
  "2 chapatis + dal'": "2 chapatis + daal",
  "1 bowl curry + 1 cup rice": "1 bol de curry + 1 tasse de riz",
  "1 bhatura + chole": "1 bhatura + chole",
  "1 paratha": "1 paratha",
  "1 bowl + 2 rotis": "1 bol + 2 rotis",
  "1 cup + 1 bowl": "1 tasse + 1 bol",
  "1 bowl + 1 cup rice": "1 bol + 1 tasse de riz",
  "1 bowl + 1 bread slice": "1 bol + 1 tranche de pain",
  "2 theplas + ½ cup curd": "2 theplas + ½ tasse de yaourt",
  "1 bowl + 2 chapatis": "1 bol + 2 chapatis",
  "1 bowl + 1 naan": "1 bol + 1 naan",
  "2 rotis + paneer": "2 rotis + paneer",
  "1 bowl + 2 slices": "1 bol + 2 tranches",
  "1 bowl + 2 appams": "1 bol + 2 appams",


  "3 pieces": "3 pièces",
  "2 chillas + salad": "2 chillas + salade",
  "Cal": "Cal",
  "Cropper": "Cropper",
  "Calorie Tracker": "Suivi des calories",
  "Add Calorie": "Ajouter des calories",
  "Quantity": "Quantité",
  "Ask The Coach": "Demandez au Coach",
  "This picture not available Calorie,Protein,Carbs and Fats,": "Cette image n'est pas disponible pour les calories, protéines, glucides et graisses.",
  "Ask Coach": "Demandez au Coach",
  "Write your message": "Écrivez votre message",
  "Confirm Reset": "Confirmer la réinitialisation",
  "Are you sure you want to Reset Data?": "Êtes-vous sûr de vouloir réinitialiser le compte ?",
  "Reset": "Réinitialiser",
  "You have been Reset Account": "Votre compte a été réinitialisé",
  "Personal Details": "Détails personnels",
  "Goal Weight": "Poids objectif",
  "cm": "cm",
  "Date Of Birth": "Date de naissance",
  "Gender": "Genre",
  "Male": "Homme",
  "Female": "Femme",
  "Choose your desired weight?": "Choisissez votre poids désiré ?",
  "Imperial": "Impérial",
  "Metric": "Métrique",
  "Weight": "Poids",
  "lb": "lb",
  "ft": "ft",
  "in": "in",
  "Day": "Jour",
  "January": "Janvier",
  "February": "Février",
  "March": "Mars",
  "April": "Avril",
  "June": "Juin",
  "July": "Juillet",
  "August": "Août",
  "September": "Septembre",
  "October": "Octobre",
  "November": "Novembre",
  "December": "Décembre",
  "Update Your Gender": "Mettre à jour votre genre",
  "Adjust Goals": "Ajuster les objectifs",
  "How many workout do you per week?": "Combien de séances d'entraînement par semaine ?",
  "This will used to calibrate your custom plan": "Cela sera utilisé pour calibrer votre plan personnalisé",
  "Choose your height and weight": "Choisissez votre taille et votre poids",
  "Select your height and weight to calibrate your custom plan": "Sélectionnez votre taille et votre poids pour calibrer votre plan personnalisé",
  "Workout Now and then": "S'entraîner de temps en temps",
  "A few workout per week": "Quelques entraînements par semaine",
  "Dedicated athlete": "Athlète dédié",
  "What is your goal?": "Quel est votre objectif ?",
  "This helps is generate a plan for your calorie intake.": "Cela aide à générer un plan pour votre apport calorique.",
  "Gain Weight": "Prendre du poids",
  "Lose Weight": "Perdre du poids",
  "Update Calorie Goal": "Mettre à jour l'objectif calorique",
  "Save": "Sauvegarder",
  "Calorie Goal": "Objectif calorique",
  "Update Protein Goal": "Mettre à jour l'objectif en protéines",
  "Protein goal": "Objectif en protéines",
  "Update Carb Goal": "Mettre à jour l'objectif en glucides",
  "Carb goal": "Objectif en glucides",
  "Update Fat Goal": "Mettre à jour l'objectif en graisses",
  "Auto Generate Goal": "Générer automatiquement l'objectif",
  "Fruit Salad": "Salade de fruits",
  "Roasted Chickpeas": "Pois chiches grillés",
  "Mixed Nuts": "Noix mélangées",
  "Yogurt with Honey": "Yaourt avec du miel",
  "Apple with Peanut Butter": "Pomme avec beurre de cacahuète",
  "Protein Bar": "Barre protéinée",
  "Whole Wheat Crackers": "Craquelins de blé entier",
  "Granola Bar": "Barre granola",
  "Peanut Chikki": "Chikki aux arachides",
  "Bhel Puri": "Bhel Puri",
  "Khakra": "Khakra",
  "Masala Makhana": "Masala Makhana",
  "Hummus with Veggies": "Houmous avec des légumes",
  "Paneer Cubes": "Cubes de paneer",
  "Milkshake (Low Sugar)": "Milkshake (peu sucré)",
  "Dhokla": "Dhokla",
  "Vegetable Soup": "Soupe aux légumes",
  "Idli with Chutney": "Idli avec chutney",
  "Cheese Slice": "Tranche de fromage",
  "Chana Chaat": "Chana Chaat",
  "Moong Dal Chilla": "Moong Dal Chilla",
  "Rice Cake with Peanut Butter": "Galette de riz avec du beurre de cacahuète",
  "Popcorn (Air-popped)": "Pop-corn (air soufflé)",
  "Avocado Toast": "Toast à l'avocat",
  "Stuffed Dates": "Dattes farcies",
  "Oats Cookies": "Biscuits à l'avoine",
  "Fruit Smoothie": "Smoothie aux fruits",
  "Carrot Sticks with Hummus": "Bâtonnets de carottes avec houmous",
  "Soy Nuts": "Noix de soja",
  "Trail Mix": "Mélange de fruits secs",
  "Besan Ladoo": "Besan Ladoo",
  "Upma (small portion)": "Upma (petite portion)",
  "Egg Roll (Mini)": "Rouleau d'œuf (mini)",
  "Rice Idli": "Idli de riz",
  "Cucumber Sandwich": "Sandwich au concombre",
  "Fruit Chaat": "Fruit Chaat",
  "Lassi (Sweet)": "Lassi (sucré)",
  "Cold Coffee (Low Sugar)": "Café froid (peu sucré)",
  "Rava Dhokla": "Rava Dhokla",
  "Vegetable Cutlet": "Croquette de légumes",
  "Chikki with Jaggery": "Chikki avec jaggery",
  "Milk (Low Fat)": "Lait (faible en matières grasses)",
  "Baked Samosa": "Samosa cuit",
  "Vegetable Wrap": "Wrap aux légumes",
  "Roasted Soybeans": "Soja rôti",
  "1/2 cup": "1/2 tasse",
  "1 handful": "1 poignée",
  "1 apple + 1 tbsp PB": "1 pomme + 1 cuil. à soupe de beurre de cacahuète",
  "1 bar": "1 barre",
  "5 pieces": "5 pièces",
  "½ cup hummus + veggies": "½ tasse de houmous + légumes",
  "50g": "50g",
  "1 idli + chutney": "1 idli + chutney",
  "1 slice": "1 tranche",
  "1 chilla": "1 chilla",
  "1 cake + 1 tbsp PB": "1 gâteau + 1 cuil. à soupe de beurre de cacahuète",
  "2 cups": "2 tasses",
  "1 toast": "1 toast",
  "3 dates": "3 dattes",
  "2 cookies": "2 biscuits",
  "½ cup": "½ tasse",
  "1 small bowl": "1 petit bol",
  "1 roll": "1 rouleau",
  "1 wrap": "1 wrap",
  "Chapati with Sabzi": "Chapati avec Sabzi",
  "Grilled Fish": "Poisson grillé",
  "Moong Dal Khichdi": "Moong Dal Khichdi",
  "Paneer Bhurji with Roti": "Paneer Bhurji avec Roti",
  "Brown Rice with Veg Curry": "Riz brun avec curry de légumes",
  "Quinoa with Stir Fry Veggies": "Quinoa avec légumes sautés",
  "Grilled Tofu with Salad": "Tofu grillé avec salade",
  "Vegetable Pulao": "Pulao aux légumes",
  "Palak Paneer with Chapati": "Palak Paneer avec Chapati",
  "Mixed Vegetable Soup": "Soupe de légumes mélangés",
  "Stuffed Paratha with Curd": "Paratha farci avec du yaourt",
  "Oats Khichdi": "Khichdi à l'avoine",
  "Roti with Bhindi": "Roti avec Bhindi",
  "Dal Tadka with Jeera Rice": "Dal Tadka avec riz Jeera",
  "Vegetable Handvo": "Handvo aux légumes",
  "Kadhi with Bajra Roti": "Kadhi avec Bajra Roti",
  "Tofu Curry with Quinoa": "Curry de tofu avec quinoa",
  "Bhakri with Thecha": "Bhakri avec Thecha",
  "Biryani (Veg)": "Biryani (Végétarien)",
  "Rajma with Brown Rice": "Rajma avec riz brun",
  "Daliya (Broken Wheat Porridge)": "Daliya (Bouillie de blé cassé)",
  "Pumpkin Sabzi with Chapati": "Sabzi de citrouille avec Chapati",
  "Cauliflower Stir Fry": "Sauté de chou-fleur",
  "Boiled Egg Salad": "Salade d'œufs durs",
  "Tomato Rasam with Rice": "Rasam à la tomate avec riz",
  "Sweet Potato with Curd": "Patate douce avec yaourt",
  "Stuffed Capsicum": "Poivron farci",
  "Paneer Tikka with Mint Chutney": "Paneer Tikka avec chutney à la menthe",
  "Rice with Sambar": "Riz avec sambar",
  "Vegetable Thepla with Dahi": "Thepla aux légumes avec yaourt",
  "Grilled Mushroom Skewers": "Brochettes de champignons grillés",
  "Beetroot Sabzi with Roti": "Sabzi de betterave avec roti",
  "Spinach Dal with Rice": "Dal aux épinards avec riz",
  "Lentil Soup with Toast": "Soupe de lentilles avec toast",
  "Tinda Curry with Chapati": "Curry de Tinda avec chapati",
  "Egg Bhurji with Roti": "Œufs bhurji avec roti",
  "Karela Sabzi with Roti": "Sabzi de karela avec roti",
  "Zucchini Stir Fry": "Poêlée de courgettes",
  "Low Carb Paneer Bowl": "Bol de paneer faible en glucides",
  "Stuffed Tomato": "Tomate farcie",
  "Vegetable Rava Upma": "Upma de semoule aux légumes",
  "2 chapatis + sabzi": "2 chapatis + sabzi",
  "1 fillet": "1 filet",
  "1 bowl + 1 roti": "1 bol + 1 roti",
  "1 plate": "1 assiette",
  "1 cup rice + dal": "1 tasse de riz + dal",
  "1 paratha + ½ cup curd": "1 paratha + ½ tasse de yaourt",
  "2 rotis + bhindi": "2 rotis + bhindi",
  "1 roti + 1 bowl kadhi": "1 roti + 1 bol de kadhi",
  "1 bhakri + chutney": "1 bhakri + chutney",
  "1 bowl curry + 1 roti": "1 bol de curry + 1 roti",
  "2 chillas": "2 chillas",
  "1 bowl + ½ cup curd": "1 bol + ½ tasse de yaourt",
  "1 serving": "1 portion",
  "1 cup rice + sambar": "1 tasse de riz + sambar",
  "1 thepla + curd": "1 thepla + yaourt",
  "1 skewer": "1 brochette",
  "1 bowl + 1 toast": "1 bol + 1 toast",
  "1 bowl + 1 appam": "1 bol + 1 appam",
  "1 tomato": "1 tomate",
  "Restore": "Restaurer",
  "Get Premium": "Obtenez Premium",
  "Get All The New Exciting Features": "Obtenez toutes les nouvelles fonctionnalités passionnantes",
  "Unlock Food Scanner": "Déverrouiller le scanner alimentaire",
  "Unlock Food Calorie": "Déverrouiller les calories alimentaires",
  "Unlock Unlimited Chat with Ai": "Déverrouiller la discussion illimitée avec l'IA",
  "Unlimited Food Scanner To Calorie": "Scanner alimentaire illimité vers les calories",
  "Most Popular": "Les plus populaires",
  "Subscription": "Abonnement",
  "BUY NOW": "ACHETEZ MAINTENANT",
  "Terms of Condition": "Conditions d'utilisation",
  "Welcome": "Bienvenue",
  "Calorie tracking made easy": "Suivi des calories simplifié",
  "Just snap a quick photo of your meal and we''ll do the rest": "Prenez une photo rapide de votre repas et nous ferons le reste",
  "In-depth nutrition analyses": "Analyses nutritionnelles approfondies",
  "We will keep your informed about your food choicer and their nutritional content": "Nous vous tiendrons informé de vos choix alimentaires et de leur contenu nutritionnel",
  "Transform your body": "Transformez votre corps",
  "Today is best time to start working toward your dream body": "Aujourd'hui est le meilleur moment pour commencer à travailler pour atteindre votre corps de rêve",
  "Where were you born?": "Où êtes-vous né ?",
  "This Will be used to calibrate your custom plan": "Cela sera utilisé pour calibrer votre plan personnalisé",
  "What's stopping you from reaching your goals?": "Qu'est-ce qui vous empêche d'atteindre vos objectifs ?",
  "Lack of consistency": "Manque de cohérence",
  "Unhealthy eating habits": "Habitudes alimentaires malsaines",
  "Lack of supports": "Manque de soutien",
  "Busy schedule": "Emploi du temps chargé",
  "Lack of meal inspiration": "Manque d'inspiration pour les repas",
  "We're setting": "Nous préparons",
  "everything up for you": "tout pour vous",
  "Customizing health plan....": "Personnalisation du plan de santé....",
  // Dynamic meal description components
  "meal_contains": "Ce repas contient",
  "conjunction_and": "et",
  
  // Units and labels
  "kcal_unit": "kcal",
  "gram_unit": "g",
  "protein_unit": "g",
  "carbs_unit": "g",
  "fat_unit": "g", 
  "meal_label": "Repas"
  ,
  // Abbreviations for compact badges
  "cals": "cals",
  "prot": "prot",
  "carbs": "gluc",
  "fats": "lip",
  // Permission UI
  "grant_camera_access_in_scanner": "Appuyez sur le cadre pour autoriser l'accès à la caméra",
  "camera_permission_denied_title": "Permission de la caméra requise",
  "camera_permission_denied_message": "L'accès à la caméra a été refusé. Veuillez activer la permission de la caméra dans les paramètres de votre appareil pour utiliser le scanner.",
  "ok": "OK",
  
  // Premium paywall (modern)
  'premium_badge': 'PREMIUM',
  'go_premium_title': 'Passez en Premium',
  'go_premium_subtitle': 'L’expérience complète du meilleur programme diététique',
  'feature_ai_scan_title': 'Gérez votre poids et mangez mieux',
  'feature_ai_scan_subtitle': 'avec le Scan de repas IA, retours quotidiens',
  'feature_results_title': 'Obtenez des résultats durables',
  'feature_results_subtitle': 'avec Autopilot et le suivi des macros',
    'feature_chatbot_title': 'Chatbot IA "Coach"',
  'feature_chatbot_subtitle': 'Guidance nutritionnelle instantanée',
  'feature_recipes_title': 'Des recettes et régimes premium',
  'feature_recipes_subtitle': 'vous guideront vers la réussite',
  'best_value': 'MEILLEUR CHOIX',
  'save_percent': 'ÉCONOMISEZ {percent}%*',
  'months_12': '12 mois',
  'month_1': '1 mois',
  'billed_annually': 'Facturé annuellement',
  'billed_monthly': 'Facturé mensuellement',
  'per_month': 'Par mois',
  'continue_cta': 'Continuer',
  'compared_to_monthly': '*Comparé aux paiements mensuels',
  'currency_dzd': 'DZD',

  // Weight tracking UI
  "Target Weight": "Poids cible",
  "to go": "à atteindre",
  "Try to update once a week to help us adjust your plan": "Essayez de mettre à jour une fois par semaine pour nous aider à ajuster votre plan",
  "Weight Overview": "Aperçu du poids",
  "Current": "Actuel",
  "Goal": "Objectif",
  "invalid_number": "Veuillez entrer un nombre entier valide",
  "weight_out_of_range": "Veuillez entrer un poids entre 20 et 300 kg",
  
  // Celebration strip messages
  "goal_achieved_message": "Objectif atteint ! Continuez à briller.",
  "on_a_roll_message": "Super lancée — chaque pas compte !",
  "keep_momentum_message": "Des progrès réalisés — gardez l'élan !",
  
  // Notifications
  "update_targets_title": "Cibles mises à jour",
  "update_targets_body": "Nous avons recalculé vos objectifs quotidiens de calories et de macronutriments en fonction de votre nouveau poids.",

  // Donut chart center texts
  "daily_macros": "Macros quotidiennes",
  "daily_macros_reached": "Macros quotidiennes atteintes 🎉",

  // Recipes Section
  "recipes_title": "Recettes",
  "top_recipes": "Meilleures recettes",
  "all_recipes": "Toutes les recettes", 
  "top_recipes_subtitle": "Découvrez des recettes saines et délicieuses conçues pour vos objectifs",
  "no_recipes_available": "Aucune recette disponible",
  "min": "min",
  "cal": "Cal",
  "close": "Fermer",
};
