const Map<String, String> german ={
  "Home": "Startseite",
  "Calorie": "Kalorien",
  "Analytics": "Analyse",
  "Setting": "Einstellungen",
  "Track Food": "Essen verfolgen",
  "Consumed": "Verbraucht",
  "Remaining": "Verbleibend",
  "Protein": "Eiweiß",
  "Carbs": "Kohlenhydrate",
  "Fats": "Fette",
  "History": "Verlauf",
  "View All": "Alle anzeigen",
  "BreakFast": "Frühstück",
  "Lunch": "Mittagessen",
  "snack(s)": "Snack",
  "Dinner": "Abendessen",
  "Which meal would you like to track?": "Welche Mahlzeit möchtest du verfolgen?",
  "Snap Tips": "Foto-Tipps",
  "Too close": "Zu nah",
  "Too far": "Zu weit",
  "Multi-species": "Mehrere Arten",
  "Continue": "Weiter",
  "OverView": "Übersicht",
  "Weight Goal": "Gewichtsziel",
  "Update": "Aktualisieren",
  "Current Weight": "Aktuelles Gewicht",
  "kg": "kg",
  "Try to update once a week so we can adjust your plan to ensure you hit your goal": "Versuche, einmal pro Woche zu aktualisieren, damit wir deinen Plan anpassen können",
  "Update Weight": "Gewicht aktualisieren",
  "Week": "Woche",
  "Month": "Monat",
  "Year": "Jahr",
  "Update Weight Goal": "Gewichtsziel aktualisieren",
  "Enter new weight (kg)": "Neues Gewicht eingeben (kg)",
  "Cancel": "Abbrechen",
  "Calorie Your Week :": "Kalorien in deiner Woche:",
  "Sun": "So",
  "Mon": "Mo",
  "Tue": "Di",
  "Wed": "Mi",
  "Thu": "Do",
  "Fri": "Fr",
  "Sat": "Sa",
  "Average Calorie Month :": "Durchschnittliche Kalorien pro Monat:",
  "Average Calorie Yearly :": "Durchschnittliche Kalorien pro Jahr:",
  "Jan": "Jan",
  "Feb": "Feb",
  "Mar": "Mär",
  "Apr": "Apr",
  "May": "Mai",
  "Jun": "Jun",
  "Jul": "Jul",
  "Aug": "Aug",
  "Sep": "Sep",
  "Oct": "Okt",
  "Nov": "Nov",
  "Dec": "Dez",
  "Age": "Alter",
  "Height": "Größe",
  "Customization": "Anpassung",
  "Dark Mode": "Dunkelmodus",
  "Language": "Sprache",
  "Personal details": "Persönliche Daten",
  "Adjust goals": "Ziele anpassen",
  "Calories,carbs,fat and protein": "Kalorien, Kohlenhydrate, Fette und Eiweiß",
  "Chat history": "Chatverlauf",
  "Legal": "Rechtliches",
  "Terms and Condition": "Allgemeine Geschäftsbedingungen",
  "Privacy Policy": "Datenschutzrichtlinie",
  "Reset Data?": "Konto zurücksetzen?",
  "VERSION": "VERSION",
  "History not found": "Verlauf nicht gefunden",
  "Delete Item": "Element löschen",
  "Are you sure you want to delete this item?": "Bist du sicher, dass du dieses Element löschen möchtest?",
  "Delete": "Löschen",
  "Search by Food Name/Dish": "Nach Speise oder Gericht suchen",
  "🎯 Calorie Goal Reached": "🎯 Kalorienziel erreicht",
  "You've completed your calorie goal for today. Would you like to add more?": "Du hast dein Kalorienziel für heute erreicht. Möchtest du mehr hinzufügen?",
  "Done": "Fertig",
  "Add More Calories": "Weitere Kalorien hinzufügen",
  "Boiled Egg": "Gekochtes Ei",
  "Oatmeal": "Haferbrei",
  "Banana": "Banane",
  "Paratha": "Paratha",
  "Idli": "Idli",
  "Dosa": "Dosa",
  "Upma": "Upma",
  "Poha": "Poha",
  "Bread Butter": "Brot mit Butter",
  "Cornflakes with Milk": "Cornflakes mit Milch",
  "Chilla (Besan)": "Chilla (Kichererbsenmehl)",
  "Sprouts Salad": "Sprossensalat",
  "Pancakes": "Pfannkuchen",
  "Apple": "Apfel",
  "Milk": "Milch",
  "Almonds": "Mandeln",
  "Smoothie (Fruit)": "Smoothie (Frucht)",
  "Yogurt (Plain)": "Joghurt (Natur)",
  "Khichdi": "Khichdi",
  "Thepla": "Thepla (gewürztes Fladenbrot)",
  "Cheela (Moong dal)": "Cheela (Pfannkuchen aus Mungobohnen)",
  "Pav Bhaji": "Pav Bhaji (Gemüsecurry mit Brötchen)",
  "Sabudana Khichdi": "Sabudana Khichdi (Tapiokagericht)",
  "Roti with Sabzi": "Roti mit Gemüse",
  "Peanut Butter Bread": "Erdnussbutterbrot",
  "Fruit Bowl": "Obstschale",
  "Vegetable Sandwich": "Gemüsesandwich",
  "Rice Idli with Sambar": "Reis-Idli mit Sambar",
  "Boiled Corn": "Gekochter Mais",
  "Paneer Bhurji": "Paneer Bhurji (zerbröselter Frischkäse mit Gewürzen)",
  "Protein Shake": "Proteinshake",
  "Muesli with Milk": "Müsli mit Milch",
  "Chapati with Curd": "Chapati mit Joghurt",
  "Porridge (Daliya)": "Porridge (Weizengrütze)",
  "Rava Upma": "Rava Upma (Grießgericht)",
  "Chickpea Salad": "Kichererbsensalat",
  "Boiled Sweet Potato": "Gekochte Süßkartoffel",
  "Coconut Water": "Kokoswasser",
  "Masala Omelette": "Masala-Omelett",
  "Vegetable Poha": "Gemüse-Poha (Flachreisgericht)",
  "1 egg": "1 Ei",
  "1 bowl": "1 Schüssel",
  "1 medium": "1 mittelgroß",
  "1 piece": "1 Stück",
  "1 cup": "1 Tasse",
  "2 slices": "2 Scheiben",
  "2 small pieces": "2 kleine Stücke",
  "10 pieces": "10 Stücke",
  "1 glass": "1 Glas",
  "2 pavs + bhaji": "2 Brötchen + Bhaji",
  "1 roti + sabzi": "1 Roti + Gemüse",
  "1 sandwich": "1 Sandwich",
  "2 idlis + sambar'": "2 Idlis + Sambar",
  "1 chapati + ½ cup curd": "1 Chapati + ½ Tasse Joghurt",
  "Rice with Dal": "Reis mit Linsen",
  "Grilled Chicken": "Gegrilltes Hähnchen",
  "Paneer Curry": "Paneer-Curry",
  "Mixed Vegetable Curry": "Gemüsecurry",
  "Chapati with Daal": "Chapati mit Daal",
  "Fish Curry with Rice": "Fischcurry mit Reis",
  "Rajma Chawal": "Rajma Chawal (rote Bohnen mit Reis)",
  "Chole Bhature": "Chole Bhature (Kichererbsen mit frittiertem Brot)",
  "Kadhi with Rice": "Kadhi mit Reis (Joghurtsoße)",
  "Palak Paneer": "Palak Paneer (Spinat mit Frischkäse)",
  "Stuffed Paratha": "Gefülltes Paratha",
  "Veg Pulao": "Gemüse-Pulao",
  "Biryani with Raita": "Biryani mit Raita",
  "Tofu Stir Fry": "Tofu-Pfannengericht",
  "Chicken Tikka": "Chicken Tikka",
  "Veg Fried Rice": "Gebratener Reis mit Gemüse",
  "Aloo Gobi with Roti": "Aloo Gobi mit Roti",
  "Baingan Bharta": "Baingan Bharta (geröstete Aubergine)",
  "Sambar with Rice": "Sambar mit Reis",
  "Chicken Curry with Roti": "Hähnchencurry mit Roti",
  "Bhindi Masala with Roti": "Okraschoten-Masala mit Roti",
  "Egg Curry with Rice": "Eiercurry mit Reis",
  "Lentil Soup with Bread": "Linsensuppe mit Brot",
  "Methi Thepla with Curd": "Methi Thepla mit Joghurt",
  "Soybean Curry with Rice": "Sojabohnen-Curry mit Reis",
  "Cabbage Sabzi with Chapati": "Kohl-Gemüse mit Chapati",
  "Dal Makhani with Naan": "Dal Makhani mit Naan",
  "Vegetable Korma with Roti": "Gemüse-Korma mit Roti",
  "Tandoori Roti with Paneer": "Tandoori Roti mit Paneer",
  "Mixed Dal with Rice": "Gemischte Linsen mit Reis",
  "Bottle Gourd Curry with Roti": "Flaschenkürbis-Curry mit Roti",
  "Kofta Curry with Roti": "Kofta-Curry mit Roti",
  "Paneer Bhurji with Bread": "Paneer Bhurji mit Brot",
  "Chana Masala with Rice": "Chana Masala mit Reis",
  "Curd Rice": "Joghurtreis",
  "Tomato Rice": "Tomatenreis",
  "Vegetable Stew with Appam": "Gemüseeintopf mit Appam",
  "Dhokla with Green Chutney": "Dhokla mit grünem Chutney",
  "Besan Chilla with Salad": "Kichererbsenpfannkuchen mit Salat",
  "Lauki Chana Dal": "Flaschenkürbis mit Kichererbsen-Linsen",
  "Spinach Corn Curry": "Spinat-Mais-Curry",
  "Tinda Masala with Roti": "Tinda Masala mit Roti",
  "Masoor Dal with Rice": "Rote Linsen mit Reis",
  "Vegetable Handi with Naan": "Gemüse-Handi mit Naan",
  "Egg Bhurji with Chapati": "Eier-Bhurji mit Chapati",
  "Pumpkin Curry with Rice": "Kürbiscurry mit Reis",
  "2 rotis + sabzi": "2 Rotis + Gemüse",
  "1 cup rice + 1 cup dal": "1 Tasse Reis + 1 Tasse Linsen",
  "1 breast": "1 Hähnchenbrust",
  "2 chapatis + dal'": "2 Chapatis + Daal",
  "1 bowl curry + 1 cup rice": "1 Schüssel Curry + 1 Tasse Reis",
  "1 bhatura + chole": "1 Bhatura + Chole",
  "1 paratha": "1 Paratha",
  "1 bowl + 2 rotis": "1 Schüssel + 2 Rotis",
  "1 cup + 1 bowl": "1 Tasse + 1 Schüssel",
  "1 bowl + 1 cup rice": "1 Schüssel + 1 Tasse Reis",
  "1 bowl + 1 bread slice": "1 Schüssel + 1 Brotscheibe",
  "2 theplas + ½ cup curd": "2 Theplas + ½ Tasse Joghurt",
  "1 bowl + 2 chapatis": "1 Schüssel + 2 Chapatis",
  "1 bowl + 1 naan": "1 Schüssel + 1 Naan",
  "2 rotis + paneer": "2 Rotis + Paneer",
  "1 bowl + 2 slices": "1 Schüssel + 2 Scheiben",
  "1 bowl + 2 appams": "1 Schüssel + 2 Appams",


  "3 pieces": "3 Stücke",
  "2 chillas + salad": "2 Chillas + Salat",
  "Cal": "Cal",
  "Cropper": "Cropper",
  "Calorie Tracker": "Kalorien Tracker",
  "Add Calorie": "Kalorie hinzufügen",
  "Quantity": "Menge",
  "Ask With Open AI": "Fragen Sie mit Open AI",
  "This picture not available Calorie,Protein,Carbs and Fats,": "Dieses Bild ist nicht verfügbar für Kalorien, Protein, Kohlenhydrate und Fette.",
  "Ask Botanist": "Fragen Sie den Botaniker",
  "Write your message": "Schreiben Sie Ihre Nachricht",
  "Confirm Reset": "Zurücksetzen bestätigen",
  "Are you sure you want to Reset Data?": "Möchten Sie Ihr Konto wirklich zurücksetzen?",
  "Reset": "Zurücksetzen",
  "You have been Reset Account": "Ihr Konto wurde zurückgesetzt",
  "Personal Details": "Persönliche Details",
  "Goal Weight": "Zielgewicht",
  "cm": "cm",
  "Date Of Birth": "Geburtsdatum",
  "Gender": "Geschlecht",
  "Male": "Männlich",
  "Female": "Weiblich",
  "Choose your desired weight?": "Wählen Sie Ihr gewünschtes Gewicht?",
  "Imperial": "Imperial",
  "Metric": "Metrisch",
  "Weight": "Gewicht",
  "lb": "lb",
  "ft": "ft",
  "in": "in",
  "Day": "Tag",
  "January": "Januar",
  "February": "Februar",
  "March": "März",
  "April": "April",
  "June": "Juni",
  "July": "Juli",
  "August": "August",
  "September": "September",
  "October": "Oktober",
  "November": "November",
  "December": "Dezember",
  "Update Your Gender": "Aktualisieren Sie Ihr Geschlecht",
  "Other": "Andere",
  "Adjust Goals": "Ziele anpassen",
  "How many workout do you per week?": "Wie viele Workouts machen Sie pro Woche?",
  "This will used to calibrate your custom plan": "Dies wird verwendet, um Ihren individuellen Plan zu kalibrieren",
  "Workout Now and then": "Ab und zu trainieren",
  "A few workout per week": "Ein paar Workouts pro Woche",
  "Dedicated athlete": "Engagierter Athlet",
  "What is your goal?": "Was ist Ihr Ziel?",
  "This helps is generate a plan for your calorie intake.": "Dies hilft, einen Plan für Ihre Kalorienaufnahme zu erstellen.",
  "Gain Weight": "Gewicht zunehmen",
  "Lose Weight": "Gewicht verlieren",
  "Update Calorie Goal": "Kalorienziel aktualisieren",
  "Save": "Speichern",
  "Calorie Goal": "Kalorienziel",
  "Update Protein Goal": "Protein-Ziel aktualisieren",
  "Protein goal": "Protein-Ziel",
  "Update Carb Goal": "Kohlenhydrat-Ziel aktualisieren",
  "Carb goal": "Kohlenhydrat-Ziel",
  "Update Fat Goal": "Fett-Ziel aktualisieren",
  "Auto Generate Goal": "Ziel automatisch generieren",
  "Fruit Salad": "Fruchtsalat",
  "Roasted Chickpeas": "Geröstete Kichererbsen",
  "Mixed Nuts": "Gemischte Nüsse",
  "Yogurt with Honey": "Joghurt mit Honig",
  "Apple with Peanut Butter": "Apfel mit Erdnussbutter",
  "Protein Bar": "Proteinriegel",
  "Whole Wheat Crackers": "Vollkorn-Cracker",
  "Granola Bar": "Granola-Riegel",
  "Peanut Chikki": "Erdnuss-Chikki",
  "Bhel Puri": "Bhel Puri",
  "Khakra": "Khakra",
  "Masala Makhana": "Masala Makhana",
  "Hummus with Veggies": "Hummus mit Gemüse",
  "Paneer Cubes": "Paneer-Würfel",
  "Milkshake (Low Sugar)": "Milkshake (wenig Zucker)",
  "Dhokla": "Dhokla",
  "Vegetable Soup": "Gemüsesuppe",
  "Idli with Chutney": "Idli mit Chutney",
  "Cheese Slice": "Käsescheibe",
  "Chana Chaat": "Chana Chaat",
  "Moong Dal Chilla": "Moong Dal Chilla",
  "Rice Cake with Peanut Butter": "Reiskuchen mit Erdnussbutter",
  "Popcorn (Air-popped)": "Popcorn (Luftgepoppt)",
  "Avocado Toast": "Avocado-Toast",
  "Stuffed Dates": "Gefüllte Datteln",
  "Oats Cookies": "Haferkekse",
  "Fruit Smoothie": "Frucht-Smoothie",
  "Carrot Sticks with Hummus": "Karottensticks mit Hummus",
  "Soy Nuts": "Soja-Nüsse",
  "Trail Mix": "Müsliriegel-Mix",
  "Besan Ladoo": "Besan Ladoo",
  "Upma (small portion)": "Upma (kleine Portion)",
  "Egg Roll (Mini)": "Eierrolle (Mini)",
  "Rice Idli": "Reis-Idli",
  "Cucumber Sandwich": "Gurkensandwich",
  "Fruit Chaat": "Frucht Chaat",
  "Lassi (Sweet)": "Lassi (süß)",
  "Cold Coffee (Low Sugar)": "Eiskaffee (wenig Zucker)",
  "Rava Dhokla": "Rava Dhokla",
  "Vegetable Cutlet": "Gemüse-Kotelett",
  "Chikki with Jaggery": "Chikki mit Jaggery",
  "Milk (Low Fat)": "Milch (fettarm)",
  "Baked Samosa": "Gebackene Samosa",
  "Vegetable Wrap": "Gemüse Wrap",
  "Roasted Soybeans": "Geröstete Sojabohnen",
  "1/2 cup": "1/2 Tasse",
  "1 handful": "1 Handvoll",
  "1 apple + 1 tbsp PB": "1 Apfel + 1 EL PB",
  "1 bar": "1 Riegel",
  "5 pieces": "5 Stücke",
  "½ cup hummus + veggies": "½ Tasse Hummus + Gemüse",
  "50g": "50g",
  "1 idli + chutney": "1 Idli + Chutney",
  "1 slice": "1 Scheibe",
  "1 chilla": "1 Chilla",
  "1 cake + 1 tbsp PB": "1 Kuchen + 1 EL PB",
  "2 cups": "2 Tassen",
  "1 toast": "1 Toast",
  "3 dates": "3 Datteln",
  "2 cookies": "2 Kekse",
  "½ cup": "½ Tasse",
  "1 small bowl": "1 kleiner Teller",
  "1 roll": "1 Rolle",
  "1 wrap": "1 Wrap",
  "Chapati with Sabzi": "Chapati mit Sabzi",
  "Grilled Fish": "Gegrillter Fisch",
  "Moong Dal Khichdi": "Moong Dal Khichdi",
  "Paneer Bhurji with Roti": "Paneer Bhurji mit Roti",
  "Brown Rice with Veg Curry": "Brauner Reis mit Gemüse-Curry",
  "Quinoa with Stir Fry Veggies": "Quinoa mit Gemüse aus der Pfanne",
  "Grilled Tofu with Salad": "Gegrillter Tofu mit Salat",
  "Vegetable Pulao": "Gemüse Pulao",
  "Palak Paneer with Chapati": "Palak Paneer mit Chapati",
  "Mixed Vegetable Soup": "Gemüsesuppe gemischt",
  "Stuffed Paratha with Curd": "Gefülltes Paratha mit Joghurt",
  "Oats Khichdi": "Hafer-Khichdi",
  "Roti with Bhindi": "Roti mit Bhindi",
  "Dal Tadka with Jeera Rice": "Dal Tadka mit Jeera-Reis",
  "Vegetable Handvo": "Gemüse Handvo",
  "Kadhi with Bajra Roti": "Kadhi mit Bajra Roti",
  "Tofu Curry with Quinoa": "Tofu-Curry mit Quinoa",
  "Bhakri with Thecha": "Bhakri mit Thecha",
  "Biryani (Veg)": "Biryani (Vegan)",
  "Rajma with Brown Rice": "Rajma mit braunem Reis",
  "Daliya (Broken Wheat Porridge)": "Daliya (Brechweizenbrei)",
  "Pumpkin Sabzi with Chapati": "Kürbis Sabzi mit Chapati",
  "Cauliflower Stir Fry": "Blumenkohl aus der Pfanne",
  "Boiled Egg Salad": "Kochsalat",
  "Tomato Rasam with Rice": "Tomaten Rasam mit Reis",
  "Sweet Potato with Curd": "Süßkartoffel mit Joghurt",
  "Stuffed Capsicum": "Gefüllte Paprika",
  "Paneer Tikka with Mint Chutney": "Paneer Tikka mit Minz-Chutney",
  "Rice with Sambar": "Reis mit Sambar",
  "Vegetable Thepla with Dahi": "Gemüse Thepla mit Joghurt",
  "Grilled Mushroom Skewers": "Gegrillte Pilzspieße",
  "Beetroot Sabzi with Roti": "Rote Bete Sabzi mit Roti",
  "Spinach Dal with Rice": "Spinat Dal mit Reis",
  "Lentil Soup with Toast": "Linsensuppe mit Toast",
  "Tinda Curry with Chapati": "Tinda Curry mit Chapati",
  "Egg Bhurji with Roti": "Eier Bhurji mit Roti",
  "Karela Sabzi with Roti": "Karela Sabzi mit Roti",
  "Zucchini Stir Fry": "Zucchini Stir-Fry",
  "Low Carb Paneer Bowl": "Low Carb Paneer Schale",
  "Stuffed Tomato": "Gefüllte Tomate",
  "Vegetable Rava Upma": "Gemüse Rava Upma",
  "2 chapatis + sabzi": "2 Chapatis + Sabzi",
  "1 fillet": "1 Filet",
  "1 bowl + 1 roti": "1 Schale + 1 Roti",
  "1 plate": "1 Teller",
  "1 cup rice + dal": "1 Tasse Reis + Dal",
  "1 paratha + ½ cup curd": "1 Paratha + ½ Tasse Joghurt",
  "2 rotis + bhindi": "2 Rotis + Bhindi",
  "1 roti + 1 bowl kadhi": "1 Roti + 1 Schale Kadhi",
  "1 bhakri + chutney": "1 Bhakri + Chutney",
  "1 bowl curry + 1 roti": "1 Schale Curry + 1 Roti",
  "2 chillas": "2 Chillas",
  "1 bowl + ½ cup curd": "1 Schale + ½ Tasse Joghurt",
  "1 serving": "1 Portion",
  "1 cup rice + sambar": "1 Tasse Reis + Sambar",
  "1 thepla + curd": "1 Thepla + Joghurt",
  "1 skewer": "1 Spieß",
  "1 bowl + 1 toast": "1 Schale + 1 Toast",
  "1 bowl + 1 appam": "1 Schale + 1 Appam",
  "1 tomato": "1 Tomate",
  "Restore": "Wiederherstellen",
  "Get Premium": "Premium holen",
  "Get All The New Exciting Features": "Alle neuen aufregenden Funktionen holen",
  "Unlock Food Scanner": "Lebensmittelscanner freischalten",
  "Unlock Food Calorie": "Lebensmittelkalorien freischalten",
  "Unlock Unlimited Chat with Ai": "Unbegrenzten Chat mit KI freischalten",
  "Unlimited Food Scanner To Calorie": "Unbegrenzter Lebensmittelscanner zu Kalorien",
  "Most Popular": "Am beliebtesten",
  "Subscription": "Abonnement",
  "BUY NOW": "JETZT KAUFEN",
  "Terms of Condition": "Nutzungsbedingungen",
  "Welcome": "Willkommen",
  "Calorie tracking made easy": "Kalorienverfolgung leicht gemacht",
  "Just snap a quick photo of your meal and we''ll do the rest": "Machen Sie einfach ein schnelles Foto von Ihrer Mahlzeit und wir erledigen den Rest",
  "In-depth nutrition analyses": "Detaillierte Ernährungsanalyse",
  "We will keep your informed about your food choicer and their nutritional content": "Wir halten Sie über Ihre Lebensmittelwahl und deren Nährstoffgehalt auf dem Laufenden",
  "Transform your body": "Verwandle deinen Körper",
  "Today is best time to start working toward your dream body": "Heute ist der beste Zeitpunkt, um an deinem Traumkörper zu arbeiten",
  "Where were you born?": "Wo bist du geboren?",
  "This Will be used to calibrate your custom plan": "Dies wird verwendet, um deinen individuellen Plan zu kalibrieren",
  "What's stopping you from reaching your goals?": "Was hindert dich daran, deine Ziele zu erreichen?",
  "Lack of consistency": "Mangel an Konsequenz",
  "Unhealthy eating habits": "Ungesunde Essgewohnheiten",
  "Lack of supports": "Mangel an Unterstützung",
  "Busy schedule": "Voller Zeitplan",
  "Lack of meal inspiration": "Mangel an Mahlzeiteninspiration",
  "We're setting": "Wir richten ein",
  "everything up for you": "alles für dich ein",
  "Customizing health plan....": "Gesundheitsplan wird angepasst...."

};
