const Map<String, String> hindi = {
  "Home": "होम",
  "Calorie": "कैलोरी",
  "Analytics": "विश्लेषण",
  "Setting": "सेटिंग",
  "Track Food": "भोजन ट्रैक करें",
  "Consumed": "खपत",
  "Remaining": "शेष",
  "Protein": "प्रोटीन",
  "Carbs": "कार्ब्स",
  "Fats": "वसा",
  "History": "इतिहास",
  "View All": "सभी देखें",
  "BreakFast": "नाश्ता",
  "Lunch": "दोपहर का खाना",
  "snack(s)": "स्नैक",
  "Dinner": "रात का खाना",
  "Which meal would you like to track?": "आप कौन सा भोजन ट्रैक करना चाहेंगे?",
  "Snap Tips": "फोटो टिप्स",
  "Too close": "बहुत पास",
  "Too far": "बहुत दूर",
  "Multi-species": "अनेक प्रकार",
  "Continue": "जारी रखें",
  "OverView": "अवलोकन",
  "Weight Goal": "वज़न लक्ष्य",
  "Update": "अपडेट करें",
  "Current Weight": "वर्तमान वजन",
  "kg": "किलोग्राम",
  "Try to update once a week so we can adjust your plan to ensure you hit your goal": "सप्ताह में एक बार अपडेट करें ताकि हम आपकी योजना समायोजित कर सकें",
  "Update Weight": "वजन अपडेट करें",
  "Week": "सप्ताह",
  "Month": "महीना",
  "Year": "वर्ष",
  "Update Weight Goal": "वज़न लक्ष्य अपडेट करें",
  "Enter new weight (kg)": "नया वजन दर्ज करें (किलोग्राम)",
  "Cancel": "रद्द करें",
  "Calorie Your Week :": "आपका साप्ताहिक कैलोरी:",
  "Sun": "रवि",
  "Mon": "सोम",
  "Tue": "मंगल",
  "Wed": "बुध",
  "Thu": "गुरु",
  "Fri": "शुक्र",
  "Sat": "शनि",
  "Average Calorie Month :": "औसत मासिक कैलोरी:",
  "Average Calorie Yearly :": "औसत वार्षिक कैलोरी:",
  "Jan": "जनवरी",
  "Feb": "फरवरी",
  "Mar": "मार्च",
  "Apr": "अप्रैल",
  "May": "मई",
  "Jun": "जून",
  "Jul": "जुलाई",
  "Aug": "अगस्त",
  "Sep": "सितंबर",
  "Oct": "अक्टूबर",
  "Nov": "नवंबर",
  "Dec": "दिसंबर",
  "Age": "आयु",
  "Height": "ऊँचाई",
  "Customization": "अनुकूलन",
  "Dark Mode": "डार्क मोड",
  "Language": "भाषा",
  "Personal details": "व्यक्तिगत विवरण",
  "Adjust goals": "लक्ष्य समायोजित करें",
  "Calories,carbs,fat and protein": "कैलोरी, कार्ब्स, वसा और प्रोटीन",
  "Chat history": "चैट इतिहास",
  "Legal": "कानूनी",
  "Terms and Condition": "नियम और शर्तें",
  "Privacy Policy": "गोपनीयता नीति",
  "Reset Data?": "खाता रीसेट करें?",
  "VERSION": "संस्करण",
  "History not found": "इतिहास नहीं मिला",
  "Delete Item": "आइटम हटाएं",
  "Are you sure you want to delete this item?": "क्या आप वाकई इस आइटम को हटाना चाहते हैं?",
  "Delete": "हटाएं",
  "Search by Food Name/Dish": "भोजन/डिश के नाम से खोजें",
  "🎯 Calorie Goal Reached": "🎯 कैलोरी लक्ष्य पूरा हुआ",
  "You've completed your calorie goal for today. Would you like to add more?": "आपने आज का कैलोरी लक्ष्य पूरा कर लिया है। क्या आप और जोड़ना चाहेंगे?",
  "Done": "पूर्ण",
  "Add More Calories": "अधिक कैलोरी जोड़ें",
  "Boiled Egg": "उबला अंडा",
  "Oatmeal": "ओटमील",
  "Banana": "केला",
  "Paratha": "पराठा",
  "Idli": "इडली",
  "Dosa": "डोसा",
  "Upma": "उपमा",
  "Poha": "पोहा",
  "Bread Butter": "ब्रेड बटर",
  "Cornflakes with Milk": "कॉर्नफ्लेक्स विद मिल्क",
  "Chilla (Besan)": "चिल्ला (बेसन)",
  "Sprouts Salad": "अंकुरित सलाद",
  "Pancakes": "पैनकेक्स",
  "Apple": "सेब",
  "Milk": "दूध",
  "Almonds": "बादाम",
  "Smoothie (Fruit)": "स्मूदी (फल)",
  "Yogurt (Plain)": "दही (सादा)",
  "Khichdi": "खिचड़ी",
  "Thepla": "थेपला",
  "Cheela (Moong dal)": "चीला (मूंग दाल)",
  "Pav Bhaji": "पाव भाजी",
  "Sabudana Khichdi": "साबूदाना खिचड़ी",
  "Roti with Sabzi": "रोटी के साथ सब्ज़ी",
  "Peanut Butter Bread": "मूंगफली मक्खन ब्रेड",
  "Fruit Bowl": "फलों की कटोरी",
  "Vegetable Sandwich": "सब्ज़ी सैंडविच",
  "Rice Idli with Sambar": "चावल इडली सांभर के साथ",
  "Boiled Corn": "उबला हुआ मक्का",
  "Paneer Bhurji": "पनीर भुर्जी",
  "Protein Shake": "प्रोटीन शेक",
  "Muesli with Milk": "म्यूसली दूध के साथ",
  "Chapati with Curd": "चपाती दही के साथ",
  "Porridge (Daliya)": "दलिया",
  "Rava Upma": "रवा उपमा",
  "Chickpea Salad": "चना सलाद",
  "Boiled Sweet Potato": "उबली शकरकंद",
  "Coconut Water": "नारियल पानी",
  "Masala Omelette": "मसाला ऑमलेट",
  "Vegetable Poha": "सब्ज़ी पोहा",
  "1 egg": "1 अंडा",
  "1 bowl": "1 कटोरी",
  "1 medium": "1 मध्यम आकार",
  "1 piece": "1 टुकड़ा",
  "1 cup": "1 कप",
  "2 slices": "2 स्लाइस",
  "2 small pieces": "2 छोटे टुकड़े",
  "10 pieces": "10 टुकड़े",
  "1 glass": "1 गिलास",
  "2 pavs + bhaji": "2 पाव + भाजी",
  "1 roti + sabzi": "1 रोटी + सब्ज़ी",
  "1 sandwich": "1 सैंडविच",
  "2 idlis + sambar'": "2 इडली + सांभर",
  "1 chapati + ½ cup curd": "1 चपाती + ½ कप दही",
  "Rice with Dal": "चावल और दाल",
  "Grilled Chicken": "ग्रील्ड चिकन",
  "Paneer Curry": "पनीर करी",
  "Mixed Vegetable Curry": "मिक्स वेज करी",
  "Chapati with Daal": "चपाती के साथ दाल",
  "Fish Curry with Rice": "फिश करी चावल के साथ",
  "Rajma Chawal": "राजमा चावल",
  "Chole Bhature": "छोले भटूरे",
  "Kadhi with Rice": "कढ़ी चावल के साथ",
  "Palak Paneer": "पालक पनीर",
  "Stuffed Paratha": "भरवां पराठा",
  "Veg Pulao": "वेज पुलाव",
  "Biryani with Raita": "बिरयानी रायते के साथ",
  "Tofu Stir Fry": "टोफू स्टिर फ्राई",
  "Chicken Tikka": "चिकन टिक्का",
  "Veg Fried Rice": "वेज फ्राइड राइस",
  "Aloo Gobi with Roti": "आलू गोभी रोटी के साथ",
  "Baingan Bharta": "बैंगन का भरता",
  "Sambar with Rice": "सांभर चावल के साथ",
  "Chicken Curry with Roti": "चिकन करी रोटी के साथ",
  "Bhindi Masala with Roti": "भिंडी मसाला रोटी के साथ",
  "Egg Curry with Rice": "अंडा करी चावल के साथ",
  "Lentil Soup with Bread": "दाल का सूप ब्रेड के साथ",
  "Methi Thepla with Curd": "मेथी थेपला दही के साथ",
  "Soybean Curry with Rice": "सोयाबीन करी चावल के साथ",
  "Cabbage Sabzi with Chapati": "पत्ता गोभी की सब्ज़ी चपाती के साथ",
  "Dal Makhani with Naan": "दाल मखनी नान के साथ",
  "Vegetable Korma with Roti": "वेज कोरमा रोटी के साथ",
  "Tandoori Roti with Paneer": "तंदूरी रोटी पनीर के साथ",
  "Mixed Dal with Rice": "मिक्स दाल चावल के साथ",
  "Bottle Gourd Curry with Roti": "लौकी की सब्ज़ी रोटी के साथ",
  "Kofta Curry with Roti": "कोफ्ता करी रोटी के साथ",
  "Paneer Bhurji with Bread": "पनीर भुर्जी ब्रेड के साथ",
  "Chana Masala with Rice": "चना मसाला चावल के साथ",
  "Curd Rice": "दही चावल",
  "Tomato Rice": "टमाटर चावल",
  "Vegetable Stew with Appam": "सब्ज़ी स्टू अप्पम के साथ",
  "Dhokla with Green Chutney": "ढोकला हरी चटनी के साथ",
  "Besan Chilla with Salad": "बेसन चीला सलाद के साथ",
  "Lauki Chana Dal": "लौकी चना दाल",
  "Spinach Corn Curry": "पालक मक्का करी",
  "Tinda Masala with Roti": "टिंडा मसाला रोटी के साथ",
  "Masoor Dal with Rice": "मसूर दाल चावल के साथ",
  "Vegetable Handi with Naan": "वेजिटेबल हांडी नान के साथ",
  "Egg Bhurji with Chapati": "अंडा भुर्जी चपाती के साथ",
  "Pumpkin Curry with Rice": "कद्दू करी चावल के साथ",
  "2 rotis + sabzi": "2 रोटियां + सब्ज़ी",
  "1 cup rice + 1 cup dal": "1 कप चावल + 1 कप दाल",
  "1 breast": "1 ब्रेस्ट पीस",
  "2 chapatis + dal'": "2 चपातियां + दाल",
  "1 bowl curry + 1 cup rice": "1 कटोरी करी + 1 कप चावल",
  "1 bhatura + chole": "1 भटूरा + छोले",
  "1 paratha": "1 पराठा",
  "1 bowl + 2 rotis": "1 कटोरी + 2 रोटियां",
  "1 cup + 1 bowl": "1 कप + 1 कटोरी",
  "1 bowl + 1 cup rice": "1 कटोरी + 1 कप चावल",
  "1 bowl + 1 bread slice": "1 कटोरी + 1 ब्रेड स्लाइस",
  "2 theplas + ½ cup curd": "2 थेपले + ½ कप दही",
  "1 bowl + 2 chapatis": "1 कटोरी + 2 चपातियां",
  "1 bowl + 1 naan": "1 कटोरी + 1 नान",
  "2 rotis + paneer": "2 रोटियां + पनीर",
  "1 bowl + 2 slices": "1 कटोरी + 2 स्लाइस",
  "1 bowl + 2 appams": "1 कटोरी + 2 अप्पम",


  "3 pieces": "3 टुकड़े",
  "2 chillas + salad": "2 चिल्ला + सलाद",
  "Cal": "कल",
  "Cropper": "क्रॉपper",
  "Calorie Tracker": "कैलोरी ट्रैकर",
  "Add Calorie": "कैलोरी जोड़ें",
  "Quantity": "मात्रा",
  "Ask With Open AI": "Open AI से पूछें",
  "This picture not available Calorie,Protein,Carbs and Fats,": "यह चित्र कैलोरी, प्रोटीन, कार्ब्स और वसा के लिए उपलब्ध नहीं है।",
  "Ask Botanist": "बॉटनीस्ट से पूछें",
  "Write your message": "अपना संदेश लिखें",
  "Confirm Reset": "रीसेट कंफर्म करें",
  "Are you sure you want to Reset Data?": "क्या आप वाकई अपना खाता रीसेट करना चाहते हैं?",
  "Reset": "रीसेट",
  "You have been Reset Account": "आपका खाता रीसेट कर दिया गया है",
  "Personal Details": "व्यक्तिगत विवरण",
  "Goal Weight": "लक्ष्य वजन",
  "cm": "सेमी",
  "Date Of Birth": "जन्मतिथि",
  "Gender": "लिंग",
  "Male": "पुरुष",
  "Female": "महिला",
  "Choose your desired weight?": "अपना इच्छित वजन चुनें?",
  "Imperial": "इम्पीरियल",
  "Metric": "मीटरिक",
  "Weight": "वजन",
  "lb": "पाउंड",
  "ft": "फुट",
  "in": "इंच",
  "Day": "दिन",
  "January": "जनवरी",
  "February": "फरवरी",
  "March": "मार्च",
  "April": "अप्रैल",
  "June": "जून",
  "July": "जुलाई",
  "August": "अगस्त",
  "September": "सितंबर",
  "October": "अक्टूबर",
  "November": "नवंबर",
  "December": "दिसंबर",
  "Update Your Gender": "अपना लिंग अपडेट करें",
  "Other": "अन्य",
  "Adjust Goals": "लक्ष्य समायोजित करें",
  "How many workout do you per week?": "आप प्रति सप्ताह कितने वर्कआउट करते हैं?",
  "This will used to calibrate your custom plan": "यह आपके कस्टम प्लान को कैलिब्रेट करने के लिए उपयोग किया जाएगा",
  "Workout Now and then": "अब और फिर वर्कआउट करें",
  "A few workout per week": "प्रति सप्ताह कुछ वर्कआउट करें",
  "Dedicated athlete": "समर्पित एथलीट",
  "What is your goal?": "आपका लक्ष्य क्या है?",
  "This helps is generate a plan for your calorie intake.": "यह आपके कैलोरी सेवन के लिए एक योजना बनाने में मदद करता है।",
  "Gain Weight": "वजन बढ़ाना",
  "Lose Weight": "वजन घटाना",
  "Update Calorie Goal": "कैलोरी लक्ष्य अपडेट करें",
  "Save": "सहेजें",
  "Calorie Goal": "कैलोरी लक्ष्य",
  "Update Protein Goal": "प्रोटीन लक्ष्य अपडेट करें",
  "Protein goal": "प्रोटीन लक्ष्य",
  "Update Carb Goal": "कार्ब लक्ष्य अपडेट करें",
  "Carb goal": "कार्ब लक्ष्य",
  "Update Fat Goal": "वसा लक्ष्य अपडेट करें",
  "Auto Generate Goal": "स्वचालित लक्ष्य जनरेट करें",
  "Fruit Salad": "फ्रूट सलाद",
  "Roasted Chickpeas": "भुने हुए चने",
  "Mixed Nuts": "मिश्रित मेवे",
  "Yogurt with Honey": "दही और शहद",
  "Apple with Peanut Butter": "सेब और मूंगफली का बटर",
  "Protein Bar": "प्रोटीन बार",
  "Whole Wheat Crackers": "संपूर्ण गेहूं के क्रैकर",
  "Granola Bar": "ग्रेनोला बार",
  "Peanut Chikki": "मूंगफली की चिक्की",
  "Bhel Puri": "भेल पुरी",
  "Khakra": "खाखरा",
  "Masala Makhana": "मसाला मखाना",
  "Hummus with Veggies": "हम्मस और सब्जियां",
  "Paneer Cubes": "पनीर के टुकड़े",
  "Milkshake (Low Sugar)": "मिल्कशेक (कम शक्कर)",
  "Dhokla": "ढोकला",
  "Vegetable Soup": "सब्जी सूप",
  "Idli with Chutney": "इडली और चटनी",
  "Cheese Slice": "पनीर की स्लाइस",
  "Chana Chaat": "चना चाट",
  "Moong Dal Chilla": "मूंग दाल चिल्ला",
  "Rice Cake with Peanut Butter": "चावल केक और मूंगफली का बटर",
  "Popcorn (Air-popped)": "पॉपकॉर्न (एयर-पॉप्ड)",
  "Avocado Toast": "एवोकाडो टोस्ट",
  "Stuffed Dates": "भरवां खजूर",
  "Oats Cookies": "ओट्स कुकीज",
  "Fruit Smoothie": "फ्रूट स्मूदी",
  "Carrot Sticks with Hummus": "गाजर के स्टिक्स और हम्मस",
  "Soy Nuts": "सोया नट्स",
  "Trail Mix": "ट्रेल मिक्स",
  "Besan Ladoo": "बेसन लड्डू",
  "Upma (small portion)": "उपमा (छोटी मात्रा)",
  "Egg Roll (Mini)": "एग रोल (मिनी)",
  "Rice Idli": "चावल की इडली",
  "Cucumber Sandwich": "खीरे का सैंडविच",
  "Fruit Chaat": "फ्रूट चाट",
  "Lassi (Sweet)": "लस्सी (मीठी)",
  "Cold Coffee (Low Sugar)": "कोल्ड कॉफी (कम शक्कर)",
  "Rava Dhokla": "रावा ढोकला",
  "Vegetable Cutlet": "सब्जी कटलेट",
  "Chikki with Jaggery": "गुड़ की चिक्की",
  "Milk (Low Fat)": "दूध (कम वसा)",
  "Baked Samosa": "बेक्ड समोसा",
  "Vegetable Wrap": "सब्जी रैप",
  "Roasted Soybeans": "भुनी हुई सोयाबीन",
  "1/2 cup": "1/2 कप",
  "1 handful": "1 मुट्ठी",
  "1 apple + 1 tbsp PB": "1 सेब + 1 टेबल स्पून पीबी",
  "1 bar": "1 बार",
  "5 pieces": "5 टुकड़े",
  "½ cup hummus + veggies": "½ कप हम्मस + सब्जियां",
  "50g": "50 ग्राम",
  "1 idli + chutney": "1 इडली + चटनी",
  "1 slice": "1 स्लाइस",
  "1 chilla": "1 चिल्ला",
  "1 cake + 1 tbsp PB": "1 केक + 1 टेबल स्पून पीबी",
  "2 cups": "2 कप",
  "1 toast": "1 टोस्ट",
  "3 dates": "3 खजूर",
  "2 cookies": "2 कुकीज",
  "½ cup": "½ कप",
  "1 small bowl": "1 छोटा कटोरा",
  "1 roll": "1 रोल",
  "1 wrap": "1 रैप",
  "Chapati with Sabzi": "चपाती और सब्जी",
  "Grilled Fish": "ग्रिल्ड मछली",
  "Moong Dal Khichdi": "मूंग दाल खिचड़ी",
  "Paneer Bhurji with Roti": "पनीर भुर्जी और रोटी",
  "Brown Rice with Veg Curry": "ब्राउन राइस और वेज करी",
  "Quinoa with Stir Fry Veggies": "क्विनोआ और स्टिर फ्राई सब्जियां",
  "Grilled Tofu with Salad": "ग्रिल्ड टोफू और सलाद",
  "Vegetable Pulao": "वेज पुलाव",
  "Palak Paneer with Chapati": "पालक पनीर और चपाती",
  "Mixed Vegetable Soup": "मिक्स वेजिटेबल सूप",
  "Stuffed Paratha with Curd": "स्टफ्ड पराठा और दही",
  "Oats Khichdi": "ओट्स खिचड़ी",
  "Roti with Bhindi": "रोटी और भिंडी",
  "Dal Tadka with Jeera Rice": "दाल तड़का और जीरा राइस",
  "Vegetable Handvo": "वेजिटेबल हैंडवो",
  "Kadhi with Bajra Roti": "कढ़ी और बाजरा रोटी",
  "Tofu Curry with Quinoa": "टोफू करी और क्विनोआ",
  "Bhakri with Thecha": "भाकरी और थेचा",
  "Biryani (Veg)": "बिरयानी (वेज)",
  "Rajma with Brown Rice": "राजमा और ब्राउन राइस",
  "Daliya (Broken Wheat Porridge)": "दलिया (ब्रोकन व्हीट पोरीज़)",
  "Pumpkin Sabzi with Chapati": "कद्दू सब्जी और चपाती",
  "Cauliflower Stir Fry": "फूलगोभी स्टिर फ्राई",
  "Boiled Egg Salad": "उबला अंडा सलाद",
  "Tomato Rasam with Rice": "टमाटर रसम के साथ चावल",
  "Sweet Potato with Curd": "शकरकंद के साथ दही",
  "Stuffed Capsicum": "भरवां शिमला मिर्च",
  "Paneer Tikka with Mint Chutney": "पनीर टिक्का पुदीने की चटनी के साथ",
  "Rice with Sambar": "चावल के साथ सांबर",
  "Vegetable Thepla with Dahi": "सब्जी थेपला के साथ दही",
  "Grilled Mushroom Skewers": "ग्रिल्ड मशरूम स्क्यूअर्स",
  "Beetroot Sabzi with Roti": "चुकंदर सब्जी के साथ रोटी",
  "Spinach Dal with Rice": "पालक दाल के साथ चावल",
  "Lentil Soup with Toast": "दाल सूप के साथ टोस्ट",
  "Tinda Curry with Chapati": "टिंडा करी के साथ चपाती",
  "Egg Bhurji with Roti": "अंडा भुर्जी के साथ रोटी",
  "Karela Sabzi with Roti": "करेला सब्जी के साथ रोटी",
  "Zucchini Stir Fry": "ज़ुकीनी स्टिर फ्राई",
  "Low Carb Paneer Bowl": "लो कार्ब पनीर बाउल",
  "Stuffed Tomato": "भरवां टमाटर",
  "Vegetable Rava Upma": "सब्जी रवा उपमा",
  "2 chapatis + sabzi": "2 चपाती + सब्जी",
  "1 fillet": "1 फिलेट",
  "1 bowl + 1 roti": "1 कटोरी + 1 रोटी",
  "1 plate": "1 प्लेट",
  "1 cup rice + dal": "1 कप चावल + दाल",
  "1 paratha + ½ cup curd": "1 पराठा + ½ कप दही",
  "2 rotis + bhindi": "2 रोटियां + भिंडी",
  "1 roti + 1 bowl kadhi": "1 रोटी + 1 कटोरी कढ़ी",
  "1 bhakri + chutney": "1 भाकरी + चटनी",
  "1 bowl curry + 1 roti": "1 कटोरी करी + 1 रोटी",
  "2 chillas": "2 चिल्ला",
  "1 bowl + ½ cup curd": "1 कटोरी + ½ कप दही",
  "1 serving": "1 सर्विंग",
  "1 cup rice + sambar": "1 कप चावल + सांबर",
  "1 thepla + curd": "1 थेपला + दही",
  "1 skewer": "1 स्क्यूअर",
  "1 bowl + 1 toast": "1 कटोरी + 1 टोस्ट",
  "1 bowl + 1 appam": "1 कटोरी + 1 अप्पम",
  "1 tomato": "1 टमाटर",
  "Restore": "पुनर्स्थापित करें",
  "Get Premium": "प्रीमियम प्राप्त करें",
  "Get All The New Exciting Features": "सभी नई रोमांचक सुविधाएँ प्राप्त करें",
  "Unlock Food Scanner": "फूड स्कैनर अनलॉक करें",
  "Unlock Food Calorie": "फूड कैलोरी अनलॉक करें",
  "Unlock Unlimited Chat with Ai": "AI के साथ अनलिमिटेड चैट अनलॉक करें",
  "Unlimited Food Scanner To Calorie": "असीमित फूड स्कैनर से कैलोरी",
  "Most Popular": "सबसे लोकप्रिय",
  "Subscription": "सदस्यता",
  "BUY NOW": "अब खरीदें",
  "Terms of Condition": "नियम और शर्तें",
  "Welcome": "स्वागत है",
  "Calorie tracking made easy": "कैलोरी ट्रैकिंग को आसान बनाना",
  "Just snap a quick photo of your meal and we''ll do the rest": "अपने भोजन की एक त्वरित फोटो लें और हम बाकी का काम करेंगे",
  "In-depth nutrition analyses": "गहन पोषण विश्लेषण",
  "We will keep your informed about your food choicer and their nutritional content": "हम आपको आपके खाद्य चयन और उनके पोषण सामग्री के बारे में सूचित रखते हैं",
  "Transform your body": "अपने शरीर को बदलें",
  "Today is best time to start working toward your dream body": "आज अपने ड्रीम बॉडी की दिशा में काम करने का सबसे अच्छा समय है",
  "Where were you born?": "आप कहां पैदा हुए थे?",
  "This Will be used to calibrate your custom plan": "यह आपके कस्टम प्लान को कैलिब्रेट करने के लिए उपयोग किया जाएगा",
  "What's stopping you from reaching your goals?": "आपके लक्ष्यों को प्राप्त करने से क्या रोक रहा है?",
  "Lack of consistency": "संगति की कमी",
  "Unhealthy eating habits": "अस्वस्थ खाने की आदतें",
  "Lack of supports": "समर्थन की कमी",
  "Busy schedule": "व्यस्त कार्यक्रम",
  "Lack of meal inspiration": "भोजन प्रेरणा की कमी",
  "We're setting": "हम सेट कर रहे हैं",
  "everything up for you": "सब कुछ आपके लिए सेट कर रहे हैं",
  "Customizing health plan....": "स्वास्थ्य योजना कस्टमाइज़ की जा रही है...."
}
;
