const Map<String, String> indonesia = {
  "Home": "Beranda",
  "Calorie": "Kalori",
  "Analytics": "Analitik",
  "Setting": "Pengaturan",
  "Track Food": "Lacak Makanan",
  "Consumed": "Dikonsumsi",
  "Remaining": "Tersisa",
  "Protein": "Protein",
  "Carbs": "Karbohidrat",
  "Fats": "Lemak",
  "History": "Riwayat",
  "View All": "Lihat Semua",
  "BreakFast": "Sarapan",
  "Lunch": "Makan Siang",
  "snack(s)": "Camilan",
  "Dinner": "Makan Malam",
  "Which meal would you like to track?": "Makanan mana yang ingin Anda lacak?",
  "Snap Tips": "Tips Foto",
  "Too close": "Terlalu dekat",
  "Too far": "Terlalu jauh",
  "Multi-species": "Multi-spesies",
  "Continue": "Lanjutkan",
  "OverView": "Ikhtisar",
  "Weight Goal": "Target Berat Badan",
  "Update": "Perbarui",
  "Current Weight": "Berat Saat Ini",
  "kg": "kg",
  "Try to update once a week so we can adjust your plan to ensure you hit your goal": "Cobalah perbarui seminggu sekali agar kami dapat menyesuaikan rencana Anda",
  "Update Weight": "Perbarui Berat",
  "Week": "Minggu",
  "Month": "Bulan",
  "Year": "Tahun",
  "Update Weight Goal": "Perbarui Target Berat",
  "Enter new weight (kg)": "Masukkan berat baru (kg)",
  "Cancel": "Batal",
  "Calorie Your Week :": "Kalori Mingguan Anda:",
  "Sun": "Min",
  "Mon": "Sen",
  "Tue": "Sel",
  "Wed": "Rab",
  "Thu": "Kam",
  "Fri": "Jum",
  "Sat": "Sab",
  "Average Calorie Month :": "Rata-rata Kalori Bulanan:",
  "Average Calorie Yearly :": "Rata-rata Kalori Tahunan:",
  "Jan": "Jan",
  "Feb": "Feb",
  "Mar": "Mar",
  "Apr": "Apr",
  "May": "Mei",
  "Jun": "Jun",
  "Jul": "Jul",
  "Aug": "Agu",
  "Sep": "Sep",
  "Oct": "Okt",
  "Nov": "Nov",
  "Dec": "Des",
  "Age": "Usia",
  "Height": "Tinggi",
  "Customization": "Kustomisasi",
  "Dark Mode": "Mode Gelap",
  "Language": "Bahasa",
  "Personal details": "Detail Pribadi",
  "Adjust goals": "Sesuaikan Tujuan",
  "Calories,carbs,fat and protein": "Kalori, karbohidrat, lemak dan protein",
  "Chat history": "Riwayat Chat",
  "Legal": "Legal",
  "Terms and Condition": "Syarat dan Ketentuan",
  "Privacy Policy": "Kebijakan Privasi",
  "Reset Data?": "Atur Ulang Akun?",
  "VERSION": "VERSI",
  "History not found": "Riwayat tidak ditemukan",
  "Delete Item": "Hapus Item",
  "Are you sure you want to delete this item?": "Apakah Anda yakin ingin menghapus item ini?",
  "Delete": "Hapus",
  "Search by Food Name/Dish": "Cari berdasarkan Nama Makanan/Hidangan",
  "🎯 Calorie Goal Reached": "🎯 Tujuan Kalori Tercapai",
  "You've completed your calorie goal for today. Would you like to add more?": "Anda telah menyelesaikan tujuan kalori hari ini. Ingin menambahkan lagi?",
  "Done": "Selesai",
  "Add More Calories": "Tambahkan Kalori Lagi",
  "Boiled Egg": "Telur Rebus",
  "Oatmeal": "Oatmeal",
  "Banana": "Pisang",
  "Paratha": "Paratha",
  "Idli": "Idli",
  "Dosa": "Dosa",
  "Upma": "Upma",
  "Poha": "Poha",
  "Bread Butter": "Roti Mentega",
  "Cornflakes with Milk": "Cornflakes dengan Susu",
  "Chilla (Besan)": "Chilla (Tepung Buncis)",
  "Sprouts Salad": "Salad Tauge",
  "Pancakes": "Pancake",
  "Apple": "Apel",
  "Milk": "Susu",
  "Almonds": "Almond",
  "Smoothie (Fruit)": "Smoothie (Buah)",
  "Yogurt (Plain)": "Yogurt (Tawar)",
  "Khichdi": "Khichdi",
  "Thepla": "Thepla",
  "Cheela (Moong dal)": "Cheela (kacang hijau)",
  "Pav Bhaji": "Pav Bhaji",
  "Sabudana Khichdi": "Sabudana Khichdi",
  "Roti with Sabzi": "Roti dengan sayur",
  "Peanut Butter Bread": "Roti selai kacang",
  "Fruit Bowl": "Mangkok buah",
  "Vegetable Sandwich": "Sandwich sayur",
  "Rice Idli with Sambar": "Idli nasi dengan sambar",
  "Boiled Corn": "Jagung rebus",
  "Paneer Bhurji": "Orak-arik paneer",
  "Protein Shake": "Minuman protein",
  "Muesli with Milk": "Muesli dengan susu",
  "Chapati with Curd": "Chapati dengan yogurt",
  "Porridge (Daliya)": "Bubur gandum",
  "Rava Upma": "Rava upma",
  "Chickpea Salad": "Salad kacang arab",
  "Boiled Sweet Potato": "Ubi manis rebus",
  "Coconut Water": "Air kelapa",
  "Masala Omelette": "Omelet masala",
  "Vegetable Poha": "Poha sayur",
  "1 egg": "1 telur",
  "1 bowl": "1 mangkok",
  "1 medium": "1 ukuran sedang",
  "1 piece": "1 potong",
  "1 cup": "1 cangkir",
  "2 slices": "2 iris",
  "2 small pieces": "2 potong kecil",
  "10 pieces": "10 potong",
  "1 glass": "1 gelas",
  "2 pavs + bhaji": "2 roti pav + bhaji",
  "1 roti + sabzi": "1 roti + sayur",
  "1 sandwich": "1 sandwich",
  "2 idlis + sambar'": "2 idli + sambar",
  "1 chapati + ½ cup curd": "1 chapati + ½ cangkir yogurt",
  "Rice with Dal": "Nasi dengan dal",
  "Grilled Chicken": "Ayam panggang",
  "Paneer Curry": "Kari paneer",
  "Mixed Vegetable Curry": "Kari sayur campur",
  "Chapati with Daal": "Chapati dengan dal",
  "Fish Curry with Rice": "Kari ikan dengan nasi",
  "Rajma Chawal": "Rajma dengan nasi",
  "Chole Bhature": "Chole Bhature",
  "Kadhi with Rice": "Kadhi dengan nasi",
  "Palak Paneer": "Palak paneer",
  "Stuffed Paratha": "Paratha isi",
  "Veg Pulao": "Nasi pilaf sayur",
  "Biryani with Raita": "Biryani dengan raita",
  "Tofu Stir Fry": "Tumis tahu",
  "Chicken Tikka": "Chicken tikka",
  "Veg Fried Rice": "Nasi goreng sayur",
  "Aloo Gobi with Roti": "Aloo gobi dengan roti",
  "Baingan Bharta": "Terong panggang (Baingan Bharta)",
  "Sambar with Rice": "Sambar dengan nasi",
  "Chicken Curry with Roti": "Kari ayam dengan roti",
  "Bhindi Masala with Roti": "Okra masala dengan roti",
  "Egg Curry with Rice": "Kari telur dengan nasi",
  "Lentil Soup with Bread": "Sup kacang lentil dengan roti",
  "Methi Thepla with Curd": "Methi thepla dengan yogurt",
  "Soybean Curry with Rice": "Kari kedelai dengan nasi",
  "Cabbage Sabzi with Chapati": "Kubis tumis dengan chapati",
  "Dal Makhani with Naan": "Dal makhani dengan naan",
  "Vegetable Korma with Roti": "Korma sayur dengan roti",
  "Tandoori Roti with Paneer": "Roti tandoori dengan paneer",
  "Mixed Dal with Rice": "Campuran dal dengan nasi",
  "Bottle Gourd Curry with Roti": "Kari labu dengan roti",
  "Kofta Curry with Roti": "Kari kofta dengan roti",
  "Paneer Bhurji with Bread": "Orak-arik paneer dengan roti",
  "Chana Masala with Rice": "Chana masala dengan nasi",
  "Curd Rice": "Nasi yogurt",
  "Tomato Rice": "Nasi tomat",
  "Vegetable Stew with Appam": "Sup sayur dengan appam",
  "Dhokla with Green Chutney": "Dhokla dengan sambal hijau",
  "Besan Chilla with Salad": "Besan chilla dengan salad",
  "Lauki Chana Dal": "Labu dengan chana dal",
  "Spinach Corn Curry": "Kari bayam jagung",
  "Tinda Masala with Roti": "Tinda masala dengan roti",
  "Masoor Dal with Rice": "Masoor dal dengan nasi",
  "Vegetable Handi with Naan": "Sayur handi dengan naan",
  "Egg Bhurji with Chapati": "Orak-arik telur dengan chapati",
  "Pumpkin Curry with Rice": "Kari labu dengan nasi",
  "2 rotis + sabzi": "2 roti + sayur",
  "1 cup rice + 1 cup dal": "1 cangkir nasi + 1 cangkir dal",
  "1 breast": "1 dada ayam",
  "2 chapatis + dal'": "2 chapati + dal",
  "1 bowl curry + 1 cup rice": "1 mangkok kari + 1 cangkir nasi",
  "1 bhatura + chole": "1 bhatura + chole",
  "1 paratha": "1 paratha",
  "1 bowl + 2 rotis": "1 mangkok + 2 roti",
  "1 cup + 1 bowl": "1 cangkir + 1 mangkok",
  "1 bowl + 1 cup rice": "1 mangkok + 1 cangkir nasi",
  "1 bowl + 1 bread slice": "1 mangkok + 1 iris roti",
  "2 theplas + ½ cup curd": "2 thepla + ½ cangkir yogurt",
  "1 bowl + 2 chapatis": "1 mangkok + 2 chapati",
  "1 bowl + 1 naan": "1 mangkok + 1 naan",
  "2 rotis + paneer": "2 roti + paneer",
  "1 bowl + 2 slices": "1 mangkok + 2 iris",
  "1 bowl + 2 appams": "1 mangkok + 2 appam",


  "3 pieces": "3 potong",
  "2 chillas + salad": "2 chilla + salad",
  "Cal": "Kal",
  "Cropper": "Cropper",
  "Calorie Tracker": "Pelacak Kalori",
  "Add Calorie": "Tambah Kalori",
  "Quantity": "Kuantitas",
  "Ask With Open AI": "Tanya Dengan Open AI",
  "This picture not available Calorie,Protein,Carbs and Fats,": "Gambar ini tidak tersedia untuk Kalori, Protein, Karbohidrat, dan Lemak.",
  "Ask Botanist": "Tanya Botanist",
  "Write your message": "Tulis pesan Anda",
  "Confirm Reset": "Konfirmasi Reset",
  "Are you sure you want to Reset Data?": "Apakah Anda yakin ingin mereset akun?",
  "Reset": "Reset",
  "You have been Reset Account": "Akun Anda telah direset",
  "Personal Details": "Detail Pribadi",
  "Goal Weight": "Berat Tujuan",
  "cm": "cm",
  "Date Of Birth": "Tanggal Lahir",
  "Gender": "Jenis Kelamin",
  "Male": "Pria",
  "Female": "Wanita",
  "Choose your desired weight?": "Pilih berat badan yang Anda inginkan?",
  "Imperial": "Imperial",
  "Metric": "Metrik",
  "Weight": "Berat",
  "lb": "lb",
  "ft": "ft",
  "in": "in",
  "Day": "Hari",
  "January": "Januari",
  "February": "Februari",
  "March": "Maret",
  "April": "April",
  "June": "Juni",
  "July": "Juli",
  "August": "Agustus",
  "September": "September",
  "October": "Oktober",
  "November": "November",
  "December": "Desember",
  "Update Your Gender": "Perbarui Jenis Kelamin Anda",
  "Other": "Lainnya",
  "Adjust Goals": "Sesuaikan Tujuan",
  "How many workout do you per week?": "Berapa banyak latihan yang Anda lakukan per minggu?",
  "This will used to calibrate your custom plan": "Ini akan digunakan untuk mengkalibrasi rencana kustom Anda",
  "Workout Now and then": "Latihan sesekali",
  "A few workout per week": "Beberapa latihan per minggu",
  "Dedicated athlete": "Atlet yang berdedikasi",
  "What is your goal?": "Apa tujuan Anda?",
  "This helps is generate a plan for your calorie intake.": "Ini membantu untuk menghasilkan rencana untuk asupan kalori Anda.",
  "Gain Weight": "Menambah Berat Badan",
  "Lose Weight": "Menurunkan Berat Badan",
  "Update Calorie Goal": "Perbarui Tujuan Kalori",
  "Save": "Simpan",
  "Calorie Goal": "Tujuan Kalori",
  "Update Protein Goal": "Perbarui Tujuan Protein",
  "Protein goal": "Tujuan Protein",
  "Update Carb Goal": "Perbarui Tujuan Karbohidrat",
  "Carb goal": "Tujuan Karbohidrat",
  "Update Fat Goal": "Perbarui Tujuan Lemak",
  "Auto Generate Goal": "Hasilkan Tujuan Secara Otomatis",
  "Fruit Salad": "Salad Buah",
  "Roasted Chickpeas": "Kacang Arab Panggang",
  "Mixed Nuts": "Kacang Campur",
  "Yogurt with Honey": "Yogurt dengan Madu",
  "Apple with Peanut Butter": "Apel dengan Selai Kacang",
  "Protein Bar": "Bar Protein",
  "Whole Wheat Crackers": "Kerupuk Gandum Utuh",
  "Granola Bar": "Granola Bar",
  "Peanut Chikki": "Chikki Kacang Tanah",
  "Bhel Puri": "Bhel Puri",
  "Khakra": "Khakra",
  "Masala Makhana": "Makhana Masala",
  "Hummus with Veggies": "Hummus dengan Sayuran",
  "Paneer Cubes": "Potongan Paneer",
  "Milkshake (Low Sugar)": "Milkshake (Rendah Gula)",
  "Dhokla": "Dhokla",
  "Vegetable Soup": "Sup Sayuran",
  "Idli with Chutney": "Idli dengan Chutney",
  "Cheese Slice": "Irisan Keju",
  "Chana Chaat": "Chana Chaat",
  "Moong Dal Chilla": "Chilla Dal Moong",
  "Rice Cake with Peanut Butter": "Kue Beras dengan Selai Kacang",
  "Popcorn (Air-popped)": "Popcorn (Dipopkan Udara)",
  "Avocado Toast": "Roti Avokad",
  "Stuffed Dates": "Kurma Isi",
  "Oats Cookies": "Kue Oats",
  "Fruit Smoothie": "Smoothie Buah",
  "Carrot Sticks with Hummus": "Stik Wortel dengan Hummus",
  "Soy Nuts": "Kacang Kedelai",
  "Trail Mix": "Campuran Trail",
  "Besan Ladoo": "Ladoo Besan",
  "Upma (small portion)": "Upma (porsi kecil)",
  "Egg Roll (Mini)": "Roll Telur (Mini)",
  "Rice Idli": "Idli Nasi",
  "Cucumber Sandwich": "Sandwich Mentimun",
  "Fruit Chaat": "Chaat Buah",
  "Lassi (Sweet)": "Lassi (Manis)",
  "Cold Coffee (Low Sugar)": "Kopi Dingin (Rendah Gula)",
  "Rava Dhokla": "Dhokla Rava",
  "Vegetable Cutlet": "Vegetable Cutlet",
  "Chikki with Jaggery": "Chikki dengan Gula Merah",
  "Milk (Low Fat)": "Susu (Rendah Lemak)",
  "Baked Samosa": "Samosa Panggang",
  "Vegetable Wrap": "Wrap Sayuran",
  "Roasted Soybeans": "Kedelai Panggang",
  "1/2 cup": "1/2 cangkir",
  "1 handful": "1 genggam",
  "1 apple + 1 tbsp PB": "1 apel + 1 sdm PB",
  "1 bar": "1 bar",
  "5 pieces": "5 potong",
  "½ cup hummus + veggies": "½ cangkir hummus + sayuran",
  "50g": "50g",
  "1 idli + chutney": "1 idli + chutney",
  "1 slice": "1 iris",
  "1 chilla": "1 chilla",
  "1 cake + 1 tbsp PB": "1 kue + 1 sdm PB",
  "2 cups": "2 cangkir",
  "1 toast": "1 roti bakar",
  "3 dates": "3 kurma",
  "2 cookies": "2 kue",
  "½ cup": "½ cangkir",
  "1 small bowl": "1 mangkuk kecil",
  "1 roll": "1 roll",
  "1 wrap": "1 wrap",
  "Chapati with Sabzi": "Chapati dengan Sabzi",
  "Grilled Fish": "Ikan Bakar",
  "Moong Dal Khichdi": "Khichdi Dal Moong",
  "Paneer Bhurji with Roti": "Paneer Bhurji dengan Roti",
  "Brown Rice with Veg Curry": "Nasi Coklat dengan Kari Sayur",
  "Quinoa with Stir Fry Veggies": "Quinoa dengan Sayuran Tumis",
  "Grilled Tofu with Salad": "Tofu Bakar dengan Salad",
  "Vegetable Pulao": "Pulao Sayuran",
  "Palak Paneer with Chapati": "Palak Paneer dengan Chapati",
  "Mixed Vegetable Soup": "Sup Sayuran Campur",
  "Stuffed Paratha with Curd": "Paratha Isi dengan Yogurt",
  "Oats Khichdi": "Khichdi Oats",
  "Roti with Bhindi": "Roti dengan Bhindi",
  "Dal Tadka with Jeera Rice": "Dal Tadka dengan Nasi Jeera",
  "Vegetable Handvo": "Handvo Sayuran",
  "Kadhi with Bajra Roti": "Kadhi dengan Bajra Roti",
  "Tofu Curry with Quinoa": "Curry Tofu dengan Quinoa",
  "Bhakri with Thecha": "Bhakri dengan Thecha",
  "Biryani (Veg)": "Biryani (Vegan)",
  "Rajma with Brown Rice": "Rajma dengan Nasi Coklat",
  "Daliya (Broken Wheat Porridge)": "Daliya (Bubur Gandum Pecah)",
  "Pumpkin Sabzi with Chapati": "Sabzi Labu dengan Chapati",
  "Cauliflower Stir Fry": "Tumis Kembang Kol",
  "Boiled Egg Salad": "Salad Telur Rebus",
  "Tomato Rasam with Rice": "Rasam Tomat dengan Nasi",
  "Sweet Potato with Curd": "Ubi Jalar dengan Yogurt",
  "Stuffed Capsicum": "Paprika Isi",
  "Paneer Tikka with Mint Chutney": "Paneer Tikka dengan Chutney Mint",
  "Rice with Sambar": "Nasi dengan Sambar",
  "Vegetable Thepla with Dahi": "Thepla Sayuran dengan Yogurt",
  "Grilled Mushroom Skewers": "Tusuk Jamur Panggang",
  "Beetroot Sabzi with Roti": "Sabzi Bit dengan Roti",
  "Spinach Dal with Rice": "Dal Bayam dengan Nasi",
  "Lentil Soup with Toast": "Sup Lentil dengan Roti Panggang",
  "Tinda Curry with Chapati": "Kari Tinda dengan Chapati",
  "Egg Bhurji with Roti": "Telur Bhurji dengan Roti",
  "Karela Sabzi with Roti": "Sabzi Karela dengan Roti",
  "Zucchini Stir Fry": "Tumis Zucchini",
  "Low Carb Paneer Bowl": "Mangkuk Paneer Rendah Karbohidrat",
  "Stuffed Tomato": "Tomat Isi",
  "Vegetable Rava Upma": "Upma Semolina Sayuran",
  "2 chapatis + sabzi": "2 Chapati + Sabzi",
  "1 fillet": "1 Fillet",
  "1 bowl + 1 roti": "1 Mangkuk + 1 Roti",
  "1 plate": "1 Piring",
  "1 cup rice + dal": "1 Cangkir Nasi + Dal",
  "1 paratha + ½ cup curd": "1 Paratha + ½ Cangkir Yogurt",
  "2 rotis + bhindi": "2 Roti + Bhindi",
  "1 roti + 1 bowl kadhi": "1 Roti + 1 Mangkuk Kadhi",
  "1 bhakri + chutney": "1 Bhakri + Chutney",
  "1 bowl curry + 1 roti": "1 Mangkuk Kari + 1 Roti",
  "2 chillas": "2 Chillas",
  "1 bowl + ½ cup curd": "1 Mangkuk + ½ Cangkir Yogurt",
  "1 serving": "1 Porsi",
  "1 cup rice + sambar": "1 Cangkir Nasi + Sambar",
  "1 thepla + curd": "1 Thepla + Yogurt",
  "1 skewer": "1 Tusuk",
  "1 bowl + 1 toast": "1 Mangkuk + 1 Roti Panggang",
  "1 bowl + 1 appam": "1 Mangkuk + 1 Appam",
  "1 tomato": "1 Tomat",
  "Restore": "Pulihkan",
  "Get Premium": "Dapatkan Premium",
  "Get All The New Exciting Features": "Dapatkan Semua Fitur Baru yang Menarik",
  "Unlock Food Scanner": "Buka Pemindai Makanan",
  "Unlock Food Calorie": "Buka Kalori Makanan",
  "Unlock Unlimited Chat with Ai": "Buka Chat Tak Terbatas dengan AI",
  "Unlimited Food Scanner To Calorie": "Pemindai Makanan Tak Terbatas ke Kalori",
  "Most Popular": "Paling Populer",
  "Subscription": "Langganan",
  "BUY NOW": "BELI SEKARANG",
  "Terms of Condition": "Syarat dan Ketentuan",
  "Welcome": "Selamat Datang",
  "Calorie tracking made easy": "Pelacakan Kalori Jadi Mudah",
  "Just snap a quick photo of your meal and we''ll do the rest": "Ambil foto cepat makanan Anda dan kami akan mengurus sisanya",
  "In-depth nutrition analyses": "Analisis Gizi Mendalam",
  "We will keep your informed about your food choicer and their nutritional content": "Kami akan memberi tahu Anda tentang pilihan makanan Anda dan kandungan gizinya",
  "Transform your body": "Transformasikan Tubuh Anda",
  "Today is best time to start working toward your dream body": "Hari ini adalah waktu terbaik untuk mulai bekerja menuju tubuh impian Anda",
  "Where were you born?": "Dimana Anda dilahirkan?",
  "This Will be used to calibrate your custom plan": "Ini akan digunakan untuk mengkalibrasi rencana kustom Anda",
  "What's stopping you from reaching your goals?": "Apa yang menghalangi Anda untuk mencapai tujuan Anda?",
  "Lack of consistency": "Kurangnya Konsistensi",
  "Unhealthy eating habits": "Kebiasaan Makan Tidak Sehat",
  "Lack of supports": "Kurangnya Dukungan",
  "Busy schedule": "Jadwal Sibuk",
  "Lack of meal inspiration": "Kurangnya Inspirasi Makan",
  "We're setting": "Kami sedang menyiapkan",
  "everything up for you": "semua untuk Anda",
  "Customizing health plan....": "Menyesuaikan rencana kesehatan...."
}
;
