const Map<String, String> italian = {
  "Home": "Home",
  "Calorie": "Calorie",
  "Analytics": "Analisi",
  "Setting": "Impostazioni",
  "Track Food": "Traccia Cibo",
  "Consumed": "Consumate",
  "Remaining": "Rimanenti",
  "Protein": "Proteine",
  "Carbs": "Carboidrati",
  "Fats": "Grassi",
  "History": "Storico",
  "View All": "Vedi Tutto",
  "BreakFast": "Colazione",
  "Lunch": "Pranzo",
  "snack(s)": "Spuntino",
  "Dinner": "Cena",
  "Which meal would you like to track?": "Quale pasto vuoi tracciare?",
  "Snap Tips": "Suggerimenti Foto",
  "Too close": "Troppo vicino",
  "Too far": "Troppo lontano",
  "Multi-species": "Multi-specie",
  "Continue": "Continua",
  "OverView": "Panoramica",
  "Weight Goal": "Obiettivo di Peso",
  "Update": "Aggiorna",
  "Current Weight": "Peso Attuale",
  "kg": "kg",
  "Try to update once a week so we can adjust your plan to ensure you hit your goal": "Prova ad aggiornare una volta a settimana per adattare il tuo piano",
  "Update Weight": "Aggiorna Peso",
  "Week": "Settimana",
  "Month": "Mese",
  "Year": "Anno",
  "Update Weight Goal": "Aggiorna Obiettivo di Peso",
  "Enter new weight (kg)": "Inserisci nuovo peso (kg)",
  "Cancel": "Annulla",
  "Calorie Your Week :": "Calorie della tua Settimana:",
  "Sun": "Dom",
  "Mon": "Lun",
  "Tue": "Mar",
  "Wed": "Mer",
  "Thu": "Gio",
  "Fri": "Ven",
  "Sat": "Sab",
  "Average Calorie Month :": "Media Calorie Mensile:",
  "Average Calorie Yearly :": "Media Calorie Annuale:",
  "Jan": "Gen",
  "Feb": "Feb",
  "Mar": "Mar",
  "Apr": "Apr",
  "May": "Mag",
  "Jun": "Giu",
  "Jul": "Lug",
  "Aug": "Ago",
  "Sep": "Set",
  "Oct": "Ott",
  "Nov": "Nov",
  "Dec": "Dic",
  "Age": "Età",
  "Height": "Altezza",
  "Customization": "Personalizzazione",
  "Dark Mode": "Modalità Scura",
  "Language": "Lingua",
  "Personal details": "Dettagli personali",
  "Adjust goals": "Regola obiettivi",
  "Calories,carbs,fat and protein": "Calorie, carboidrati, grassi e proteine",
  "Chat history": "Cronologia chat",
  "Legal": "Legale",
  "Terms and Condition": "Termini e Condizioni",
  "Privacy Policy": "Politica sulla Privacy",
  "Reset Data?": "Reimpostare Account?",
  "VERSION": "VERSIONE",
  "History not found": "Cronologia non trovata",
  "Delete Item": "Elimina Elemento",
  "Are you sure you want to delete this item?": "Sei sicuro di voler eliminare questo elemento?",
  "Delete": "Elimina",
  "Search by Food Name/Dish": "Cerca per Nome Cibo/Piatto",
  "🎯 Calorie Goal Reached": "🎯 Obiettivo Calorico Raggiunto",
  "You've completed your calorie goal for today. Would you like to add more?": "Hai raggiunto il tuo obiettivo calorico di oggi. Vuoi aggiungerne altri?",
  "Done": "Fatto",
  "Add More Calories": "Aggiungi Altre Calorie",
  "Boiled Egg": "Uovo Sodo",
  "Oatmeal": "Porridge",
  "Banana": "Banana",
  "Paratha": "Paratha",
  "Idli": "Idli",
  "Dosa": "Dosa",
  "Upma": "Upma",
  "Poha": "Poha",
  "Bread Butter": "Pane e Burro",
  "Cornflakes with Milk": "Cornflakes con Latte",
  "Chilla (Besan)": "Chilla (Farina di Ceci)",
  "Sprouts Salad": "Insalata di Germogli",
  "Pancakes": "Pancake",
  "Apple": "Mela",
  "Milk": "Latte",
  "Almonds": "Mandorle",
  "Smoothie (Fruit)": "Frullato (Frutta)",
  "Yogurt (Plain)": "Yogurt (Naturale)",
  "Khichdi": "Khichdi",
  "Thepla": "Thepla",
  "Cheela (Moong dal)": "Cheela (lenticchie verdi)",
  "Pav Bhaji": "Pav Bhaji",
  "Sabudana Khichdi": "Sabudana Khichdi",
  "Roti with Sabzi": "Roti con verdure",
  "Peanut Butter Bread": "Pane con burro di arachidi",
  "Fruit Bowl": "Ciotola di frutta",
  "Vegetable Sandwich": "Panino con verdure",
  "Rice Idli with Sambar": "Idli di riso con sambar",
  "Boiled Corn": "Mais bollito",
  "Paneer Bhurji": "Paneer strapazzato",
  "Protein Shake": "Frullato proteico",
  "Muesli with Milk": "Muesli con latte",
  "Chapati with Curd": "Chapati con yogurt",
  "Porridge (Daliya)": "Porridge (Daliya)",
  "Rava Upma": "Rava Upma",
  "Chickpea Salad": "Insalata di ceci",
  "Boiled Sweet Potato": "Patata dolce bollita",
  "Coconut Water": "Acqua di cocco",
  "Masala Omelette": "Omelette speziata",
  "Vegetable Poha": "Poha di verdure",
  "1 egg": "1 uovo",
  "1 bowl": "1 ciotola",
  "1 medium": "1 medio",
  "1 piece": "1 pezzo",
  "1 cup": "1 tazza",
  "2 slices": "2 fette",
  "2 small pieces": "2 pezzi piccoli",
  "10 pieces": "10 pezzi",
  "1 glass": "1 bicchiere",
  "2 pavs + bhaji": "2 panini + bhaji",
  "1 roti + sabzi": "1 roti + verdure",
  "1 sandwich": "1 panino",
  "2 idlis + sambar'": "2 idli + sambar",
  "1 chapati + ½ cup curd": "1 chapati + ½ tazza di yogurt",
  "Rice with Dal": "Riso con lenticchie",
  "Grilled Chicken": "Pollo alla griglia",
  "Paneer Curry": "Curry di paneer",
  "Mixed Vegetable Curry": "Curry di verdure miste",
  "Chapati with Daal": "Chapati con lenticchie",
  "Fish Curry with Rice": "Curry di pesce con riso",
  "Rajma Chawal": "Fagioli rossi con riso",
  "Chole Bhature": "Chole Bhature",
  "Kadhi with Rice": "Kadhi con riso",
  "Palak Paneer": "Paneer agli spinaci",
  "Stuffed Paratha": "Paratha ripieno",
  "Veg Pulao": "Pulao di verdure",
  "Biryani with Raita": "Biryani con raita",
  "Tofu Stir Fry": "Tofu saltato",
  "Chicken Tikka": "Chicken Tikka",
  "Veg Fried Rice": "Riso fritto vegetariano",
  "Aloo Gobi with Roti": "Aloo Gobi con roti",
  "Baingan Bharta": "Melanzane affumicate (Baingan Bharta)",
  "Sambar with Rice": "Sambar con riso",
  "Chicken Curry with Roti": "Curry di pollo con roti",
  "Bhindi Masala with Roti": "Okra speziata con roti",
  "Egg Curry with Rice": "Curry di uova con riso",
  "Lentil Soup with Bread": "Zuppa di lenticchie con pane",
  "Methi Thepla with Curd": "Methi Thepla con yogurt",
  "Soybean Curry with Rice": "Curry di soia con riso",
  "Cabbage Sabzi with Chapati": "Cavolo con chapati",
  "Dal Makhani with Naan": "Dal Makhani con naan",
  "Vegetable Korma with Roti": "Korma di verdure con roti",
  "Tandoori Roti with Paneer": "Roti tandoori con paneer",
  "Mixed Dal with Rice": "Lenticchie miste con riso",
  "Bottle Gourd Curry with Roti": "Curry di zucca con roti",
  "Kofta Curry with Roti": "Curry di kofta con roti",
  "Paneer Bhurji with Bread": "Paneer strapazzato con pane",
  "Chana Masala with Rice": "Chana masala con riso",
  "Curd Rice": "Riso allo yogurt",
  "Tomato Rice": "Riso al pomodoro",
  "Vegetable Stew with Appam": "Spezzatino di verdure con appam",
  "Dhokla with Green Chutney": "Dhokla con chutney verde",
  "Besan Chilla with Salad": "Besan Chilla con insalata",
  "Lauki Chana Dal": "Zucca con chana dal",
  "Spinach Corn Curry": "Curry di spinaci e mais",
  "Tinda Masala with Roti": "Tinda speziato con roti",
  "Masoor Dal with Rice": "Masoor dal con riso",
  "Vegetable Handi with Naan": "Verdure Handi con naan",
  "Egg Bhurji with Chapati": "Uova strapazzate con chapati",
  "Pumpkin Curry with Rice": "Curry di zucca con riso",
  "2 rotis + sabzi": "2 roti + verdure",
  "1 cup rice + 1 cup dal": "1 tazza di riso + 1 tazza di lenticchie",
  "1 breast": "1 petto",
  "2 chapatis + dal'": "2 chapati + lenticchie",
  "1 bowl curry + 1 cup rice": "1 ciotola di curry + 1 tazza di riso",
  "1 bhatura + chole": "1 bhatura + chole",
  "1 paratha": "1 paratha",
  "1 bowl + 2 rotis": "1 ciotola + 2 roti",
  "1 cup + 1 bowl": "1 tazza + 1 ciotola",
  "1 bowl + 1 cup rice": "1 ciotola + 1 tazza di riso",
  "1 bowl + 1 bread slice": "1 ciotola + 1 fetta di pane",
  "2 theplas + ½ cup curd": "2 thepla + ½ tazza di yogurt",
  "1 bowl + 2 chapatis": "1 ciotola + 2 chapati",
  "1 bowl + 1 naan": "1 ciotola + 1 naan",
  "2 rotis + paneer": "2 roti + paneer",
  "1 bowl + 2 slices": "1 ciotola + 2 fette",
  "1 bowl + 2 appams": "1 ciotola + 2 appam",


  "3 pieces": "3 pezzi",
  "2 chillas + salad": "2 chilla + insalata",
  "Cal": "Cal",
  "Cropper": "Cropper",
  "Calorie Tracker": "Tracciatore di Calorie",
  "Add Calorie": "Aggiungi Caloria",
  "Quantity": "Quantità",
  "Ask With Open AI": "Chiedi con Open AI",
  "This picture not available Calorie,Protein,Carbs and Fats,": "Questa immagine non è disponibile per Calorie, Proteine, Carboidrati e Grassi.",
  "Ask Botanist": "Chiedi al Botanico",
  "Write your message": "Scrivi il tuo messaggio",
  "Confirm Reset": "Conferma Reset",
  "Are you sure you want to Reset Data?": "Sei sicuro di voler resettare l'account?",
  "Reset": "Reset",
  "You have been Reset Account": "Il tuo account è stato resettato",
  "Personal Details": "Dettagli Personali",
  "Goal Weight": "Peso Obiettivo",
  "cm": "cm",
  "Date Of Birth": "Data di Nascita",
  "Gender": "Genere",
  "Male": "Maschio",
  "Female": "Femmina",
  "Choose your desired weight?": "Scegli il peso desiderato?",
  "Imperial": "Imperiale",
  "Metric": "Metrico",
  "Weight": "Peso",
  "lb": "lb",
  "ft": "ft",
  "in": "in",
  "Day": "Giorno",
  "January": "Gennaio",
  "February": "Febbraio",
  "March": "Marzo",
  "April": "Aprile",
  "June": "Giugno",
  "July": "Luglio",
  "August": "Agosto",
  "September": "Settembre",
  "October": "Ottobre",
  "November": "Novembre",
  "December": "Dicembre",
  "Update Your Gender": "Aggiorna il tuo Genere",
  "Other": "Altro",
  "Adjust Goals": "Regola Obiettivi",
  "How many workout do you per week?": "Quante volte ti alleni a settimana?",
  "This will used to calibrate your custom plan": "Questo verrà utilizzato per calibrare il tuo piano personalizzato",
  "Workout Now and then": "Allenamento ogni tanto",
  "A few workout per week": "Alcuni allenamenti a settimana",
  "Dedicated athlete": "Atleta dedicato",
  "What is your goal?": "Qual è il tuo obiettivo?",
  "This helps is generate a plan for your calorie intake.": "Questo aiuta a generare un piano per l'assunzione di calorie.",
  "Gain Weight": "Aumentare il Peso",
  "Lose Weight": "Perdere Peso",
  "Update Calorie Goal": "Aggiorna l'Obiettivo di Calorie",
  "Save": "Salva",
  "Calorie Goal": "Obiettivo di Calorie",
  "Update Protein Goal": "Aggiorna l'Obiettivo di Proteine",
  "Protein goal": "Obiettivo di Proteine",
  "Update Carb Goal": "Aggiorna l'Obiettivo di Carboidrati",
  "Carb goal": "Obiettivo di Carboidrati",
  "Update Fat Goal": "Aggiorna l'Obiettivo di Grassi",
  "Auto Generate Goal": "Genera Obiettivo Automaticamente",
  "Fruit Salad": "Insalata di Frutta",
  "Roasted Chickpeas": "Ceci Arrostiti",
  "Mixed Nuts": "Noci Miste",
  "Yogurt with Honey": "Yogurt con Miele",
  "Apple with Peanut Butter": "Mela con Burro di Arachidi",
  "Protein Bar": "Barra Proteica",
  "Whole Wheat Crackers": "Cracker di Grano Intero",
  "Granola Bar": "Barra di Granola",
  "Peanut Chikki": "Chikki di Arachidi",
  "Bhel Puri": "Bhel Puri",
  "Khakra": "Khakra",
  "Masala Makhana": "Makhana Masala",
  "Hummus with Veggies": "Hummus con Verdure",
  "Paneer Cubes": "Cubetti di Paneer",
  "Milkshake (Low Sugar)": "Milkshake (Basso Zucchero)",
  "Dhokla": "Dhokla",
  "Vegetable Soup": "Zuppa di Verdure",
  "Idli with Chutney": "Idli con Chutney",
  "Cheese Slice": "Fetta di Formaggio",
  "Chana Chaat": "Chana Chaat",
  "Moong Dal Chilla": "Chilla di Moong Dal",
  "Rice Cake with Peanut Butter": "Torta di Riso con Burro di Arachidi",
  "Popcorn (Air-popped)": "Popcorn (Aria Popcorn)",
  "Avocado Toast": "Toast con Avocado",
  "Stuffed Dates": "Datteri Ripieni",
  "Oats Cookies": "Biscotti di Avena",
  "Fruit Smoothie": "Frullato di Frutta",
  "Carrot Sticks with Hummus": "Bastoncini di Carota con Hummus",
  "Soy Nuts": "Noci di Soia",
  "Trail Mix": "Mix di Trail",
  "Besan Ladoo": "Ladoo di Besan",
  "Upma (small portion)": "Upma (piccola porzione)",
  "Egg Roll (Mini)": "Rotolo di Uovo (Mini)",
  "Rice Idli": "Idli di Riso",
  "Cucumber Sandwich": "Sandwich di Cetriolo",
  "Fruit Chaat": "Chaat di Frutta",
  "Lassi (Sweet)": "Lassi (Dolce)",
  "Cold Coffee (Low Sugar)": "Caffè Freddo (Basso Zucchero)",
  "Rava Dhokla": "Dhokla di Rava",
  "Vegetable Cutlet": "Crocchetta di Verdure",
  "Chikki with Jaggery": "Chikki con Jaggery",
  "Milk (Low Fat)": "Latte (Basso Contenuto di Grassi)",
  "Baked Samosa": "Samosa al Forno",
  "Vegetable Wrap": "Wrap di Verdure",
  "Roasted Soybeans": "Soia Tostata",
  "1/2 cup": "1/2 tazza",
  "1 handful": "1 manciata",
  "1 apple + 1 tbsp PB": "1 mela + 1 cucchiaio di PB",
  "1 bar": "1 barretta",
  "5 pieces": "5 pezzi",
  "½ cup hummus + veggies": "½ tazza di hummus + verdure",
  "50g": "50g",
  "1 idli + chutney": "1 idli + chutney",
  "1 slice": "1 fetta",
  "1 chilla": "1 chilla",
  "1 cake + 1 tbsp PB": "1 torta + 1 cucchiaio di PB",
  "2 cups": "2 tazze",
  "1 toast": "1 toast",
  "3 dates": "3 datteri",
  "2 cookies": "2 biscotti",
  "½ cup": "½ tazza",
  "1 small bowl": "1 piccola ciotola",
  "1 roll": "1 rotolo",
  "1 wrap": "1 wrap",
  "Chapati with Sabzi": "Chapati con Sabzi",
  "Grilled Fish": "Pesce alla Griglia",
  "Moong Dal Khichdi": "Khichdi di Moong Dal",
  "Paneer Bhurji with Roti": "Paneer Bhurji con Roti",
  "Brown Rice with Veg Curry": "Riso Integrale con Curry di Verdure",
  "Quinoa with Stir Fry Veggies": "Quinoa con Verdure Saltate",
  "Grilled Tofu with Salad": "Tofu alla Griglia con Insalata",
  "Vegetable Pulao": "Pulao di Verdure",
  "Palak Paneer with Chapati": "Palak Paneer con Chapati",
  "Mixed Vegetable Soup": "Zuppa di Verdure Miste",
  "Stuffed Paratha with Curd": "Paratha Ripieno con Yogurt",
  "Oats Khichdi": "Khichdi di Avena",
  "Roti with Bhindi": "Roti con Bhindi",
  "Dal Tadka with Jeera Rice": "Dal Tadka con Riso Jeera",
  "Vegetable Handvo": "Handvo di Verdure",
  "Kadhi with Bajra Roti": "Kadhi con Bajra Roti",
  "Tofu Curry with Quinoa": "Curry di Tofu con Quinoa",
  "Bhakri with Thecha": "Bhakri con Thecha",
  "Biryani (Veg)": "Biryani (Veg)",
  "Rajma with Brown Rice": "Rajma con Riso Integrale",
  "Daliya (Broken Wheat Porridge)": "Daliya (Porridge di Grano Spezzato)",
  "Pumpkin Sabzi with Chapati": "Sabzi di Zucca con Chapati",
  "Cauliflower Stir Fry": "Tumis Cavolfiore",
  "Boiled Egg Salad": "Insalata con Uovo Sodo",
  "Tomato Rasam with Rice": "Rasam di pomodoro con riso",
  "Sweet Potato with Curd": "Patata dolce con yogurt",
  "Stuffed Capsicum": "Peperone ripieno",
  "Paneer Tikka with Mint Chutney": "Paneer Tikka con chutney di menta",
  "Rice with Sambar": "Riso con Sambar",
  "Vegetable Thepla with Dahi": "Thepla di verdure con yogurt",
  "Grilled Mushroom Skewers": "Spiedini di funghi grigliati",
  "Beetroot Sabzi with Roti": "Sabzi di barbabietola con roti",
  "Spinach Dal with Rice": "Dal di spinaci con riso",
  "Lentil Soup with Toast": "Zuppa di lenticchie con toast",
  "Tinda Curry with Chapati": "Curry di Tinda con chapati",
  "Egg Bhurji with Roti": "Uova Bhurji con roti",
  "Karela Sabzi with Roti": "Sabzi di Karela con roti",
  "Zucchini Stir Fry": "Saltato di zucchine",
  "Low Carb Paneer Bowl": "Ciotola di paneer a basso contenuto di carboidrati",
  "Stuffed Tomato": "Pomodoro ripieno",
  "Vegetable Rava Upma": "Upma di semola e verdure",
  "2 chapatis + sabzi": "2 chapati + sabzi",
  "1 fillet": "1 filetto",
  "1 bowl + 1 roti": "1 ciotola + 1 roti",
  "1 plate": "1 piatto",
  "1 cup rice + dal": "1 tazza di riso + dal",
  "1 paratha + ½ cup curd": "1 paratha + ½ tazza di yogurt",
  "2 rotis + bhindi": "2 roti + bhindi",
  "1 roti + 1 bowl kadhi": "1 roti + 1 ciotola di kadhi",
  "1 bhakri + chutney": "1 bhakri + chutney",
  "1 bowl curry + 1 roti": "1 ciotola di curry + 1 roti",
  "2 chillas": "2 chillas",
  "1 bowl + ½ cup curd": "1 ciotola + ½ tazza di yogurt",
  "1 serving": "1 porzione",
  "1 cup rice + sambar": "1 tazza di riso + sambar",
  "1 thepla + curd": "1 thepla + yogurt",
  "1 skewer": "1 spiedino",
  "1 bowl + 1 toast": "1 ciotola + 1 toast",
  "1 bowl + 1 appam": "1 ciotola + 1 appam",
  "1 tomato": "1 pomodoro",
  "Restore": "Ripristina",
  "Get Premium": "Ottieni Premium",
  "Get All The New Exciting Features": "Ottieni tutte le nuove e entusiasmanti funzionalità",
  "Unlock Food Scanner": "Sblocca il lettore di alimenti",
  "Unlock Food Calorie": "Sblocca le calorie degli alimenti",
  "Unlock Unlimited Chat with Ai": "Sblocca chat illimitata con Ai",
  "Unlimited Food Scanner To Calorie": "Lettore di alimenti illimitato per le calorie",
  "Most Popular": "Più popolare",
  "Subscription": "Abbonamento",
  "BUY NOW": "ACQUISTA ORA",
  "Terms of Condition": "Termini e condizioni",
  "Welcome": "Benvenuto",
  "Calorie tracking made easy": "Monitoraggio delle calorie reso facile",
  "Just snap a quick photo of your meal and we''ll do the rest": "Scatta una foto veloce del tuo pasto e faremo il resto",
  "In-depth nutrition analyses": "Analisi nutrizionali approfondite",
  "We will keep your informed about your food choicer and their nutritional content": "Ti terremo informato sulle tue scelte alimentari e sul loro contenuto nutrizionale",
  "Transform your body": "Trasforma il tuo corpo",
  "Today is best time to start working toward your dream body": "Oggi è il miglior momento per iniziare a lavorare per il tuo corpo dei sogni",
  "Where were you born?": "Dove sei nato?",
  "This Will be used to calibrate your custom plan": "Questo sarà utilizzato per calibrare il tuo piano personalizzato",
  "What's stopping you from reaching your goals?": "Cosa ti sta impedendo di raggiungere i tuoi obiettivi?",
  "Lack of consistency": "Mancanza di costanza",
  "Unhealthy eating habits": "Abitudini alimentari poco sane",
  "Lack of supports": "Mancanza di supporto",
  "Busy schedule": "Programma impegnato",
  "Lack of meal inspiration": "Mancanza di ispirazione per i pasti",
  "We're setting": "Stiamo preparando",
  "everything up for you": "tutto per te",
  "Customizing health plan....": "Personalizzazione del piano salute...."
}
;
