const Map<String, String> japanese = {
  "Home": "ホーム",
  "Calorie": "カロリー",
  "Analytics": "分析",
  "Setting": "設定",
  "Track Food": "食事を記録",
  "Consumed": "摂取済み",
  "Remaining": "残り",
  "Protein": "たんぱく質",
  "Carbs": "炭水化物",
  "Fats": "脂質",
  "History": "履歴",
  "View All": "すべて表示",
  "BreakFast": "朝食",
  "Lunch": "昼食",
  "snack(s)": "間食",
  "Dinner": "夕食",
  "Which meal would you like to track?": "どの食事を記録しますか？",
  "Snap Tips": "撮影のコツ",
  "Too close": "近すぎる",
  "Too far": "遠すぎる",
  "Multi-species": "複数の食品",
  "Continue": "続ける",
  "OverView": "概要",
  "Weight Goal": "体重目標",
  "Update": "更新",
  "Current Weight": "現在の体重",
  "kg": "kg",
  "Try to update once a week so we can adjust your plan to ensure you hit your goal": "週に一度体重を更新すると、目標達成に合わせたプラン調整が可能です",
  "Update Weight": "体重を更新",
  "Week": "週",
  "Month": "月",
  "Year": "年",
  "Update Weight Goal": "体重目標を更新",
  "Enter new weight (kg)": "新しい体重を入力（kg）",
  "Cancel": "キャンセル",
  "Calorie Your Week :": "今週のカロリー：",
  "Sun": "日",
  "Mon": "月",
  "Tue": "火",
  "Wed": "水",
  "Thu": "木",
  "Fri": "金",
  "Sat": "土",
  "Average Calorie Month :": "月平均カロリー：",
  "Average Calorie Yearly :": "年間平均カロリー：",
  "Jan": "1月",
  "Feb": "2月",
  "Mar": "3月",
  "Apr": "4月",
  "May": "5月",
  "Jun": "6月",
  "Jul": "7月",
  "Aug": "8月",
  "Sep": "9月",
  "Oct": "10月",
  "Nov": "11月",
  "Dec": "12月",
  "Age": "年齢",
  "Height": "身長",
  "Customization": "カスタマイズ",
  "Dark Mode": "ダークモード",
  "Language": "言語",
  "Personal details": "個人情報",
  "Adjust goals": "目標を調整",
  "Calories,carbs,fat and protein": "カロリー、炭水化物、脂質、たんぱく質",
  "Chat history": "チャット履歴",
  "Legal": "法的情報",
  "Terms and Condition": "利用規約",
  "Privacy Policy": "プライバシーポリシー",
  "Reset Data?": "アカウントをリセットしますか？",
  "VERSION": "バージョン",
  "History not found": "履歴が見つかりません",
  "Delete Item": "アイテムを削除",
  "Are you sure you want to delete this item?": "このアイテムを削除してもよろしいですか？",
  "Delete": "削除",
  "Search by Food Name/Dish": "食品名／料理名で検索",
  "🎯 Calorie Goal Reached": "🎯 カロリー目標達成",
  "You've completed your calorie goal for today. Would you like to add more?": "本日のカロリー目標を達成しました。さらに追加しますか？",
  "Done": "完了",
  "Add More Calories": "カロリーを追加",
  "Boiled Egg": "ゆで卵",
  "Oatmeal": "オートミール",
  "Banana": "バナナ",
  "Paratha": "パラタ",
  "Idli": "イディリ",
  "Dosa": "ドーサ",
  "Upma": "ウプマ",
  "Poha": "ポハ",
  "Bread Butter": "バター付きパン",
  "Cornflakes with Milk": "コーンフレークとミルク",
  "Chilla (Besan)": "チラ（ベサン）",
  "Sprouts Salad": "スプラウトサラダ",
  "Pancakes": "パンケーキ",
  "Apple": "りんご",
  "Milk": "ミルク",
  "Almonds": "アーモンド",
  "Smoothie (Fruit)": "スムージー（フルーツ）",
  "Yogurt (Plain)": "ヨーグルト（プレーン）",
  "Khichdi": "キチュリ",
  "Thepla": "テープラ",
  "Cheela (Moong dal)": "チーラ（ムング豆）",
  "Pav Bhaji": "パブ・バジ",
  "Sabudana Khichdi": "サブダナ・キチディ",
  "Roti with Sabzi": "ロティとサブジ",
  "Peanut Butter Bread": "ピーナッツバターブレッド",
  "Fruit Bowl": "フルーツボウル",
  "Vegetable Sandwich": "野菜サンドイッチ",
  "Rice Idli with Sambar": "ライス・イドリとサンバル",
  "Boiled Corn": "茹でたトウモロコシ",
  "Paneer Bhurji": "パニール・ブールジ",
  "Protein Shake": "プロテインシェイク",
  "Muesli with Milk": "ミューズリーとミルク",
  "Chapati with Curd": "チャパティとヨーグルト",
  "Porridge (Daliya)": "お粥（ダリヤ）",
  "Rava Upma": "ラヴァ・ウプマ",
  "Chickpea Salad": "ひよこ豆のサラダ",
  "Boiled Sweet Potato": "茹でたサツマイモ",
  "Coconut Water": "ココナッツウォーター",
  "Masala Omelette": "マサラオムレツ",
  "Vegetable Poha": "野菜ポハ",
  "1 egg": "卵1個",
  "1 bowl": "1杯",
  "1 medium": "中サイズ1個",
  "1 piece": "1個",
  "1 cup": "1カップ",
  "2 slices": "2枚",
  "2 small pieces": "小さな2個",
  "10 pieces": "10個",
  "1 glass": "1杯",
  "2 pavs + bhaji": "パブ2個＋バジ",
  "1 roti + sabzi": "ロティ1枚＋サブジ",
  "1 sandwich": "サンドイッチ1個",
  "2 idlis + sambar'": "イドリ2個＋サンバル",
  "1 chapati + ½ cup curd": "チャパティ1枚＋ヨーグルト½カップ",
  "Rice with Dal": "ダールご飯",
  "Grilled Chicken": "グリルチキン",
  "Paneer Curry": "パニールカレー",
  "Mixed Vegetable Curry": "ミックス野菜カレー",
  "Chapati with Daal": "チャパティとダール",
  "Fish Curry with Rice": "魚カレーとご飯",
  "Rajma Chawal": "ラジマ・チャワル",
  "Chole Bhature": "チョレ・バトゥーレ",
  "Kadhi with Rice": "カディとご飯",
  "Palak Paneer": "パラク・パニール",
  "Stuffed Paratha": "詰め物入りパラタ",
  "Veg Pulao": "野菜プラオ",
  "Biryani with Raita": "ビリヤニとライタ",
  "Tofu Stir Fry": "豆腐の炒め物",
  "Chicken Tikka": "チキンティッカ",
  "Veg Fried Rice": "野菜チャーハン",
  "Aloo Gobi with Roti": "アル・ゴビとロティ",
  "Baingan Bharta": "ベイガン・バルタ",
  "Sambar with Rice": "サンバルとご飯",
  "Chicken Curry with Roti": "チキンカレーとロティ",
  "Bhindi Masala with Roti": "オクラマサラとロティ",
  "Egg Curry with Rice": "卵カレーとご飯",
  "Lentil Soup with Bread": "レンズ豆スープとパン",
  "Methi Thepla with Curd": "メティ・テープラとヨーグルト",
  "Soybean Curry with Rice": "大豆カレーとご飯",
  "Cabbage Sabzi with Chapati": "キャベツのサブジとチャパティ",
  "Dal Makhani with Naan": "ダール・マカニとナン",
  "Vegetable Korma with Roti": "野菜コルマとロティ",
  "Tandoori Roti with Paneer": "タンドーリロティとパニール",
  "Mixed Dal with Rice": "ミックスダールとご飯",
  "Bottle Gourd Curry with Roti": "ボトルゴーヤカレーとロティ",
  "Kofta Curry with Roti": "コフタカレーとロティ",
  "Paneer Bhurji with Bread": "パニール・ブールジとパン",
  "Chana Masala with Rice": "チャナマサラとご飯",
  "Curd Rice": "ヨーグルトご飯",
  "Tomato Rice": "トマトご飯",
  "Vegetable Stew with Appam": "野菜シチューとアッパム",
  "Dhokla with Green Chutney": "ドクラとグリーンチャツネ",
  "Besan Chilla with Salad": "ベサン・チラとサラダ",
  "Lauki Chana Dal": "ロウキとチャナダール",
  "Spinach Corn Curry": "ほうれん草とトウモロコシのカレー",
  "Tinda Masala with Roti": "ティンダマサラとロティ",
  "Masoor Dal with Rice": "マスールダールとご飯",
  "Vegetable Handi with Naan": "野菜ハンディとナン",
  "Egg Bhurji with Chapati": "卵ブールジとチャパティ",
  "Pumpkin Curry with Rice": "カボチャカレーとご飯",
  "2 rotis + sabzi": "ロティ2枚＋サブジ",
  "1 cup rice + 1 cup dal": "ご飯1カップ＋ダール1カップ",
  "1 breast": "胸肉1枚",
  "2 chapatis + dal'": "チャパティ2枚＋ダール",
  "1 bowl curry + 1 cup rice": "カレー1杯＋ご飯1カップ",
  "1 bhatura + chole": "バトゥーラ1個＋チョレ",
  "1 paratha": "パラタ1枚",
  "1 bowl + 2 rotis": "1杯＋ロティ2枚",
  "1 cup + 1 bowl": "1カップ＋1杯",
  "1 bowl + 1 cup rice": "1杯＋ご飯1カップ",
  "1 bowl + 1 bread slice": "1杯＋パン1枚",
  "2 theplas + ½ cup curd": "テープラ2枚＋ヨーグルト½カップ",
  "1 bowl + 2 chapatis": "1杯＋チャパティ2枚",
  "1 bowl + 1 naan": "1杯＋ナン1枚",
  "2 rotis + paneer": "ロティ2枚＋パニール",
  "1 bowl + 2 slices": "1杯＋パン2枚",
  "1 bowl + 2 appams": "1杯＋アッパム2枚",


  "3 pieces": "3つのピース",
  "2 chillas + salad": "2つのチラ + サラダ",
  "Cal": "カロリー",
  "Cropper": "クロッパー",
  "Calorie Tracker": "カロリートラッカー",
  "Add Calorie": "カロリーを追加",
  "Quantity": "数量",
  "Ask With Open AI": "Open AIに質問",
  "This picture not available Calorie,Protein,Carbs and Fats,": "この画像にはカロリー、タンパク質、炭水化物、脂肪が含まれていません。",
  "Ask Botanist": "植物学者に質問",
  "Write your message": "メッセージを入力",
  "Confirm Reset": "リセットを確認",
  "Are you sure you want to Reset Data?": "本当にアカウントをリセットしますか？",
  "Reset": "リセット",
  "You have been Reset Account": "アカウントがリセットされました",
  "Personal Details": "個人情報",
  "Goal Weight": "目標体重",
  "cm": "センチメートル",
  "Date Of Birth": "生年月日",
  "Gender": "性別",
  "Male": "男性",
  "Female": "女性",
  "Choose your desired weight?": "希望体重を選んでください。",
  "Imperial": "インペリアル",
  "Metric": "メートル法",
  "Weight": "体重",
  "lb": "ポンド",
  "ft": "フィート",
  "in": "インチ",
  "Day": "日",
  "January": "1月",
  "February": "2月",
  "March": "3月",
  "April": "4月",
  "June": "6月",
  "July": "7月",
  "August": "8月",
  "September": "9月",
  "October": "10月",
  "November": "11月",
  "December": "12月",
  "Update Your Gender": "性別を更新",
  "Other": "その他",
  "Adjust Goals": "目標を調整",
  "How many workout do you per week?": "週に何回運動しますか？",
  "This will used to calibrate your custom plan": "これはあなたのカスタムプランを調整するために使用されます。",
  "Workout Now and then": "たまに運動する",
  "A few workout per week": "週に数回の運動",
  "Dedicated athlete": "専念するアスリート",
  "What is your goal?": "あなたの目標は何ですか？",
  "This helps is generate a plan for your calorie intake.": "これはあなたのカロリー摂取量の計画を生成するのに役立ちます。",
  "Gain Weight": "体重を増やす",
  "Lose Weight": "体重を減らす",
  "Update Calorie Goal": "カロリー目標を更新",
  "Save": "保存",
  "Calorie Goal": "カロリー目標",
  "Update Protein Goal": "タンパク質目標を更新",
  "Protein goal": "タンパク質目標",
  "Update Carb Goal": "炭水化物目標を更新",
  "Carb goal": "炭水化物目標",
  "Update Fat Goal": "脂肪目標を更新",
  "Auto Generate Goal": "目標を自動生成",
  "Fruit Salad": "フルーツサラダ",
  "Roasted Chickpeas": "ローストひよこ豆",
  "Mixed Nuts": "ミックスナッツ",
  "Yogurt with Honey": "ヨーグルトと蜂蜜",
  "Apple with Peanut Butter": "ピーナッツバターを添えたリンゴ",
  "Protein Bar": "プロテインバー",
  "Whole Wheat Crackers": "全粒粉クラッカー",
  "Granola Bar": "グラノーラバー",
  "Peanut Chikki": "ピーナッツチッキ",
  "Bhel Puri": "ベールプーリ",
  "Khakra": "カクラ",
  "Masala Makhana": "マサラマカナ",
  "Hummus with Veggies": "野菜とフムス",
  "Paneer Cubes": "パニールキューブ",
  "Milkshake (Low Sugar)": "ミルクシェイク（低糖）",
  "Dhokla": "ドクラ",
  "Vegetable Soup": "野菜スープ",
  "Idli with Chutney": "チュットニー付きイドリ",
  "Cheese Slice": "チーズスライス",
  "Chana Chaat": "チャナチャート",
  "Moong Dal Chilla": "ムングダールチラ",
  "Rice Cake with Peanut Butter": "ピーナッツバター付きライスケーキ",
  "Popcorn (Air-popped)": "ポップコーン（エアポップ）",
  "Avocado Toast": "アボカドトースト",
  "Stuffed Dates": "詰め物をしたデーツ",
  "Oats Cookies": "オーツクッキー",
  "Fruit Smoothie": "フルーツスムージー",
  "Carrot Sticks with Hummus": "フムスとニンジンスティック",
  "Soy Nuts": "大豆ナッツ",
  "Trail Mix": "トレイルミックス",
  "Besan Ladoo": "ベサンラドゥ",
  "Upma (small portion)": "ウプマ（小さなポーション）",
  "Egg Roll (Mini)": "エッグロール（ミニ）",
  "Rice Idli": "ライスイドリ",
  "Cucumber Sandwich": "キュウリサンドイッチ",
  "Fruit Chaat": "フルーツチャート",
  "Lassi (Sweet)": "ラッシー（甘口）",
  "Cold Coffee (Low Sugar)": "アイスコーヒー（低糖）",
  "Rava Dhokla": "ラヴァドクラ",
  "Vegetable Cutlet": "野菜カトレット",
  "Chikki with Jaggery": "ジャグリー付きチッキ",
  "Milk (Low Fat)": "ミルク（低脂肪）",
  "Baked Samosa": "焼きサモサ",
  "Vegetable Wrap": "野菜ラップ",
  "Roasted Soybeans": "ロースト大豆",
  "1/2 cup": "1/2カップ",
  "1 handful": "1つかみ",
  "1 apple + 1 tbsp PB": "1つのリンゴ + 1大さじのピーナッツバター",
  "1 bar": "1バー",
  "5 pieces": "5つのピース",
  "½ cup hummus + veggies": "½カップのフムス + 野菜",
  "50g": "50g",
  "1 idli + chutney": "1イドリ + チュットニー",
  "1 slice": "1スライス",
  "1 chilla": "1チラ",
  "1 cake + 1 tbsp PB": "1ケーキ + 1大さじのピーナッツバター",
  "2 cups": "2カップ",
  "1 toast": "1トースト",
  "3 dates": "3つのデーツ",
  "2 cookies": "2クッキー",
  "½ cup": "½カップ",
  "1 small bowl": "1小さいボウル",
  "1 roll": "1ロール",
  "1 wrap": "1ラップ",
  "Chapati with Sabzi": "サブジとチャパティ",
  "Grilled Fish": "グリル魚",
  "Moong Dal Khichdi": "ムングダールキチディ",
  "Paneer Bhurji with Roti": "パニールブルジとロティ",
  "Brown Rice with Veg Curry": "ブラウンライスと野菜カレー",
  "Quinoa with Stir Fry Veggies": "キヌアと炒めた野菜",
  "Grilled Tofu with Salad": "グリルした豆腐とサラダ",
  "Vegetable Pulao": "野菜プラオ",
  "Palak Paneer with Chapati": "パラクパニールとチャパティ",
  "Mixed Vegetable Soup": "ミックス野菜スープ",
  "Stuffed Paratha with Curd": "詰め物をしたパラタとヨーグルト",
  "Oats Khichdi": "オーツキチディ",
  "Roti with Bhindi": "ロティとビンディ",
  "Dal Tadka with Jeera Rice": "ダルタダカとジーラライス",
  "Vegetable Handvo": "野菜ハンドヴォ",
  "Kadhi with Bajra Roti": "カディとバジュラロティ",
  "Tofu Curry with Quinoa": "豆腐カレーとキヌア",
  "Bhakri with Thecha": "バクリとテチャ",
  "Biryani (Veg)": "ビリヤニ（野菜）",
  "Rajma with Brown Rice": "ラジマとブラウンライス",
  "Daliya (Broken Wheat Porridge)": "ダリヤ（砕いた小麦の粥）",
  "Pumpkin Sabzi with Chapati": "カボチャサブジとチャパティ",
  "Cauliflower Stir Fry": "カリフラワーの炒め物",
  "Boiled Egg Salad": "茹で卵サラダ",
  "Tomato Rasam with Rice": "トマトラサムとご飯",
  "Sweet Potato with Curd": "さつまいもとヨーグルト",
  "Stuffed Capsicum": "詰め物をしたピーマン",
  "Paneer Tikka with Mint Chutney": "パニールティッカとミントチャツネ",
  "Rice with Sambar": "サンバルとご飯",
  "Vegetable Thepla with Dahi": "野菜テプラとダヒ",
  "Grilled Mushroom Skewers": "グリルしたマッシュルームの串焼き",
  "Beetroot Sabzi with Roti": "ビートルートサブジとロティ",
  "Spinach Dal with Rice": "ほうれん草ダールとご飯",
  "Lentil Soup with Toast": "レンズ豆のスープとトースト",
  "Tinda Curry with Chapati": "ティンダカレーとチャパティ",
  "Egg Bhurji with Roti": "エッグブルジとロティ",
  "Karela Sabzi with Roti": "カレラサブジとロティ",
  "Zucchini Stir Fry": "ズッキーニの炒め物",
  "Low Carb Paneer Bowl": "低炭水化物パニールボウル",
  "Stuffed Tomato": "詰め物をしたトマト",
  "Vegetable Rava Upma": "野菜ラヴァアップマ",
  "2 chapatis + sabzi": "チャパティ2枚 + サブジ",
  "1 fillet": "1切れ",
  "1 bowl + 1 roti": "1ボウル + 1ロティ",
  "1 plate": "1皿",
  "1 cup rice + dal": "1カップのご飯 + ダール",
  "1 paratha + ½ cup curd": "1パラタ + ½カップのヨーグルト",
  "2 rotis + bhindi": "ロティ2枚 + ビンディ",
  "1 roti + 1 bowl kadhi": "1ロティ + 1ボウルのカディ",
  "1 bhakri + chutney": "1バクリ + チャツネ",
  "1 bowl curry + 1 roti": "1ボウルのカレー + 1ロティ",
  "2 chillas": "2チラ",
  "1 bowl + ½ cup curd": "1ボウル + ½カップのヨーグルト",
  "1 serving": "1人前",
  "1 cup rice + sambar": "1カップのご飯 + サンバル",
  "1 thepla + curd": "1テプラ + ヨーグルト",
  "1 skewer": "1串",
  "1 bowl + 1 toast": "1ボウル + 1トースト",
  "1 bowl + 1 appam": "1ボウル + 1アッパム",
  "1 tomato": "1トマト",
  "Restore": "復元",
  "Get Premium": "プレミアムを取得",
  "Get All The New Exciting Features": "すべての新しいエキサイティングな機能を取得",
  "Unlock Food Scanner": "フードスキャナーをアンロック",
  "Unlock Food Calorie": "フードカロリーをアンロック",
  "Unlock Unlimited Chat with Ai": "AIとの無制限チャットをアンロック",
  "Unlimited Food Scanner To Calorie": "無制限のフードスキャナーでカロリー計算",
  "Most Popular": "最も人気のある",
  "Subscription": "サブスクリプション",
  "BUY NOW": "今すぐ購入",
  "Terms of Condition": "利用規約",
  "Welcome": "ようこそ",
  "Calorie tracking made easy": "カロリートラッキングを簡単に",
  "Just snap a quick photo of your meal and we''ll do the rest": "お食事の写真を素早く撮影してください。残りは私たちがやります。",
  "In-depth nutrition analyses": "詳細な栄養分析",
  "We will keep your informed about your food choicer and their nutritional content": "あなたの食事選択とその栄養成分についてお知らせします。",
  "Transform your body": "あなたの体を変えよう",
  "Today is best time to start working toward your dream body": "今日が夢の体に向けて取り組む最良の時です",
  "Where were you born?": "あなたはどこで生まれましたか？",
  "This Will be used to calibrate your custom plan": "これはあなたのカスタムプランを調整するために使用されます",
  "What's stopping you from reaching your goals?": "あなたが目標を達成するのを妨げているのは何ですか？",
  "Lack of consistency": "一貫性の欠如",
  "Unhealthy eating habits": "不健康な食習慣",
  "Lack of supports": "サポート不足",
  "Busy schedule": "忙しいスケジュール",
  "Lack of meal inspiration": "食事のインスピレーション不足",
  "We're setting": "私たちは設定しています",
  "everything up for you": "すべてをあなたのためにセットアップしています",
  "Customizing health plan....": "健康プランをカスタマイズしています...."
};
