const Map<String, String> polish ={
  "Home": "Strona główna",
  "Calorie": "Kalorie",
  "Analytics": "Analiza",
  "Setting": "Ustawienia",
  "Track Food": "Śledź jedzenie",
  "Consumed": "Spożyte",
  "Remaining": "Pozostało",
  "Protein": "Białko",
  "Carbs": "Węglowodany",
  "Fats": "Tłuszcze",
  "History": "Historia",
  "View All": "Zobacz wszystkie",
  "BreakFast": "Śniadanie",
  "Lunch": "Obiad",
  "snack(s)": "Przekąska",
  "Dinner": "Kolacja",
  "Which meal would you like to track?": "Który posiłek chcesz śledzić?",
  "Snap Tips": "Wskazówki dotyczące zdjęć",
  "Too close": "Za blisko",
  "Too far": "Za daleko",
  "Multi-species": "Wiele składników",
  "Continue": "Kontynuuj",
  "OverView": "Przegląd",
  "Weight Goal": "Cel wagowy",
  "Update": "Aktualizuj",
  "Current Weight": "Aktualna waga",
  "kg": "kg",
  "Try to update once a week so we can adjust your plan to ensure you hit your goal": "Aktualizuj raz w tygodniu, aby dostosować plan do Twojego celu",
  "Update Weight": "Zaktualizuj wagę",
  "Week": "Tydzień",
  "Month": "Miesiąc",
  "Year": "Rok",
  "Update Weight Goal": "Zaktualizuj cel wagowy",
  "Enter new weight (kg)": "Wprowadź nową wagę (kg)",
  "Cancel": "Anuluj",
  "Calorie Your Week :": "Kalorie w tym tygodniu:",
  "Sun": "Nie",
  "Mon": "Pon",
  "Tue": "Wto",
  "Wed": "Śro",
  "Thu": "Czw",
  "Fri": "Pią",
  "Sat": "Sob",
  "Average Calorie Month :": "Średnia kalorii miesięcznie:",
  "Average Calorie Yearly :": "Średnia kalorii roczna:",
  "Jan": "Sty",
  "Feb": "Lut",
  "Mar": "Mar",
  "Apr": "Kwi",
  "May": "Maj",
  "Jun": "Cze",
  "Jul": "Lip",
  "Aug": "Sie",
  "Sep": "Wrz",
  "Oct": "Paź",
  "Nov": "Lis",
  "Dec": "Gru",
  "Age": "Wiek",
  "Height": "Wzrost",
  "Customization": "Dostosowanie",
  "Dark Mode": "Tryb ciemny",
  "Language": "Język",
  "Personal details": "Dane osobowe",
  "Adjust goals": "Dostosuj cele",
  "Calories,carbs,fat and protein": "Kalorie, węglowodany, tłuszcze i białka",
  "Chat history": "Historia czatu",
  "Legal": "Informacje prawne",
  "Terms and Condition": "Regulamin",
  "Privacy Policy": "Polityka prywatności",
  "Reset Data?": "Zresetować konto?",
  "VERSION": "WERSJA",
  "History not found": "Historia nieznaleziona",
  "Delete Item": "Usuń element",
  "Are you sure you want to delete this item?": "Czy na pewno chcesz usunąć ten element?",
  "Delete": "Usuń",
  "Search by Food Name/Dish": "Szukaj według nazwy jedzenia/dania",
  "🎯 Calorie Goal Reached": "🎯 Cel kaloryczny osiągnięty",
  "You've completed your calorie goal for today. Would you like to add more?": "Osiągnąłeś dzienny cel kaloryczny. Chcesz dodać więcej?",
  "Done": "Gotowe",
  "Add More Calories": "Dodaj więcej kalorii",
  "Boiled Egg": "Jajko gotowane",
  "Oatmeal": "Owsianka",
  "Banana": "Banan",
  "Paratha": "Paratha",
  "Idli": "Idli",
  "Dosa": "Dosa",
  "Upma": "Upma",
  "Poha": "Poha",
  "Bread Butter": "Chleb z masłem",
  "Cornflakes with Milk": "Płatki kukurydziane z mlekiem",
  "Chilla (Besan)": "Chilla (z ciecierzycy)",
  "Sprouts Salad": "Sałatka z kiełków",
  "Pancakes": "Naleśniki",
  "Apple": "Jabłko",
  "Milk": "Mleko",
  "Almonds": "Migdały",
  "Smoothie (Fruit)": "Smoothie (owocowe)",
  "Yogurt (Plain)": "Jogurt (naturalny)",
  "Khichdi": "Khichdi",
  "Thepla": "Thepla",
  "Cheela (Moong dal)": "Cheela (Moong dal)",
  "Pav Bhaji": "Pav Bhaji",
  "Sabudana Khichdi": "Sabudana Khichdi",
  "Roti with Sabzi": "Roti z Sabzi",
  "Peanut Butter Bread": "Chleb z masłem orzechowym",
  "Fruit Bowl": "Miska owoców",
  "Vegetable Sandwich": "Kanapka warzywna",
  "Rice Idli with Sambar": "Idli ryżowe z sambarem",
  "Boiled Corn": "Gotowana kukurydza",
  "Paneer Bhurji": "Paneer Bhurji",
  "Protein Shake": "Białkowy shake",
  "Muesli with Milk": "Musli z mlekiem",
  "Chapati with Curd": "Chapati z jogurtem",
  "Porridge (Daliya)": "Kasza (Daliya)",
  "Rava Upma": "Rava Upma",
  "Chickpea Salad": "Sałatka z ciecierzycy",
  "Boiled Sweet Potato": "Gotowany słodki ziemniak",
  "Coconut Water": "Woda kokosowa",
  "Masala Omelette": "Omlet masala",
  "Vegetable Poha": "Poha warzywne",
  "1 egg": "1 jajko",
  "1 bowl": "1 miska",
  "1 medium": "1 średni",
  "1 piece": "1 kawałek",
  "1 cup": "1 kubek",
  "2 slices": "2 kromki",
  "2 small pieces": "2 małe kawałki",
  "10 pieces": "10 kawałków",
  "1 glass": "1 szklanka",
  "2 pavs + bhaji": "2 pavs + bhaji",
  "1 roti + sabzi": "1 roti + sabzi",
  "1 sandwich": "1 kanapka",
  "2 idlis + sambar'": "2 idlis + sambar",
  "1 chapati + ½ cup curd": "1 chapati + ½ filiżanki jogurtu",
  "Rice with Dal": "Ryż z dal",
  "Grilled Chicken": "Grillowany kurczak",
  "Paneer Curry": "Paneer curry",
  "Mixed Vegetable Curry": "Curry z mieszanych warzyw",
  "Chapati with Daal": "Chapati z dal",
  "Fish Curry with Rice": "Curry z rybą z ryżem",
  "Rajma Chawal": "Rajma Chawal",
  "Chole Bhature": "Chole Bhature",
  "Kadhi with Rice": "Kadhi z ryżem",
  "Palak Paneer": "Palak Paneer",
  "Stuffed Paratha": "Paratha nadziewane",
  "Veg Pulao": "Veg Pulao",
  "Biryani with Raita": "Biryani z raitą",
  "Tofu Stir Fry": "Tofu stir fry",
  "Chicken Tikka": "Chicken Tikka",
  "Veg Fried Rice": "Warzywne smażone ryż",
  "Aloo Gobi with Roti": "Aloo Gobi z roti",
  "Baingan Bharta": "Baingan Bharta",
  "Sambar with Rice": "Sambar z ryżem",
  "Chicken Curry with Roti": "Kurczak curry z roti",
  "Bhindi Masala with Roti": "Bhindi masala z roti",
  "Egg Curry with Rice": "Curry z jajkami z ryżem",
  "Lentil Soup with Bread": "Zupa soczewicowa z chlebem",
  "Methi Thepla with Curd": "Methi Thepla z jogurtem",
  "Soybean Curry with Rice": "Curry z soi z ryżem",
  "Cabbage Sabzi with Chapati": "Kapusta Sabzi z chapati",
  "Dal Makhani with Naan": "Dal Makhani z naan",
  "Vegetable Korma with Roti": "Warzywne Korma z roti",
  "Tandoori Roti with Paneer": "Tandoori roti z paneer",
  "Mixed Dal with Rice": "Mixed dal z ryżem",
  "Bottle Gourd Curry with Roti": "Curry z dynią butelkową z roti",
  "Kofta Curry with Roti": "Curry Kofta z roti",
  "Paneer Bhurji with Bread": "Paneer Bhurji z chlebem",
  "Chana Masala with Rice": "Chana masala z ryżem",
  "Curd Rice": "Ryż z jogurtem",
  "Tomato Rice": "Ryż pomidorowy",
  "Vegetable Stew with Appam": "Gulasz warzywny z appam",
  "Dhokla with Green Chutney": "Dhokla z zielonym chutney",
  "Besan Chilla with Salad": "Besan Chilla z sałatką",
  "Lauki Chana Dal": "Lauki Chana Dal",
  "Spinach Corn Curry": "Curry ze szpinakiem i kukurydzą",
  "Tinda Masala with Roti": "Tinda Masala z roti",
  "Masoor Dal with Rice": "Masoor Dal z ryżem",
  "Vegetable Handi with Naan": "Warzywne Handi z naan",
  "Egg Bhurji with Chapati": "Egg Bhurji z chapati",
  "Pumpkin Curry with Rice": "Curry z dynią z ryżem",
  "2 rotis + sabzi": "2 roti + sabzi",
  "1 cup rice + 1 cup dal": "1 kubek ryżu + 1 kubek dal",
  "1 breast": "1 pierś",
  "2 chapatis + dal'": "2 chapati + dal",
  "1 bowl curry + 1 cup rice": "1 miska curry + 1 kubek ryżu",
  "1 bhatura + chole": "1 bhatura + chole",
  "1 paratha": "1 paratha",
  "1 bowl + 2 rotis": "1 miska + 2 roti",
  "1 cup + 1 bowl": "1 kubek + 1 miska",
  "1 bowl + 1 cup rice": "1 miska + 1 kubek ryżu",
  "1 bowl + 1 bread slice": "1 miska + 1 kromka chleba",
  "2 theplas + ½ cup curd": "2 theplas + ½ filiżanki jogurtu",
  "1 bowl + 2 chapatis": "1 miska + 2 chapati",
  "1 bowl + 1 naan": "1 miska + 1 naan",
  "2 rotis + paneer": "2 roti + paneer",
  "1 bowl + 2 slices": "1 miska + 2 kromki",
  "1 bowl + 2 appams": "1 miska + 2 appams",


  "3 pieces": "3 kawałki",
  "2 chillas + salad": "2 chillas + sałatka",
  "Cal": "Kalorie",
  "Cropper": "Cropper",
  "Calorie Tracker": "Tracker kalorii",
  "Add Calorie": "Dodaj kalorię",
  "Quantity": "Ilość",
  "Ask With Open AI": "Zadaj pytanie z Open AI",
  "This picture not available Calorie,Protein,Carbs and Fats,": "To zdjęcie nie zawiera kalorii, białka, węglowodanów i tłuszczów.",
  "Ask Botanist": "Zadaj pytanie botanika",
  "Write your message": "Napisz swoją wiadomość",
  "Confirm Reset": "Potwierdź reset",
  "Are you sure you want to Reset Data?": "Czy na pewno chcesz zresetować konto?",
  "Reset": "Resetuj",
  "You have been Reset Account": "Twoje konto zostało zresetowane",
  "Personal Details": "Dane osobowe",
  "Goal Weight": "Waga docelowa",
  "cm": "cm",
  "Date Of Birth": "Data urodzenia",
  "Gender": "Płeć",
  "Male": "Mężczyzna",
  "Female": "Kobieta",
  "Choose your desired weight?": "Wybierz swoją docelową wagę.",
  "Imperial": "Imperialny",
  "Metric": "Metryczny",
  "Weight": "Waga",
  "lb": "funt",
  "ft": "stopa",
  "in": "cal",
  "Day": "Dzień",
  "January": "Styczeń",
  "February": "Luty",
  "March": "Marzec",
  "April": "Kwiecień",
  "June": "Czerwiec",
  "July": "Lipiec",
  "August": "Sierpień",
  "September": "Wrzesień",
  "October": "Październik",
  "November": "Listopad",
  "December": "Grudzień",
  "Update Your Gender": "Zaktualizuj swoją płeć",
  "Other": "Inne",
  "Adjust Goals": "Dostosuj cele",
  "How many workout do you per week?": "Ile razy w tygodniu ćwiczysz?",
  "This will used to calibrate your custom plan": "To będzie użyte do skalibrowania twojego planu",
  "Workout Now and then": "Ćwicz czasami",
  "A few workout per week": "Kilka treningów w tygodniu",
  "Dedicated athlete": "Zdecydowany sportowiec",
  "What is your goal?": "Jaki jest twój cel?",
  "This helps is generate a plan for your calorie intake.": "To pomoże wygenerować plan spożycia kalorii.",
  "Gain Weight": "Zwiększyć wagę",
  "Lose Weight": "Schudnąć",
  "Update Calorie Goal": "Zaktualizuj cel kaloryczny",
  "Save": "Zapisz",
  "Calorie Goal": "Cel kaloryczny",
  "Update Protein Goal": "Zaktualizuj cel białkowy",
  "Protein goal": "Cel białkowy",
  "Update Carb Goal": "Zaktualizuj cel węglowodanowy",
  "Carb goal": "Cel węglowodanowy",
  "Update Fat Goal": "Zaktualizuj cel tłuszczowy",
  "Auto Generate Goal": "Automatycznie generuj cel",
  "Fruit Salad": "Sałatka owocowa",
  "Roasted Chickpeas": "Prażona ciecierzyca",
  "Mixed Nuts": "Mieszanka orzechów",
  "Yogurt with Honey": "Jogurt z miodem",
  "Apple with Peanut Butter": "Jabłko z masłem orzechowym",
  "Protein Bar": "Baton białkowy",
  "Whole Wheat Crackers": "Krakersy pełnoziarniste",
  "Granola Bar": "Baton granola",
  "Peanut Chikki": "Chikki z orzeszkami ziemnymi",
  "Bhel Puri": "Bhel Puri",
  "Khakra": "Khakra",
  "Masala Makhana": "Masala Makhana",
  "Hummus with Veggies": "Hummus z warzywami",
  "Paneer Cubes": "Kostki paneer",
  "Milkshake (Low Sugar)": "Mleczny koktajl (niska zawartość cukru)",
  "Dhokla": "Dhokla",
  "Vegetable Soup": "Zupa warzywna",
  "Idli with Chutney": "Idli z chutney",
  "Cheese Slice": "Plasterek sera",
  "Chana Chaat": "Chana Chaat",
  "Moong Dal Chilla": "Moong Dal Chilla",
  "Rice Cake with Peanut Butter": "Ciastko ryżowe z masłem orzechowym",
  "Popcorn (Air-popped)": "Popcorn (powietrznie poppopcorn)",
  "Avocado Toast": "Tost z awokado",
  "Stuffed Dates": "Faszerowane daktyle",
  "Oats Cookies": "Ciasteczka owsiane",
  "Fruit Smoothie": "Owocowy koktajl",
  "Carrot Sticks with Hummus": "Marchewkowe paski z hummusem",
  "Soy Nuts": "Orzechy sojowe",
  "Trail Mix": "Mieszanka trailowa",
  "Besan Ladoo": "Besan Ladoo",
  "Upma (small portion)": "Upma (mała porcja)",
  "Egg Roll (Mini)": "Mini jajeczne rolki",
  "Rice Idli": "Rice Idli",
  "Cucumber Sandwich": "Kanapka z ogórkiem",
  "Fruit Chaat": "Owocowa Chaat",
  "Lassi (Sweet)": "Lassi (słodka)",
  "Cold Coffee (Low Sugar)": "Kawa mrożona (niska zawartość cukru)",
  "Rava Dhokla": "Rava Dhokla",
  "Vegetable Cutlet": "Kotlet warzywny",
  "Chikki with Jaggery": "Chikki z jaggery",
  "Milk (Low Fat)": "Mleko (niskotłuszczowe)",
  "Baked Samosa": "Pieczenie samosy",
  "Vegetable Wrap": "Wrap warzywny",
  "Roasted Soybeans": "Prażona soja",
  "1/2 cup": "1/2 filiżanki",
  "1 handful": "1 garść",
  "1 apple + 1 tbsp PB": "1 jabłko + 1 łyżka PB",
  "1 bar": "1 batonik",
  "5 pieces": "5 kawałków",
  "½ cup hummus + veggies": "½ filiżanki hummusu + warzywa",
  "50g": "50g",
  "1 idli + chutney": "1 idli + chutney",
  "1 slice": "1 plasterek",
  "1 chilla": "1 chilla",
  "1 cake + 1 tbsp PB": "1 ciastko + 1 łyżka PB",
  "2 cups": "2 filiżanki",
  "1 toast": "1 tost",
  "3 dates": "3 daktyle",
  "2 cookies": "2 ciasteczka",
  "½ cup": "½ filiżanki",
  "1 small bowl": "1 mała miska",
  "1 roll": "1 rolka",
  "1 wrap": "1 wrap",
  "Chapati with Sabzi": "Chapati z Sabzi",
  "Grilled Fish": "Grillowana ryba",
  "Moong Dal Khichdi": "Moong Dal Khichdi",
  "Paneer Bhurji with Roti": "Paneer Bhurji z Roti",
  "Brown Rice with Veg Curry": "Brązowy ryż z curry warzywnym",
  "Quinoa with Stir Fry Veggies": "Quinoa z warzywami smażonymi",
  "Grilled Tofu with Salad": "Grillowany tofu z sałatą",
  "Vegetable Pulao": "Warzywne Pulao",
  "Palak Paneer with Chapati": "Palak Paneer z Chapati",
  "Mixed Vegetable Soup": "Zupa warzywna mieszana",
  "Stuffed Paratha with Curd": "Paratha faszerowana z jogurtem",
  "Oats Khichdi": "Khichdi z owsem",
  "Roti with Bhindi": "Roti z Bhindi",
  "Dal Tadka with Jeera Rice": "Dal Tadka z ryżem Jeera",
  "Vegetable Handvo": "Warzywny Handvo",
  "Kadhi with Bajra Roti": "Kadhi z Bajra Roti",
  "Tofu Curry with Quinoa": "Tofu Curry z Quinoa",
  "Bhakri with Thecha": "Bhakri z Thecha",
  "Biryani (Veg)": "Biryani (wegetariańska)",
  "Rajma with Brown Rice": "Rajma z brązowym ryżem",
  "Daliya (Broken Wheat Porridge)": "Daliya (kasza z pszenicy)",
  "Pumpkin Sabzi with Chapati": "Sabzi z dynią i chapati",
  "Cauliflower Stir Fry": "Smażony kalafior",
  "Boiled Egg Salad": "Sałatka z gotowanym jajkiem",
  "Tomato Rasam with Rice": "Rasam pomidorowy z ryżem",
  "Sweet Potato with Curd": "Bataty z jogurtem",
  "Stuffed Capsicum": "Papryka nadziewana",
  "Paneer Tikka with Mint Chutney": "Paneer Tikka z miętowym chutney",
  "Rice with Sambar": "Ryż z sambarem",
  "Vegetable Thepla with Dahi": "Warzywne thepla z dahi",
  "Grilled Mushroom Skewers": "Grillowane szaszłyki z grzybami",
  "Beetroot Sabzi with Roti": "Sabzi z burakami z roti",
  "Spinach Dal with Rice": "Dal szpinakowy z ryżem",
  "Lentil Soup with Toast": "Zupa z soczewicy z tostami",
  "Tinda Curry with Chapati": "Curry z tindą z chapati",
  "Egg Bhurji with Roti": "Jajka bhurji z roti",
  "Karela Sabzi with Roti": "Sabzi z kareli z roti",
  "Zucchini Stir Fry": "Tumis z cukinią",
  "Low Carb Paneer Bowl": "Miska paneer o niskiej zawartości węglowodanów",
  "Stuffed Tomato": "Pomidor nadziewany",
  "Vegetable Rava Upma": "Warzywne upma z ravy",
  "2 chapatis + sabzi": "2 chapati + sabzi",
  "1 fillet": "1 filet",
  "1 bowl + 1 roti": "1 miska + 1 roti",
  "1 plate": "1 talerz",
  "1 cup rice + dal": "1 filiżanka ryżu + dal",
  "1 paratha + ½ cup curd": "1 paratha + ½ filiżanki jogurtu",
  "2 rotis + bhindi": "2 roti + bhindi",
  "1 roti + 1 bowl kadhi": "1 roti + 1 miska kadhi",
  "1 bhakri + chutney": "1 bhakri + chutney",
  "1 bowl curry + 1 roti": "1 miska curry + 1 roti",
  "2 chillas": "2 chillas",
  "1 bowl + ½ cup curd": "1 miska + ½ filiżanki jogurtu",
  "1 serving": "1 porcja",
  "1 cup rice + sambar": "1 filiżanka ryżu + sambar",
  "1 thepla + curd": "1 thepla + jogurt",
  "1 skewer": "1 szaszłyk",
  "1 bowl + 1 toast": "1 miska + 1 tost",
  "1 bowl + 1 appam": "1 miska + 1 appam",
  "1 tomato": "1 pomidor",
  "Restore": "Przywróć",
  "Get Premium": "Zdobądź Premium",
  "Get All The New Exciting Features": "Uzyskaj wszystkie nowe ekscytujące funkcje",
  "Unlock Food Scanner": "Odblokuj skaner jedzenia",
  "Unlock Food Calorie": "Odblokuj kalorie jedzenia",
  "Unlock Unlimited Chat with Ai": "Odblokuj nieograniczony czat z AI",
  "Unlimited Food Scanner To Calorie": "Nieograniczony skaner jedzenia do kalorii",
  "Most Popular": "Najpopularniejsze",
  "Subscription": "Subskrypcja",
  "BUY NOW": "KUP TERAZ",
  "Terms of Condition": "Warunki",
  "Welcome": "Witamy",
  "Calorie tracking made easy": "Śledzenie kalorii stało się łatwe",
  "Just snap a quick photo of your meal and we''ll do the rest": "Zrób szybkie zdjęcie swojego posiłku, a resztę zrobimy my",
  "In-depth nutrition analyses": "Szczegółowe analizy żywieniowe",
  "We will keep your informed about your food choicer and their nutritional content": "Będziemy cię informować o wyborach żywieniowych i ich zawartości odżywczej",
  "Transform your body": "Przekształć swoje ciało",
  "Today is best time to start working toward your dream body": "Dziś jest najlepszy czas, aby zacząć dążyć do wymarzonego ciała",
  "Where were you born?": "Gdzie się urodziłeś?",
  "This Will be used to calibrate your custom plan": "To zostanie użyte do kalibracji twojego planu",
  "What's stopping you from reaching your goals?": "Co powstrzymuje cię przed osiągnięciem celów?",
  "Lack of consistency": "Brak konsekwencji",
  "Unhealthy eating habits": "Niezdrowe nawyki żywieniowe",
  "Lack of supports": "Brak wsparcia",
  "Busy schedule": "Zajęty harmonogram",
  "Lack of meal inspiration": "Brak inspiracji do posiłków",
  "We're setting": "Ustawiamy",
  "everything up for you": "wszystko dla ciebie",
  "Customizing health plan....": "Dostosowywanie planu zdrowotnego...."
}
;
