const Map<String, String> portugal = {
  "Home": "Início",
  "Calorie": "Caloria",
  "Analytics": "Análises",
  "Setting": "Configurações",
  "Track Food": "Rastrear Alimento",
  "Consumed": "Consumido",
  "Remaining": "Restante",
  "Protein": "Proteína",
  "Carbs": "Carboidratos",
  "Fats": "Gorduras",
  "History": "Histórico",
  "View All": "Ver Todos",
  "BreakFast": "Café da manhã",
  "Lunch": "Almoço",
  "snack(s)": "Lanche",
  "Dinner": "Jantar",
  "Which meal would you like to track?": "Qual refeição você gostaria de rastrear?",
  "Snap Tips": "Dicas de Foto",
  "Too close": "Muito perto",
  "Too far": "Muito longe",
  "Multi-species": "Multi-específicos",
  "Continue": "Continuar",
  "OverView": "Visão geral",
  "Weight Goal": "Meta de peso",
  "Update": "Atualizar",
  "Current Weight": "Peso atual",
  "kg": "kg",
  "Try to update once a week so we can adjust your plan to ensure you hit your goal": "Tente atualizar uma vez por semana para que possamos ajustar seu plano para garantir que você alcance seu objetivo",
  "Update Weight": "Atualizar peso",
  "Week": "Semana",
  "Month": "Mês",
  "Year": "Ano",
  "Update Weight Goal": "Atualizar meta de peso",
  "Enter new weight (kg)": "Digite o novo peso (kg)",
  "Cancel": "Cancelar",
  "Calorie Your Week :": "Calorias da sua semana:",
  "Sun": "Dom",
  "Mon": "Seg",
  "Tue": "Ter",
  "Wed": "Qua",
  "Thu": "Qui",
  "Fri": "Sex",
  "Sat": "Sáb",
  "Average Calorie Month :": "Média de Calorias Mensal:",
  "Average Calorie Yearly :": "Média de Calorias Anual:",
  "Jan": "Jan",
  "Feb": "Fev",
  "Mar": "Mar",
  "Apr": "Abr",
  "May": "Mai",
  "Jun": "Jun",
  "Jul": "Jul",
  "Aug": "Ago",
  "Sep": "Set",
  "Oct": "Out",
  "Nov": "Nov",
  "Dec": "Dez",
  "Age": "Idade",
  "Height": "Altura",
  "Customization": "Personalização",
  "Dark Mode": "Modo Escuro",
  "Language": "Idioma",
  "Personal details": "Detalhes pessoais",
  "Adjust goals": "Ajustar metas",
  "Calories,carbs,fat and protein": "Calorias, carboidratos, gorduras e proteínas",
  "Chat history": "Histórico de chat",
  "Legal": "Legal",
  "Terms and Condition": "Termos e Condições",
  "Privacy Policy": "Política de Privacidade",
  "Reset Data?": "Redefinir conta?",
  "VERSION": "VERSÃO",
  "History not found": "Histórico não encontrado",
  "Delete Item": "Excluir item",
  "Are you sure you want to delete this item?": "Tem certeza de que deseja excluir este item?",
  "Delete": "Excluir",
  "Search by Food Name/Dish": "Buscar por nome do alimento/prato",
  "🎯 Calorie Goal Reached": "🎯 Meta de Calorias atingida",
  "You've completed your calorie goal for today. Would you like to add more?": "Você atingiu sua meta de calorias para hoje. Gostaria de adicionar mais?",
  "Done": "Feito",
  "Add More Calories": "Adicionar mais calorias",
  "Boiled Egg": "Ovo cozido",
  "Oatmeal": "Aveia",
  "Banana": "Banana",
  "Paratha": "Paratha",
  "Idli": "Idli",
  "Dosa": "Dosa",
  "Upma": "Upma",
  "Poha": "Poha",
  "Bread Butter": "Pão com manteiga",
  "Cornflakes with Milk": "Cornflakes com leite",
  "Chilla (Besan)": "Chilla (Farinha de grão de bico)",
  "Sprouts Salad": "Salada de brotos",
  "Pancakes": "Panquecas",
  "Apple": "Maçã",
  "Milk": "Leite",
  "Almonds": "Amêndoas",
  "Smoothie (Fruit)": "Smoothie (Frutas)",
  "Yogurt (Plain)": "Iogurte (Natural)",
  "Khichdi": "Khichdi",
  "Thepla": "Thepla",
  "Cheela (Moong dal)": "Cheela (Moong dal)",
  "Pav Bhaji": "Pav Bhaji",
  "Sabudana Khichdi": "Sabudana Khichdi",
  "Roti with Sabzi": "Roti com Sabzi",
  "Peanut Butter Bread": "Pão com manteiga de amendoim",
  "Fruit Bowl": "Tigela de frutas",
  "Vegetable Sandwich": "Sanduíche de vegetais",
  "Rice Idli with Sambar": "Idli de arroz com Sambar",
  "Boiled Corn": "Milho cozido",
  "Paneer Bhurji": "Paneer Bhurji",
  "Protein Shake": "Shake de proteína",
  "Muesli with Milk": "Muesli com leite",
  "Chapati with Curd": "Chapati com iogurte",
  "Porridge (Daliya)": "Pap (Daliya)",
  "Rava Upma": "Rava Upma",
  "Chickpea Salad": "Salada de grão-de-bico",
  "Boiled Sweet Potato": "Batata doce cozida",
  "Coconut Water": "Água de coco",
  "Masala Omelette": "Omelete masala",
  "Vegetable Poha": "Poha de vegetais",
  "1 egg": "1 ovo",
  "1 bowl": "1 tigela",
  "1 medium": "1 médio",
  "1 piece": "1 peça",
  "1 cup": "1 xícara",
  "2 slices": "2 fatias",
  "2 small pieces": "2 pequenos pedaços",
  "10 pieces": "10 peças",
  "1 glass": "1 copo",
  "2 pavs + bhaji": "2 pavs + bhaji",
  "1 roti + sabzi": "1 roti + sabzi",
  "1 sandwich": "1 sanduíche",
  "2 idlis + sambar'": "2 idlis + sambar",
  "1 chapati + ½ cup curd": "1 chapati + ½ xícara de iogurte",
  "Rice with Dal": "Arroz com Dal",
  "Grilled Chicken": "Frango grelhado",
  "Paneer Curry": "Curry de Paneer",
  "Mixed Vegetable Curry": "Curry de vegetais mistos",
  "Chapati with Daal": "Chapati com Daal",
  "Fish Curry with Rice": "Curry de peixe com arroz",
  "Rajma Chawal": "Rajma Chawal",
  "Chole Bhature": "Chole Bhature",
  "Kadhi with Rice": "Kadhi com arroz",
  "Palak Paneer": "Palak Paneer",
  "Stuffed Paratha": "Paratha recheado",
  "Veg Pulao": "Veg Pulao",
  "Biryani with Raita": "Biryani com Raita",
  "Tofu Stir Fry": "Tofu stir fry",
  "Chicken Tikka": "Chicken Tikka",
  "Veg Fried Rice": "Arroz frito de vegetais",
  "Aloo Gobi with Roti": "Aloo Gobi com Roti",
  "Baingan Bharta": "Baingan Bharta",
  "Sambar with Rice": "Sambar com arroz",
  "Chicken Curry with Roti": "Curry de frango com Roti",
  "Bhindi Masala with Roti": "Bhindi masala com Roti",
  "Egg Curry with Rice": "Curry de ovo com arroz",
  "Lentil Soup with Bread": "Sopa de lentilhas com pão",
  "Methi Thepla with Curd": "Methi Thepla com iogurte",
  "Soybean Curry with Rice": "Curry de soja com arroz",
  "Cabbage Sabzi with Chapati": "Sabzi de repolho com Chapati",
  "Dal Makhani with Naan": "Dal Makhani com Naan",
  "Vegetable Korma with Roti": "Vegetable Korma com Roti",
  "Tandoori Roti with Paneer": "Tandoori Roti com Paneer",
  "Mixed Dal with Rice": "Mixed Dal com arroz",
  "Bottle Gourd Curry with Roti": "Curry de abóbora com Roti",
  "Kofta Curry with Roti": "Curry de Kofta com Roti",
  "Paneer Bhurji with Bread": "Paneer Bhurji com pão",
  "Chana Masala with Rice": "Chana Masala com arroz",
  "Curd Rice": "Arroz com iogurte",
  "Tomato Rice": "Arroz de tomate",
  "Vegetable Stew with Appam": "Ensopado de vegetais com Appam",
  "Dhokla with Green Chutney": "Dhokla com chutney verde",
  "Besan Chilla with Salad": "Besan Chilla com salada",
  "Lauki Chana Dal": "Lauki Chana Dal",
  "Spinach Corn Curry": "Curry de espinafre e milho",
  "Tinda Masala with Roti": "Tinda Masala com Roti",
  "Masoor Dal with Rice": "Masoor Dal com arroz",
  "Vegetable Handi with Naan": "Handi de vegetais com Naan",
  "Egg Bhurji with Chapati": "Egg Bhurji com Chapati",
  "Pumpkin Curry with Rice": "Curry de abóbora com arroz",
  "2 rotis + sabzi": "2 rotis + sabzi",
  "1 cup rice + 1 cup dal": "1 xícara de arroz + 1 xícara de dal",
  "1 breast": "1 peito",
  "2 chapatis + dal'": "2 chapatis + dal",
  "1 bowl curry + 1 cup rice": "1 tigela de curry + 1 xícara de arroz",
  "1 bhatura + chole": "1 bhatura + chole",
  "1 paratha": "1 paratha",
  "1 bowl + 2 rotis": "1 tigela + 2 rotis",
  "1 cup + 1 bowl": "1 xícara + 1 tigela",
  "1 bowl + 1 cup rice": "1 tigela + 1 xícara de arroz",
  "1 bowl + 1 bread slice": "1 tigela + 1 fatia de pão",
  "2 theplas + ½ cup curd": "2 theplas + ½ xícara de iogurte",
  "1 bowl + 2 chapatis": "1 tigela + 2 chapatis",
  "1 bowl + 1 naan": "1 tigela + 1 naan",
  "2 rotis + paneer": "2 rotis + paneer",
  "1 bowl + 2 slices": "1 tigela + 2 fatias",
  "1 bowl + 2 appams": "1 tigela + 2 appams",


  "3 pieces": "3 peças",
  "2 chillas + salad": "2 chillas + salada",
  "Cal": "Calorias",
  "Cropper": "Cropper",
  "Calorie Tracker": "Rastreador de Calorias",
  "Add Calorie": "Adicionar Caloria",
  "Quantity": "Quantidade",
  "Ask With Open AI": "Perguntar com Open AI",
  "This picture not available Calorie,Protein,Carbs and Fats,": "Esta imagem não está disponível Calorias, Proteínas, Carboidratos e Gorduras.",
  "Ask Botanist": "Perguntar ao Botânico",
  "Write your message": "Escreva sua mensagem",
  "Confirm Reset": "Confirmar Reset",
  "Are you sure you want to Reset Data?": "Tem certeza de que deseja redefinir a conta?",
  "Reset": "Redefinir",
  "You have been Reset Account": "Sua conta foi redefinida",
  "Personal Details": "Detalhes Pessoais",
  "Goal Weight": "Peso de Meta",
  "cm": "cm",
  "Date Of Birth": "Data de Nascimento",
  "Gender": "Gênero",
  "Male": "Masculino",
  "Female": "Feminino",
  "Choose your desired weight?": "Escolha seu peso desejado?",
  "Imperial": "Imperial",
  "Metric": "Métrico",
  "Weight": "Peso",
  "lb": "lb",
  "ft": "ft",
  "in": "in",
  "Day": "Dia",
  "January": "Janeiro",
  "February": "Fevereiro",
  "March": "Março",
  "April": "Abril",
  "June": "Junho",
  "July": "Julho",
  "August": "Agosto",
  "September": "Setembro",
  "October": "Outubro",
  "November": "Novembro",
  "December": "Dezembro",
  "Update Your Gender": "Atualizar seu Gênero",
  "Other": "Outro",
  "Adjust Goals": "Ajustar Metas",
  "How many workout do you per week?": "Quantos treinos você faz por semana?",
  "This will used to calibrate your custom plan": "Isso será usado para calibrar seu plano personalizado",
  "Workout Now and then": "Treino de vez em quando",
  "A few workout per week": "Alguns treinos por semana",
  "Dedicated athlete": "Atleta dedicado",
  "What is your goal?": "Qual é o seu objetivo?",
  "This helps is generate a plan for your calorie intake.": "Isso ajuda a gerar um plano para o seu consumo de calorias.",
  "Gain Weight": "Ganhar Peso",
  "Lose Weight": "Perder Peso",
  "Update Calorie Goal": "Atualizar Meta de Calorias",
  "Save": "Salvar",
  "Calorie Goal": "Meta de Calorias",
  "Update Protein Goal": "Atualizar Meta de Proteínas",
  "Protein goal": "Meta de Proteínas",
  "Update Carb Goal": "Atualizar Meta de Carboidratos",
  "Carb goal": "Meta de Carboidratos",
  "Update Fat Goal": "Atualizar Meta de Gorduras",
  "Auto Generate Goal": "Gerar Meta Automaticamente",
  "Fruit Salad": "Salada de Frutas",
  "Roasted Chickpeas": "Grão de bico torrado",
  "Mixed Nuts": "Castanhas Mistas",
  "Yogurt with Honey": "Iogurte com Mel",
  "Apple with Peanut Butter": "Maçã com Manteiga de Amendoim",
  "Protein Bar": "Barra de Proteína",
  "Whole Wheat Crackers": "Biscoitos integrais",
  "Granola Bar": "Barra de Granola",
  "Peanut Chikki": "Chikki de Amendoim",
  "Bhel Puri": "Bhel Puri",
  "Khakra": "Khakra",
  "Masala Makhana": "Masala Makhana",
  "Hummus with Veggies": "Hummus com Legumes",
  "Paneer Cubes": "Cubos de Paneer",
  "Milkshake (Low Sugar)": "Milkshake (Baixo em Açúcar)",
  "Dhokla": "Dhokla",
  "Vegetable Soup": "Sopa de Legumes",
  "Idli with Chutney": "Idli com Chutney",
  "Cheese Slice": "Fatias de Queijo",
  "Chana Chaat": "Chana Chaat",
  "Moong Dal Chilla": "Moong Dal Chilla",
  "Rice Cake with Peanut Butter": "Bolo de Arroz com Manteiga de Amendoim",
  "Popcorn (Air-popped)": "Pipoca (Feita no Ar)",
  "Avocado Toast": "Torrada de Abacate",
  "Stuffed Dates": "Tâmaras Recheadas",
  "Oats Cookies": "Biscoitos de Aveia",
  "Fruit Smoothie": "Smoothie de Frutas",
  "Carrot Sticks with Hummus": "Palitos de Cenoura com Hummus",
  "Soy Nuts": "Nozes de Soja",
  "Trail Mix": "Mistura de Trilha",
  "Besan Ladoo": "Besan Ladoo",
  "Upma (small portion)": "Upma (porção pequena)",
  "Egg Roll (Mini)": "Rolo de Ovos (Mini)",
  "Rice Idli": "Idli de Arroz",
  "Cucumber Sandwich": "Sanduíche de Pepino",
  "Fruit Chaat": "Chaat de Frutas",
  "Lassi (Sweet)": "Lassi (Doce)",
  "Cold Coffee (Low Sugar)": "Café Gelado (Baixo em Açúcar)",
  "Rava Dhokla": "Rava Dhokla",
  "Vegetable Cutlet": "Corte de Legumes",
  "Chikki with Jaggery": "Chikki com Jaggery",
  "Milk (Low Fat)": "Leite (Baixo Teor de Gordura)",
  "Baked Samosa": "Samosa Assada",
  "Vegetable Wrap": "Wrap de Legumes",
  "Roasted Soybeans": "Soja Torrada",
  "1/2 cup": "1/2 xícara",
  "1 handful": "1 punhado",
  "1 apple + 1 tbsp PB": "1 maçã + 1 colher de sopa de PB",
  "1 bar": "1 barra",
  "5 pieces": "5 peças",
  "½ cup hummus + veggies": "½ xícara de hummus + legumes",
  "50g": "50g",
  "1 idli + chutney": "1 idli + chutney",
  "1 slice": "1 fatia",
  "1 chilla": "1 chilla",
  "1 cake + 1 tbsp PB": "1 bolo + 1 colher de sopa de PB",
  "2 cups": "2 xícaras",
  "1 toast": "1 torrada",
  "3 dates": "3 tâmaras",
  "2 cookies": "2 biscoitos",
  "½ cup": "½ xícara",
  "1 small bowl": "1 tigela pequena",
  "1 roll": "1 rolo",
  "1 wrap": "1 wrap",
  "Chapati with Sabzi": "Chapati com Sabzi",
  "Grilled Fish": "Peixe Grelhado",
  "Moong Dal Khichdi": "Moong Dal Khichdi",
  "Paneer Bhurji with Roti": "Paneer Bhurji com Roti",
  "Brown Rice with Veg Curry": "Arroz Integral com Curry de Legumes",
  "Quinoa with Stir Fry Veggies": "Quinoa com Legumes Refogados",
  "Grilled Tofu with Salad": "Tofu Grelhado com Salada",
  "Vegetable Pulao": "Pulao de Legumes",
  "Palak Paneer with Chapati": "Palak Paneer com Chapati",
  "Mixed Vegetable Soup": "Sopa de Legumes Mistos",
  "Stuffed Paratha with Curd": "Paratha Recheada com Coalhada",
  "Oats Khichdi": "Khichdi de Aveia",
  "Roti with Bhindi": "Roti com Bhindi",
  "Dal Tadka with Jeera Rice": "Dal Tadka com Arroz Jeera",
  "Vegetable Handvo": "Handvo de Legumes",
  "Kadhi with Bajra Roti": "Kadhi com Bajra Roti",
  "Tofu Curry with Quinoa": "Curry de Tofu com Quinoa",
  "Bhakri with Thecha": "Bhakri com Thecha",
  "Biryani (Veg)": "Biryani (Vegetariano)",
  "Rajma with Brown Rice": "Rajma com Arroz Integral",
  "Daliya (Broken Wheat Porridge)": "Daliya (Cozido de Trigo)",
  "Pumpkin Sabzi with Chapati": "Sabzi de Abóbora com Chapati",
  "Cauliflower Stir Fry": "Couve-flor Salteada",
  "Boiled Egg Salad": "Salada de Ovo Cozido",
  "Tomato Rasam with Rice": "Rasam de tomate com arroz",
  "Sweet Potato with Curd": "Batata doce com iogurte",
  "Stuffed Capsicum": "Pimentão recheado",
  "Paneer Tikka with Mint Chutney": "Paneer Tikka com chutney de hortelã",
  "Rice with Sambar": "Arroz com Sambar",
  "Vegetable Thepla with Dahi": "Thepla de legumes com dahi",
  "Grilled Mushroom Skewers": "Espetinhos de cogumelos grelhados",
  "Beetroot Sabzi with Roti": "Sabzi de beterraba com roti",
  "Spinach Dal with Rice": "Dal de espinafre com arroz",
  "Lentil Soup with Toast": "Sopa de lentilhas com torradas",
  "Tinda Curry with Chapati": "Curry de Tinda com chapati",
  "Egg Bhurji with Roti": "Egg Bhurji com roti",
  "Karela Sabzi with Roti": "Sabzi de Karela com roti",
  "Zucchini Stir Fry": "Refogado de abobrinha",
  "Low Carb Paneer Bowl": "Bowl de Paneer com baixo carboidrato",
  "Stuffed Tomato": "Tomate recheado",
  "Vegetable Rava Upma": "Upma de rava com legumes",
  "2 chapatis + sabzi": "2 chapatis + sabzi",
  "1 fillet": "1 filé",
  "1 bowl + 1 roti": "1 tigela + 1 roti",
  "1 plate": "1 prato",
  "1 cup rice + dal": "1 xícara de arroz + dal",
  "1 paratha + ½ cup curd": "1 paratha + ½ xícara de iogurte",
  "2 rotis + bhindi": "2 rotis + bhindi",
  "1 roti + 1 bowl kadhi": "1 roti + 1 tigela de kadhi",
  "1 bhakri + chutney": "1 bhakri + chutney",
  "1 bowl curry + 1 roti": "1 tigela de curry + 1 roti",
  "2 chillas": "2 chillas",
  "1 bowl + ½ cup curd": "1 tigela + ½ xícara de iogurte",
  "1 serving": "1 porção",
  "1 cup rice + sambar": "1 xícara de arroz + sambar",
  "1 thepla + curd": "1 thepla + iogurte",
  "1 skewer": "1 espetinho",
  "1 bowl + 1 toast": "1 tigela + 1 torrada",
  "1 bowl + 1 appam": "1 tigela + 1 appam",
  "1 tomato": "1 tomate",
  "Restore": "Restaurar",
  "Get Premium": "Obtenha Premium",
  "Get All The New Exciting Features": "Obtenha todos os novos recursos emocionantes",
  "Unlock Food Scanner": "Desbloquear scanner de alimentos",
  "Unlock Food Calorie": "Desbloquear calorias dos alimentos",
  "Unlock Unlimited Chat with Ai": "Desbloquear chat ilimitado com a IA",
  "Unlimited Food Scanner To Calorie": "Scanner de alimentos ilimitado para calorias",
  "Most Popular": "Mais Popular",
  "Subscription": "Assinatura",
  "BUY NOW": "COMPRE AGORA",
  "Terms of Condition": "Termos e Condições",
  "Welcome": "Bem-vindo",
  "Calorie tracking made easy": "Rastreamento de calorias facilitado",
  "Just snap a quick photo of your meal and we''ll do the rest": "Tire uma foto rápida da sua refeição e faremos o resto",
  "In-depth nutrition analyses": "Análises nutricionais detalhadas",
  "We will keep your informed about your food choicer and their nutritional content": "Nós o manteremos informado sobre suas escolhas alimentares e seu conteúdo nutricional",
  "Transform your body": "Transforme seu corpo",
  "Today is best time to start working toward your dream body": "Hoje é o melhor momento para começar a trabalhar no corpo dos seus sonhos",
  "Where were you born?": "Onde você nasceu?",
  "This Will be used to calibrate your custom plan": "Isso será usado para calibrar seu plano personalizado",
  "What's stopping you from reaching your goals?": "O que está impedindo você de alcançar seus objetivos?",
  "Lack of consistency": "Falta de consistência",
  "Unhealthy eating habits": "Hábitos alimentares não saudáveis",
  "Lack of supports": "Falta de apoio",
  "Busy schedule": "Agenda cheia",
  "Lack of meal inspiration": "Falta de inspiração para refeições",
  "We're setting": "Estamos configurando",
  "everything up for you": "tudo para você",
  "Customizing health plan....": "Personalizando o plano de saúde...."
};
