const Map<String, String> russian = {
  "Home": "Главная",
  "Calorie": "Калория",
  "Analytics": "Аналитика",
  "Setting": "Настройки",
  "Track Food": "Отслеживание пищи",
  "Consumed": "Потреблено",
  "Remaining": "Осталось",
  "Protein": "Белки",
  "Carbs": "Углеводы",
  "Fats": "Жиры",
  "History": "История",
  "View All": "Просмотр всех",
  "BreakFast": "Завтрак",
  "Lunch": "Ужин",
  "snack(s)": "Перекус",
  "Dinner": "Ужин",
  "Which meal would you like to track?": "Какую еду вы хотите отслеживать?",
  "Snap Tips": "Советы по фотографии",
  "Too close": "Слишком близко",
  "Too far": "Слишком далеко",
  "Multi-species": "Множество ингредиентов",
  "Continue": "Продолжить",
  "OverView": "Обзор",
  "Weight Goal": "Цель по весу",
  "Update": "Обновить",
  "Current Weight": "Текущий вес",
  "kg": "кг",
  "Try to update once a week so we can adjust your plan to ensure you hit your goal": "Попробуйте обновлять данные раз в неделю, чтобы мы могли скорректировать ваш план и помочь достичь цели",
  "Update Weight": "Обновить вес",
  "Week": "Неделя",
  "Month": "Месяц",
  "Year": "Год",
  "Update Weight Goal": "Обновить цель по весу",
  "Enter new weight (kg)": "Введите новый вес (кг)",
  "Cancel": "Отменить",
  "Calorie Your Week :": "Ваши калории на этой неделе:",
  "Sun": "Вс",
  "Mon": "Пн",
  "Tue": "Вт",
  "Wed": "Ср",
  "Thu": "Чт",
  "Fri": "Пт",
  "Sat": "Сб",
  "Average Calorie Month :": "Среднее количество калорий за месяц:",
  "Average Calorie Yearly :": "Среднее количество калорий за год:",
  "Jan": "Янв",
  "Feb": "Фев",
  "Mar": "Мар",
  "Apr": "Апр",
  "May": "Май",
  "Jun": "Июн",
  "Jul": "Июл",
  "Aug": "Авг",
  "Sep": "Сен",
  "Oct": "Окт",
  "Nov": "Ноя",
  "Dec": "Дек",
  "Age": "Возраст",
  "Height": "Рост",
  "Customization": "Настройка",
  "Dark Mode": "Тёмная тема",
  "Language": "Язык",
  "Personal details": "Личные данные",
  "Adjust goals": "Настроить цели",
  "Calories,carbs,fat and protein": "Калории, углеводы, жиры и белки",
  "Chat history": "История чатов",
  "Legal": "Юридическая информация",
  "Terms and Condition": "Условия использования",
  "Privacy Policy": "Политика конфиденциальности",
  "Reset Data?": "Сбросить аккаунт?",
  "VERSION": "ВЕРСИЯ",
  "History not found": "История не найдена",
  "Delete Item": "Удалить элемент",
  "Are you sure you want to delete this item?": "Вы уверены, что хотите удалить этот элемент?",
  "Delete": "Удалить",
  "Search by Food Name/Dish": "Поиск по названию еды/блюда",
  "🎯 Calorie Goal Reached": "🎯 Цель по калориям достигнута",
  "You've completed your calorie goal for today. Would you like to add more?": "Вы достигли своей цели по калориям на сегодня. Хотите добавить еще?",
  "Done": "Готово",
  "Add More Calories": "Добавить калории",
  "Boiled Egg": "Варёное яйцо",
  "Oatmeal": "Овсянка",
  "Banana": "Банан",
  "Paratha": "Парата",
  "Idli": "Идли",
  "Dosa": "Доса",
  "Upma": "Упма",
  "Poha": "Поха",
  "Bread Butter": "Хлеб с маслом",
  "Cornflakes with Milk": "Кукурузные хлопья с молоком",
  "Chilla (Besan)": "Чила (из муки из нута)",
  "Sprouts Salad": "Салат из проростков",
  "Pancakes": "Блинчики",
  "Apple": "Яблоко",
  "Milk": "Молоко",
  "Almonds": "Миндали",
  "Smoothie (Fruit)": "Смузи (фрукты)",
  "Yogurt (Plain)": "Йогурт (простой)",
  "Khichdi": "Кхичди",
  "Thepla": "Тепла",
  "Cheela (Moong dal)": "Чила (Мунг дал)",
  "Pav Bhaji": "Пав Бхаджи",
  "Sabudana Khichdi": "Сабудана Хичди",
  "Roti with Sabzi": "Роти с сабзи",
  "Peanut Butter Bread": "Хлеб с арахисовым маслом",
  "Fruit Bowl": "Чаша с фруктами",
  "Vegetable Sandwich": "Овощной сэндвич",
  "Rice Idli with Sambar": "Идли из риса с самбаром",
  "Boiled Corn": "Вареная кукуруза",
  "Paneer Bhurji": "Панир Бхурджи",
  "Protein Shake": "Протеиновый коктейль",
  "Muesli with Milk": "Мюсли с молоком",
  "Chapati with Curd": "Чапати с йогуртом",
  "Porridge (Daliya)": "Каша (Далия)",
  "Rava Upma": "Рава Упма",
  "Chickpea Salad": "Салат из нута",
  "Boiled Sweet Potato": "Вареный сладкий картофель",
  "Coconut Water": "Кокосовая вода",
  "Masala Omelette": "Омлет масала",
  "Vegetable Poha": "Поа с овощами",
  "1 egg": "1 яйцо",
  "1 bowl": "1 чаша",
  "1 medium": "1 средний",
  "1 piece": "1 кусок",
  "1 cup": "1 чашка",
  "2 slices": "2 ломтика",
  "2 small pieces": "2 маленьких кусочка",
  "10 pieces": "10 кусочков",
  "1 glass": "1 стакан",
  "2 pavs + bhaji": "2 павс + бхаджи",
  "1 roti + sabzi": "1 роти + сабзи",
  "1 sandwich": "1 сэндвич",
  "2 idlis + sambar'": "2 идли + самбар",
  "1 chapati + ½ cup curd": "1 чапати + ½ чашки йогурта",
  "Rice with Dal": "Рис с далом",
  "Grilled Chicken": "Гриль-курица",
  "Paneer Curry": "Кари с паниром",
  "Mixed Vegetable Curry": "Кари с овощами",
  "Chapati with Daal": "Чапати с далом",
  "Fish Curry with Rice": "Рыбное кари с рисом",
  "Rajma Chawal": "Раджма Чавал",
  "Chole Bhature": "Чоле Бхатуре",
  "Kadhi with Rice": "Кадхи с рисом",
  "Palak Paneer": "Палак Панир",
  "Stuffed Paratha": "Парата с начинкой",
  "Veg Pulao": "Овощное пуляо",
  "Biryani with Raita": "Бириани с раитой",
  "Tofu Stir Fry": "Жареный тофу",
  "Chicken Tikka": "Курица Тикка",
  "Veg Fried Rice": "Овощной жареный рис",
  "Aloo Gobi with Roti": "Алу Гоби с роти",
  "Baingan Bharta": "Байнган Бхарта",
  "Sambar with Rice": "Самбар с рисом",
  "Chicken Curry with Roti": "Курица карри с роти",
  "Bhindi Masala with Roti": "Бхинди масала с роти",
  "Egg Curry with Rice": "Яичное карри с рисом",
  "Lentil Soup with Bread": "Суп из чечевицы с хлебом",
  "Methi Thepla with Curd": "Мети Тепла с йогуртом",
  "Soybean Curry with Rice": "Кари из сои с рисом",
  "Cabbage Sabzi with Chapati": "Капустное сабзи с чапати",
  "Dal Makhani with Naan": "Дал Махани с нааном",
  "Vegetable Korma with Roti": "Овощное корма с роти",
  "Tandoori Roti with Paneer": "Тандури роти с паниром",
  "Mixed Dal with Rice": "Смешанный дал с рисом",
  "Bottle Gourd Curry with Roti": "Кари с бутылочной тыквой и роти",
  "Kofta Curry with Roti": "Кофта карри с роти",
  "Paneer Bhurji with Bread": "Панир Бхурджи с хлебом",
  "Chana Masala with Rice": "Чана масала с рисом",
  "Curd Rice": "Рис с йогуртом",
  "Tomato Rice": "Рис с помидорами",
  "Vegetable Stew with Appam": "Овощной рагу с аппам",
  "Dhokla with Green Chutney": "Дхокла с зеленым чатни",
  "Besan Chilla with Salad": "Бесан Чилла с салатом",
  "Lauki Chana Dal": "Лауки Чана дал",
  "Spinach Corn Curry": "Кари со шпинатом и кукурузой",
  "Tinda Masala with Roti": "Тинда масала с роти",
  "Masoor Dal with Rice": "Масур дал с рисом",
  "Vegetable Handi with Naan": "Овощное ханди с нааном",
  "Egg Bhurji with Chapati": "Эг Бхурджи с чапати",
  "Pumpkin Curry with Rice": "Тыквенное карри с рисом",
  "2 rotis + sabzi": "2 роти + сабзи",
  "1 cup rice + 1 cup dal": "1 чашка риса + 1 чашка дала",
  "1 breast": "1 грудка",
  "2 chapatis + dal'": "2 чапати + дал",
  "1 bowl curry + 1 cup rice": "1 чаша карри + 1 чашка риса",
  "1 bhatura + chole": "1 бхатура + чоле",
  "1 paratha": "1 парата",
  "1 bowl + 2 rotis": "1 чаша + 2 роти",
  "1 cup + 1 bowl": "1 чашка + 1 чаша",
  "1 bowl + 1 cup rice": "1 чаша + 1 чашка риса",
  "1 bowl + 1 bread slice": "1 чаша + 1 ломтик хлеба",
  "2 theplas + ½ cup curd": "2 теплы + ½ чашки йогурта",
  "1 bowl + 2 chapatis": "1 чаша + 2 чапати",
  "1 bowl + 1 naan": "1 чаша + 1 наан",
  "2 rotis + paneer": "2 роти + панир",
  "1 bowl + 2 slices": "1 чаша + 2 ломтика",
  "1 bowl + 2 appams": "1 чаша + 2 аппама",


  "3 pieces": "3 штуки",
  "2 chillas + salad": "2 чиллы + салат",
  "Cal": "Калории",
  "Cropper": "Кроппер",
  "Calorie Tracker": "Трекер калорий",
  "Add Calorie": "Добавить калорию",
  "Quantity": "Количество",
  "Ask With Open AI": "Спросить у Open AI",
  "This picture not available Calorie,Protein,Carbs and Fats,": "Это изображение недоступно. Калории, Белки, Углеводы и Жиры.",
  "Ask Botanist": "Спросить у ботаника",
  "Write your message": "Напишите ваше сообщение",
  "Confirm Reset": "Подтвердить сброс",
  "Are you sure you want to Reset Data?": "Вы уверены, что хотите сбросить аккаунт?",
  "Reset": "Сбросить",
  "You have been Reset Account": "Ваш аккаунт был сброшен",
  "Personal Details": "Личные данные",
  "Goal Weight": "Целевой вес",
  "cm": "см",
  "Date Of Birth": "Дата рождения",
  "Gender": "Пол",
  "Male": "Мужчина",
  "Female": "Женщина",
  "Choose your desired weight?": "Выберите желаемый вес",
  "Imperial": "Имперская система",
  "Metric": "Метрическая система",
  "Weight": "Вес",
  "lb": "фунты",
  "ft": "футы",
  "in": "дюймы",
  "Day": "День",
  "January": "Январь",
  "February": "Февраль",
  "March": "Март",
  "April": "Апрель",
  "June": "Июнь",
  "July": "Июль",
  "August": "Август",
  "September": "Сентябрь",
  "October": "Октябрь",
  "November": "Ноябрь",
  "December": "Декабрь",
  "Update Your Gender": "Обновить ваш пол",
  "Other": "Другой",
  "Adjust Goals": "Настроить цели",
  "How many workout do you per week?": "Сколько тренировок вы проводите в неделю?",
  "This will used to calibrate your custom plan": "Это будет использоваться для калибровки вашего индивидуального плана",
  "Workout Now and then": "Тренировки время от времени",
  "A few workout per week": "Несколько тренировок в неделю",
  "Dedicated athlete": "Посвящённый спортсмен",
  "What is your goal?": "Какая ваша цель?",
  "This helps is generate a plan for your calorie intake.": "Это помогает создать план для вашего потребления калорий.",
  "Gain Weight": "Набрать вес",
  "Lose Weight": "Похудеть",
  "Update Calorie Goal": "Обновить цель по калориям",
  "Save": "Сохранить",
  "Calorie Goal": "Цель по калориям",
  "Update Protein Goal": "Обновить цель по белкам",
  "Protein goal": "Цель по белкам",
  "Update Carb Goal": "Обновить цель по углеводам",
  "Carb goal": "Цель по углеводам",
  "Update Fat Goal": "Обновить цель по жирам",
  "Auto Generate Goal": "Автоматически сгенерировать цель",
  "Fruit Salad": "Фруктовый салат",
  "Roasted Chickpeas": "Жареный нут",
  "Mixed Nuts": "Смешанные орехи",
  "Yogurt with Honey": "Йогурт с медом",
  "Apple with Peanut Butter": "Яблоко с арахисовым маслом",
  "Protein Bar": "Протеиновый батончик",
  "Whole Wheat Crackers": "Крекеры из цельной пшеницы",
  "Granola Bar": "Гранола батончик",
  "Peanut Chikki": "Чикки с арахисом",
  "Bhel Puri": "Бхел Пури",
  "Khakra": "Хакра",
  "Masala Makhana": "Масала Макхана",
  "Hummus with Veggies": "Хумус с овощами",
  "Paneer Cubes": "Кубики панира",
  "Milkshake (Low Sugar)": "Молочный коктейль (с низким содержанием сахара)",
  "Dhokla": "Дхокла",
  "Vegetable Soup": "Овощной суп",
  "Idli with Chutney": "Идли с чатни",
  "Cheese Slice": "Ломтик сыра",
  "Chana Chaat": "Чана Чаат",
  "Moong Dal Chilla": "Чилла из моонг дал",
  "Rice Cake with Peanut Butter": "Рисовый торт с арахисовым маслом",
  "Popcorn (Air-popped)": "Попкорн (воздушный)",
  "Avocado Toast": "Тост с авокадо",
  "Stuffed Dates": "Финики с начинкой",
  "Oats Cookies": "Овсяное печенье",
  "Fruit Smoothie": "Фруктовый смузи",
  "Carrot Sticks with Hummus": "Морковные палочки с хумусом",
  "Soy Nuts": "Соевые орехи",
  "Trail Mix": "Смесь для туристов",
  "Besan Ladoo": "Бесан Ладу",
  "Upma (small portion)": "Упма (маленькая порция)",
  "Egg Roll (Mini)": "Мини-ролл с яйцом",
  "Rice Idli": "Рисовое идли",
  "Cucumber Sandwich": "Сэндвич с огурцом",
  "Fruit Chaat": "Фруктовый чат",
  "Lassi (Sweet)": "Ласси (сладкое)",
  "Cold Coffee (Low Sugar)": "Холодный кофе (с низким содержанием сахара)",
  "Rava Dhokla": "Рава Дхокла",
  "Vegetable Cutlet": "Овощной котлет",
  "Chikki with Jaggery": "Чикки с пальмовым сахаром",
  "Milk (Low Fat)": "Молоко (низкий жир)",
  "Baked Samosa": "Печёная самоса",
  "Vegetable Wrap": "Овощной ролл",
  "Roasted Soybeans": "Жареная соя",
  "1/2 cup": "1/2 чашки",
  "1 handful": "1 горсть",
  "1 apple + 1 tbsp PB": "1 яблоко + 1 ст. ложка арахисового масла",
  "1 bar": "1 батончик",
  "5 pieces": "5 штук",
  "½ cup hummus + veggies": "½ чашки хумуса + овощи",
  "50g": "50 г",
  "1 idli + chutney": "1 идли + чатни",
  "1 slice": "1 ломтик",
  "1 chilla": "1 чилла",
  "1 cake + 1 tbsp PB": "1 торт + 1 ст. ложка арахисового масла",
  "2 cups": "2 чашки",
  "1 toast": "1 тост",
  "3 dates": "3 финика",
  "2 cookies": "2 печенья",
  "½ cup": "½ чашки",
  "1 small bowl": "1 маленькая чашка",
  "1 roll": "1 рулет",
  "1 wrap": "1 обертка",
  "Chapati with Sabzi": "Чапати с сабзи",
  "Grilled Fish": "Жареная рыба",
  "Moong Dal Khichdi": "Кхичди из моонг дал",
  "Paneer Bhurji with Roti": "Панир Бхурджи с роти",
  "Brown Rice with Veg Curry": "Коричневый рис с овощным карри",
  "Quinoa with Stir Fry Veggies": "Киноа с жареными овощами",
  "Grilled Tofu with Salad": "Жареный тофу с салатом",
  "Vegetable Pulao": "Овощной пилав",
  "Palak Paneer with Chapati": "Палак панир с чапати",
  "Mixed Vegetable Soup": "Суп из смешанных овощей",
  "Stuffed Paratha with Curd": "Парата с начинкой и йогуртом",
  "Oats Khichdi": "Кхичди из овса",
  "Roti with Bhindi": "Роти с бхинди",
  "Dal Tadka with Jeera Rice": "Дал Тадка с рисом джира",
  "Vegetable Handvo": "Овощной хандво",
  "Kadhi with Bajra Roti": "Кадхи с бажра роти",
  "Tofu Curry with Quinoa": "Курри с тофу и киноа",
  "Bhakri with Thecha": "Бхакри с течей",
  "Biryani (Veg)": "Бирьяни (вегетарианское)",
  "Rajma with Brown Rice": "Раджма с коричневым рисом",
  "Daliya (Broken Wheat Porridge)": "Далия (каша из дробленой пшеницы)",
  "Pumpkin Sabzi with Chapati": "Тыквенное сабзи с чапати",
  "Cauliflower Stir Fry": "Жареная цветная капуста",
  "Boiled Egg Salad": "Салат с вареными яйцами",
  "Tomato Rasam with Rice": "Томатный расам с рисом",
  "Sweet Potato with Curd": "Сладкий картофель с йогуртом",
  "Stuffed Capsicum": "Перец, фаршированный",
  "Paneer Tikka with Mint Chutney": "Панир Тикка с мятным чатни",
  "Rice with Sambar": "Рис с самбаром",
  "Vegetable Thepla with Dahi": "Овощное тхепла с дахи",
  "Grilled Mushroom Skewers": "Шашлыки из грибов на гриле",
  "Beetroot Sabzi with Roti": "Свекольный сабзи с роти",
  "Spinach Dal with Rice": "Дал со шпинатом с рисом",
  "Lentil Soup with Toast": "Суп из чечевицы с тостами",
  "Tinda Curry with Chapati": "Карри с тиндой и чапати",
  "Egg Bhurji with Roti": "Яйца Бхурджи с роти",
  "Karela Sabzi with Roti": "Сабзи из карелы с роти",
  "Zucchini Stir Fry": "Тушеная цукини",
  "Low Carb Paneer Bowl": "Миска панир с низким содержанием углеводов",
  "Stuffed Tomato": "Фаршированный помидор",
  "Vegetable Rava Upma": "Овощное рава упма",
  "2 chapatis + sabzi": "2 чапати + сабзи",
  "1 fillet": "1 филе",
  "1 bowl + 1 roti": "1 миска + 1 роти",
  "1 plate": "1 тарелка",
  "1 cup rice + dal": "1 чашка риса + дал",
  "1 paratha + ½ cup curd": "1 парата + ½ чашки йогурта",
  "2 rotis + bhindi": "2 роти + бинди",
  "1 roti + 1 bowl kadhi": "1 роти + 1 миска кадхи",
  "1 bhakri + chutney": "1 бахри + чатни",
  "1 bowl curry + 1 roti": "1 миска карри + 1 роти",
  "2 chillas": "2 чиллы",
  "1 bowl + ½ cup curd": "1 миска + ½ чашки йогурта",
  "1 serving": "1 порция",
  "1 cup rice + sambar": "1 чашка риса + самбар",
  "1 thepla + curd": "1 тхепла + йогурт",
  "1 skewer": "1 шампур",
  "1 bowl + 1 toast": "1 миска + 1 тост",
  "1 bowl + 1 appam": "1 миска + 1 аппам",
  "1 tomato": "1 помидор",
  "Restore": "Восстановить",
  "Get Premium": "Получить Premium",
  "Get All The New Exciting Features": "Получите все новые захватывающие функции",
  "Unlock Food Scanner": "Разблокировать сканер пищи",
  "Unlock Food Calorie": "Разблокировать калории пищи",
  "Unlock Unlimited Chat with Ai": "Разблокировать неограниченный чат с ИИ",
  "Unlimited Food Scanner To Calorie": "Неограниченный сканер пищи для калорий",
  "Most Popular": "Самые популярные",
  "Subscription": "Подписка",
  "BUY NOW": "КУПИТЕ СЕЙЧАС",
  "Terms of Condition": "Условия",
  "Welcome": "Добро пожаловать",
  "Calorie tracking made easy": "Отслеживание калорий стало проще",
  "Just snap a quick photo of your meal and we''ll do the rest": "Просто сделайте быстрый снимок своей еды, и мы сделаем все остальное",
  "In-depth nutrition analyses": "Подробный анализ питания",
  "We will keep your informed about your food choicer and their nutritional content": "Мы будем держать вас в курсе ваших выборов пищи и их питательной ценности",
  "Transform your body": "Преобразите свое тело",
  "Today is best time to start working toward your dream body": "Сегодня лучший день, чтобы начать работать над телом своей мечты",
  "Where were you born?": "Где вы родились?",
  "This Will be used to calibrate your custom plan": "Это будет использовано для калибровки вашего индивидуального плана",
  "What's stopping you from reaching your goals?": "Что мешает вам достичь ваших целей?",
  "Lack of consistency": "Отсутствие последовательности",
  "Unhealthy eating habits": "Нездоровые пищевые привычки",
  "Lack of supports": "Отсутствие поддержки",
  "Busy schedule": "Занятый график",
  "Lack of meal inspiration": "Отсутствие вдохновения для еды",
  "We're setting": "Мы настраиваем",
  "everything up for you": "все для вас",
  "Customizing health plan....": "Настройка плана здоровья...."
}
;
