const Map<String, String> spanish = {
  "Home": "Inicio",
  "Calorie": "Caloría",
  "Analytics": "Análisis",
  "Setting": "Configuración",
  "Track Food": "Rastrear comida",
  "Consumed": "Consumido",
  "Remaining": "Restante",
  "Protein": "Proteína",
  "Carbs": "Carbohidratos",
  "Fats": "Grasas",
  "History": "Historial",
  "View All": "Ver todo",
  "BreakFast": "Desayuno",
  "Lunch": "Almuerzo",
  "snack(s)": "Merienda",
  "Dinner": "Cena",
  "Which meal would you like to track?": "¿Qué comida te gustaría rastrear?",
  "Snap Tips": "Consejos de foto",
  "Too close": "Demasiado cerca",
  "Too far": "Demasiado lejos",
  "Multi-species": "Múltiples ingredientes",
  "Continue": "Continuar",
  "OverView": "Resumen",
  "Weight Goal": "Objetivo de peso",
  "Update": "Actualizar",
  "Current Weight": "Peso actual",
  "kg": "kg",
  "Try to update once a week so we can adjust your plan to ensure you hit your goal": "Intenta actualizar una vez a la semana para que podamos ajustar tu plan y garantizar que alcances tu objetivo",
  "Update Weight": "Actualizar peso",
  "Week": "Semana",
  "Month": "Mes",
  "Year": "Año",
  "Update Weight Goal": "Actualizar objetivo de peso",
  "Enter new weight (kg)": "Ingresa el nuevo peso (kg)",
  "Cancel": "Cancelar",
  "Calorie Your Week :": "Tus calorías esta semana:",
  "Sun": "Dom",
  "Mon": "Lun",
  "Tue": "Mar",
  "Wed": "Mié",
  "Thu": "Jue",
  "Fri": "Vie",
  "Sat": "Sáb",
  "Average Calorie Month :": "Promedio de calorías mensual:",
  "Average Calorie Yearly :": "Promedio de calorías anual:",
  "Jan": "Ene",
  "Feb": "Feb",
  "Mar": "Mar",
  "Apr": "Abr",
  "May": "May",
  "Jun": "Jun",
  "Jul": "Jul",
  "Aug": "Ago",
  "Sep": "Sep",
  "Oct": "Oct",
  "Nov": "Nov",
  "Dec": "Dic",
  "Age": "Edad",
  "Height": "Altura",
  "Customization": "Personalización",
  "Dark Mode": "Modo oscuro",
  "Language": "Idioma",
  "Personal details": "Detalles personales",
  "Adjust goals": "Ajustar metas",
  "Calories,carbs,fat and protein": "Calorías, carbohidratos, grasas y proteínas",
  "Chat history": "Historial de chat",
  "Legal": "Legal",
  "Terms and Condition": "Términos y condiciones",
  "Privacy Policy": "Política de privacidad",
  "Reset Data?": "¿Restablecer cuenta?",
  "VERSION": "VERSIÓN",
  "History not found": "Historial no encontrado",
  "Delete Item": "Eliminar elemento",
  "Are you sure you want to delete this item?": "¿Estás seguro de que quieres eliminar este elemento?",
  "Delete": "Eliminar",
  "Search by Food Name/Dish": "Buscar por nombre de comida/plato",
  "🎯 Calorie Goal Reached": "🎯 Objetivo de calorías alcanzado",
  "You've completed your calorie goal for today. Would you like to add more?": "Has alcanzado tu objetivo de calorías para hoy. ¿Te gustaría agregar más?",
  "Done": "Hecho",
  "Add More Calories": "Agregar más calorías",
  "Boiled Egg": "Huevo hervido",
  "Oatmeal": "Avena",
  "Banana": "Plátano",
  "Paratha": "Paratha",
  "Idli": "Idli",
  "Dosa": "Dosa",
  "Upma": "Upma",
  "Poha": "Poha",
  "Bread Butter": "Pan con mantequilla",
  "Cornflakes with Milk": "Cornflakes con leche",
  "Chilla (Besan)": "Chilla (Harina de garbanzo)",
  "Sprouts Salad": "Ensalada de brotes",
  "Pancakes": "Panqueques",
  "Apple": "Manzana",
  "Milk": "Leche",
  "Almonds": "Almendras",
  "Smoothie (Fruit)": "Smoothie (Fruta)",
  "Yogurt (Plain)": "Yogur (Natural)",
  "Khichdi": "Khichdi",
  "Thepla": "Thepla",
  "Cheela (Moong dal)": "Cheela (Moong dal)",
  "Pav Bhaji": "Pav Bhaji",
  "Sabudana Khichdi": "Sabudana Khichdi",
  "Roti with Sabzi": "Roti con Sabzi",
  "Peanut Butter Bread": "Pan con mantequilla de maní",
  "Fruit Bowl": "Tazón de frutas",
  "Vegetable Sandwich": "Sándwich de verduras",
  "Rice Idli with Sambar": "Idli de arroz con Sambar",
  "Boiled Corn": "Maíz hervido",
  "Paneer Bhurji": "Paneer Bhurji",
  "Protein Shake": "Batido de proteínas",
  "Muesli with Milk": "Muesli con leche",
  "Chapati with Curd": "Chapati con yogur",
  "Porridge (Daliya)": "Porridge (Daliya)",
  "Rava Upma": "Rava Upma",
  "Chickpea Salad": "Ensalada de garbanzos",
  "Boiled Sweet Potato": "Batata hervida",
  "Coconut Water": "Agua de coco",
  "Masala Omelette": "Omelette masala",
  "Vegetable Poha": "Poha de verduras",
  "1 egg": "1 huevo",
  "1 bowl": "1 tazón",
  "1 medium": "1 mediano",
  "1 piece": "1 pieza",
  "1 cup": "1 taza",
  "2 slices": "2 rebanadas",
  "2 small pieces": "2 piezas pequeñas",
  "10 pieces": "10 piezas",
  "1 glass": "1 vaso",
  "2 pavs + bhaji": "2 pavs + bhaji",
  "1 roti + sabzi": "1 roti + sabzi",
  "1 sandwich": "1 sándwich",
  "2 idlis + sambar'": "2 idlis + sambar",
  "1 chapati + ½ cup curd": "1 chapati + ½ taza de yogur",
  "Rice with Dal": "Arroz con Dal",
  "Grilled Chicken": "Pollo a la parrilla",
  "Paneer Curry": "Curry de Paneer",
  "Mixed Vegetable Curry": "Curry de verduras mixtas",
  "Chapati with Daal": "Chapati con Daal",
  "Fish Curry with Rice": "Curry de pescado con arroz",
  "Rajma Chawal": "Rajma Chawal",
  "Chole Bhature": "Chole Bhature",
  "Kadhi with Rice": "Kadhi con arroz",
  "Palak Paneer": "Palak Paneer",
  "Stuffed Paratha": "Paratha relleno",
  "Veg Pulao": "Veg Pulao",
  "Biryani with Raita": "Biryani con Raita",
  "Tofu Stir Fry": "Tofu salteado",
  "Chicken Tikka": "Pollo Tikka",
  "Veg Fried Rice": "Arroz frito de verduras",
  "Aloo Gobi with Roti": "Aloo Gobi con Roti",
  "Baingan Bharta": "Baingan Bharta",
  "Sambar with Rice": "Sambar con arroz",
  "Chicken Curry with Roti": "Curry de pollo con Roti",
  "Bhindi Masala with Roti": "Bhindi masala con Roti",
  "Egg Curry with Rice": "Curry de huevo con arroz",
  "Lentil Soup with Bread": "Sopa de lentejas con pan",
  "Methi Thepla with Curd": "Methi Thepla con yogur",
  "Soybean Curry with Rice": "Curry de soja con arroz",
  "Cabbage Sabzi with Chapati": "Sabzi de repollo con Chapati",
  "Dal Makhani with Naan": "Dal Makhani con Naan",
  "Vegetable Korma with Roti": "Korma de verduras con Roti",
  "Tandoori Roti with Paneer": "Tandoori Roti con Paneer",
  "Mixed Dal with Rice": "Dal mixto con arroz",
  "Bottle Gourd Curry with Roti": "Curry de calabaza con Roti",
  "Kofta Curry with Roti": "Curry de Kofta con Roti",
  "Paneer Bhurji with Bread": "Paneer Bhurji con pan",
  "Chana Masala with Rice": "Chana Masala con arroz",
  "Curd Rice": "Arroz con yogur",
  "Tomato Rice": "Arroz con tomate",
  "Vegetable Stew with Appam": "Estofado de verduras con Appam",
  "Dhokla with Green Chutney": "Dhokla con chutney verde",
  "Besan Chilla with Salad": "Besan Chilla con ensalada",
  "Lauki Chana Dal": "Lauki Chana Dal",
  "Spinach Corn Curry": "Curry de espinacas y maíz",
  "Tinda Masala with Roti": "Tinda Masala con Roti",
  "Masoor Dal with Rice": "Masoor Dal con arroz",
  "Vegetable Handi with Naan": "Handi de verduras con Naan",
  "Egg Bhurji with Chapati": "Egg Bhurji con Chapati",
  "Pumpkin Curry with Rice": "Curry de calabaza con arroz",
  "2 rotis + sabzi": "2 rotis + sabzi",
  "1 cup rice + 1 cup dal": "1 taza de arroz + 1 taza de dal",
  "1 breast": "1 pechuga",
  "2 chapatis + dal'": "2 chapatis + dal",
  "1 bowl curry + 1 cup rice": "1 tazón de curry + 1 taza de arroz",
  "1 bhatura + chole": "1 bhatura + chole",
  "1 paratha": "1 paratha",
  "1 bowl + 2 rotis": "1 tazón + 2 rotis",
  "1 cup + 1 bowl": "1 taza + 1 tazón",
  "1 bowl + 1 cup rice": "1 tazón + 1 taza de arroz",
  "1 bowl + 1 bread slice": "1 tazón + 1 rebanada de pan",
  "2 theplas + ½ cup curd": "2 theplas + ½ taza de yogur",
  "1 bowl + 2 chapatis": "1 tazón + 2 chapatis",
  "1 bowl + 1 naan": "1 tazón + 1 naan",
  "2 rotis + paneer": "2 rotis + paneer",
  "1 bowl + 2 slices": "1 tazón + 2 rebanadas",
  "1 bowl + 2 appams": "1 tazón + 2 appams",


  "3 pieces": "3 piezas",
  "2 chillas + salad": "2 chillas + ensalada",
  "Cal": "Calorías",
  "Cropper": "Cropper",
  "Calorie Tracker": "Rastreador de Calorías",
  "Add Calorie": "Agregar Caloría",
  "Quantity": "Cantidad",
  "Ask With Open AI": "Preguntar a Open AI",
  "This picture not available Calorie,Protein,Carbs and Fats,": "Esta imagen no está disponible. Calorías, Proteínas, Carbohidratos y Grasas.",
  "Ask Botanist": "Preguntar al Botánico",
  "Write your message": "Escribe tu mensaje",
  "Confirm Reset": "Confirmar Reinicio",
  "Are you sure you want to Reset Data?": "¿Estás seguro de que quieres reiniciar la cuenta?",
  "Reset": "Reiniciar",
  "You have been Reset Account": "Tu cuenta ha sido reiniciada",
  "Personal Details": "Detalles Personales",
  "Goal Weight": "Peso Objetivo",
  "cm": "cm",
  "Date Of Birth": "Fecha de Nacimiento",
  "Gender": "Género",
  "Male": "Masculino",
  "Female": "Femenino",
  "Choose your desired weight?": "¿Elige tu peso deseado?",
  "Imperial": "Imperial",
  "Metric": "Métrico",
  "Weight": "Peso",
  "lb": "lb",
  "ft": "pies",
  "in": "pulgadas",
  "Day": "Día",
  "January": "Enero",
  "February": "Febrero",
  "March": "Marzo",
  "April": "Abril",
  "June": "Junio",
  "July": "Julio",
  "August": "Agosto",
  "September": "Septiembre",
  "October": "Octubre",
  "November": "Noviembre",
  "December": "Diciembre",
  "Update Your Gender": "Actualizar tu Género",
  "Other": "Otro",
  "Adjust Goals": "Ajustar Objetivos",
  "How many workout do you per week?": "¿Cuántos entrenamientos haces por semana?",
  "This will used to calibrate your custom plan": "Esto se usará para calibrar tu plan personalizado",
  "Workout Now and then": "Entrenamiento de vez en cuando",
  "A few workout per week": "Algunos entrenamientos por semana",
  "Dedicated athlete": "Atleta dedicado",
  "What is your goal?": "¿Cuál es tu objetivo?",
  "This helps is generate a plan for your calorie intake.": "Esto ayuda a generar un plan para tu ingesta de calorías.",
  "Gain Weight": "Ganar Peso",
  "Lose Weight": "Perder Peso",
  "Update Calorie Goal": "Actualizar Objetivo de Calorías",
  "Save": "Guardar",
  "Calorie Goal": "Objetivo de Calorías",
  "Update Protein Goal": "Actualizar Objetivo de Proteínas",
  "Protein goal": "Objetivo de Proteínas",
  "Update Carb Goal": "Actualizar Objetivo de Carbohidratos",
  "Carb goal": "Objetivo de Carbohidratos",
  "Update Fat Goal": "Actualizar Objetivo de Grasas",
  "Auto Generate Goal": "Generar Objetivo Automáticamente",
  "Fruit Salad": "Ensalada de Frutas",
  "Roasted Chickpeas": "Garbanzos Tostados",
  "Mixed Nuts": "Frutos Secos Mixtos",
  "Yogurt with Honey": "Yogur con Miel",
  "Apple with Peanut Butter": "Manzana con Mantequilla de Cacahuate",
  "Protein Bar": "Barra de Proteína",
  "Whole Wheat Crackers": "Galletas de Trigo Integral",
  "Granola Bar": "Barra de Granola",
  "Peanut Chikki": "Chikki de Maní",
  "Bhel Puri": "Bhel Puri",
  "Khakra": "Khakra",
  "Masala Makhana": "Masala Makhana",
  "Hummus with Veggies": "Hummus con Verduras",
  "Paneer Cubes": "Cubes de Paneer",
  "Milkshake (Low Sugar)": "Milkshake (Bajo en Azúcar)",
  "Dhokla": "Dhokla",
  "Vegetable Soup": "Sopa de Verduras",
  "Idli with Chutney": "Idli con Chutney",
  "Cheese Slice": "Rebanada de Queso",
  "Chana Chaat": "Chana Chaat",
  "Moong Dal Chilla": "Chilla de Moong Dal",
  "Rice Cake with Peanut Butter": "Torta de Arroz con Mantequilla de Cacahuate",
  "Popcorn (Air-popped)": "Palomitas de Maíz (Hechas al Aire)",
  "Avocado Toast": "Tostada de Aguacate",
  "Stuffed Dates": "Dátiles Rellenos",
  "Oats Cookies": "Galletas de Avena",
  "Fruit Smoothie": "Batido de Frutas",
  "Carrot Sticks with Hummus": "Palitos de Zanahoria con Hummus",
  "Soy Nuts": "Frutos de Soya",
  "Trail Mix": "Mezcla de Frutos Secos",
  "Besan Ladoo": "Besan Ladoo",
  "Upma (small portion)": "Upma (porción pequeña)",
  "Egg Roll (Mini)": "Rollito de Huevo (Mini)",
  "Rice Idli": "Idli de Arroz",
  "Cucumber Sandwich": "Sándwich de Pepino",
  "Fruit Chaat": "Chaat de Frutas",
  "Lassi (Sweet)": "Lassi (Dulce)",
  "Cold Coffee (Low Sugar)": "Café Frío (Bajo en Azúcar)",
  "Rava Dhokla": "Rava Dhokla",
  "Vegetable Cutlet": "Corte Vegetal",
  "Chikki with Jaggery": "Chikki con Jaggery",
  "Milk (Low Fat)": "Leche (Baja en Grasa)",
  "Baked Samosa": "Samosa Horneada",
  "Vegetable Wrap": "Wrap Vegetal",
  "Roasted Soybeans": "Soya Tostada",
  "1/2 cup": "1/2 taza",
  "1 handful": "1 puñado",
  "1 apple + 1 tbsp PB": "1 manzana + 1 cda. de mantequilla de maní",
  "1 bar": "1 barra",
  "5 pieces": "5 piezas",
  "½ cup hummus + veggies": "½ taza de hummus + verduras",
  "50g": "50 g",
  "1 idli + chutney": "1 idli + chutney",
  "1 slice": "1 rebanada",
  "1 chilla": "1 chilla",
  "1 cake + 1 tbsp PB": "1 pastel + 1 cda. de mantequilla de maní",
  "2 cups": "2 tazas",
  "1 toast": "1 tostada",
  "3 dates": "3 dátiles",
  "2 cookies": "2 galletas",
  "½ cup": "½ taza",
  "1 small bowl": "1 tazón pequeño",
  "1 roll": "1 rollo",
  "1 wrap": "1 wrap",
  "Chapati with Sabzi": "Chapati con Sabzi",
  "Grilled Fish": "Pescado a la Parrilla",
  "Moong Dal Khichdi": "Khichdi de Moong Dal",
  "Paneer Bhurji with Roti": "Paneer Bhurji con Roti",
  "Brown Rice with Veg Curry": "Arroz Integral con Curry de Verduras",
  "Quinoa with Stir Fry Veggies": "Quinoa con Verduras Salteadas",
  "Grilled Tofu with Salad": "Tofu a la Parrilla con Ensalada",
  "Vegetable Pulao": "Pulao de Verduras",
  "Palak Paneer with Chapati": "Palak Paneer con Chapati",
  "Mixed Vegetable Soup": "Sopa de Verduras Mixtas",
  "Stuffed Paratha with Curd": "Paratha Relleno con Yogur",
  "Oats Khichdi": "Khichdi de Avena",
  "Roti with Bhindi": "Roti con Bhindi",
  "Dal Tadka with Jeera Rice": "Dal Tadka con Arroz Jeera",
  "Vegetable Handvo": "Handvo Vegetal",
  "Kadhi with Bajra Roti": "Kadhi con Bajra Roti",
  "Tofu Curry with Quinoa": "Curry de Tofu con Quinoa",
  "Bhakri with Thecha": "Bhakri con Thecha",
  "Biryani (Veg)": "Biryani (Vegetariano)",
  "Rajma with Brown Rice": "Rajma con Arroz Integral",
  "Daliya (Broken Wheat Porridge)": "Daliya (Gachas de Trigo Partido)",
  "Pumpkin Sabzi with Chapati": "Sabzi de Calabaza con Chapati",
  "Cauliflower Stir Fry": "Salteado de Coliflor",
  "Boiled Egg Salad": "Ensalada de Huevo Cocido",
  "Tomato Rasam with Rice": "Rasam de tomate con arroz",
  "Sweet Potato with Curd": "Batata con yogur",
  "Stuffed Capsicum": "Pimiento relleno",
  "Paneer Tikka with Mint Chutney": "Paneer Tikka con chutney de menta",
  "Rice with Sambar": "Arroz con Sambar",
  "Vegetable Thepla with Dahi": "Thepla de vegetales con dahi",
  "Grilled Mushroom Skewers": "Brochetas de champiñones a la parrilla",
  "Beetroot Sabzi with Roti": "Sabzi de remolacha con roti",
  "Spinach Dal with Rice": "Dal de espinacas con arroz",
  "Lentil Soup with Toast": "Sopa de lentejas con tostadas",
  "Tinda Curry with Chapati": "Curry de Tinda con chapati",
  "Egg Bhurji with Roti": "Huevo Bhurji con roti",
  "Karela Sabzi with Roti": "Sabzi de Karela con roti",
  "Zucchini Stir Fry": "Salteado de calabacín",
  "Low Carb Paneer Bowl": "Tazón de paneer bajo en carbohidratos",
  "Stuffed Tomato": "Tomate relleno",
  "Vegetable Rava Upma": "Upma de rava con vegetales",
  "2 chapatis + sabzi": "2 chapatis + sabzi",
  "1 fillet": "1 filete",
  "1 bowl + 1 roti": "1 tazón + 1 roti",
  "1 plate": "1 plato",
  "1 cup rice + dal": "1 taza de arroz + dal",
  "1 paratha + ½ cup curd": "1 paratha + ½ taza de yogur",
  "2 rotis + bhindi": "2 rotis + bhindi",
  "1 roti + 1 bowl kadhi": "1 roti + 1 tazón de kadhi",
  "1 bhakri + chutney": "1 bhakri + chutney",
  "1 bowl curry + 1 roti": "1 tazón de curry + 1 roti",
  "2 chillas": "2 chillas",
  "1 bowl + ½ cup curd": "1 tazón + ½ taza de yogur",
  "1 serving": "1 porción",
  "1 cup rice + sambar": "1 taza de arroz + sambar",
  "1 thepla + curd": "1 thepla + yogur",
  "1 skewer": "1 brocheta",
  "1 bowl + 1 toast": "1 tazón + 1 tostada",
  "1 bowl + 1 appam": "1 tazón + 1 appam",
  "1 tomato": "1 tomate",
  "Restore": "Restaurar",
  "Get Premium": "Obtén Premium",
  "Get All The New Exciting Features": "Obtén todas las nuevas funciones emocionantes",
  "Unlock Food Scanner": "Desbloquear escáner de alimentos",
  "Unlock Food Calorie": "Desbloquear calorías de alimentos",
  "Unlock Unlimited Chat with Ai": "Desbloquear chat ilimitado con IA",
  "Unlimited Food Scanner To Calorie": "Escáner de alimentos ilimitado a calorías",
  "Most Popular": "Más Popular",
  "Subscription": "Suscripción",
  "BUY NOW": "COMPRAR AHORA",
  "Terms of Condition": "Términos y Condiciones",
  "Welcome": "Bienvenido",
  "Calorie tracking made easy": "Seguimiento de calorías hecho fácil",
  "Just snap a quick photo of your meal and we''ll do the rest": "Solo toma una foto rápida de tu comida y nosotros haremos el resto",
  "In-depth nutrition analyses": "Análisis nutricionales profundos",
  "We will keep your informed about your food choicer and their nutritional content": "Te mantendremos informado sobre tus elecciones de alimentos y su contenido nutricional",
  "Transform your body": "Transforma tu cuerpo",
  "Today is best time to start working toward your dream body": "Hoy es el mejor momento para empezar a trabajar por el cuerpo de tus sueños",
  "Where were you born?": "¿Dónde naciste?",
  "This Will be used to calibrate your custom plan": "Esto se usará para calibrar tu plan personalizado",
  "What's stopping you from reaching your goals?": "¿Qué te detiene para alcanzar tus metas?",
  "Lack of consistency": "Falta de consistencia",
  "Unhealthy eating habits": "Hábitos alimenticios no saludables",
  "Lack of supports": "Falta de apoyo",
  "Busy schedule": "Horario ocupado",
  "Lack of meal inspiration": "Falta de inspiración para las comidas",
  "We're setting": "Estamos configurando",
  "everything up for you": "todo para ti",
  "Customizing health plan....": "Personalizando el plan de salud...."
}
;
