const Map<String, String> turkish = {
  "Home": "Ana Sayfa",
  "Calorie": "Kalori",
  "Analytics": "Analizler",
  "Setting": "Ayarlar",
  "Track Food": "Yemek Takibi",
  "Consumed": "Tüketildi",
  "Remaining": "Kalan",
  "Protein": "Protein",
  "Carbs": "Karbonhidratlar",
  "Fats": "Yağlar",
  "History": "Geçmiş",
  "View All": "Hepsini Gör",
  "BreakFast": "Kahvaltı",
  "Lunch": "Öğle Yemeği",
  "snack(s)": "Atıştırmalık",
  "Dinner": "Akşam Yemeği",
  "Which meal would you like to track?": "Hangi öğünü takip etmek istersiniz?",
  "Snap Tips": "Fotoğraf İpuçları",
  "Too close": "Çok yakın",
  "Too far": "Çok uzak",
  "Multi-species": "Çoklu bileşenler",
  "Continue": "Devam Et",
  "OverView": "Genel Bakış",
  "Weight Goal": "Kilo Hedefi",
  "Update": "Güncelle",
  "Current Weight": "Mevcut Kilo",
  "kg": "kg",
  "Try to update once a week so we can adjust your plan to ensure you hit your goal": "Planınızı hedefinize ulaşmak için ayarlayabilmemiz için haftada bir kez güncelleme yapmayı deneyin.",
  "Update Weight": "Kilo Güncelle",
  "Week": "Hafta",
  "Month": "Ay",
  "Year": "Yıl",
  "Update Weight Goal": "Kilo Hedefini Güncelle",
  "Enter new weight (kg)": "Yeni kilonuzu girin (kg)",
  "Cancel": "İptal Et",
  "Calorie Your Week :": "Haftalık Kaloriniz:",
  "Sun": "Paz",
  "Mon": "Pzt",
  "Tue": "Sal",
  "Wed": "Çar",
  "Thu": "Per",
  "Fri": "Cum",
  "Sat": "Cts",
  "Average Calorie Month :": "Aylık Ortalama Kalori:",
  "Average Calorie Yearly :": "Yıllık Ortalama Kalori:",
  "Jan": "Oca",
  "Feb": "Şub",
  "Mar": "Mar",
  "Apr": "Nis",
  "May": "May",
  "Jun": "Haz",
  "Jul": "Tem",
  "Aug": "Ağu",
  "Sep": "Eyl",
  "Oct": "Eki",
  "Nov": "Kas",
  "Dec": "Ara",
  "Age": "Yaş",
  "Height": "Boy",
  "Customization": "Özelleştirme",
  "Dark Mode": "Karanlık Mod",
  "Language": "Dil",
  "Personal details": "Kişisel bilgiler",
  "Adjust goals": "Hedefleri Ayarla",
  "Calories,carbs,fat and protein": "Kaloriler, karbonhidratlar, yağlar ve proteinler",
  "Chat history": "Sohbet Geçmişi",
  "Legal": "Hukuki",
  "Terms and Condition": "Şartlar ve Koşullar",
  "Privacy Policy": "Gizlilik Politikası",
  "Reset Data?": "Hesabı Sıfırlamak İstiyor Musunuz?",
  "VERSION": "SÜRÜM",
  "History not found": "Geçmiş Bulunamadı",
  "Delete Item": "Öğeyi Sil",
  "Are you sure you want to delete this item?": "Bu öğeyi silmek istediğinizden emin misiniz?",
  "Delete": "Sil",
  "Search by Food Name/Dish": "Yemek Adı/Yemek Tarifi ile Ara",
  "🎯 Calorie Goal Reached": "🎯 Kalori Hedefi Ulaşıldı",
  "You've completed your calorie goal for today. Would you like to add more?": "Bugün kalori hedefinizi tamamladınız. Daha fazla eklemek ister misiniz?",
  "Done": "Tamam",
  "Add More Calories": "Daha Fazla Kalori Ekle",
  "Boiled Egg": "Haşlanmış Yumurta",
  "Oatmeal": "Yulaf Ezmesi",
  "Banana": "Muz",
  "Paratha": "Paratha",
  "Idli": "Idli",
  "Dosa": "Dosa",
  "Upma": "Upma",
  "Poha": "Poha",
  "Bread Butter": "Ekmek ve Tereyağı",
  "Cornflakes with Milk": "Mısır Gevreği ve Süt",
  "Chilla (Besan)": "Chilla (Nohut Unu)",
  "Sprouts Salad": "Filiz Salatası",
  "Pancakes": "Krep",
  "Apple": "Elma",
  "Milk": "Süt",
  "Almonds": "Badem",
  "Smoothie (Fruit)": "Smoothie (Meyve)",
  "Yogurt (Plain)": "Yoğurt (Doğal)",
  "Khichdi": "Khichdi",
  "Thepla": "Thepla",
  "Cheela (Moong dal)": "Cheela (Moong dal)",
  "Pav Bhaji": "Pav Bhaji",
  "Sabudana Khichdi": "Sabudana Khichdi",
  "Roti with Sabzi": "Roti ve Sabzi",
  "Peanut Butter Bread": "Fıstık Ezmesi Ekmek",
  "Fruit Bowl": "Meyve Kasesi",
  "Vegetable Sandwich": "Sebzeli Sandviç",
  "Rice Idli with Sambar": "Sambar ile Pirinç Idli",
  "Boiled Corn": "Haşlanmış Mısır",
  "Paneer Bhurji": "Paneer Bhurji",
  "Protein Shake": "Protein Shake",
  "Muesli with Milk": "Sütlü Müsli",
  "Chapati with Curd": "Çapati ve Yoğurt",
  "Porridge (Daliya)": "Sütlü Bulgur",
  "Rava Upma": "Rava Upma",
  "Chickpea Salad": "Nohut Salatası",
  "Boiled Sweet Potato": "Haşlanmış Tatlı Patates",
  "Coconut Water": "Hindistancevizi Suyu",
  "Masala Omelette": "Masala Omleti",
  "Vegetable Poha": "Sebzeli Poha",
  "1 egg": "1 Yumurta",
  "1 bowl": "1 Kase",
  "1 medium": "1 Orta Boy",
  "1 piece": "1 Parça",
  "1 cup": "1 Bardak",
  "2 slices": "2 Dilim",
  "2 small pieces": "2 Küçük Parça",
  "10 pieces": "10 Parça",
  "1 glass": "1 Bardak",
  "2 pavs + bhaji": "2 Pav + Bhaji",
  "1 roti + sabzi": "1 Roti + Sabzi",
  "1 sandwich": "1 Sandviç",
  "2 idlis + sambar'": "2 İdli + Sambar",
  "1 chapati + ½ cup curd": "1 Çapati + ½ Kase Yoğurt",
  "Rice with Dal": "Pirinç ve Dal",
  "Grilled Chicken": "Izgara Tavuk",
  "Paneer Curry": "Paneer Köri",
  "Mixed Vegetable Curry": "Karışık Sebze Köri",
  "Chapati with Daal": "Çapati ve Dal",
  "Fish Curry with Rice": "Balık Köri ve Pirinç",
  "Rajma Chawal": "Rajma Chawal",
  "Chole Bhature": "Chole Bhature",
  "Kadhi with Rice": "Kadhi ve Pirinç",
  "Palak Paneer": "Palak Paneer",
  "Stuffed Paratha": "İçli Paratha",
  "Veg Pulao": "Sebzeli Pulao",
  "Biryani with Raita": "Biryani ve Raita",
  "Tofu Stir Fry": "Tofu Sote",
  "Chicken Tikka": "Tavuk Tikka",
  "Veg Fried Rice": "Sebzeli Kızarmış Pirinç",
  "Aloo Gobi with Roti": "Aloo Gobi ve Roti",
  "Baingan Bharta": "Baingan Bharta",
  "Sambar with Rice": "Sambar ve Pirinç",
  "Chicken Curry with Roti": "Tavuk Köri ve Roti",
  "Bhindi Masala with Roti": "Bhindi Masala ve Roti",
  "Egg Curry with Rice": "Yumurta Köri ve Pirinç",
  "Lentil Soup with Bread": "Mercimek Çorbası ve Ekmek",
  "Methi Thepla with Curd": "Methi Thepla ve Yoğurt",
  "Soybean Curry with Rice": "Soja Fasulyesi Köri ve Pirinç",
  "Cabbage Sabzi with Chapati": "Lahana Sabzi ve Çapati",
  "Dal Makhani with Naan": "Dal Makhani ve Naan",
  "Vegetable Korma with Roti": "Sebzeli Korma ve Roti",
  "Tandoori Roti with Paneer": "Tandoori Roti ve Paneer",
  "Mixed Dal with Rice": "Karışık Dal ve Pirinç",
  "Bottle Gourd Curry with Roti": "Şişe Kabak Köri ve Roti",
  "Kofta Curry with Roti": "Köfte Köri ve Roti",
  "Paneer Bhurji with Bread": "Paneer Bhurji ve Ekmek",
  "Chana Masala with Rice": "Chana Masala ve Pirinç",
  "Curd Rice": "Yoğurtlu Pirinç",
  "Tomato Rice": "Domatesli Pirinç",
  "Vegetable Stew with Appam": "Sebzeli Güveç ve Appam",
  "Dhokla with Green Chutney": "Dhokla ve Yeşil Chutney",
  "Besan Chilla with Salad": "Besan Chilla ve Salata",
  "Lauki Chana Dal": "Lauki Chana Dal",
  "Spinach Corn Curry": "Ispanak ve Mısır Köri",
  "Tinda Masala with Roti": "Tinda Masala ve Roti",
  "Masoor Dal with Rice": "Masoor Dal ve Pirinç",
  "Vegetable Handi with Naan": "Sebzeli Handi ve Naan",
  "Egg Bhurji with Chapati": "Yumurtalı Bhurji ve Çapati",
  "Pumpkin Curry with Rice": "Balkabağı Köri ve Pirinç",
  "2 rotis + sabzi": "2 Roti + Sabzi",
  "1 cup rice + 1 cup dal": "1 Bardak Pirinç + 1 Bardak Dal",
  "1 breast": "1 Göğüs",
  "2 chapatis + dal'": "2 Çapati + Dal",
  "1 bowl curry + 1 cup rice": "1 Kase Köri + 1 Bardak Pirinç",
  "1 bhatura + chole": "1 Bhatura + Chole",
  "1 paratha": "1 Paratha",
  "1 bowl + 2 rotis": "1 Kase + 2 Roti",
  "1 cup + 1 bowl": "1 Bardak + 1 Kase",
  "1 bowl + 1 cup rice": "1 Kase + 1 Bardak Pirinç",
  "1 bowl + 1 bread slice": "1 Kase + 1 Dilim Ekmek",
  "2 theplas + ½ cup curd": "2 Thepla + ½ Kase Yoğurt",
  "1 bowl + 2 chapatis": "1 Kase + 2 Çapati",
  "1 bowl + 1 naan": "1 Kase + 1 Naan",
  "2 rotis + paneer": "2 Roti + Paneer",
  "1 bowl + 2 slices": "1 Kase + 2 Dilim",
  "1 bowl + 2 appams": "1 Kase + 2 Appam",


  "3 pieces": "3 parça",
  "2 chillas + salad": "2 chilla + salata",
  "Cal": "Kalori",
  "Cropper": "Cropper",
  "Calorie Tracker": "Kalori Takipçisi",
  "Add Calorie": "Kalori Ekle",
  "Quantity": "Miktar",
  "Ask With Open AI": "Open AI ile Sor",
  "This picture not available Calorie,Protein,Carbs and Fats,": "Bu resim mevcut değil. Kalori, Protein, Karbonhidratlar ve Yağlar.",
  "Ask Botanist": "Botanikçiye Sor",
  "Write your message": "Mesajını yaz",
  "Confirm Reset": "Sıfırlamayı Onayla",
  "Are you sure you want to Reset Data?": "Hesabınızı sıfırlamak istediğinizden emin misiniz?",
  "Reset": "Sıfırla",
  "You have been Reset Account": "Hesabınız sıfırlandı",
  "Personal Details": "Kişisel Detaylar",
  "Goal Weight": "Hedef Ağırlık",
  "cm": "cm",
  "Date Of Birth": "Doğum Tarihi",
  "Gender": "Cinsiyet",
  "Male": "Erkek",
  "Female": "Kadın",
  "Choose your desired weight?": "İstediğiniz kiloyu seçin?",
  "Imperial": "İmparatorluk",
  "Metric": "Metrik",
  "Weight": "Ağırlık",
  "lb": "lb",
  "ft": "ft",
  "in": "inç",
  "Day": "Gün",
  "January": "Ocak",
  "February": "Şubat",
  "March": "Mart",
  "April": "Nisan",
  "June": "Haziran",
  "July": "Temmuz",
  "August": "Ağustos",
  "September": "Eylül",
  "October": "Ekim",
  "November": "Kasım",
  "December": "Aralık",
  "Update Your Gender": "Cinsiyetinizi Güncelleyin",
  "Other": "Diğer",
  "Adjust Goals": "Hedefleri Ayarla",
  "How many workout do you per week?": "Haftada kaç antrenman yapıyorsunuz?",
  "This will used to calibrate your custom plan": "Bu, özel planınızı kalibre etmek için kullanılacaktır",
  "Workout Now and then": "Zaman zaman antrenman",
  "A few workout per week": "Haftada birkaç antrenman",
  "Dedicated athlete": "Adanmış atlet",
  "What is your goal?": "Hedefiniz nedir?",
  "This helps is generate a plan for your calorie intake.": "Bu, kalori alımınız için bir plan oluşturmanıza yardımcı olur.",
  "Gain Weight": "Kilo Almak",
  "Lose Weight": "Kilo Vermek",
  "Update Calorie Goal": "Kalori Hedefini Güncelle",
  "Save": "Kaydet",
  "Calorie Goal": "Kalori Hedefi",
  "Update Protein Goal": "Protein Hedefini Güncelle",
  "Protein goal": "Protein hedefi",
  "Update Carb Goal": "Karbonhidrat Hedefini Güncelle",
  "Carb goal": "Karbonhidrat hedefi",
  "Update Fat Goal": "Yağ Hedefini Güncelle",
  "Auto Generate Goal": "Otomatik Hedef Oluştur",
  "Fruit Salad": "Meyve Salatası",
  "Roasted Chickpeas": "Fırınlanmış Nohut",
  "Mixed Nuts": "Karışık Kuruyemiş",
  "Yogurt with Honey": "Bal ile Yoğurt",
  "Apple with Peanut Butter": "Elma ve Fıstık Ezmesi",
  "Protein Bar": "Protein Barı",
  "Whole Wheat Crackers": "Tam Buğday Krakeri",
  "Granola Bar": "Granola Barı",
  "Peanut Chikki": "Fıstık Chikki",
  "Bhel Puri": "Bhel Puri",
  "Khakra": "Khakra",
  "Masala Makhana": "Masala Makhana",
  "Hummus with Veggies": "Sebzeli Humus",
  "Paneer Cubes": "Peynir Küpleri",
  "Milkshake (Low Sugar)": "Sütlü İçecek (Düşük Şeker)",
  "Dhokla": "Dhokla",
  "Vegetable Soup": "Sebze Çorbası",
  "Idli with Chutney": "Idli ve Chutney",
  "Cheese Slice": "Peynir Dilimi",
  "Chana Chaat": "Chana Chaat",
  "Moong Dal Chilla": "Moong Dal Chilla",
  "Rice Cake with Peanut Butter": "Fıstık Ezmesiyle Pirinç Keki",
  "Popcorn (Air-popped)": "Patlamış Mısır (Hava ile Pişirilmiş)",
  "Avocado Toast": "Avokado Tostu",
  "Stuffed Dates": "Doldurulmuş Hurma",
  "Oats Cookies": "Yulaf Kurabiyesi",
  "Fruit Smoothie": "Meyveli Smoothie",
  "Carrot Sticks with Hummus": "Havuç Çubukları ile Humus",
  "Soy Nuts": "Soya Kuruyemiş",
  "Trail Mix": "Karma Karışım",
  "Besan Ladoo": "Besan Ladoo",
  "Upma (small portion)": "Upma (küçük porsiyon)",
  "Egg Roll (Mini)": "Yumurta Rulosu (Mini)",
  "Rice Idli": "Pirinci Idli",
  "Cucumber Sandwich": "Salatalık Sandviçi",
  "Fruit Chaat": "Meyve Chaat",
  "Lassi (Sweet)": "Lassi (Tatlı)",
  "Cold Coffee (Low Sugar)": "Soğuk Kahve (Düşük Şeker)",
  "Rava Dhokla": "Rava Dhokla",
  "Vegetable Cutlet": "Sebze Köftesi",
  "Chikki with Jaggery": "Jaggery ile Chikki",
  "Milk (Low Fat)": "Süt (Düşük Yağlı)",
  "Baked Samosa": "Fırınlanmış Samosa",
  "Vegetable Wrap": "Sebzeli Wrap",
  "Roasted Soybeans": "Fırınlanmış Soya Fasulyesi",
  "1/2 cup": "1/2 fincan",
  "1 handful": "1 avuç",
  "1 apple + 1 tbsp PB": "1 elma + 1 yemek kaşığı fıstık ezmesi",
  "1 bar": "1 bar",
  "5 pieces": "5 parça",
  "½ cup hummus + veggies": "½ fincan humus + sebzeler",
  "50g": "50g",
  "1 idli + chutney": "1 idli + chutney",
  "1 slice": "1 dilim",
  "1 chilla": "1 chilla",
  "1 cake + 1 tbsp PB": "1 kek + 1 yemek kaşığı fıstık ezmesi",
  "2 cups": "2 fincan",
  "1 toast": "1 tost",
  "3 dates": "3 hurma",
  "2 cookies": "2 kurabiye",
  "½ cup": "½ fincan",
  "1 small bowl": "1 küçük kâse",
  "1 roll": "1 rulo",
  "1 wrap": "1 wrap",
  "Chapati with Sabzi": "Chapati ile Sabzi",
  "Grilled Fish": "Izgara Balık",
  "Moong Dal Khichdi": "Moong Dal Khichdi",
  "Paneer Bhurji with Roti": "Paneer Bhurji ve Roti",
  "Brown Rice with Veg Curry": "Esmer Pirinç ve Sebze Kari",
  "Quinoa with Stir Fry Veggies": "Kinoa ve Sote Sebzeler",
  "Grilled Tofu with Salad": "Izgara Tofu ve Salata",
  "Vegetable Pulao": "Sebzeli Pulao",
  "Palak Paneer with Chapati": "Palak Paneer ve Chapati",
  "Mixed Vegetable Soup": "Karışık Sebze Çorbası",
  "Stuffed Paratha with Curd": "Doldurulmuş Paratha ve Yoğurt",
  "Oats Khichdi": "Yulaf Khichdi",
  "Roti with Bhindi": "Roti ve Bhindi",
  "Dal Tadka with Jeera Rice": "Dal Tadka ve Jeera Pilavı",
  "Vegetable Handvo": "Sebzeli Handvo",
  "Kadhi with Bajra Roti": "Kadhi ve Bajra Roti",
  "Tofu Curry with Quinoa": "Tofu Kari ve Kinoa",
  "Bhakri with Thecha": "Bhakri ve Thecha",
  "Biryani (Veg)": "Biryani (Sebzeli)",
  "Rajma with Brown Rice": "Rajma ve Esmer Pirinç",
  "Daliya (Broken Wheat Porridge)": "Daliya (Kırık Buğday Porridge)",
  "Pumpkin Sabzi with Chapati": "Balkabağı Sabzi ve Chapati",
  "Cauliflower Stir Fry": "Karnıbahar Sote",
  "Boiled Egg Salad": "Haşlanmış Yumurta Salatası",

};
