// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfyeiVkxn0DRZJpArExJR4qtaf39MFdmU',
    appId: '1:582471032450:android:a2abb5ed83ee9c96b0de9b',
    messagingSenderId: '582471032450',
    projectId: 'macroaize',
    storageBucket: 'macroaize.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqam_k-3WVfpHj9CdG7ZJLDg7PA3tnFxY',
    appId: '1:582471032450:ios:9acfe66988d3d111b0de9b',
    messagingSenderId: '582471032450',
    projectId: 'macroaize',
    storageBucket: 'macroaize.firebasestorage.app',
    androidClientId: '582471032450-h0bkt8rc33bk81cfh7oo3uok6qj73m07.apps.googleusercontent.com',
    iosClientId: '582471032450-ek1mh77ula8jd013uv0t5f3oeksvberc.apps.googleusercontent.com',
    iosBundleId: 'com.macroaize.app',
  );

}