// This is a lightweight stub to allow compiling without generated firebase_options.dart
// Replace with the real file generated by FlutterFire CLI in production.
// To generate: flutterfire configure --project=<your-project>
import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => const FirebaseOptions(
    apiKey: 'stub',
    appId: 'stub',
    messagingSenderId: 'stub',
    projectId: 'stub',
  );
}
